'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {fixture}=require('./map_dom_fixture.cjs');
const make=url=>{const f=fixture({htmlFile:'dist/index.html',url:url||'https://example.org/RoboPaperAtlas/index.html'});f.$$('option').forEach(o=>o.value=o.getAttribute('value')||'');f.runAsset('app.js');return f;};
const select=(f,id,value)=>{f.$(id).value=value;f.$(id).emit('change');};
test('advanced filter count remains visible when disclosure closes',()=>{const f=make();select(f,'#method-filter','VLA');select(f,'#year-filter','2025');assert.match(f.$('.filter-disclosure').querySelector('summary').textContent,/2 项/);assert.equal(f.$('#active-filters').hidden,false);});
test('removing a chip preserves other filters, view and keyboard context',()=>{const f=make('https://example.org/RoboPaperAtlas/index.html?method=WBC&resource=dataset&view=list#catalog');const chip=f.$('#active-filters').children[0];chip.focus();chip.emit('click');assert.equal(f.$('#method-filter').value,'all');assert.equal(f.$('#resource-filter').value,'dataset');assert.equal(f.document.activeElement,f.$('#active-filters').children[0]);assert(f.$('#paper-grid').classList.contains('list-view'));f.$('#active-filters').children[0].emit('click');assert.equal(f.document.activeElement,f.$('.catalog-search-trigger'));});
test('clear all focuses a retained control and does not change sort or view',()=>{const f=make('https://example.org/RoboPaperAtlas/index.html?q=UMI&method=WBC&sort=title&view=list#catalog');f.$('.clear-all').emit('click');assert.equal(f.$('#search').value,'');assert.equal(f.$('#method-filter').value,'all');assert.equal(f.$('#sort').value,'title');assert.equal(f.document.activeElement,f.$('.catalog-search-trigger'));assert(f.$('#paper-grid').classList.contains('list-view'));});
test('Escape dismisses only the filter disclosure and restores focus',()=>{const f=make();const disclosure=f.$('.filter-disclosure');disclosure.open=true;select(f,'#method-filter','WBC');f.$('#method-filter').emit('keydown',{key:'Escape'});assert.equal(disclosure.open,false);assert.equal(f.$('#method-filter').value,'WBC');assert.equal(f.document.activeElement,disclosure.querySelector('summary'));});
test('mobile panel is left-aligned within its containing result bar and motion is bounded',()=>{const css=fs.readFileSync('assets/experience.css','utf8');assert.match(css,/\.results-actions\{width:100%;position:relative\}/);assert.match(css,/\.filter-panel\{left:0;right:auto;top:100%/);assert.match(css,/max-height:min\(60vh,520px\)/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)\{\.active-filters button,\.filter-disclosure>summary\{transition:none\}/);});

test('unchanged feedback keeps its DOM identity during other renders',()=>{const f=make('https://example.org/RoboPaperAtlas/index.html?method=WBC');const chip=f.$('#active-filters').children[0];chip.focus();select(f,'#sort','title');assert.equal(f.$('#active-filters').children[0],chip);assert.equal(f.document.activeElement,chip);});
