'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),root=path.resolve(__dirname,'..');
cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();p.write_preview(r,r/'dist')"],{cwd:root});
const html=fs.readFileSync(path.join(root,'dist/research/navigation/index.html'),'utf8');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await wait(20);}assert.ok(fn(),'expected asynchronous production state');}
async function page(t){
 const errors=[],external=[];class Resources extends ResourceLoader{fetch(url){external.push(url);return null;}}
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const d=new JSDOM(html,{url:'https://example.org/research/navigation/',runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.fetch=async url=>{const p=path.resolve(root,'dist/research/navigation',url);assert.ok(p.startsWith(path.join(root,'dist/research/navigation/content/')));return {ok:fs.existsSync(p),status:404,arrayBuffer:async()=>fs.readFileSync(p)};};}});
 t.after(async()=>{const a=d.window.NavigationProductApp;if(a){const c=a.getContent();if(c)await until(()=>Object.keys(a.getBundle().entities).every(id=>c.status(id)!=='loading'));await new Promise(r=>d.window.requestAnimationFrame(()=>d.window.requestAnimationFrame(r)));}d.window.close();});await until(()=>d.window.NavigationProductApp);return {w:d.window,a:d.window.NavigationProductApp,errors,external};
}
async function selected(x,scope,paper,entity){const b=x.a.getBundle(),p=Object.values(b.positions).find(p=>p.scopeId===scope&&p.tree==='l'&&p.entityId===entity);assert.ok(p);x.a.navigate(x.w.NavigationProductModel.routeForPosition(b,{scope},p.id));await until(()=>x.w.document.querySelector('#np-detail-content [data-claim-id]'));assert.equal(x.a.getState().route.paper,paper);return p;}
function claims(x){return [...x.w.document.querySelectorAll('#np-detail-content .np-evidence > [data-claim-id]')].map(n=>n.dataset.claimId);}
test('new HieraNav route shows SAP fixed single-goal method evidence while preserving PlaNaVid',async t=>{const x=await page(t);assert.deepEqual(x.external,[]);const b=x.a.getBundle();assert.equal(b.coverage['task:hieranav'].total.methodCount,2);await selected(x,'task:hieranav','sap-nav','methods:pipeline-sapnav');assert.equal(x.a.getState().route.version,'arxiv:2608.12707v1');assert.ok(claims(x).includes('method-claim:sapnav:langmap-single-v1'));assert.deepEqual(new Set(claims(x)),new Set(['method-claim:sapnav:langmap-single-v1','method-claim:sapnav:qssr-avv-v1','claim:c:candidate_verification:sapnav2026:technical_approach','claim:c:candidate_verification:sapnav2026:boundary']));assert.match(x.w.document.querySelector('#np-detail-content').textContent,/单目标/);assert.match(x.w.document.querySelector('#np-tree').textContent,/AVV拒绝/);const ci=Object.values(b.positions).find(p=>p.tree==='c'&&p.scopeId==='task:hieranav'&&p.entityId==='methods:insight:ci_candidate_verification:sap-nav');assert.ok(ci);x.a.navigate(x.w.NavigationProductModel.routeForPosition(b,{scope:'task:hieranav'},ci.id),{cross:true});await until(()=>x.a.getState().route.tree==='c');assert.equal(x.a.getState().route.version,'arxiv:2608.12707v1');assert.deepEqual(x.errors,[]);});
for(const [scope,own,other] of [['task:goat','goat-run','ir2r-tour'],['task:ivln','ir2r-tour','goat-run']])test('NavHarness '+scope+' displays only its own run protocol and the existing v1 analysis',async t=>{const x=await page(t);await selected(x,scope,'navharness','methods:pipeline-navharness-benchmark-v1');const ids=claims(x);assert.ok(ids.includes('method-claim:navharness:v1:'+own));assert.ok(!ids.some(id=>id.endsWith(':'+other)||id.endsWith(':extended-tours')));assert.equal(x.a.getState().route.version,'arxiv:2609.34276v1');assert.ok(x.w.document.querySelector('.np-relations .np-relation-condition'));assert.equal(x.w.document.querySelector('.np-relations').open,false);const b=x.a.getBundle(),analysis=b.analyses.navharness['arxiv:2609.34276v1'];assert.ok(analysis);assert.equal(b.summary.answeredAnalysisContexts,3);assert.deepEqual(x.errors,[]);});
test('NavMCP active-EQA selected sources stay fixed v1 and snapshot CI remains separate',async t=>{const x=await page(t);await selected(x,'task:active-eqa','navmcp','methods:pipeline-navmcp-fixed-v1');assert.equal(x.a.getState().route.version,'arxiv:2608.30396v1');assert.deepEqual(new Set(claims(x)),new Set(['new-method:navmcp','claim:t:navmcp26:application']));const refs=[...x.w.document.querySelectorAll('#np-detail-content .np-evidence > .np-claim a[href]')].map(a=>a.href).filter(h=>h.startsWith('https://arxiv.org/'));assert.ok(refs.length);assert.ok(refs.every(h=>h.includes('2608.30396v1')));assert.ok([...x.w.document.querySelectorAll('.np-relations .np-related-source-scope')].filter(n=>n.dataset.versionRelation==='other-version').every(n=>n.textContent.includes('不能替代当前版本')));assert.equal(x.a.getBundle().analyses.navmcp,undefined);assert.deepEqual(x.errors,[]);});
