'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),zlib=require('node:zlib'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),root=path.resolve(__dirname,'..'),raw=zlib.gunzipSync(fs.readFileSync(path.join(root,'tests/fixtures/navigation-product-pr52-1229.json.gz')));
// Historical PR52 external-loader fixture. Current inline/sharded production is tested separately.
const html=zlib.gunzipSync(fs.readFileSync(path.join(root,'tests/fixtures/navigation-pr52-startup.html.gz'))).toString('utf8');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function production(mode='ok',options={}){
 let calls=0,release=null,failFirst=true;
 class Resources extends ResourceLoader {fetch(url){const name=new URL(url).pathname.split('/').at(-1);if(!name.endsWith('.js'))return null;
  if((mode==='model-pending'&&name.includes('-model'))||(mode==='app-pending'&&name==='navigation-product.js')){const pending=new Promise(()=>{});pending.abort=()=>{};return pending;}
  if(mode==='app-error'&&name==='navigation-product.js')return Promise.reject(new Error('script unavailable'));
  if(mode==='syntax-error'&&name==='navigation-product.js')return Promise.resolve(Buffer.from('not valid javascript ]'));
  return Promise.resolve(fs.readFileSync(path.join(root,'assets',name)));}}
 const d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/'+(options.hash||''),runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:new VirtualConsole(),beforeParse(w){
  const timer=w.setTimeout.bind(w);w.setTimeout=(fn,ms,...args)=>timer(fn,ms===30000?120:ms,...args);
  w.HTMLElement.prototype.scrollIntoView=function(){};w.scrollTo=()=>{};w.TextDecoder=TextDecoder;
  Object.defineProperty(w.crypto,'subtle',{value:{digest:async(...args)=>mode==='hash-pending'?new Promise(()=>{}):crypto.webcrypto.subtle.digest(...args)}});
  if(options.saved)w.history.replaceState(options.saved,'',w.location.href);
  w.fetch=()=>{calls++;if(mode==='sync-fetch')throw new Error('synchronous network error');if(mode==='fetch-pending')return new Promise(()=>{});if(mode==='retry'&&failFirst){failFirst=false;return Promise.resolve({ok:false,status:503});}if(mode==='late-body'&&calls===1)return Promise.resolve({ok:true,arrayBuffer:()=>new Promise(r=>{release=r;})});return Promise.resolve({ok:mode!=='http-error',status:404,arrayBuffer:()=>mode==='body-pending'?new Promise(()=>{}):Promise.resolve(mode==='wrong-bytes'?Buffer.from('{}'):raw)});};
 }});
 return {d,w:d.window,calls:()=>calls,release:()=>release&&release(raw)};
}
for(const mode of ['app-error','syntax-error','model-pending','app-pending','fetch-pending','body-pending','hash-pending','sync-fetch','http-error','wrong-bytes'])test('legacy external startup preserves actual reading on '+mode,async t=>{const x=await production(mode);t.after(()=>x.w.close());await wait(220);assert.equal(x.w.document.querySelector('#navigation-product').dataset.loadState,'failed');assert.equal(x.w.NavigationProductApp,undefined);assert.equal(x.w.document.querySelector('#np-static-reading').hidden,false);assert.match(x.w.document.querySelector('#np-static-reading').textContent,/RGB-D|类别|PONI/);assert.equal(x.w.document.querySelector('#np-retry').hidden,false);assert.equal(x.w.document.querySelector('#np-workspace').hidden,true);});
test('legacy external scripts and integrity pipeline succeed without injected bundle',async t=>{const x=await production();t.after(()=>x.w.close());await wait(220);assert.ok(x.w.NavigationProductApp);assert.equal(x.w.document.querySelector('#navigation-product').dataset.loadState,'ready');assert.equal(x.w.document.querySelector('#np-static-reading').hidden,true);assert.equal(x.calls(),1);});
test('manual retry recovers once and preserves an explicit source-bound URL',async t=>{const M=require('../assets/navigation-product-model.js'),b=JSON.parse(raw),p=Object.values(b.positions).find(p=>p.paperId==='poni'&&p.kind==='pipeline_recipe'&&p.scopeId==='task:category-objectnav'),route=M.routeForPosition(b,{scope:p.scopeId},p.id),x=await production('retry',{hash:M.encodeRoute(route)});t.after(()=>x.w.close());await wait(220);assert.equal(x.w.document.querySelector('#np-retry').hidden,false);x.w.document.querySelector('#np-retry').click();await wait(220);assert.ok(x.w.NavigationProductApp);assert.equal(x.w.NavigationProductApp.getState().route.paper,'poni');assert.equal(x.w.NavigationProductApp.getState().route.version,p.versionId);assert.equal(x.calls(),2);});
test('late body from timed-out attempt cannot overwrite successful retry or new navigation',async t=>{const x=await production('late-body');t.after(()=>x.w.close());await wait(220);x.w.document.querySelector('#np-retry').click();await wait(220);assert.ok(x.w.NavigationProductApp);x.w.NavigationProductApp.navigate({scope:'task:vln',tree:'c'});x.release();await wait(100);assert.equal(x.w.NavigationProductApp.getState().route.scope,'task:vln');assert.equal(x.w.NavigationProductApp.getState().route.tree,'c');});
test('retries are explicit and bounded to two',async t=>{const x=await production('http-error');t.after(()=>x.w.close());await wait(220);assert.equal(x.calls(),1);for(let i=0;i<2;i++){x.w.document.querySelector('#np-retry').click();await wait(220);}assert.equal(x.calls(),3);assert.equal(x.w.document.querySelector('#np-retry').hidden,true);x.w.document.querySelector('#np-retry').click();await wait(20);assert.equal(x.calls(),3);});
test('no scripts still has task, methods, challenge reading and fixed sources',()=>{const d=new JSDOM(html);try{const content=d.window.document.querySelector('#np-static-reading');assert.ok(content.querySelectorAll('.np-static-card').length>=12);assert.ok(content.querySelectorAll('a[href^="https:"]').length>=6);assert.match(content.textContent,/原59节点|解析树/);assert.ok(d.window.document.querySelector('[data-workspace-jump]'));}finally{d.window.close();}});
test('invalid old saved state at ordinary root is discarded without deleting external history',async t=>{const M=require('../assets/navigation-product-model.js'),x=await production('ok',{saved:{[M.KEY]:{route:{paper:'missing'}},otherApplication:'retained'}});t.after(()=>x.w.close());await wait(220);assert.ok(x.w.NavigationProductApp);assert.equal(x.w.NavigationProductApp.getState().route.paper,null);assert.equal(x.w.history.state.otherApplication,'retained');});
test('unselected analysis offers three explicit partial versions without choosing one',async t=>{const x=await production();t.after(()=>x.w.close());await wait(220);x.w.document.querySelector('[data-tree-tab="a"]').click();assert.equal(x.w.NavigationProductApp.getState().route.paper,null);const panel=x.w.document.querySelector('.np-analysis-library');assert.ok(panel);assert.equal(panel.querySelectorAll('button').length,3);assert.match(panel.textContent,/未填|部分/);assert.match(panel.querySelector('button').textContent,/当前范围/);panel.querySelector('button').click();assert.equal(x.w.NavigationProductApp.getState().route.paper,'poni');assert.ok(x.w.NavigationProductApp.getState().route.version);});
test('all actual HOV-SG source locators render human-readable text without changing links',async t=>{const x=await production();t.after(()=>x.w.close());await wait(220);const b=x.w.NavigationProductApp.getBundle(),M=x.w.NavigationProductModel,p=Object.values(b.positions).find(p=>p.scopeId==='task:language-objectnav'&&p.paperId==='hovsg'&&p.kind==='pipeline_recipe');x.w.NavigationProductApp.navigate(M.routeForPosition(b,{scope:p.scopeId},p.id));const content=x.w.document.querySelector('#np-detail-content');assert.doesNotMatch(content.textContent,/\[object Object\]/);assert.ok([...content.querySelectorAll('a')].some(a=>a.href==='https://arxiv.org/html/2403.17846v2'));});
test('source locator formatting handles strings, structured arrays, null and unsupported objects',()=>{const vm=require('node:vm'),source=fs.readFileSync(path.join(root,'assets/navigation-product.js'),'utf8'),fn=source.slice(source.indexOf('function sourceLocator('),source.indexOf('function entityFor(')),locator=vm.runInNewContext(fn+';sourceLocator');assert.equal(locator({locator:'§3.1'}),'§3.1');assert.equal(locator({locator:[{locator:'§III-A–C'},{locator:'Fig.2–5'}]}),'§III-A–C；Fig.2–5');for(const value of [null,{},[{unsupported:'not a locator'}],'unknown'])assert.equal(locator({locator:value}),'原文入口（具体定位待核）');});
