const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),{JSDOM}=require('jsdom'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),M=require('../assets/navigation-product-model.js'),raw=zlib.gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz'))),b=JSON.parse(raw);
const html=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();print(p.render(r,p.payloads(r)[1]))"],{cwd:root,encoding:'utf8',maxBuffer:2e6});
async function boot(bundle=b,hash=''){const d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/'+hash,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,writable:true,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};w.NAVIGATION_PRODUCT=bundle;for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await new Promise(r=>setTimeout(r,35));return d;}
function select(w,p){w.NavigationProductApp.navigate(M.routeForPosition(b,w.NavigationProductApp.getState().route,p.id),{cross:true});}
const positions=Object.values(b.positions);
test('frozen model and all task forests have valid identities',()=>{assert.equal(M.validateBundle(b),b);for(const s of b.scopes){const state=M.initialState(b,{scope:s.id});assert.equal(M.validateState(b,state),state);}});
for(const bad of ['constructor','__proto__','missing'])test('reject prototype/unknown scope '+bad,()=>assert.throws(()=>M.validateRoute(b,{scope:bad})));
test('task is not a benchmark',()=>assert.throws(()=>M.validateRoute(b,{scope:'scope:all',bench:'task:category-objectnav'})));
test('generic reference actually contains all original nodes',()=>{const x=structuredClone(b),root=x.template.roots[0],ids=M.descendants(x,[root]),leaf=ids.find(id=>x.positions[id].childIds.length===0),p=x.positions[leaf];x.positions[p.parentId].childIds=x.positions[p.parentId].childIds.filter(id=>id!==leaf);delete x.positions[leaf];assert.throws(()=>M.validateBundle(x));});
test('real three-tree DOM, startup coverage and equivalent outline',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document;assert.ok(w.NavigationProductApp);assert.equal(doc.querySelectorAll('[data-tree-tab]').length,3);assert.ok(doc.querySelectorAll('[role=treeitem]').length>1);assert.ok(doc.querySelectorAll('#np-recommended button').length<=6);doc.getElementById('np-layout-toggle').click();assert.equal(w.NavigationProductApp.getState().route.mode,'outline');assert.equal(doc.getElementById('np-tree').dataset.mode,'outline');assert.ok(doc.getElementById('np-coverage-table').textContent.includes('未'));});
for(const scope of ['task:category-objectnav','task:goat','task:instanceimagenav','task:vln','task:vln-ce','task:pointnav'])test('actual literature and challenge DOM: '+scope,async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window;w.NavigationProductApp.navigate({scope,tree:'l'});assert.equal(w.NavigationProductApp.getState().route.scope,scope);assert.ok(w.document.querySelectorAll('[role=treeitem]').length);w.document.querySelector('[data-tree-tab=c]').click();assert.equal(w.NavigationProductApp.getState().route.tree,'c');assert.ok(w.document.getElementById('np-tree-caption').textContent.length);});
test('PONI method -> CI -> original analysis -> explicit return',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const start=w.NavigationProductApp.getState().route;assert.match(doc.getElementById('np-detail-content').textContent,/FMM/);const ci=[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent.startsWith('挑战'));assert.ok(ci);ci.click();assert.equal(w.NavigationProductApp.getState().route.tree,'c');const analysis=[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent==='消融证据');assert.ok(analysis);analysis.click();assert.equal(w.NavigationProductApp.getState().route.tree,'a');assert.equal(w.NavigationProductApp.getState().route.paper,'poni');assert.match(doc.getElementById('np-detail-content').textContent,/Table|表|消融/);const trail=doc.querySelectorAll('#np-origin-trail button')[1];assert.ok(trail);trail.click();assert.equal(w.NavigationProductApp.getState().route.node,start.node);});
test('reference mode retains unread paper version and zero answers',async t=>{const p=positions.find(p=>p.paperId==='harnessvln'&&p.tree==='l'&&String(p.versionId).includes('v1'));assert.ok(p);const r=M.routeForPosition(b,{scope:p.scopeId},p.id);Object.assign(r,{tree:'a',node:null,claim:null,template:'1'});const d=await boot(b,M.encodeRoute(r));t.after(()=>d.window.close());const w=d.window;assert.ok(w.NavigationProductApp);assert.equal(w.NavigationProductApp.getState().route.version,p.versionId);assert.match(w.document.body.textContent,/未填|未绑定/);assert.equal(M.descendants(b,M.roots(b,r)).length,59);assert.ok(M.descendants(b,M.roots(b,r)).every(id=>b.positions[id].genericTemplate));});
test('invalid deep link never substitutes another paper',async t=>{const d=await boot(b,'#nav=1&scope=constructor');t.after(()=>d.window.close());assert.equal(d.window.NavigationProductApp,undefined);assert.equal(d.window.document.getElementById('np-workspace').hidden,true);});
test('damaged model fails closed',async t=>{const x=structuredClone(b);delete x.positions[x.template.roots[0]];const d=await boot(x);t.after(()=>d.window.close());assert.equal(d.window.NavigationProductApp,undefined);assert.equal(d.window.document.getElementById('navigation-product').dataset.error,'true');});
const settle=()=>new Promise(r=>setTimeout(r,65));
test('new cross-tree target resets DOM scroll; origin and browser history restore exact source',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);await settle();const start=w.NavigationProductApp.getState().route;doc.getElementById('np-detail-scroll').scrollTop=570;doc.getElementById('np-tree-scroll').scrollTop=130;w.scrollTo(0,250);[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent.startsWith('挑战')).click();await settle();assert.equal(doc.getElementById('np-detail-scroll').scrollTop,0);assert.equal(doc.getElementById('np-tree-scroll').scrollTop,0);w.history.back();await settle();assert.equal(w.NavigationProductApp.getState().route.node,start.node);assert.equal(doc.getElementById('np-detail-scroll').scrollTop,570);assert.equal(doc.getElementById('np-tree-scroll').scrollTop,130);assert.equal(w.scrollY,250);w.history.forward();await settle();assert.equal(w.NavigationProductApp.getState().route.tree,'c');doc.querySelectorAll('#np-origin-trail button')[1].click();await settle();assert.equal(w.NavigationProductApp.getState().route.node,start.node);assert.equal(doc.getElementById('np-detail-scroll').scrollTop,570);});
test('keyboard hierarchy and bounded narrow indentation remain genuine tree structure',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,first=doc.querySelector('[role=treeitem]');first.focus();first.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.notEqual(doc.activeElement,first);const selected=doc.activeElement.dataset.position;doc.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await settle();assert.equal(w.NavigationProductApp.getState().route.node,selected);assert.equal(doc.activeElement.dataset.position,selected);const css=fs.readFileSync(path.join(root,'assets/navigation-product.css'),'utf8');assert.ok(css.includes('.np-tree ul ul ul,.np-tree ul.np-tree-deep{margin-left:0;padding-left:0;border-left:0}'));assert.ok(doc.querySelector('[aria-level] .np-node-level'));});
test('production fetch path rejects missing or changed data before mounting trees',async t=>{for(const kind of ['404','bytes']){const d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/',runScripts:'outside-only'});t.after(()=>d.window.close());const w=d.window;w.fetch=async()=>({ok:kind!=='404',status:404,arrayBuffer:async()=>new TextEncoder().encode('{}').buffer});Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextDecoder=TextDecoder;for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await settle();assert.equal(w.NavigationProductApp,undefined);assert.equal(w.document.getElementById('np-workspace').hidden,true);assert.equal(w.document.getElementById('navigation-product').dataset.error,'true');}});
test('production loader accepts only the pinned exact scientific bytes',async t=>{const d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/',runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>d.window.close());const w=d.window;w.fetch=async url=>{assert.ok(url.startsWith('product-data.json?v=a3d5b3cc'));return {ok:true,arrayBuffer:async()=>raw.buffer.slice(raw.byteOffset,raw.byteOffset+raw.byteLength)};};Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextDecoder=TextDecoder;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await settle();assert.ok(w.NavigationProductApp);assert.ok(w.document.querySelector('[role=treeitem]'));});
test('dense evidence is optional and exact claim links open the matching evidence',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const evidence=w.document.querySelector('#np-detail-content details.np-evidence');assert.ok(evidence);assert.equal(evidence.open,false);assert.ok(w.document.querySelector('.np-pipeline'));const claim=evidence.querySelector('[data-claim-id]').dataset.claimId;w.NavigationProductApp.navigate(Object.assign({},w.NavigationProductApp.getState().route,{claim}));assert.equal(w.document.querySelector('#np-detail-content details.np-evidence').open,true);});
test('directory search never repeats nested family members',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,input=w.document.getElementById('np-directory-search');input.value='交互';input.dispatchEvent(new w.Event('input'));const labels=[...w.document.querySelectorAll('#np-directory-list .np-directory-row button')].map(n=>n.textContent);assert.ok(labels.length);assert.equal(new Set(labels).size,labels.length);});

test('missing generic reference root fails closed',()=>{const x=structuredClone(b);x.template.roots=[];assert.throws(()=>M.validateBundle(x));});
test('PONI recipe exposes exact typed SemExp reuse and replacement evidence',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const relation=w.document.querySelector('[data-relation-type=explicit_component_reuse_and_policy_replacement]');assert.ok(relation);assert.match(relation.textContent,/复用|替换/);assert.ok(relation.querySelector('[data-claim-id="method-edge:89"]'));assert.ok(relation.closest('details'));});

test('reselecting the same paper or version preserves explicit unread reference context',async t=>{const p=positions.find(p=>p.paperId==='harnessvln'&&p.tree==='l'&&String(p.versionId).includes('v1'));const r=Object.assign(M.routeForPosition(b,{scope:p.scopeId},p.id),{tree:'a',node:null,claim:null,template:'1'}),d=await boot(b,M.encodeRoute(r));t.after(()=>d.window.close());const w=d.window;for(const id of ['np-paper','np-version']){w.document.getElementById(id).dispatchEvent(new w.Event('change'));assert.equal(w.NavigationProductApp.getState().route.version,p.versionId);assert.equal(w.NavigationProductApp.getState().route.template,'1');}});
