'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {fixture}=require('./map_dom_fixture.cjs');
test('split map keeps all canonical paper results visible in map mode',()=>{const f=fixture();assert.equal(f.$('#paper-map').dataset.view,'map');assert.equal(f.$('.map-list-wrap').hidden,false);assert.equal(f.$$('[data-map-row]').filter(r=>!r.hidden).length,95);assert.equal(f.$('#map-results-title').textContent,'全部论文');assert.match(f.$('#map-selection-status').textContent,/95/)});
test('direction controls immediately update adjacent heading and real result count',()=>{const f=fixture();const button=f.$$('[data-map-topic]').find(b=>b.dataset.mapTopic!=='all');f.click(`[data-map-topic="${button.dataset.mapTopic}"]`);const visible=f.$$('[data-map-row]').filter(r=>!r.hidden);assert(visible.length>0&&visible.length<95);assert.notEqual(f.$('#map-results-title').textContent,'全部论文');assert(f.$('#map-selection-status').textContent.includes(String(visible.length)));f.click('[data-map-reset]');assert.equal(f.$$('[data-map-row]').filter(r=>!r.hidden).length,95);assert.equal(f.$('#map-results-title').textContent,'全部论文')});
test('paper list remains available on narrow screen with optional map enabled',()=>{const f=fixture({mobile:true});f.changeMedia('(max-width: 760px)',true);f.click('[data-map-view="map"]');assert.equal(f.$('.map-list-wrap').hidden,false);assert.equal(f.$('.map-canvas-wrap').hidden,false)});
test('every canonical row has a native independently expandable summary and detail link',()=>{const f=fixture();for(const row of f.$$('[data-map-row]')){assert(row.querySelector('details'));assert(row.querySelector('summary'));assert(row.querySelector('details').querySelector('p').textContent.length>0);assert.match(row.querySelector('details').querySelector('a').getAttribute('href'),/papers\//)}});
test('search empty and browser history restore visible results status',()=>{const f=fixture();f.input('noSuchPaperXYZ');assert.match(f.$('#map-selection-status').textContent,/共 0 篇/);f.setURL('https://example.org/RoboPaperAtlas/map/');assert.match(f.$('#map-selection-status').textContent,/共 95 篇/);assert.equal(f.$('.map-list-wrap').hidden,false)});

test('split list resets inherited fixed desktop height so canonical rows cannot be clipped',()=>{const css=require('node:fs').readFileSync(require('node:path').join(__dirname,'../assets/paper-map.css'),'utf8').split('/* Split research view:')[1];assert.match(css,/\.paper-map \.map-list-wrap\{[^}]*height:auto;[^}]*max-height:none;[^}]*overflow:visible/)});

test('optional narrow-screen map precedes rather than follows the paper list',()=>{const css=require('node:fs').readFileSync(require('node:path').join(__dirname,'../assets/paper-map.css'),'utf8').split('/* Split research view:')[1];assert.match(css,/\.paper-map \.map-explore\{position:static;order:0;/);assert.match(css,/\.paper-map \.map-results-column\{order:1;width:100%/)});
