'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(root,'.navigation-desktop-'));
cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;p.write_preview(Path('.').resolve(),Path(sys.argv[1]))",temp],{cwd:root});
const output=path.join(temp,'research/navigation'),html=fs.readFileSync(path.join(output,'index.html'),'utf8'),wait=ms=>new Promise(r=>setTimeout(r,ms));
test.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
async function frames(w){await new Promise(r=>w.requestAnimationFrame(()=>w.requestAnimationFrame(r)));}
async function page(hash='',saved=null,options={}){const errors=[];class NoNetwork extends ResourceLoader{fetch(url){throw new Error('Unexpected network '+url);}}const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(html,{url:'https://example.org/research/navigation/'+hash,resources:new NoNetwork(),runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};if(saved)w.history.replaceState(saved,'',w.location.href);w.fetch=url=>options.fetch?options.fetch(url):Promise.resolve({ok:true,arrayBuffer:async()=>fs.readFileSync(path.join(output,url))});}});for(let i=0;i<300&&!d.window.NavigationProductApp;i++)await wait(10);const w=d.window;assert.ok(w.NavigationProductApp,d.window.document.getElementById('np-loading')?.textContent);await frames(w);return {w,d:w.document,a:w.NavigationProductApp,M:w.NavigationProductModel,errors};}
async function ready(x){const content=x.a.getContent();for(let i=0;i<300;i++){if(!Object.keys(x.a.getBundle().delivery.packets).some(id=>content.status(id)==='loading')){await frames(x.w);return;}await wait(10);}throw Error('content timeout');}
async function close(x){await ready(x);assert.deepEqual(x.errors,[]);x.w.close();}
async function point(x,id,options={cross:true}){x.a.navigate(x.M.routeForPosition(x.a.getBundle(),x.a.getState().route,id),options);await ready(x);}
async function task(x,id='task:category-objectnav',tree='l'){x.a.navigate(x.M.initialState(x.a.getBundle(),{scope:id,tree}).route,{cross:true,initialExpand:true});await ready(x);}
function openRelations(x){const disclosure=x.d.getElementById('np-task-route-relations');assert.ok(disclosure);if(!disclosure.open)x.d.getElementById('np-task-route-relations-summary').click();assert.equal(disclosure.open,true);return disclosure;}
function oneTree(x,t){assert.equal(x.a.getState().route.tree,t);assert.deepEqual([...x.d.querySelectorAll('#np-tree [data-parallel-tree]')].map(n=>n.dataset.parallelTree),[t]);assert.equal(x.d.querySelectorAll('#np-tree [role=tree]').length,1);assert.equal(x.d.querySelectorAll('#np-tree [role=treeitem][tabindex="0"]').length,1);}
test('L/C switch restores exact cross-paper selection, expansion, focus and both scroll axes',async t=>{const x=await page();t.after(()=>close(x));await task(x);await point(x,'pos:l:98bc421b8bfd17d6699922');const l=x.a.getState().route,lNode=x.d.getElementById('np-node-'+l.node);lNode.focus();x.d.getElementById('np-tree-scroll').scrollTop=117;x.d.getElementById('np-tree-scroll').scrollLeft=36;x.d.getElementById('np-detail-scroll').scrollTop=219;x.d.querySelector('[data-tree-tab=c]').click();await ready(x);oneTree(x,'c');await point(x,'pos:c:6a8a9d2f7b1f3ab3a8ada5');const c=x.a.getState().route,cNode=x.d.getElementById('np-node-'+c.node);cNode.focus();x.d.getElementById('np-tree-scroll').scrollTop=62;x.d.getElementById('np-detail-scroll').scrollTop=91;x.d.querySelector('[data-tree-tab=l]').click();await ready(x);oneTree(x,'l');assert.deepEqual(x.a.getState().route,l);assert.equal(x.d.activeElement.id,lNode.id);assert.equal(x.d.getElementById('np-tree-scroll').scrollTop,117);assert.equal(x.d.getElementById('np-tree-scroll').scrollLeft,36);assert.equal(x.d.getElementById('np-detail-scroll').scrollTop,219);x.d.querySelector('[data-tree-tab=c]').click();await ready(x);oneTree(x,'c');assert.deepEqual(x.a.getState().route,c);assert.equal(x.d.activeElement.id,cNode.id);assert.equal(x.d.getElementById('np-tree-scroll').scrollTop,62);assert.equal(x.d.getElementById('np-detail-scroll').scrollTop,91);x.M.validateState(x.a.getBundle(),x.a.getState());});
test('relation selection is presentation only; same-hash history, exact endpoint and explicit origin retain it',async t=>{const x=await page();t.after(()=>close(x));await task(x);const route=x.a.getState().route,hash=x.w.location.hash,selector=x.d.querySelector('[data-task-change="methods:relation:90"]');assert.ok(selector);assert.equal(selector.closest('[role=tree]'),null);assert.ok(x.d.getElementById('np-tree-scroll').contains(selector));assert.equal(x.d.querySelector('#np-reader-summary [data-route-method]'),null);const overview=openRelations(x);assert.ok(overview.compareDocumentPosition(x.d.getElementById('np-tree'))&x.w.Node.DOCUMENT_POSITION_FOLLOWING);selector.focus();selector.click();await ready(x);assert.deepEqual(x.a.getState().route,route);assert.equal(x.w.location.hash,hash);const detail=x.d.querySelector('[data-selected-task-relation="methods:relation:90"]');assert.ok(detail);assert.equal(x.d.querySelectorAll('[data-selected-task-relation]').length,1);assert.equal(detail.dataset.relationType,'explicit_component_reuse_and_policy_replacement');assert.equal(detail.dataset.renderAsTree,'false');const claim=detail.querySelector('[data-task-change-claim="method-edge:89"]');assert.ok(claim.textContent.includes(x.a.getBundle().claims['method-edge:89'].statement));assert.ok(claim.querySelector('a[href]'));const target=detail.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]');target.focus();x.d.getElementById('np-detail-scroll').scrollTop=133;target.click();await ready(x);assert.equal(x.a.getState().route.version,'publication:poni:e83f98bb7132');assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);x.d.querySelector('#np-origin-trail .np-return-previous').click();await ready(x);assert.deepEqual(x.a.getState().route,route);assert.equal(x.d.activeElement.id,target.id);assert.equal(x.d.getElementById('np-task-route-relations').open,true);assert.equal(x.d.getElementById('np-detail-scroll').scrollTop,133);assert.ok(x.d.querySelector('[data-selected-task-relation="methods:relation:90"]'));x.d.getElementById('np-task-route-return').click();await ready(x);assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);assert.equal(x.d.activeElement.id,selector.id);x.w.history.back();await wait(60);await ready(x);assert.ok(x.d.querySelector('[data-selected-task-relation="methods:relation:90"]'));x.M.validateState(x.a.getBundle(),x.a.getState());});
test('unknown full relation namespace stays unavailable after cold loading without substituting methods relation 90',async t=>{const x=await page();await task(x);const state=x.a.getState(),bucket=x.M.getBucket(state);bucket.relationViewByTree={l:{id:'tasks:relation:90',route:structuredClone(state.route)}};bucket.focusTarget='np-task-relation-title';const hash=x.M.encodeRoute(state.route),saved=x.M.mergeHistory({},state);await close(x);const y=await page(hash,saved);t.after(()=>close(y));await ready(y);assert.equal(y.d.querySelector('.np-task-relation-reading').dataset.relationState,'unavailable');assert.equal(y.d.querySelector('[data-selected-task-relation]'),null);assert.equal(y.d.querySelector('[data-task-change="methods:relation:90"]').getAttribute('aria-pressed'),'false');assert.equal(JSON.stringify(y.a.getState().route),JSON.stringify(state.route));});
test('version analysis explicitly distinguishes imported partial A and unread template',async t=>{const x=await page();t.after(()=>close(x));await task(x);await point(x,'pos:l:98bc421b8bfd17d6699922');assert.equal(x.d.querySelector('[data-analysis-state]').dataset.analysisState,'imported');assert.match(x.d.querySelector('[data-analysis-state]').textContent,/22/);x.d.getElementById('np-open-version-analysis').click();await ready(x);assert.equal(x.a.getState().route.tree,'a');assert.equal(x.a.getState().route.version,'publication:poni:e83f98bb7132');assert.equal(x.a.getState().route.template,null);await point(x,'pos:l:ff0298ffa17b4cfcf009bd');assert.equal(x.d.querySelector('[data-analysis-state]').dataset.analysisState,'not-imported');const v=x.a.getState().route.version;x.d.getElementById('np-open-analysis-template').click();await ready(x);assert.equal(x.a.getState().route.template,'1');assert.equal(x.a.getState().route.version,v);assert.match(x.d.getElementById('np-tree-caption').textContent,/0答案/);});
test('restoring global view removes only a mismatched g relation after taking its origin snapshot',async t=>{const x=await page();t.after(()=>close(x));const b=x.a.getBundle(),id=b.researchMap.canonicalScopePositionIds['task:category-objectnav'];await point(x,id,{newStart:true});openRelations(x);x.d.querySelector('[data-task-change="methods:relation:90"]').click();await ready(x);x.d.querySelector('[data-tree-tab=g]').click();await ready(x);x.M.validateState(b,x.a.getState());assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);});
test('rapid L/C/L before animation frames and immediate pagehide preserve the intended view focus on cold restore',async t=>{const x=await page();await task(x);await point(x,'pos:l:98bc421b8bfd17d6699922');const l=x.a.getState().route,rootId=x.a.getBundle().forests[l.scope].l[0],focusId='np-node-'+rootId;x.d.getElementById(focusId).focus();x.d.getElementById('np-tree-scroll').scrollTop=74;x.d.querySelector('[data-tree-tab=c]').click();await ready(x);await point(x,'pos:c:6a8a9d2f7b1f3ab3a8ada5');const native=x.w.requestAnimationFrame,queued=[];x.w.requestAnimationFrame=fn=>{queued.push(fn);return queued.length;};x.d.querySelector('[data-tree-tab=l]').click();x.d.querySelector('[data-tree-tab=c]').click();x.d.querySelector('[data-tree-tab=l]').click();x.w.dispatchEvent(new x.w.Event('pagehide'));const state=x.a.getState(),saved=JSON.parse(JSON.stringify(x.w.history.state)),hash=x.w.location.hash;assert.equal(JSON.stringify(state.route),JSON.stringify(l));assert.equal(x.M.taskView(state).focusTargetByTree.l,rootId);x.M.validateState(x.a.getBundle(),state);x.w.requestAnimationFrame=native;for(const callback of queued)callback(0);await close(x);const y=await page(hash,saved);t.after(()=>close(y));await ready(y);oneTree(y,'l');assert.equal(JSON.stringify(y.a.getState().route),JSON.stringify(l));assert.equal(y.d.activeElement.id,focusId);assert.equal(y.d.getElementById('np-tree-scroll').scrollTop,74);});
test('legacy roster focus maps to a reachable active-tree node and never silently switches C or g to L',async t=>{const source=await page();await task(source);const rootState=source.a.getState(),method='pos:l:98bc421b8bfd17d6699922',cases=[];for(const tree of ['l','c','g']){let route=tree==='g'?source.M.routeForPosition(source.a.getBundle(),rootState.route,source.a.getBundle().researchMap.canonicalScopePositionIds[rootState.route.scope]):source.M.initialState(source.a.getBundle(),{scope:rootState.route.scope,tree}).route;const state=source.M.initialState(source.a.getBundle(),route);source.M.getBucket(state).focusTarget='np-task-route-method-'+method;cases.push({tree,route,saved:source.M.mergeHistory({},state)});}await close(source);for(const fixture of cases){const x=await page('#'+new URLSearchParams(Object.entries(fixture.route).filter(([,v])=>v!==null)).toString(),fixture.saved);await ready(x);assert.equal(JSON.stringify(x.a.getState().route),JSON.stringify(fixture.route));assert.equal(x.d.activeElement.id,fixture.tree==='l'?'np-node-'+method:'np-tree-heading');if(fixture.tree==='c')oneTree(x,'c');x.M.validateState(x.a.getBundle(),x.a.getState());await close(x);}});
test('legacy endpoint history restores only the full allowed relation and exact original endpoint version',async t=>{const source=await page();await task(source);const baseline=source.a.getState(),scope=baseline.route.scope,fixtures=[{relation:'methods:relation:90',position:'pos:l:98bc421b8bfd17d6699922',valid:true},{relation:'tasks:relation:90',position:'pos:l:98bc421b8bfd17d6699922',valid:false},{relation:'methods:relation:92',position:'pos:l:8be2c09f4c65785416c820',valid:false},{relation:'methods:relation:90',position:'pos:l:98bc421b8bfd17d6699922',prefixScope:'task:imagenav',valid:false}].map(row=>{const state=source.M.clone(baseline),bucket=source.M.getBucket(state);delete bucket.relationViewByTree;delete bucket.relationOverviewByTree;const focus='np-task-change-target-'+(row.prefixScope||scope)+'-'+row.relation+'-'+row.position;bucket.focusTarget=focus;bucket.detailScrollByTree.l=143;return {...row,focus,route:state.route,saved:source.M.mergeHistory({},state)};});await close(source);for(const fixture of fixtures){const hash='#'+new URLSearchParams(Object.entries(fixture.route).filter(([,v])=>v!==null)).toString(),x=await page(hash,fixture.saved);await ready(x);assert.equal(JSON.stringify(x.a.getState().route),JSON.stringify(fixture.route));if(fixture.valid){assert.equal(x.d.querySelector('[data-selected-task-relation]').dataset.selectedTaskRelation,fixture.relation);assert.equal(x.d.activeElement.id,fixture.focus);assert.equal(x.d.getElementById('np-detail-scroll').scrollTop,143);}else{assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);assert.ok(!x.M.getBucket(x.a.getState()).relationViewByTree?.l);assert.equal(x.d.activeElement.id,'np-task-route-relations-summary');}x.M.validateState(x.a.getBundle(),x.a.getState());await close(x);}});
test('g presentation rejects a source-scope-bearing position that is not its exact canonical task entry',async t=>{const x=await page();t.after(()=>close(x));const b=x.M.clone(x.a.getBundle()),scope='task:category-objectnav',canonical=b.researchMap.canonicalScopePositionIds[scope],other=Object.values(b.positions).find(p=>p.tree==='g'&&p.id!==canonical&&p.id!==b.researchMap.roots[0]);other.sourceScopeId=scope;const state=x.M.initialState(b,x.M.routeForPosition(b,x.a.getState().route,other.id)),bucket=x.M.getBucket(state);bucket.relationOverviewByTree={g:{route:x.M.clone(state.route),open:true}};assert.throws(()=>x.M.validateState(b,state));delete bucket.relationOverviewByTree;bucket.relationViewByTree={g:{route:x.M.clone(state.route),id:'methods:relation:90'}};assert.throws(()=>x.M.validateState(b,state));});

test('new wheel interaction cancels deferred legacy relationship migration without reader replacement or focus theft',async t=>{const source=await page();await task(source);const state=source.a.getState(),bucket=source.M.getBucket(state);delete bucket.relationViewByTree;bucket.focusTarget='np-task-change-target-task:category-objectnav-methods:relation:90-pos:l:98bc421b8bfd17d6699922';const saved=source.M.mergeHistory({},state),hash=source.M.encodeRoute(state.route);await close(source);const pending=new Map(),x=await page(hash,saved,{fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>close(x));assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);x.d.getElementById('np-tree-scroll').dispatchEvent(new x.w.WheelEvent('wheel',{bubbles:true}));const focus=x.d.activeElement;x.d.getElementById('np-detail-scroll').scrollTop=91;for(const [url,resolve] of pending)resolve({ok:true,arrayBuffer:async()=>fs.readFileSync(path.join(output,url))});await ready(x);assert.equal(x.d.querySelector('[data-selected-task-relation]'),null);assert.equal(x.d.activeElement,focus);assert.equal(x.d.getElementById('np-detail-scroll').scrollTop,91);assert.equal(JSON.stringify(x.a.getState().route),JSON.stringify(state.route));});

test('selected methods and CI retain complete scientific conditions while omitting only exact historical import bookkeeping',async t=>{
 const x=await page();t.after(()=>close(x));
 const raw=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz'))));
 const notes=['编辑归纳绑定：direct_to_LH_VLN_method；需新增MGDM论文/版本后计数。','编辑归纳绑定：direct_to_v5_setting；新建paper/version绑定后才可计入覆盖。'];
 const records=Object.values(raw.entities).filter(e=>typeof e.detail?.condition==='string'&&notes.some(note=>e.detail.condition.startsWith(note)));
 assert.equal(records.length,12,'keep the complete known bookkeeping inventory');
 const privateHelper=fs.readFileSync(path.join(root,'assets/navigation-product.js'),'utf8').split('\n').find(line=>line.startsWith('function readingConditionText('));assert.ok(privateHelper);const display=require('node:vm').runInNewContext(privateHelper+';readingConditionText',{textOf:String});
 for(const e of records){const p=Object.values(raw.positions).find(p=>p.entityId===e.id&&p.scopeId!=='scope:all');for(const versionId of [null,'arxiv:2403.09905v4','publication:cvpr2025:other'])assert.equal(display(e.detail.condition,{...p,versionId}),e.detail.condition,e.id+' never suppresses a prefix for an unpinned or different version');assert.equal(display(e.detail.condition,{...p,paperId:'unrelated-paper'}),e.detail.condition,e.id+' never suppresses for another paper with matching entity/version');assert.equal(display(e.detail.condition,{...p,entityId:'methods:unlisted'}),e.detail.condition,e.id+' never suppresses for an unlisted entity with matching paper/version');}
 for(const e of records){
  const p=Object.values(raw.positions).find(p=>p.entityId===e.id&&p.scopeId!=='scope:all'&&['l','c'].includes(p.tree));assert.ok(p,e.id);await point(x,p.id);
  const reader=x.d.querySelector('#np-reader-summary'),blocks=[...reader.querySelectorAll('.np-detail-block')],condition=blocks.find(block=>block.querySelector('h3')?.textContent==='适用条件');assert.ok(condition,e.id);
  const note=notes.find(note=>e.detail.condition.startsWith(note)),tail=e.detail.condition.slice(note.length).trimStart();assert.equal(condition.querySelector('p').textContent,tail,e.id+' preserves all original scientific tail and locators');
  for(const note of notes)assert.ok(!reader.textContent.includes(note),e.id+' hides only obsolete import note');
  for(const requirement of e.detail.requiredDisplayConditions||[]){assert.ok(reader.textContent.includes(requirement.statement),e.id+' required statement');assert.ok(reader.textContent.includes(requirement.locator),e.id+' source locator');}
 }
 const p=Object.values(raw.positions).find(p=>p.entityId==='methods:pipeline-mgdm'&&p.tree==='l'&&p.scopeId!=='scope:all');await point(x,p.id);
 const e=x.a.getBundle().entities[p.entityId],original=e.detail.condition,distinct='原文条件引用：'+notes[0]+' 后续科学限定不得截断。';e.detail.condition=distinct;
 await point(x,Object.values(raw.positions).find(q=>q.entityId==='methods:insight:mgdm:lhvln-mgdm'&&q.tree==='c'&&q.scopeId!=='scope:all').id);await point(x,p.id);
 const condition=[...x.d.querySelectorAll('#np-reader-summary .np-detail-block')].find(block=>block.querySelector('h3')?.textContent==='适用条件');assert.equal(condition.querySelector('p').textContent,distinct,'matching text inside a scientific condition is never filtered');e.detail.condition=original;
 const other=Object.values(raw.positions).find(q=>q.entityId==='methods:pipeline-poni'&&q.tree==='l'&&q.scopeId==='task:category-objectnav');await point(x,other.id);const foreign=x.a.getBundle().entities[other.entityId],foreignOriginal=foreign.detail.condition;foreign.detail.condition=notes[0]+' Other paper scientific condition.';await point(x,p.id);await point(x,other.id);const otherCondition=[...x.d.querySelectorAll('#np-reader-summary .np-detail-block')].find(block=>block.querySelector('h3')?.textContent==='适用条件');assert.equal(otherCondition.querySelector('p').textContent,foreign.detail.condition,'an identical prefix in another entity/paper/version remains literal');foreign.detail.condition=foreignOriginal;
});
