'use strict';
// Regression model grounded in the 1180 × 757 deployed browser finding.
// Deterministic DOM/geometry checks supplement, never replace, deployed-browser QA.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),src=path.join(root,'previews/radar-c2-analysis'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'tree-obstructions-'));
fs.cpSync(src,tmp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),tmp,{recursive:true});
const {fixture}=require(path.join(tmp,'analysis/tests/dom_fixture.cjs')),F=require(path.join(src,'analysis/c2.js')).FaithfulTree,M=require(path.join(src,'model.js')),A=require(path.join(src,'analysis/model.js'));
const data=file=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(src,file),'utf8'),ctx);return ctx.window;};
const model=M.buildModel(data('data/catalog.js').PAPER_CATALOG,data('data/literature.js').LITERATURE_TREE,data('data/challenge.js').CHALLENGE_TREE),bundle=data('analysis/data/bundle.js').C2_DATA,d={M,A,model,bundle},plain=x=>JSON.parse(JSON.stringify(x));
const tests=[];const test=(name,fn)=>tests.push({name,fn});
const inside=(n,c,w,h)=>{const r={x:n.x*c.k+c.x,y:n.y*c.k+c.y,w:n.w*c.k,h:n.h*c.k};assert(r.x>=0&&r.y>=0&&r.x+r.w<=w+.01&&r.y+r.h<=h+.01,`${n.id} outside ${w}×${h}: ${JSON.stringify(r)}`);return r;};
function start(){const f=fixture({width:1180,height:757});const proto=Object.getPrototypeOf(f.document);Object.defineProperties(proto,{clientWidth:{configurable:true,get(){if(this.id==='ft-viewport')return f.$('.ft-workspace')?.classList.contains('ft-no-side')?1180:840;return 0;}},clientHeight:{configurable:true,get(){return this.id==='ft-viewport'?(f.$('#faithful-map')?.classList.contains('ft-fullscreen')?553:464):0;}}});f.document.emit('DOMContentLoaded');return f;}
test('analysis root and all five original main branches are visible at 1× in the observed 840×486 canvas',()=>{for(const height of [486,464]){const s=F.reduce(d,F.initial(d),{type:'tab',tab:'a'}),g=F.getGraph(d,s),v=F.view(d,s),sc=F.scene(g,v,false,840),c=F.readableCamera(g,v,sc,840,height);assert(c.k>=1);assert.equal(sc.nodes.length,6);for(const n of sc.nodes)inside(n,c,840,height);}});
test('minimap and reading hint occupy no selectable canvas rectangle',()=>{const f=start(),mini=f.$('.ft-mini'),hint=f.$('.ft-hint');assert(mini);assert(!mini.closest('#ft-viewport'),'minimap overlaps the selectable canvas');assert(hint);assert(!hint.closest('#ft-viewport'),'hint overlays selectable nodes');assert(f.$('[data-ft="minimap"]'));});
test('ordinary high-fanout expansion starts with parent and first sibling, and all 19 have positioning controls',()=>{const s=F.reduce(d,F.reduce(d,F.initial(d),{type:'mode',mode:'navigation'}),{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s),sc=F.scene(g,v,false,840),c=F.readableCamera(g,v,sc,840,486);assert.equal(g.by.get('nav:l').children.length,19);inside(sc.by.get('nav:l'),c,840,486);inside(sc.by.get(g.by.get('nav:l').children[0]),c,840,486);const f=start();f.click('[data-ft="mode"][data-mode="navigation"]');f.click('[data-ft="node"][data-id="nav:l"]');assert.equal(f.$('.ft-peer-directory')?.querySelectorAll('[data-ft="locate"]').length,19);});
test('all 19 true siblings fit a focus canvas readably without synthetic parents',()=>{const s=F.reduce(d,F.reduce(d,F.initial(d),{type:'mode',mode:'navigation'}),{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s),sc=F.scene(g,v,false,1180),c=F.readableCamera(g,v,sc,1180,553);assert(c.k>=1);assert.equal(sc.nodes.length,23);for(const n of sc.nodes){inside(n,c,1180,553);assert.equal(n.parent,g.by.get(n.id).parent);}assert.equal(sc.edges.length,22);});
test('fullscreen rejection enters honest page focus, enlarges canvas, preserves camera, and restores it on exit',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');f.click('[data-ft="mode"][data-mode="navigation"]');f.click('[data-ft="node"][data-id="nav:l"]');app.setCamera({x:31,y:42,k:1.25});const before=plain(app.getState()),oldSize=[f.$('#ft-viewport').clientWidth,f.$('#ft-viewport').clientHeight];host.requestFullscreen=()=>Promise.reject(Error('not allowed'));await app.toggleFullscreen();assert(app.isFullscreen());assert.equal(f.$('#ft-fullscreen').textContent,'退出页内专注');assert.equal(f.$('#ft-focus-status').textContent,'页内专注');assert(f.$('#ft-viewport').clientWidth>oldSize[0]);assert(f.$('#ft-viewport').clientHeight>oldSize[1]);assert.equal(F.view(d,app.getState()).camera.k,1.25);app.setCamera({x:77,y:99,k:1.5});await app.toggleFullscreen();assert.deepEqual(plain(F.view(d,app.getState()).camera),F.view(d,before).camera);assert.equal(app.getState().details,before.details);assert.equal(f.document.activeElement.id,'ft-fullscreen');});
test('zoomed-out overview gives an explicit readable-focus action without changing expansion',()=>{const f=start(),app=f.window.FaithfulTreeApp;app.setCamera({x:0,y:0,k:.2});const saved=plain(F.view(d,app.getState()).expanded);assert(f.$('.ft-hint').textContent.includes('放大'));assert(f.$('[data-ft="readable"]'));f.click('[data-ft="readable"]');assert(F.view(d,app.getState()).camera.k>=1);assert.deepEqual(plain(F.view(d,app.getState()).expanded),saved);});

test('all grid connectors avoid unrelated node rectangles and preserve every original edge',()=>{const s=F.reduce(d,F.reduce(d,F.initial(d),{type:'mode',mode:'navigation'}),{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s);for(const width of [684,840,1088,1180]){const sc=F.scene(g,v,false,width);for(const child of sc.nodes.filter(n=>n.gridParent)){const parent=sc.by.get(child.parent),points=[];let previous;for(const [,op,raw]of F.pathD(parent,child).matchAll(/([MHV])([^MHV]+)/g)){const nums=raw.trim().split(/[ ,]+/).map(Number),point=op==='M'?nums:op==='H'?[nums[0],previous[1]]:[previous[0],nums[0]];points.push(point);previous=point;}for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];for(const n of sc.nodes.filter(n=>n.id!==child.id&&n.id!==parent.id)){const cross=a[0]===b[0]?a[0]>n.x&&a[0]<n.x+n.w&&Math.max(a[1],b[1])>n.y&&Math.min(a[1],b[1])<n.y+n.h:a[1]>n.y&&a[1]<n.y+n.h&&Math.max(a[0],b[0])>n.x&&Math.min(a[0],b[0])<n.x+n.w;assert(!cross,child.id+' connector crosses '+n.id);}}}}});
test('side panels toggle independently without resetting camera, branches or original-image scale',async()=>{const f=start(),app=f.window.FaithfulTreeApp;app.setCamera({x:41,y:32,k:1.3});const camera=plain(F.view(d,app.getState()).camera);f.click('[data-ft="minimap"]');assert(f.$('.ft-mini').hidden);assert(!f.$('#ft-detail').hidden);f.click('[data-ft="details"]');assert(f.$('#ft-side').hidden);assert.deepEqual(plain(F.view(d,app.getState()).camera),camera);await app.toggleFullscreen();f.click('[data-ft="minimap"]');assert(!f.$('.ft-mini').hidden);assert(f.$('#ft-detail').hidden);f.click('[data-ft="image"]');f.click('[data-ft="image-plus"]');const imageWidth=f.$('#ft-original-image').style.width;f.window.emit('resize');assert.equal(f.$('#ft-image-dialog').hidden,false);assert.equal(f.$('#ft-original-image').getAttribute('style').includes(imageWidth),true);f.$('#ft-image-close').emit('keydown',{key:'Escape'});assert(app.isFullscreen());f.$('#ft-viewport').emit('keydown',{key:'Escape'});assert(!app.isFullscreen());assert(f.$('#ft-side').hidden);assert.deepEqual(plain(F.view(d,app.getState()).camera),camera);});
test('focus exit via native browser chrome restores exact pre-entry camera',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');host.requestFullscreen=async()=>{f.document.fullscreenElement=host;f.document.emit('fullscreenchange');};await app.toggleFullscreen();assert.equal(f.$('#ft-fullscreen').textContent,'退出浏览器全屏');f.document.fullscreenElement=null;f.document.emit('fullscreenchange');assert(!app.isFullscreen());assert.equal(f.document.activeElement.id,'ft-fullscreen');});
test('leaving focus for legacy and returning through history never overwrites the target route',async()=>{const f=start(),app=f.window.FaithfulTreeApp;await app.toggleFullscreen();f.click('[data-ft="legacy"]');assert(!app.isActive());assert(!f.url().includes('#mindmap='));f.back();assert(app.isActive());assert(!app.isFullscreen());});
test('focus keeps newly selected nodes and expanded original branches on exit',async()=>{const f=start(),app=f.window.FaithfulTreeApp;await app.toggleFullscreen();f.click('[data-ft="node"][data-id="ex:l"]');const before=F.view(d,app.getState());await app.toggleFullscreen();const after=F.view(d,app.getState());assert.equal(after.selected,before.selected);assert.deepEqual(plain(after.expanded),plain(before.expanded));assert(after.camera.k>=1);});

test('late native exit cannot cancel a newer page-focus or fullscreen enter intent',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');host.requestFullscreen=async()=>{f.document.fullscreenElement=host;f.document.emit('fullscreenchange');};let finishExit;f.document.exitFullscreen=()=>new Promise(resolve=>{finishExit=()=>{f.document.fullscreenElement=null;f.document.emit('fullscreenchange');resolve();};});await app.toggleFullscreen();const leaving=app.toggleFullscreen();await app.toggleFullscreen();assert(app.isFullscreen());finishExit();await leaving;assert(app.isFullscreen());assert.equal(f.$('#ft-fullscreen').textContent,'退出页内专注');await app.toggleFullscreen();assert(!app.isFullscreen());});

test('focus and panel reflow anchor a last sibling that would otherwise leave a blank canvas',async()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="mode"][data-mode="navigation"]');f.click('[data-ft="node"][data-id="nav:l"]');const last=app.getGraph().by.get('nav:l').children.at(-1);app.dispatch({type:'locate',id:last});app.dispatch({type:'node',id:last});const before=plain(F.view(d,app.getState()).camera),k=before.k;await app.toggleFullscreen();let v=F.view(d,app.getState()),sc=F.scene(app.getGraph(),v,false,1180);assert.equal(v.camera.k,k);inside(sc.by.get(last),v.camera,1180,553);await app.toggleFullscreen();assert.deepEqual(plain(F.view(d,app.getState()).camera),before);f.click('[data-ft="minimap"]');f.click('[data-ft="details"]');v=F.view(d,app.getState());sc=F.scene(app.getGraph(),v,false,1180);inside(sc.by.get(last),v.camera,1180,464);assert.equal(v.camera.k,k);});

test('every high-fanout edge, including common ancestors and sibling tree, avoids unrelated cards',()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="mode"][data-mode="navigation"]');f.click('[data-ft="node"][data-id="nav:l"]');const g=app.getGraph(),sc=F.scene(g,F.view(d,app.getState()),false,840),edges=f.$$('[data-ft-source]');assert.equal(edges.length,sc.edges.length);for(const edge of edges){const source=edge.dataset.ftSource,target=edge.dataset.ftTarget;assert.equal(g.by.get(target).parent,source);let previous;for(const [,op,raw]of edge.getAttribute('d').matchAll(/([MHV])([^MHV]+)/g)){const nums=raw.trim().split(/[ ,]+/).map(Number),point=op==='M'?nums:op==='H'?[nums[0],previous[1]]:[previous[0],nums[0]];if(previous)for(const n of sc.nodes.filter(n=>n.id!==source&&n.id!==target)){const a=previous,b=point,cross=a[0]===b[0]?a[0]>n.x&&a[0]<n.x+n.w&&Math.max(a[1],b[1])>n.y&&Math.min(a[1],b[1])<n.y+n.h:a[1]>n.y&&a[1]<n.y+n.h&&Math.max(a[0],b[0])>n.x&&Math.min(a[0],b[0])<n.x+n.w;assert(!cross,source+' → '+target+' crosses '+n.id);}previous=point;}}});
test('resize keeps a live node or control focused without stealing an outside focus',()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="node"][data-id="ex:l"]');f.window.emit('resize');assert.equal(f.document.activeElement,f.$('[data-ft="node"][data-id="ex:l"]'));f.$('[data-ft="fit"]').focus();f.window.emit('resize');assert.equal(f.document.activeElement,f.$('[data-ft="fit"]'));const outside=f.document.body;outside.focus();f.window.emit('resize');assert.equal(f.document.activeElement,outside);});
test('source image resize preserves scale and both scroll offsets before Escape restores node focus',()=>{const f=start();f.click('[data-ft="image"]');f.click('[data-ft="image-plus"]');const width=f.$('#ft-original-image').style.width,scroll=f.$('.ft-image-scroll');scroll.scrollTop=183;scroll.scrollLeft=241;f.window.emit('resize');assert(f.$('#ft-original-image').getAttribute('style').includes(width));assert.equal(f.$('.ft-image-scroll').scrollTop,183);assert.equal(f.$('.ft-image-scroll').scrollLeft,241);f.$('#ft-image-close').emit('keydown',{key:'Escape'});assert.equal(f.document.activeElement.dataset.ft,'node');});

test('queued native-exit event after Promise resolution does not cancel a newer focus intent',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');let requests=0;host.requestFullscreen=async()=>{requests++;f.document.fullscreenElement=host;f.document.emit('fullscreenchange');};f.document.exitFullscreen=async()=>{f.document.fullscreenElement=null;};await app.toggleFullscreen();await app.toggleFullscreen();await app.toggleFullscreen();assert(app.isFullscreen());assert.equal(requests,1);f.document.emit('fullscreenchange');assert(app.isFullscreen());assert.equal(f.$('#ft-fullscreen').textContent,'退出页内专注');await app.toggleFullscreen();await app.toggleFullscreen();assert.equal(requests,2);assert.equal(f.$('#ft-fullscreen').textContent,'退出浏览器全屏');});

test('a cancelled late native request produces one exit and does not poison later entry',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');let done,requests=0,exits=[];host.requestFullscreen=()=>{requests++;if(requests>1){f.document.fullscreenElement=host;f.document.emit('fullscreenchange');return Promise.resolve();}return new Promise(resolve=>{done=resolve;});};f.document.exitFullscreen=()=>new Promise(resolve=>{exits.push(resolve);});const entering=app.toggleFullscreen();await app.toggleFullscreen();f.document.fullscreenElement=host;done();await Promise.resolve();await Promise.resolve();f.document.emit('fullscreenchange');assert.equal(exits.length,1);f.document.fullscreenElement=null;f.document.emit('fullscreenchange');exits[0]();await entering;await app.toggleFullscreen();assert.equal(requests,2);assert(app.isFullscreen());assert.equal(f.$('#ft-fullscreen').textContent,'退出浏览器全屏');});

test('hidden detail panes cannot erase saved reading scroll during focus resize',async()=>{const f=start(),app=f.window.FaithfulTreeApp,body=f.$('#ft-detail-body'),proto=Object.getPrototypeOf(body);delete body.scrollTop;Object.defineProperty(proto,'scrollTop',{configurable:true,get(){return this.closest('#ft-detail')?.hidden?0:this._savedScrollTop||0;},set(value){if(!this.closest('#ft-detail')?.hidden)this._savedScrollTop=value;}});body.scrollTop=183;await app.toggleFullscreen();assert(f.$('#ft-detail').hidden);f.window.emit('resize');await app.toggleFullscreen();assert.equal(f.$('#ft-detail-body').scrollTop,183);assert.equal(F.view(d,app.getState()).detailScroll,183);});

test('a rejected native exit keeps an honest visible exit and can recover on a later allowed exit',async()=>{for(const sync of [false,true]){const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');host.requestFullscreen=async()=>{f.document.fullscreenElement=host;f.document.emit('fullscreenchange');};f.document.exitFullscreen=()=>{if(sync)throw Error('blocked');return Promise.reject(Error('blocked'));};await app.toggleFullscreen();await app.toggleFullscreen();assert(app.isFullscreen());assert.equal(f.$('#ft-fullscreen').textContent,'退出浏览器全屏');assert(f.$('#ft-focus-status').textContent.includes('退出受限'));f.document.exitFullscreen=async()=>{f.document.fullscreenElement=null;f.document.emit('fullscreenchange');};await app.toggleFullscreen();assert(!app.isFullscreen());}});

(async()=>{let failed=0;for(const {name,fn} of tests){try{await fn();console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+'\n'+e.stack);}}fs.rmSync(tmp,{recursive:true,force:true});console.log(JSON.stringify({passed:tests.length-failed,failed,browser:'NOT_RUN'}));process.exitCode=failed?1:0;})();
