'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const base=require('path').resolve(__dirname,'../previews/radar-c2-analysis')+'/',w={};for(const f of ['data/catalog.js','data/literature.js','data/challenge.js','analysis/data/bundle.js'])vm.runInNewContext(fs.readFileSync(base+f,'utf8'),{window:w});const plain=JSON.parse(JSON.stringify(w));for(const key of Object.keys(w))w[key]=plain[key];const M=require(base+'model.js'),A=require(base+'analysis/model.js'),m=M.buildModel(w.PAPER_CATALOG,w.LITERATURE_TREE,w.CHALLENGE_TREE),a=A.build(w.C2_DATA.schema,w.C2_DATA.mapping),before=JSON.stringify(w);let checks=0;function test(name,fn){fn();checks++;console.log('PASS '+name);}
for(const key of ['l','c']){const t=M.atlas.paths(m,key),scene=M.atlas.layout(t,{mode:'full'});test(key+': every source node and path preserved in a complete occurrence tree',()=>{assert.equal(t.sourceCount,m.trees[key].nodes.size);assert.equal(t.nodes.length-1,scene.edges.length);assert.equal(t.by.size,t.nodes.length);assert.equal(t.pathCount,m.trees[key].paths.length);assert.equal(t.paperCount,39);assert.equal(t.nodes.filter(n=>n.type==='ui_root').length,1);for(const path of m.trees[key].paths)assert(t.nodes.some(n=>JSON.stringify(n.path)===JSON.stringify(path.nodeIds)));for(const n of t.nodes){if(n.id===t.root)continue;assert(t.by.has(n.parent));const route=M.atlas.route(t,n.id);assert.equal(new Set(route).size,route.length);assert.equal(route[0],t.root);const sourcePrefix=M.atlas.route(t,n.id).slice(1).map(id=>t.by.get(id).sourceId);assert.deepEqual(sourcePrefix,n.path);}});
 test(key+': SVG has exactly every occurrence and every real parent edge',()=>{const h=M.atlas.svg(t,t.root,key,{mode:'full'});assert.equal((h.match(/data-atlas-id=/g)||[]).length,t.nodes.length);assert.equal((h.match(/data-source=/g)||[]).length,t.nodes.length-1);assert(h.includes(key==='l'?'文献脉络':'挑战与思路'));assert(!h.includes('>UI</text>'));for(const edge of scene.edges)assert.equal(t.by.get(edge.target).parent,edge.source);});
 test(key+': all occurrences locate through the canonical reducer without inventing paths',()=>{for(const n of t.nodes){const next=M.reduce(m,M.initialState(),{type:'locate',key,id:n.id});assert.equal(JSON.stringify(next[key]),JSON.stringify(n.type==='paper_ref'?n.path.slice(0,-1):n.path));assert.equal(next.paper,n.type==='paper_ref'?n.paperId:null);if(next.paper){assert.deepEqual(next.origin.path,n.path);assert(m.papers.has(next.paper));}assert.deepEqual(M.deserialize(m,M.serialize(next)),next);}});
 test(key+': default and alternate geometry stays within viewport, all roots ordered',()=>{for(const width of [400,720,1100])for(const height of [350,620,900]){const g=M.atlas.layout(t,{width,mode:'full'});assert.equal(g.nodes.length,t.nodes.length);for(const n of g.nodes){assert(Number.isFinite(n.x)&&Number.isFinite(n.y));assert(n.x>=0&&n.x+n.w<=g.width&&n.y>=0&&n.y+n.h<=g.height);}const roots=g.nodes.filter(n=>n.depth===1);for(let i=1;i<roots.length;i++)assert(roots[i].y>roots[i-1].y);}});
}
test('analysis: all 72 original/instance vertices and exact 71 source parent edges',()=>{const t=M.atlas.analysis(a),g=M.atlas.layout(t,{mode:'full'});assert.equal(t.nodes.length,72);assert.equal(g.edges.length,71);assert.deepEqual(new Set(t.by.keys()),new Set(a.nodes.keys()));assert.equal(t.by.get(t.root).children.length,5);for(const e of g.edges)assert.equal(e.source,a.nodes.get(e.target).parent);for(const id of a.nodes.keys()){const s=A.locate(a,A.initial(a),id),h=M.atlas.svg(t,s.selected,'a',{mode:'full'});assert.equal((h.match(/data-atlas-id=/g)||[]).length,72);assert.equal((h.match(/aria-current=/g)||[]).length,1);assert(h.includes('data-atlas-id="'+id+'"'));}});
test('all 38 pending papers use 59 source nodes with no copied answers or unresolved evidence',()=>{for(const paper of m.papers.keys()){if(paper==='harnessvln')continue;const pending=A.build(w.C2_DATA.schema,w.C2_DATA.mapping,paper),t=M.atlas.analysis(pending);assert.equal(t.nodes.length,59);assert.equal(pending.answers.size,0);assert.equal(pending.mapping,null);assert.equal(pending.questions.length,0);}});
test('default semantic skeleton preserves every original root and discloses exact folded count',()=>{for(const t of [M.atlas.paths(m,'l'),M.atlas.paths(m,'c'),M.atlas.analysis(a)]){const g=M.atlas.layout(t),ids=new Set(g.nodes.map(n=>n.id));for(const id of t.by.get(t.root).children)assert(ids.has(id));assert.equal(g.visibleCount+g.foldedCount,t.nodes.length);assert(g.visibleCount<t.nodes.length);for(const e of g.edges)assert.equal(t.by.get(e.target).parent,e.source);const h=M.atlas.html(t);assert(h.includes('完整展开'));assert(h.includes(g.foldedCount+' 位置折叠'));}});
test('horizontal focus keeps complete labels, all ancestors and nonoverlapping text boxes for every node/page',()=>{for(const width of [220,366,650,1100])for(const id of a.nodes.keys()){let s=A.locate(a,A.initial(a),id);for(let page=0;page<=A.branch(a,s).maxPage;page++){s=A.reduce(a,s,{type:'page',page});const g=A.layout(a,s,width);for(const n of g.nodes){assert(n.x+n.w<=g.width+.001);assert(n.y+n.h<=g.height+.001);assert.equal(n.labelLines.join(''),a.nodes.get(n.id).label.replace(/\n/g,''));}for(let i=0;i<g.nodes.length;i++)for(let j=i+1;j<g.nodes.length;j++){const n=g.nodes[i],q=g.nodes[j];assert(n.x+n.w<=q.x||q.x+q.w<=n.x||n.y+n.h<=q.y||q.y+q.h<=n.y);}for(const e of g.edges)assert.equal(a.nodes.get(e.target).parent,e.source);}}});
test('the unique Protocol→Paper source-depth-3 leaf uses the Paper column without a fabricated Module',()=>{const protocols=m.trees.l.paths.filter(p=>p.viewKind==='protocol');assert.equal(protocols.length,1);const path=protocols[0],t=M.atlas.paths(m,'l'),leaf=t.nodes.find(n=>JSON.stringify(n.path)===JSON.stringify(path.nodeIds)),parent=t.by.get(leaf.parent),originalIds=new Set(t.nodes.map(n=>n.id));assert.equal(path.nodeIds.length,3);assert.equal(parent.type,'protocol');assert.equal(leaf.type,'paper_ref');for(const mode of ['semantic','full']){const g=M.atlas.layout(t,{selected:leaf.id,mode}),n=g.nodes.find(n=>n.id===leaf.id),p=g.nodes.find(n=>n.id===parent.id);assert.equal(n.depth,3);assert.equal(n.column,4);assert.equal(p.column,2);assert.equal(n.x,g.columnPositions[3]);assert.equal(p.x,g.columnPositions[1]);assert(g.columnPositions[2]<n.x);assert(n.x>p.x+p.w);assert(g.edges.some(e=>e.source===parent.id&&e.target===leaf.id));assert.equal(g.nodes.filter(x=>x.sourceId===path.nodeIds.at(-1)).length>=1,true);assert(g.nodes.every(x=>originalIds.has(x.id)));for(const q of g.nodes.filter(x=>x.type==='paper_ref'))assert.equal(q.x,n.x);const html=M.atlas.svg(t,leaf.id,'l',{mode});assert(html.includes('data-source="'+parent.id+'" data-target="'+leaf.id+'"'));assert(html.includes('data-column="3" x="'+g.columnPositions[2]+'"'));assert(html.includes('data-column="4" x="'+g.columnPositions[3]+'"'));}assert.equal(t.nodes.length,814);assert.equal(t.pathCount,362);assert.equal(t.paperCount,39);assert.deepEqual(leaf.path,path.nodeIds);});
test('neutral task/UI/protocol locations preserve the selected facet; explicit source branches alone switch it',()=>{const t=M.atlas.paths(m,'l');for(const facet of ['pipeline','representation'])for(const n of t.nodes){const before=M.reduce(m,M.initialState(),{type:'facet',facet}),after=M.reduce(m,before,{type:'locate',key:'l',id:n.id}),explicit=n.path.map(id=>m.trees.l.nodes.get(id)).find(node=>['pipeline','representation'].includes(node.type));assert.equal(after.lFacet,explicit?explicit.type:facet,n.sourceId+' silently changed '+facet);if(n.type==='task_contract')assert.equal(after.lFacet,M.reduce(m,before,{type:'root',key:'l',id:n.sourceId}).lFacet);}});
test('shared model is read-only over source, answers, unresolved and scientific state',()=>assert.equal(JSON.stringify(w),before));
console.log(JSON.stringify({checks,kind:'deterministic model/SVG geometry, not browser QA',counts:{literature:814,challenge:132,analysis:72}}));
