'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),{JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),html=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();print(p.render(r,p.payloads(r)[1]))"],{cwd:root,encoding:'utf8',maxBuffer:14e6});
const wait=ms=>new Promise(r=>setTimeout(r,ms)),clean=x=>JSON.parse(JSON.stringify(x));
async function page(){const errors=[],calls=[],v=new VirtualConsole();v.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(html,{url:'https://example.org/research/navigation/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:v,beforeParse(w){w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.fetch=url=>{calls.push(url);return new Promise(()=>{});};}});for(let i=0;i<100&&!d.window.NavigationProductApp;i++)await wait(20);assert.ok(d.window.NavigationProductApp);await frames(d.window);return {w:d.window,calls,errors};}
async function frames(w){await new Promise(r=>w.requestAnimationFrame(()=>w.requestAnimationFrame(r)));}
function visible(w){return [...w.document.querySelectorAll('#np-tree [role=treeitem]')].map(n=>n.dataset.position);}
test('production global startup exposes actual tasks, both branches, roles and exact benchmark links without network',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,b=a.getBundle(),d=w.document;assert.equal(a.getState().route.tree,'g');assert.equal(x.calls.length,0);const nodes=visible(w).map(id=>b.positions[id]);for(const eid of ['legacy:nav:goal','legacy:nav:l','legacy:nav:c','task:pointnav','task:category-objectnav','task:goat'])assert.ok(nodes.some(p=>p.entityId===eid),eid);assert.ok(nodes.filter(p=>p.sourceRootPositionIds).length>=20);assert.equal(d.querySelectorAll('[data-scope-entry]').length,64);assert.equal(d.querySelector('#np-common'),null);assert.ok(d.querySelectorAll('#np-tree .np-task-benchmark').length>=20);const target=d.querySelector('[data-scope-benchmarks="task:category-objectnav"] button');assert.ok(target);target.click();assert.equal(a.getState().route.scope,'task:category-objectnav');assert.ok(b.scopes.find(s=>s.id==='task:category-objectnav').benchmarkIds.includes(a.getState().route.bench));assert.equal(d.querySelector('#np-task-conditions').open,true);assert.deepEqual(x.errors,[]);});
test('global task focus, equivalent outline, zoom and return retain the exact reading context',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),d=w.document,initial=visible(w);d.querySelector('#np-zoom-out').click();assert.equal(M.getBucket(a.getState()).graphScale,.9);const row=b.researchMap.scopeEntries.find(r=>r.scopeId==='task:goat');d.querySelector('[data-scope-entry="task:goat"] button').click();assert.equal(a.getState().route.node,row.canonicalPositionId);const before=visible(w);d.querySelector('#np-layout-toggle').click();assert.equal(a.getState().route.mode,'outline');assert.deepEqual(visible(w),before);d.querySelector('[data-tree-tab=g]').click();assert.equal(a.getState().route.node,b.researchMap.roots[0]);assert.deepEqual(visible(w),initial);const route=clean(a.getState().route);d.querySelector('#np-graph-fullscreen').click();assert.deepEqual(clean(a.getState().route),route,'unsupported fullscreen preserves reading context');assert.deepEqual(x.errors,[]);});
test('an explicit historical version selected from a global work opens that version without borrowing another',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),d=w.document,p=Object.values(b.researchMap.positions).find(p=>p.paperId==='vlfm'&&p.versionId&&b.papers.vlfm.versionIds.length>1);assert.ok(p);a.navigate(M.routeForPosition(b,a.getState().route,p.id));const next=b.papers.vlfm.versionIds.find(v=>v!==p.versionId);d.querySelector('#np-version').value=next;d.querySelector('#np-version').dispatchEvent(new w.Event('change'));assert.equal(a.getState().route.tree,'l');assert.equal(a.getState().route.paper,'vlfm');assert.equal(a.getState().route.version,next);assert.equal(d.querySelector('#np-navigation-error').hidden,true);});
