'use strict';
const fs=require('fs'),assert=require('assert'),path=require('path');
const source=path.join(__dirname,'../previews/radar-trees-c');
const G=require(path.join(source,'graph.js')),data=JSON.parse(fs.readFileSync(path.join(source,'data/graph-data.json'),'utf8'));
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const fresh=()=>G.initialState();
test('public graph contract: 3 tasks, 5 routes, 10 core, 6 candidate, 0 academic edges',()=>{assert.equal(data.tasks.length,3);assert.equal(data.routes.length,5);assert.equal(data.papers.length,10);assert.equal(data.candidates.length,6);assert.deepEqual(data.academic_edges,[]);assert.equal(data.public_only,true);});
test('periods stay separate: today 0; previous weekly 238 / 11 / 6 / 5',()=>{assert.equal(data.daily.date,'2026-10-05');assert.equal(data.daily.candidate_count,0);assert.equal(data.weekly.date,'2026-10-04');assert.equal(data.weekly.candidate_count,238);assert.equal(data.weekly.abstract_count,11);assert.equal(data.weekly.mapping_ids.length,6);assert.equal(data.weekly.unmapped_abstracts.length,5);});
test('default scene is graphical and contains all task / route main branches',()=>{const s=G.buildScene(data,fresh());assert.equal(s.nodes.filter(n=>n.kind==='task').length,3);assert.equal(s.nodes.filter(n=>n.kind==='route').length,5);assert(s.nodes.some(n=>n.kind==='insight'));assert(s.nodes.some(n=>n.kind==='evidence'));assert(s.edges.some(e=>e.cross&&e.active));assert(s.nodes.some(n=>n.dim));});
test('default selects one canonical NavHarness with multiple route memberships',()=>{const s=G.buildScene(data,fresh());assert.equal(s.nodes.filter(n=>n.kind==='paper'&&n.canonical==='navharness').length,1);assert(s.nodes.some(n=>n.id==='challenge-memory-validity-navharness'&&n.active));});
test('all visible edge endpoints exist and all bridges are same paper',()=>{for(const mode of ['baseline','weekly']){const state=fresh();state.mode=mode;const s=G.buildScene(data,state);const nodes=Object.fromEntries(s.nodes.map(n=>[n.id,n]));assert.equal(Object.keys(nodes).length,s.nodes.length);s.edges.forEach(e=>{assert(nodes[e.source]);assert(nodes[e.target]);assert.equal(e.attribution,'curator_organization');if(e.cross){assert.equal(nodes[e.source].canonical,nodes[e.target].canonical);assert.equal(e.same_paper,nodes[e.source].canonical);}});}});
test('synthetic multi-group paper keeps proxy IDs unique and every same-paper bridge',()=>{const modified=JSON.parse(JSON.stringify(data));modified.papers.find(p=>p.canonical_id==='navharness').groups.push('evidence-and-action');const state=fresh();const scene=G.buildScene(modified,state);assert.equal(new Set(scene.nodes.map(n=>n.id)).size,scene.nodes.length);const challenges=scene.nodes.filter(n=>n.kind==='challenge'&&n.canonical==='navharness');assert.equal(challenges.length,2);const papers=scene.nodes.filter(n=>n.kind==='paper'&&n.canonical==='navharness');const bridges=scene.edges.filter(e=>e.same_paper==='navharness');assert.equal(bridges.length,challenges.length*papers.length);assert(bridges.every(e=>challenges.some(n=>n.id===e.target)));});
test('all 10 core identities reachable through progressive route expansion',()=>{const state=fresh();data.routes.forEach(r=>state.expandedRoutes.add(r.id));data.groups.forEach(g=>state.expandedGroups.add(g.id));const s=G.buildScene(data,state);assert.equal(s.uniqueVisible,10);assert.equal(s.nodes.filter(n=>n.kind==='challenge').length,10);});
test('weekly mode reaches exactly 6 candidate identities, not entire pool',()=>{const state=fresh();state.mode='weekly';data.routes.forEach(r=>state.expandedRoutes.add(r.id));const s=G.buildScene(data,state);assert.equal(s.uniqueVisible,6);assert(s.nodes.filter(n=>n.kind==='paper').every(n=>n.candidate));assert(!s.nodes.some(n=>n.kind==='paper'&&n.paper.read_scope==='section'));});
test('two NavHarness papers remain distinct canonical IDs',()=>{const both=data.candidates.filter(p=>p.short_name.startsWith('NavHarness'));assert.equal(both.length,2);assert.notEqual(both[0].canonical_id,both[1].canonical_id);assert.equal(both.find(p=>p.existing_paper_id).canonical_id,'navharness');});
test('candidate source URLs pinned; all scope flags stay false',()=>{data.candidates.forEach(p=>{assert(p.source_url.endsWith(p.versioned_id));assert.equal(p.full_paper_read,false);assert.equal(p.version_comparison_performed,false);assert.equal(p.experiments_independently_verified,false);});data.papers.forEach(p=>assert(/v\d+(?:#.*)?$/.test(p.source_url)));});
test('partial placement is visually encoded; proposals do not become graph branches',()=>{const state=fresh();state.mode='weekly';data.routes.forEach(r=>state.expandedRoutes.add(r.id));const s=G.buildScene(data,state);assert(s.edges.some(e=>e.partial));const branches=s.nodes.filter(n=>n.kind==='route'||n.kind==='task');assert.equal(branches.length,8);assert(!branches.some(n=>n.label.includes('研究空白')));});
test('search matches paper content and no-result is explicit',()=>{const state=fresh();state.search='NavHarness';assert.equal(G.filteredPapers(data,state).length,1);state.search='unlikely-no-paper-xyz';assert(G.buildScene(data,state).empty);});
test('task filtering preserves actual paper task membership',()=>{const state=fresh();state.task='task-continual';const s=G.buildScene(data,state);assert(s.papers.every(p=>p.tasks.includes('task-continual')));assert.equal(s.nodes.filter(n=>n.kind==='task').length,1);});
test('click route expands and collapses repeatedly; challenge does likewise',()=>{const state=fresh(),node={kind:'route',id:'route-runtime'};G.applyAction(state,{type:'toggle',node});assert(state.expandedRoutes.has(node.id));G.applyAction(state,{type:'toggle',node});assert(!state.expandedRoutes.has(node.id));const ch={kind:'challenge',canonical:'navharness'};G.applyAction(state,{type:'toggle',node:ch});assert(!state.expandedChallenges.has('navharness'));G.applyAction(state,{type:'toggle',node:ch});assert(state.expandedChallenges.has('navharness'));});
test('zoom clamps at 65–400%; mode clears stale search and expansion',()=>{const state=fresh();G.applyAction(state,{type:'zoom',value:99});assert.equal(state.zoom,4);G.applyAction(state,{type:'zoom',value:0});assert.equal(state.zoom,.65);state.search='test';state.expandedRoutes.add('route-context');G.applyAction(state,{type:'mode',mode:'weekly'});assert.equal(state.search,'');assert.equal(state.expandedRoutes.size,0);assert.equal(state.selected.canonical,'navharness');});
test('fit geometry contains default, weekly and expanded scenes in desktop/mobile viewports',()=>{for(const mode of ['baseline','weekly']){for(const expanded of [false,true]){const state=fresh();state.mode=mode;if(expanded){data.routes.forEach(r=>state.expandedRoutes.add(r.id));data.groups.forEach(g=>state.expandedGroups.add(g.id));G.activePapers(data,state).forEach(p=>state.expandedChallenges.add(p.canonical_id));}const scene=G.buildScene(data,state);for(const [w,h] of [[1334,535],[1050,510],[390,450]]){const zoom=G.computeFitZoom(w,h,scene.width,scene.height),renderedWidth=w*zoom,renderedHeight=renderedWidth*scene.height/scene.width;assert(renderedWidth<=w+.001);assert(renderedHeight<=h+.001);assert(scene.nodes.every(n=>n.y+n.h<=scene.height));}}}});
test('focus off leaves nodes undimmed without changing underlying graph',()=>{const state=fresh();state.focus=false;const s=G.buildScene(data,state);assert(!s.nodes.some(n=>n.dim));assert(s.edges.some(e=>e.active));});
// Minimal in-memory DOM contract; deliberately not a browser or rendering test.
class Element {
 constructor(tag,doc){this.tagName=tag;this.doc=doc;this.children=[];this.attrs={};this.dataset={};this.style={};this.events={};this.hidden=false;this.value='';this.innerHTML='';this.textContent='';this.scrollTop=0;this.scrollLeft=0;}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='id'){this.id=v;this.doc.ids[v]=this;}if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
 getAttribute(k){return this.attrs[k];} appendChild(c){this.children.push(c);c.parent=this;return c;} removeChild(c){this.children.splice(this.children.indexOf(c),1);} get lastChild(){return this.children.at(-1)||null;} addEventListener(k,fn){(this.events[k]??=[]).push(fn);} fire(k,event={}){this.events[k]?.forEach(fn=>fn({target:this,preventDefault(){},...event}));} focus(){this.doc.focused=this;} scrollIntoView(){this.scrolled=true;}
}
function fakeDocument(){const doc={ids:{},createElementNS(ns,t){return new Element(t,this);},createElement(t){return new Element(t,this);},getElementById(id){return this.ids[id];},querySelectorAll(selector){if(selector==='[data-mode]')return [this.ids['mode-baseline'],this.ids['mode-weekly']];if(selector==='[data-tab]')return ['overview','evidence','conditions'].map(x=>this.ids['tab-'+x]);return [];}};const html=fs.readFileSync(path.join(source,'index.html'),'utf8');for(const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"[^>]*>/g)){const el=new Element(match[1],doc);el.setAttribute('id',match[2]);for(const a of match[0].matchAll(/(data-[\w-]+)="([^"]*)"/g))el.setAttribute(a[1],a[2]);}return doc;}
const doc=fakeDocument(),app=G.mount(doc,data),$=id=>doc.getElementById(id);
test('mounted default has real SVG nodes, canonical IDs, accessible controls',()=>{assert.equal($('research-graph').getAttribute('viewBox').split(' ')[2],'1280');assert.equal($('node-task-vln').getAttribute('role'),'button');assert.equal($('expand-challenge-memory-validity-navharness').getAttribute('aria-expanded'),'true');assert($('selection-summary').innerHTML.includes('统一论文 ID：navharness'));});
test('mounted click & repeated click really expand / collapse route DOM',()=>{$('expand-route-runtime').fire('click');assert(app.getState().expandedRoutes.has('route-runtime'));assert.equal($('expand-route-runtime').getAttribute('aria-expanded'),'true');$('expand-route-runtime').fire('click');assert(!app.getState().expandedRoutes.has('route-runtime'));});
test('mounted keyboard works for node expansion and evidence tab',()=>{$('expand-challenge-memory-validity-navharness').fire('keydown',{key:'Enter'});assert.equal($('expand-challenge-memory-validity-navharness').getAttribute('aria-expanded'),'false');$('expand-challenge-memory-validity-navharness').fire('keydown',{key:' '});$('node-evidence-memory-validity-navharness').fire('click');assert.equal(app.getState().tab,'evidence');assert($('detail-content').innerHTML.includes('§3.3–3.5'));$('tab-evidence').fire('keydown',{key:'ArrowRight'});assert.equal(app.getState().tab,'conditions');});
test('weekly toggle resets cleanly and never inherits baseline body evidence',()=>{$('mode-weekly').fire('click');assert.equal(app.getState().mode,'weekly');assert($('selection-summary').innerHTML.includes('10-04 周窗'));assert($('detail-content').innerHTML.includes('本轮未读全文'));$('tab-evidence').fire('click');assert($('detail-content').innerHTML.includes('Abstract'));assert(!$('detail-content').innerHTML.includes('§3.3–3.5'));assert($('detail-content').innerHTML.includes('2609.34276v1'));});
test('weekly partial fit and conditions are displayed on selected candidate',()=>{app.selectPaper('arxiv:2609.39166');$('tab-evidence').fire('click');assert($('detail-content').innerHTML.includes('部分贴合'));$('tab-conditions').fire('click');assert($('detail-content').innerHTML.includes('未创建'));assert($('detail-content').innerHTML.includes('非研究空白'));});
test('mounted search, Escape reset, no-result, task filter and clear filter',()=>{$('graph-search').value='unlikely-no-paper-xyz';$('graph-search').fire('input');assert.equal($('graph-empty').hidden,false);$('graph-search').fire('keydown',{key:'Escape'});assert.equal($('graph-empty').hidden,true);$('task-filter').value='task-vln';$('task-filter').fire('change');assert(app.getScene().papers.every(p=>p.tasks.includes('task-vln')));$('clear-filters').fire('click');assert.equal(app.getState().task,'all');});
test('mounted focus toggle, zoom, fit, reset, scope and clear controls',()=>{$('focus-path').checked=false;$('focus-path').fire('change');assert(!app.getScene().nodes.some(n=>n.dim));$('zoom-in').fire('click');assert.equal(app.getState().zoom,1.15);$('zoom-fit').fire('click');assert.equal(app.getState().zoom,1);$('scope-details').fire('click');assert.equal($('scope-notes').open,true);$('clear-selection').fire('click');assert.equal(app.getState().selected,null);$('graph-reset').fire('click');assert.equal(app.getState().mode,'weekly');assert.equal(app.getState().selected.canonical,'navharness');assert.equal(app.getState().focus,true);});
test('mounted fit preserves readable scale and resets both scroll axes',()=>{const viewport=$('graph-viewport');viewport.clientWidth=1334;viewport.clientHeight=535;viewport.scrollTop=75;viewport.scrollLeft=40;$('zoom-fit').fire('click');const expected=Math.max(G.computeFitZoom(1334,535,1280,app.getScene().height),1280*.95/1334);assert.equal(app.getState().zoom,expected);assert.equal($('research-graph').style.minWidth,'0');assert.equal(viewport.scrollLeft,0);assert.equal(viewport.scrollTop,0);$('mode-baseline').fire('click');assert.equal(app.getState().zoom,Math.max(G.computeFitZoom(1334,535,1280,app.getScene().height),1280*.95/1334));});
test('search excluding selected NavHarness clears selection and stale sidebar',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('graph-search').value='HarnessVLN';e('graph-search').fire('input');assert.equal(a.getState().selected,null);assert.deepEqual(a.getScene().papers.map(p=>p.canonical_id),['harnessvln']);assert(!e('selection-summary').innerHTML.includes('NavHarness'));assert(!e('detail-content').innerHTML.includes('§3.3–3.5'));assert(e('detail-content').innerHTML.includes('筛选变更已清除原选中论文'));assert.equal(e('detail-tabs').hidden,true);a.selectPaper('harnessvln');assert.equal(a.getState().selected.canonical,'harnessvln');assert.equal(a.getState().selectionNotice,'');});
test('task filter excluding selected NavHarness clears selection; retained matching selection stays valid',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('task-filter').value='task-continual';e('task-filter').fire('change');assert.equal(a.getState().selected.canonical,'navharness');assert.equal(a.getState().selectionNotice,'');e('task-filter').value='task-vln';e('task-filter').fire('change');assert.equal(a.getState().selected,null);assert(!e('selection-summary').innerHTML.includes('NavHarness'));assert(e('detail-content').innerHTML.includes('选择已随筛选更新'));assert(a.getScene().papers.every(p=>p.tasks.includes('task-vln')));e('clear-filters').fire('click');assert.equal(a.getState().selected,null);assert.equal(a.getState().task,'all');});
test('mobile fit/reset preserves readable 13.3px text and zoom still reaches native SVG scale',()=>{for(const width of [720,360]){const d=fakeDocument(),e=id=>d.getElementById(id);e('graph-viewport').clientWidth=width;e('graph-viewport').clientHeight=450;const a=G.mount(d,data);assert.equal(a.getState().zoom,Math.max(G.computeFitZoom(width,450,1280,a.getScene().height),1280*.95/width));assert.equal(e('zoom-in').disabled,false);let steps=0;while(!e('zoom-in').disabled&&steps++<40)e('zoom-in').fire('click');assert.equal(a.getState().zoom,4);assert.equal(e('zoom-in').disabled,true);assert(width*a.getState().zoom>=1280);assert(14*(width*a.getState().zoom/1280)>=14);e('zoom-out').fire('click');assert.equal(a.getState().zoom,3.85);assert.equal(e('zoom-in').disabled,false);e('zoom-fit').fire('click');assert(width*a.getState().zoom>=1280*.95-.001);e('zoom-in').fire('click');e('graph-reset').fire('click');assert.equal(a.getState().zoom,Math.max(G.computeFitZoom(width,450,1280,a.getScene().height),1280*.95/width));assert.equal(a.getState().selected.canonical,'navharness');assert.equal(e('zoom-in').disabled,false);}});
test('source data loads without fetch and relative text routes match integration',()=>{const js=fs.readFileSync(path.join(source,'graph.js'),'utf8'),html=fs.readFileSync(path.join(source,'index.html'),'utf8');assert(!/\bfetch\s*\(/.test(js));assert(html.includes('data/graph-data.js'));assert(html.includes('href="literature.html"'));assert(html.includes('href="challenge.html"'));assert(html.includes('href="weekly-2026-10-04.html"'));assert(!html.includes('../literature.html'));assert(html.includes('<noscript>'));});

test('view card does not toggle expansion; explicit control toggles repeatedly',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('node-route-runtime').fire('click');assert(!a.getState().expandedRoutes.has('route-runtime'));assert.equal(e('node-route-runtime').getAttribute('aria-expanded'),undefined);e('expand-route-runtime').fire('click');assert(a.getState().expandedRoutes.has('route-runtime'));assert.equal(a.getState().selected.kind,'route');e('node-route-runtime').fire('click');assert(a.getState().expandedRoutes.has('route-runtime'));e('expand-route-runtime').fire('click');assert(!a.getState().expandedRoutes.has('route-runtime'));});
test('AgenticNav has one canonical node, two incoming routes, correct memberships and readable reveal',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('graph-viewport').clientWidth=820;e('graph-viewport').clientHeight=510;e('expand-route-runtime').fire('click');const id='paper-agenticnav-tool-harness';e('node-'+id).fire('click');const scene=a.getScene(),cards=scene.nodes.filter(n=>n.canonical==='agenticnav-tool-harness'&&n.kind==='paper');assert.equal(cards.length,1);assert.equal(cards[0].routeCount,2);assert.equal(cards.filter(n=>n.selected).length,1);assert.equal(scene.edges.filter(x=>x.target===id&&x.source.startsWith('route-')).length,2);assert.equal(a.getState().selected.id,id);assert(e('selection-summary').innerHTML.includes('所属路线（2）：运行与反馈闭环 / 上下文分配'));assert.equal(e('detail-title').textContent,'选中论文');assert(e('current-path').textContent.includes('AgenticNav · 论文；所属路线：运行与反馈闭环 / 上下文分配'));assert(e('visible-count').textContent.includes('篇独立论文'));assert(e('visible-count').textContent.includes('条路线关联'));assert(e('graph-viewport').scrollTop>0);const scale=820*a.getState().zoom/1280,targets=scene.nodes.filter(n=>n.canonical==='agenticnav-tool-harness'&&['challenge','insight','evidence'].includes(n.kind));assert(Math.max(...targets.map(n=>(n.y+n.h)*scale))<=e('graph-viewport').scrollTop+510);e('graph-viewport').scrollTop=0;e('locate-selection').fire('click');assert(e('graph-viewport').scrollTop>0);a.getState().zoom=4;e('locate-selection').fire('click');assert(a.getState().zoom<4);assert(820*a.getState().zoom/1280>=.95);e('clear-selection').fire('click');assert.equal(e('locate-selection').disabled,true);});
test('problem card opens detail without hiding insight; expansion remains explicit',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id),id='challenge-memory-validity-navharness';e('node-'+id).fire('click');assert(a.getState().expandedChallenges.has('navharness'));assert.equal(e('detail-title').textContent,'选中本文问题');e('expand-'+id).fire('click');assert(!a.getState().expandedChallenges.has('navharness'));});
test('context text is not faded and controls have visible verb labels',()=>{const css=fs.readFileSync(path.join(source,'graph.css'),'utf8'),html=fs.readFileSync(path.join(source,'index.html'),'utf8');assert(css.includes('.graph-node.dim{opacity:1}'));assert(!css.includes('.graph-node.dim{opacity:.25}'));assert(html.includes('定位选中'));assert(html.includes('点卡片查看'));});
test('Escape restores graph keyboard focus after redraw',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id),id='node-paper-navharness';e('graph-viewport').fire('keydown',{key:'Escape',target:e(id)});assert.equal(a.getState().selected,null);assert.equal(d.focused,e(id));});
test('64 mode/filter/search/expansion combinations keep canonical papers unique and applicable route edges complete',()=>{for(const mode of ['baseline','weekly'])for(const task of ['all',...data.tasks.map(t=>t.id)])for(const search of ['', 'NavHarness', 'AgenticNav', 'no-match-xyz'])for(const expanded of [false,true]){const state=fresh();Object.assign(state,{mode,task,search});if(expanded)data.routes.forEach(r=>state.expandedRoutes.add(r.id));G.reconcileSelection(data,state);const scene=G.buildScene(data,state),papers=scene.nodes.filter(n=>n.kind==='paper'),routes=scene.nodes.filter(n=>n.kind==='route');assert.equal(new Set(papers.map(n=>n.canonical)).size,papers.length);assert.equal(scene.uniqueVisible,papers.length);for(const n of papers){assert.equal(n.id,'paper-'+n.canonical);const expected=routes.filter(r=>n.paper.routes.includes(r.id)).map(r=>r.id).sort();assert.deepEqual(scene.edges.filter(e=>e.target===n.id&&!e.cross).map(e=>e.source).sort(),expected);assert.deepEqual(n.routeIds.slice().sort(),expected);}assert.equal(scene.routeLinks,scene.edges.filter(e=>e.source.startsWith('route-')&&e.target.startsWith('paper-')).length);}});
test('multi-task memberships survive filtering and route expansion without duplicate cards',()=>{const p=data.papers.find(p=>p.tasks.length>1&&p.routes.length>1);assert(p);for(const task of p.tasks){const state=fresh();state.task=task;state.selected={kind:'paper',canonical:p.canonical_id};const scene=G.buildScene(data,state);assert.equal(scene.nodes.filter(n=>n.kind==='paper'&&n.canonical===p.canonical_id).length,1);assert(scene.nodes.some(n=>n.kind==='task'&&n.id===task));assert(scene.papers.every(n=>n.tasks.includes(task)));}});
test('repeated expansion/collapse keeps one selected AgenticNav with two incoming routes',()=>{const state=fresh();state.selected={kind:'paper',canonical:'agenticnav-tool-harness'};for(let i=0;i<6;i++){G.applyAction(state,{type:'toggle',node:{kind:'route',id:'route-runtime'}});G.applyAction(state,{type:'select',node:{kind:'paper',id:'paper-agenticnav-tool-harness',canonical:'agenticnav-tool-harness'}});const scene=G.buildScene(data,state);assert.equal(scene.nodes.filter(n=>n.kind==='paper'&&n.canonical==='agenticnav-tool-harness').length,1);assert.equal(scene.edges.filter(e=>e.target==='paper-agenticnav-tool-harness').length,2);}});
test('aggregated paper cards do not overlap when all routes expand',()=>{for(const mode of ['baseline','weekly']){const state=fresh();state.mode=mode;data.routes.forEach(r=>state.expandedRoutes.add(r.id));const scene=G.buildScene(data,state),nodes=scene.nodes.filter(n=>n.kind==='paper').sort((a,b)=>a.y-b.y);nodes.slice(1).forEach((n,i)=>assert(n.y>=nodes[i].y+nodes[i].h+12));assert(nodes.every(n=>n.y+n.h<=scene.height));}});


test('expansion controls preserve selected paper and evidence tab',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);a.selectPaper('agenticnav-tool-harness');e('tab-evidence').fire('click');const selected=JSON.stringify(a.getState().selected);e('expand-route-runtime').fire('click');assert.equal(JSON.stringify(a.getState().selected),selected);assert.equal(a.getState().tab,'evidence');assert(e('detail-title').textContent==='选中论文');e('expand-challenge-context-allocation-agenticnav-tool-harness').fire('click');assert.equal(JSON.stringify(a.getState().selected),selected);assert.equal(a.getState().tab,'evidence');});


test('collapsing selected child returns details to its parent and keeps collapse-button focus',()=>{for(const kind of ['insight','evidence']){const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id),group='memory-validity-navharness';e('node-'+kind+'-'+group).fire('click');assert.equal(a.getState().selected.kind,kind);e('expand-challenge-'+group).fire('keydown',{key:'Enter'});assert.equal(a.getState().selected.kind,'challenge');assert.equal(a.getState().selected.id,'challenge-'+group);assert.equal(a.getState().tab,'overview');assert.equal(e('detail-title').textContent,'选中本文问题');assert.equal(d.focused,e('expand-challenge-'+group));assert(!a.getScene().nodes.some(n=>n.kind===kind&&n.canonical==='navharness'));e('expand-challenge-'+group).fire('click');assert.equal(a.getState().selected.kind,'challenge');}});

const report={checks:count,status:'passed',coverage:'Pure graph/data model and in-memory DOM contracts only. No browser, server, screenshots or visual acceptance.',baseline_visible_nodes:G.buildScene(data,fresh()).nodes.length,baseline_core_papers:data.papers.length,candidate_count:data.candidates.length,academic_edges:data.academic_edges.length};

console.log(`\n${count} checks passed. Not browser-rendered or visually accepted.`);
