const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib'),{JSDOM}=require('jsdom'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),M=require('../assets/navigation-product-model.js'),raw=zlib.gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz'))),b=JSON.parse(raw);
const html=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();print(p.render(r,p.payloads(r)[1]))"],{cwd:root,encoding:'utf8',maxBuffer:12e6});
async function boot(bundle=b,hash='',saved=null){const d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/'+hash,runScripts:'outside-only',pretendToBeVisual:true}),w=d.window;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,writable:true,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};w.NAVIGATION_PRODUCT=bundle;if(saved)w.history.replaceState(saved,'',w.location.href);for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await new Promise(r=>setTimeout(r,35));return d;}
function select(w,p){w.NavigationProductApp.navigate(M.routeForPosition(b,w.NavigationProductApp.getState().route,p.id),{cross:true});}
const positions=Object.values(b.positions);
test('frozen model and all task forests have valid identities',()=>{assert.equal(M.validateBundle(b),b);for(const s of b.scopes){const state=M.initialState(b,{scope:s.id});assert.equal(M.validateState(b,state),state);}});
for(const bad of ['constructor','__proto__','missing'])test('reject prototype/unknown scope '+bad,()=>assert.throws(()=>M.validateRoute(b,{scope:bad})));
test('task is not a benchmark',()=>assert.throws(()=>M.validateRoute(b,{scope:'scope:all',bench:'task:category-objectnav'})));
test('generic reference actually contains all original nodes',()=>{const x=structuredClone(b),root=x.template.roots[0],ids=M.descendants(x,[root]),leaf=ids.find(id=>x.positions[id].childIds.length===0),p=x.positions[leaf];x.positions[p.parentId].childIds=x.positions[p.parentId].childIds.filter(id=>id!==leaf);delete x.positions[leaf];assert.throws(()=>M.validateBundle(x));});
test('real three-tree DOM, startup coverage and equivalent outline',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document;assert.ok(w.NavigationProductApp);assert.equal(doc.querySelectorAll('.np-tabs [data-tree-tab]').length,3);assert.ok(doc.querySelectorAll('[role=treeitem]').length>1);assert.equal(doc.querySelector('#np-recommended'),null,'global discovery replaces preferred-six cards');doc.getElementById('np-layout-toggle').click();assert.equal(w.NavigationProductApp.getState().route.mode,'outline');assert.equal(doc.getElementById('np-tree').dataset.mode,'outline');assert.ok(doc.getElementById('np-coverage-table').textContent.includes('未'));});
for(const scope of ['task:category-objectnav','task:goat','task:instanceimagenav','task:vln','task:vln-ce','task:pointnav'])test('actual literature and challenge DOM: '+scope,async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window;w.NavigationProductApp.navigate({scope,tree:'l'});assert.equal(w.NavigationProductApp.getState().route.scope,scope);assert.ok(w.document.querySelectorAll('[role=treeitem]').length);w.document.querySelector('[data-tree-tab=c]').click();assert.equal(w.NavigationProductApp.getState().route.tree,'c');assert.ok(w.document.getElementById('np-tree-caption').textContent.length);});
test('PONI method -> CI -> original analysis -> explicit return',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const start=w.NavigationProductApp.getState().route;assert.match(doc.getElementById('np-detail-content').textContent,/FMM/);const ci=[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent.startsWith('挑战'));assert.ok(ci);ci.click();assert.equal(w.NavigationProductApp.getState().route.tree,'c');const analysis=[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent==='消融证据');assert.ok(analysis);analysis.click();assert.equal(w.NavigationProductApp.getState().route.tree,'a');assert.equal(w.NavigationProductApp.getState().route.paper,'poni');assert.match(doc.getElementById('np-detail-content').textContent,/Table|表|消融/);doc.querySelector('#np-origin-trail .np-reading-history').open=true;const trail=doc.querySelectorAll('#np-origin-trail .np-reading-history button')[1];assert.ok(trail);trail.click();assert.equal(w.NavigationProductApp.getState().route.node,start.node);});
test('reference mode retains unread paper version and zero answers',async t=>{const p=positions.find(p=>p.paperId==='harnessvln'&&p.tree==='l'&&String(p.versionId).includes('v1'));assert.ok(p);const r=M.routeForPosition(b,{scope:p.scopeId},p.id);Object.assign(r,{tree:'a',node:null,claim:null,template:'1'});const d=await boot(b,M.encodeRoute(r));t.after(()=>d.window.close());const w=d.window;assert.ok(w.NavigationProductApp);assert.equal(w.NavigationProductApp.getState().route.version,p.versionId);assert.match(w.document.body.textContent,/未填|未绑定/);assert.equal(M.descendants(b,M.roots(b,r)).length,59);assert.ok(M.descendants(b,M.roots(b,r)).every(id=>b.positions[id].genericTemplate));});
test('invalid deep link never substitutes another paper',async t=>{const d=await boot(b,'#nav=1&scope=constructor');t.after(()=>d.window.close());assert.equal(d.window.NavigationProductApp,undefined);assert.equal(d.window.document.getElementById('np-workspace').hidden,true);});
test('damaged model fails closed',async t=>{const x=structuredClone(b);delete x.positions[x.template.roots[0]];const d=await boot(x);t.after(()=>d.window.close());assert.equal(d.window.NavigationProductApp,undefined);assert.equal(d.window.document.getElementById('navigation-product').dataset.error,'true');});
const settle=async w=>{await new Promise(r=>setTimeout(r,65));if(w&&typeof w.requestAnimationFrame==='function')await new Promise(r=>w.requestAnimationFrame(()=>w.requestAnimationFrame(r)));};
test('new cross-tree target resets DOM scroll; origin and browser history restore exact source',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);await settle(w);const start=w.NavigationProductApp.getState().route;doc.getElementById('np-detail-scroll').scrollTop=570;doc.getElementById('np-tree-scroll').scrollTop=130;w.scrollTo(0,250);[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent.startsWith('挑战')).click();await settle(w);assert.equal(doc.getElementById('np-detail-scroll').scrollTop,0);assert.equal(doc.getElementById('np-tree-scroll').scrollTop,0);w.history.back();await settle(w);assert.equal(w.NavigationProductApp.getState().route.node,start.node);assert.equal(doc.getElementById('np-detail-scroll').scrollTop,570);assert.equal(doc.getElementById('np-tree-scroll').scrollTop,130);assert.equal(w.scrollY,250);w.history.forward();await settle(w);assert.equal(w.NavigationProductApp.getState().route.tree,'c');doc.querySelector('#np-origin-trail .np-reading-history').open=true;doc.querySelectorAll('#np-origin-trail .np-reading-history button')[1].click();await settle(w);assert.equal(w.NavigationProductApp.getState().route.node,start.node);assert.equal(doc.getElementById('np-detail-scroll').scrollTop,570);});
test('keyboard hierarchy and bounded narrow indentation remain genuine tree structure',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,first=doc.querySelector('[role=treeitem]');first.focus();first.dispatchEvent(new w.KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));assert.notEqual(doc.activeElement,first);const selected=doc.activeElement.dataset.position;doc.activeElement.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));await settle(w);assert.equal(w.NavigationProductApp.getState().route.node,selected);assert.equal(doc.activeElement.dataset.position,selected);const css=fs.readFileSync(path.join(root,'assets/navigation-product.css'),'utf8');assert.ok(css.includes('.np-tree ul ul ul,.np-tree ul.np-tree-deep{margin-left:0;padding-left:0;border-left:0}'));assert.ok(doc.querySelector('[aria-level] .np-node-level'));});
test('legacy full-data fetch path rejects missing or changed data before mounting trees',async t=>{for(const kind of ['404','bytes']){const d=new JSDOM(zlib.gunzipSync(fs.readFileSync(path.join(root,'tests/fixtures/navigation-pr52-startup.html.gz'))).toString('utf8'),{url:'https://example.org/RoboPaperAtlas/research/navigation/',runScripts:'outside-only'});t.after(()=>d.window.close());const w=d.window;w.fetch=async()=>({ok:kind!=='404',status:404,arrayBuffer:async()=>new TextEncoder().encode('{}').buffer});Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextDecoder=TextDecoder;for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await settle(w);assert.equal(w.NavigationProductApp,undefined);assert.equal(w.document.getElementById('np-workspace').hidden,true);assert.equal(w.document.getElementById('navigation-product').dataset.error,'true');}});
test('legacy full-data loader accepts only the pinned exact scientific bytes',async t=>{const d=new JSDOM(zlib.gunzipSync(fs.readFileSync(path.join(root,'tests/fixtures/navigation-pr52-startup.html.gz'))).toString('utf8'),{url:'https://example.org/RoboPaperAtlas/research/navigation/',runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>d.window.close());const w=d.window;const historicRaw=zlib.gunzipSync(fs.readFileSync(path.join(root,'tests/fixtures/navigation-product-pr52-1229.json.gz')));assert.equal(require('node:crypto').createHash('sha256').update(historicRaw).digest('hex'),'1229372f697316dc5c0627995fce7de18496160d85f4a1acb4ffc2a6faf1d708');w.fetch=async url=>{assert.ok(url.startsWith('product-data.json?v=1229372f'));return {ok:true,arrayBuffer:async()=>historicRaw.buffer.slice(historicRaw.byteOffset,historicRaw.byteOffset+historicRaw.byteLength)};};Object.defineProperty(w,'crypto',{value:require('node:crypto').webcrypto});w.TextDecoder=TextDecoder;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));await settle(w);assert.ok(w.NavigationProductApp);assert.ok(w.document.querySelector('[role=treeitem]'));});
test('dense evidence is optional and exact claim links open the matching evidence',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const evidence=w.document.querySelector('#np-detail-content details.np-evidence');assert.ok(evidence);assert.equal(evidence.open,false);assert.ok(w.document.querySelector('.np-pipeline'));const claim=evidence.querySelector('[data-claim-id]').dataset.claimId;w.NavigationProductApp.navigate(Object.assign({},w.NavigationProductApp.getState().route,{claim}));assert.equal(w.document.querySelector('#np-detail-content details.np-evidence').open,true);});
test('directory search never repeats nested family members',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,input=w.document.getElementById('np-directory-search');input.value='交互';input.dispatchEvent(new w.Event('input'));const labels=[...w.document.querySelectorAll('#np-directory-list .np-directory-row button')].map(n=>n.textContent);assert.ok(labels.length);assert.equal(new Set(labels).size,labels.length);});

test('missing generic reference root fails closed',()=>{const x=structuredClone(b);x.template.roots=[];assert.throws(()=>M.validateBundle(x));});
test('PONI recipe exposes exact typed SemExp reuse and replacement evidence',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);const relation=w.document.querySelector('[data-relation-type=explicit_component_reuse_and_policy_replacement]');assert.ok(relation);assert.match(relation.textContent,/复用|替换/);assert.ok(relation.querySelector('[data-claim-id="method-edge:89"]'));assert.ok(relation.closest('details'));});

test('reselecting the same paper or version preserves explicit unread reference context',async t=>{const p=positions.find(p=>p.paperId==='harnessvln'&&p.tree==='l'&&String(p.versionId).includes('v1'));const r=Object.assign(M.routeForPosition(b,{scope:p.scopeId},p.id),{tree:'a',node:null,claim:null,template:'1'}),d=await boot(b,M.encodeRoute(r));t.after(()=>d.window.close());const w=d.window;for(const id of ['np-paper','np-version']){w.document.getElementById(id).dispatchEvent(new w.Event('change'));assert.equal(w.NavigationProductApp.getState().route.version,p.versionId);assert.equal(w.NavigationProductApp.getState().route.template,'1');}});
test('skip link focuses and scrolls workspace without replacing canonical reading URL or origin',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);await settle(w);const before=w.NavigationProductApp.getState(),hash=w.location.hash,length=w.history.length;const calls=[];w.HTMLElement.prototype.scrollIntoView=function(){calls.push(this.id);if(this.id==='np-workspace')w.scrollTo(0,896);};for(let i=0;i<2;i++){const allowed=doc.querySelector('.np-skip').dispatchEvent(new w.MouseEvent('click',{bubbles:true,cancelable:true}));assert.equal(allowed,false);await settle(w);assert.equal(doc.activeElement.id,'np-tree-heading');assert.equal(w.scrollY,896);assert.equal(w.location.hash,hash);assert.equal(w.history.length,length);assert.deepEqual(w.NavigationProductApp.getState().route,before.route);assert.equal(w.NavigationProductApp.getState().originTrail.length,before.originTrail.length);}assert.deepEqual(calls,['np-workspace','np-workspace']);});
test('skip activation before loading waits for real workspace and preserves a fixed-paper cold deep link',async t=>{const p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe'),route=M.routeForPosition(b,{scope:p.scopeId},p.id),hash=M.encodeRoute(route),d=new JSDOM(html,{url:'https://example.org/RoboPaperAtlas/research/navigation/'+hash,runScripts:'outside-only',pretendToBeVisual:true});t.after(()=>d.window.close());const w=d.window;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,writable:true,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){if(this.id==='np-workspace')w.scrollTo(0,896);};w.NAVIGATION_PRODUCT=b;for(const n of ['navigation-product-model.js','navigation-product.js'])w.eval(fs.readFileSync(path.join(root,'assets',n),'utf8'));w.document.querySelector('.np-skip').click();for(let i=0;i<200&&!w.NavigationProductApp;i++)await new Promise(r=>setTimeout(r,5));assert.ok(w.NavigationProductApp);for(let i=0;i<3;i++)await new Promise(r=>w.requestAnimationFrame(r));assert.equal(w.document.activeElement.id,'np-tree-heading');assert.equal(w.scrollY,896);assert.equal(w.location.hash,hash);assert.equal(w.NavigationProductApp.getState().route.paper,'poni');assert.equal(w.NavigationProductApp.getState().route.version,p.versionId);});
test('ordinary workspace fragment is an accessible jump and never a substituted paper route',async t=>{const d=await boot(b,'#np-workspace');t.after(()=>d.window.close());const w=d.window;await settle(w);assert.ok(w.NavigationProductApp);assert.equal(w.document.activeElement.id,'np-tree-heading');assert.equal(w.NavigationProductApp.getState().route.scope,'task:category-objectnav');});
test('Back to an ordinary workspace fragment restores its own paper/version/reference snapshot',async t=>{const hp=positions.find(p=>p.paperId==='harnessvln'&&p.tree==='l'&&String(p.versionId).includes('v1')),r=Object.assign(M.routeForPosition(b,{scope:hp.scopeId},hp.id),{tree:'a',node:null,claim:null,template:'1'}),d=await boot(b,M.encodeRoute(r));t.after(()=>d.window.close());const w=d.window;w.location.hash='np-workspace';await settle(w);const bound=w.NavigationProductApp.getState().route;assert.equal(bound.paper,'harnessvln');const pp=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,pp);await settle(w);assert.equal(w.NavigationProductApp.getState().route.paper,'poni');w.history.back();await settle(w);assert.equal(w.location.hash,'#np-workspace');assert.deepEqual(w.NavigationProductApp.getState().route,bound);assert.equal(w.document.activeElement.id,'np-tree-heading');});
test('a queued skip cannot overwrite a newer cross-tree route or inherit its source scroll',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,doc=w.document,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);await settle(w);doc.getElementById('np-detail-scroll').scrollTop=570;doc.getElementById('np-tree-scroll').scrollTop=140;const queue=[];w.requestAnimationFrame=fn=>{queue.push(fn);return queue.length;};doc.querySelector('.np-skip').click();[...doc.querySelectorAll('.np-cross-link')].find(n=>n.textContent.startsWith('挑战')).click();while(queue.length)queue.shift()();const state=w.NavigationProductApp.getState();assert.equal(state.route.tree,'c');assert.equal(doc.getElementById('np-detail-scroll').scrollTop,0);assert.equal(doc.getElementById('np-tree-scroll').scrollTop,0);assert.equal(w.NavigationProductModel.getBucket(state).detailScrollByTree.c,0);assert.equal(state.originTrail.at(-1).bucket.detailScrollByTree.l,570);assert.equal(doc.activeElement.dataset.position,state.route.node);});
test('repeated Back and Forward between ordinary anchor and canonical paper stays synchronized',async t=>{const d=await boot(b,'#np-workspace');t.after(()=>d.window.close());const w=d.window;await settle(w);const initial=w.NavigationProductApp.getState().route,p=positions.find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');select(w,p);await settle(w);const target=w.NavigationProductApp.getState().route;for(let i=0;i<3;i++){w.history.back();await settle(w);assert.equal(w.location.hash,'#np-workspace');assert.deepEqual(w.NavigationProductApp.getState().route,initial);w.history.forward();await settle(w);assert.equal(w.location.hash,M.encodeRoute(target));assert.equal(M.encodeRoute(w.NavigationProductApp.getState().route),M.encodeRoute(target));}});
test('AudioGoal CI resolves its declared design to readable fixed-version method and exact cross-tree link',async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,p=positions.find(p=>p.tree==='c'&&p.scopeId==='task:audiogoal'&&p.entityId==='methods:insight:adjacent:avnav-audio');assert.ok(p);select(w,p);const block=w.document.querySelector('.np-design-reference');assert.ok(block);assert.match(block.textContent,/CNN/);assert.match(block.textContent,/GRU/);assert.match(block.textContent,/PPO/);assert.doesNotMatch(block.textContent,/pipeline-adjacent/);block.querySelector('button').click();const r=w.NavigationProductApp.getState().route;assert.equal(r.tree,'l');assert.equal(r.paper,p.paperId);assert.equal(r.version,p.versionId);assert.equal(b.positions[r.node].entityId,'methods:pipeline-adjacent-avnav-audio');});
for(const kind of ['missing','other-version','other-paper','other-paper-canonical-id'])test('design reference fails closed for '+kind,async t=>{const x=structuredClone(b),p=positions.find(p=>p.tree==='c'&&p.scopeId==='task:audiogoal'&&p.entityId==='methods:insight:adjacent:avnav-audio'),target=x.entities['methods:pipeline-adjacent-avnav-audio'];if(kind==='missing')x.entities[p.entityId].detail.design='pipeline-not-imported';if(kind==='other-version')target.versionIds=[];if(kind==='other-paper')x.entities[p.entityId].detail.design='pipeline-poni';if(kind==='other-paper-canonical-id')x.entities[p.entityId].detail.design='methods:pipeline-poni';const d=await boot(x);t.after(()=>d.window.close());const w=d.window;select(w,p);const block=w.document.querySelector('[data-design-unresolved]');assert.ok(block);assert.match(block.textContent,/待核对/);assert.equal(block.querySelectorAll('button').length,0);assert.doesNotMatch(block.textContent,/CNN|PPO|pipeline-not-imported/);});
for(const kind of ['missing-version','missing-paper-and-version'])test('design cannot borrow a recipe when source position identity is '+kind,async t=>{const x=structuredClone(b),original=positions.find(p=>p.tree==='c'&&p.scopeId==='task:audiogoal'&&p.entityId==='methods:insight:adjacent:avnav-audio'),p=x.positions[original.id];p.versionId=null;if(kind==='missing-paper-and-version'){p.paperId=null;x.entities[p.entityId].paperId=null;}const d=await boot(x);t.after(()=>d.window.close());const w=d.window;assert.ok(w.NavigationProductApp);select(w,original);const block=w.document.querySelector('[data-design-unresolved]');assert.ok(block);assert.equal(block.querySelectorAll('button').length,0);assert.doesNotMatch(block.textContent,/CNN|PPO/);});
test('natural pipeline-based author prose and mathematical variable names remain literal',async t=>{const x=structuredClone(b),p=positions.find(p=>p.tree==='c'&&p.scopeId==='task:audiogoal'&&p.entityId==='methods:insight:adjacent:avnav-audio'),prose='pipeline-based method preserves p_det = P(z_t | x_t), q_value, and author_contract prose.';x.entities[p.entityId].detail.design=prose;const d=await boot(x);t.after(()=>d.window.close());const w=d.window;select(w,p);assert.ok(w.document.getElementById('np-detail-content').textContent.includes(prose));assert.equal(w.document.querySelector('[data-design-unresolved]'),null);});
for(const retained of [false,true])test('mounted reader follows an external exact share hash'+(retained?' with a retained prior snapshot':''),async t=>{const d=await boot();t.after(()=>d.window.close());const w=d.window,avos='task:aerial-visual-object-search';w.NavigationProductApp.navigate({scope:avos,tree:'l'});await settle(w);const old=w.NavigationProductApp.getState().route,p=positions.find(p=>p.tree==='a'&&p.paperId==='poni'&&p.originalNodeId==='experiments.ablation.components'),target=M.routeForPosition(b,{scope:'task:category-objectnav'},p.id),hash=M.encodeRoute(target);w.history.replaceState(Object.assign({},w.history.state,{unrelatedMetadata:'preserved'}),'',w.location.href);if(retained){w.history.pushState(w.history.state,'',hash);w.dispatchEvent(new w.HashChangeEvent('hashchange'));}else w.location.hash=hash;await settle(w);assert.equal(w.location.hash,hash);assert.equal(M.encodeRoute(w.NavigationProductApp.getState().route),M.encodeRoute(target));assert.equal(w.NavigationProductApp.getState().originTrail.length,0);if(retained)assert.equal(w.history.state.unrelatedMetadata,'preserved');assert.match(w.document.getElementById('np-detail-content').textContent,/消融|Table|表/);for(let i=0;i<2;i++){w.history.back();await settle(w);assert.deepEqual(w.NavigationProductApp.getState().route,old);w.history.forward();await settle(w);assert.equal(M.encodeRoute(w.NavigationProductApp.getState().route),M.encodeRoute(target));}});
for(const invalid of [false,true])test('cold explicit v1 reference URL ignores '+(invalid?'invalid':'different valid')+' saved v3 snapshot without borrowing answers',async t=>{const p=positions.find(p=>p.tree==='l'&&p.paperId==='harnessvln'&&String(p.versionId).includes('v1')),route=M.validateRoute(b,{scope:p.scopeId,tree:'a',paper:p.paperId,version:p.versionId,template:'1'}),old=M.initialState(b,{scope:'task:vln',tree:'a',paper:'harnessvln',version:Object.keys(b.analyses.harnessvln)[0]});if(invalid)old.route.version='not-imported';const d=await boot(b,M.encodeRoute(route),{[M.KEY]:old,unrelatedMetadata:'preserved'});t.after(()=>d.window.close());const w=d.window;assert.ok(w.NavigationProductApp);assert.equal(M.encodeRoute(w.NavigationProductApp.getState().route),M.encodeRoute(M.initialState(b,route).route));assert.equal(w.NavigationProductApp.getState().originTrail.length,0);assert.equal(w.history.state.unrelatedMetadata,'preserved');assert.ok([...w.document.querySelectorAll('#np-tree [data-position]')].every(n=>b.positions[n.dataset.position].genericTemplate));assert.match(w.document.getElementById('np-tree-caption').textContent,/0|未填|参考/);});
test('invalid explicit URL never falls back to a valid saved paper snapshot',async t=>{const old=M.initialState(b,{scope:'task:category-objectnav',tree:'l'}),d=await boot(b,'#nav=1&scope=task%3Acategory-objectnav&paper=constructor',{[M.KEY]:old});t.after(()=>d.window.close());assert.equal(d.window.NavigationProductApp,undefined);assert.equal(d.window.document.getElementById('np-workspace').hidden,true);});

// Keep the bounded evidence update under the existing CI/Pages navigation test command.
require('./test_navigation_evidence_followup.cjs');

require("./test_navigation_loading.cjs");

require('./test_navigation_tree_first.cjs');

// Keep every startup assertion in a fresh heap, as for the large global DOM group.
test('all sharded startup and delayed-content contracts pass in an isolated process',t=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_sharded_startup.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(r.stdout)t.diagnostic(r.stdout);if(r.stderr)t.diagnostic(r.stderr);assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

require('./test_navigation_global_model.cjs');
// The production-HTML group owns several large JSDOM documents. Run the complete
// group in a fresh process so earlier closed fixtures do not share its V8 heap.
test('all production global DOM and published-history contracts pass in an isolated process',t=>{
 const env={...process.env};delete env.NODE_TEST_CONTEXT;
 const result=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_global_dom.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});
 if(result.stdout)t.diagnostic(result.stdout);if(result.stderr)t.diagnostic(result.stderr);
 assert.ifError(result.error);assert.equal(result.signal,null,'global DOM runner terminated by signal');assert.equal(result.status,0,'global DOM runner must pass every test');
});

test("reading clarity counterexamples",()=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,["--test",path.join(__dirname,"test_navigation_reading_clarity.cjs")],{cwd:root,env,encoding:"utf8",maxBuffer:8*1024*1024});assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

test('scoped scientific additions retain visible protocol and version boundaries',()=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_science_routes.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

test('spatial canvas keeps complete coverage, readable default geometry and exact reading navigation',()=>{
 const env={...process.env};delete env.NODE_TEST_CONTEXT;
 const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_spatial_canvas.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});
 assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);
});

// Original scope/identity regressions remain; paired reading adds complete route coverage.
test('parallel scope forests and overview interaction regressions',()=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_parallel_scopes.cjs'),path.join(__dirname,'test_navigation_parallel_state.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

// S0 source-parent geometry and all typed edge interactions use an isolated fixture heap.
test('graphical overview preserves all source parents, typed relationships and exact reading routes',t=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_graphical_overview.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(r.stdout)t.diagnostic(r.stdout);if(r.stderr)t.diagnostic(r.stderr);assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

// Route summaries exercise real lazy packets in a separate heap.
test('selected task route summaries preserve exact scope, evidence and async navigation',t=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_task_routes.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(r.stdout)t.diagnostic(r.stdout);if(r.stderr)t.diagnostic(r.stderr);assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});

// Desktop exploration preserves optional history schema, exact L/C contexts and single-relation reading.
test('desktop exploration state and active-view reader contracts',t=>{const env={...process.env};delete env.NODE_TEST_CONTEXT;const r=cp.spawnSync(process.execPath,['--test',path.join(__dirname,'test_navigation_desktop_state.cjs'),path.join(__dirname,'test_navigation_desktop_exploration.cjs')],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(r.stdout)t.diagnostic(r.stdout);if(r.stderr)t.diagnostic(r.stderr);assert.ifError(r.error);assert.equal(r.signal,null);assert.equal(r.status,0,r.stdout+r.stderr);});
