'use strict';
// Rebuilt regression suite. All assertions run against these new bytes.
// DOM geometry models are not browser, touch, native fullscreen or font QA.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),src=path.join(root,'previews/radar-c2-analysis'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'faithful-tree-rebuilt-'));
fs.cpSync(src,tmp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),tmp,{recursive:true});
const {fixture}=require(path.join(tmp,'analysis/tests/dom_fixture.cjs')),F=require(path.join(src,'analysis/c2.js')).FaithfulTree,M=require(path.join(src,'model.js')),A=require(path.join(src,'analysis/model.js'));
const data=file=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(src,file),'utf8'),ctx);return ctx.window;};
const model=M.buildModel(data('data/catalog.js').PAPER_CATALOG,data('data/literature.js').LITERATURE_TREE,data('data/challenge.js').CHALLENGE_TREE),bundle=data('analysis/data/bundle.js').C2_DATA,d={M,A,model,bundle},plain=x=>JSON.parse(JSON.stringify(x));
let count=0;const pending=[];function test(name,fn){const result=fn();if(result?.then)pending.push(result.then(()=>{count++;console.log('PASS '+name);}));else{count++;console.log('PASS '+name);}}
// This retained suite explicitly exercises the original reference and legacy records.
const start=()=>{const f=fixture({url:'https://example.test/#mindmap='+encodeURIComponent(JSON.stringify({version:2,mode:'example',tab:'l',paper:'harnessvln',minimap:true}))});f.document.emit('DOMContentLoaded');assert(f.window.FaithfulTreeApp);assert.equal(f.errors.length,0);return f;};
const bounds=(n,c,w,h)=>{assert(n.x*c.k+c.x>=-.01);assert((n.x+n.w)*c.k+c.x<=w+.01);assert(n.y*c.k+c.y>=-.01);assert((n.y+n.h)*c.k+c.y<=h+.01);};
(async()=>{try{
test('source transcription is pinned; all 60 nodes and 59 original parent edges are reachable',()=>{assert.deepEqual(F.ORIGINAL,JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/faithful-tree-original.json'))));const g=F.sourceGraph();assert.equal(g.nodes.length,60);assert.equal(g.nodes.filter(n=>n.parent).length,59);assert.deepEqual(g.by.get('ex:goal').children,['ex:l','ex:c']);assert.equal(g.by.get('ex:goal').parent,'ex:root');for(const n of g.nodes)assert.equal(F.ancestors(g,n.id)[0],g.root);});
test('irregular source branches, nested challenges, annotations and explicit unknowns remain exact',()=>{const g=F.sourceGraph(),b=g.by;assert.equal(b.get('ex:l-neilf-plus').parent,'ex:l-neilf');assert.equal(b.get('ex:l-eclipse').parent,'ex:l-well-pipeline');assert.equal(b.get('ex:l-uncategorized').parent,'ex:l-indoor');assert.equal(b.get('ex:l-indoor-pipeline').parent,'ex:l-indoor');assert.equal(b.get('ex:c-light-model').children.length,2);assert(b.get('ex:c-light-model').children.every(id=>b.get(id).type==='challenge'));assert.equal(g.nodes.filter(n=>n.label.includes('???')).length,3);assert.equal(g.nodes.filter(n=>n.annotations?.length).length,11);assert.equal(g.nodes.filter(n=>n.uncertainty).length,34);});
test('image bytes are either exact hash matches or visibly unavailable; no fabricated substitute',()=>{const expected={dual:'c69e3c4cbd47a74b7a98b7b26c02e0b4ff8df49584fffafb26c0c2f6a8791e64',analysis:'60b1b2e8e38d912de02c18873e1c9b261fb6625564330d454c28326ef4b4aee6'};for(const [id,sha]of Object.entries(expected)){const image=F.SOURCE_IMAGES[id];assert.equal(image.sha256,sha);if(image.data){assert.equal(crypto.createHash('sha256').update(Buffer.from(image.data.split(',')[1],'base64')).digest('hex'),sha);assert.equal(image.status,'exact_bytes_verified');}else{assert.equal(image.data,null);assert.equal(image.status,'source_bytes_unavailable');}}});
test('navigation preserves every original occurrence, source path, parent and type without milestone claims',()=>{const g=F.navigationGraph(M,model);for(const key of ['l','c']){const old=M.atlas.paths(model,key);for(const n of old.nodes.filter(n=>n.id!==old.root)){const actual=g.by.get(n.id);assert(actual);for(const field of ['sourceId','type','pathId','paperId'])assert.equal(actual[field],n[field]);assert.deepEqual(actual.path,n.path);assert.equal(actual.parent,n.parent===old.root?'nav:'+key:n.parent);}assert.equal(new Set(g.nodes.filter(n=>n.key===key&&n.paperId).map(n=>n.paperId)).size,39);}assert.equal(model.papers.size,39);assert.equal([...model.trees.l.nodes.values()].filter(n=>n.type==='task_contract').length,19);assert(!g.nodes.some(n=>['milestone','improvement','first_work'].includes(n.type)));});
test('all 39 independent analysis templates preserve original 59 nodes; only 2 have their own content',()=>{let filled=0;for(const pid of model.papers.keys()){const sample=F.analysisGraph(A,bundle,pid,'example');assert.equal(sample.nodes.length,59);assert.equal(sample.analysis.answers.size,0);for(const n of bundle.schema.nodes){assert.equal(sample.by.get(n.id).parent,n.parentId);assert.equal(sample.by.get(n.id).label,n.labelOriginal);}const actual=F.analysisGraph(A,bundle,pid,'legacy');if(actual.analysis.mapping)filled++;else{assert.equal(actual.nodes.length,59);assert.equal(actual.analysis.answers.size,0);}}assert.equal(filled,2);assert.equal(F.analysisGraph(A,bundle,'navgpt','navigation').analysis.answers.size,0);});
test('analysis asymmetry, multiline leaves, two ablation leaves and three ellipses survive',()=>{const g=F.analysisGraph(A,bundle,'navgpt','example'),intro=g.nodes.filter(n=>F.ancestors(g,n.id).includes('introduction'));assert.equal(g.nodes.filter(n=>n.parent).length,58);assert.equal(g.nodes.filter(n=>n.label==='...').length,3);assert.equal(intro.find(n=>n.label==='contribution 1').children.length,2);assert.equal(intro.find(n=>n.label==='contribution 2').children.length,3);const overview=g.nodes.find(n=>n.label==='Overview');assert.equal(overview.children.length,2);for(const id of overview.children){assert.equal(g.by.get(id).children.length,0);assert(g.by.get(id).label.includes('\n'));}assert.equal(g.nodes.find(n=>n.label==='Ablation studies').children.length,2);assert(g.by.get('limitation').source.sourceNote.includes('截断'));});
test('one click expands one original level; repeated click collapses without adding nodes',()=>{let s=F.initial(d),g=F.getGraph(d,s);assert.equal(F.scene(g,F.view(d,s)).nodes.length,4);s=F.reduce(d,s,{type:'node',id:'ex:l'});assert.equal(F.scene(g,F.view(d,s)).nodes.length,4+g.by.get('ex:l').children.length);s=F.reduce(d,s,{type:'node',id:'ex:l'});assert.equal(F.scene(g,F.view(d,s)).nodes.length,4);});
test('whole-graph fit includes all source and navigation nodes even in tiny minimaps',()=>{for(const g of [F.sourceGraph(),F.navigationGraph(M,model)])for(const [w,h]of [[180,104],[1000,600]]){const sc=F.scene(g,{expanded:g.nodes.map(n=>n.id)},true),c=F.fit(sc,w,h);for(const n of sc.nodes)bounds(n,c,w,h);}});
test('anchored zoom and fit do not change branch state or scientific identities',()=>{const s=F.reduce(d,F.initial(d),{type:'node',id:'ex:l'}),g=F.getGraph(d,s),v=F.view(d,s),saved=JSON.stringify(v),c=F.fit(F.scene(g,v),1000,600),z=F.zoom(c,1.4,300,250);assert.equal(JSON.stringify(v),saved);assert(Math.abs((300-c.x)/c.k-(300-z.x)/z.k)<1e-8);assert(Math.abs((250-c.y)/c.k-(250-z.y)/z.k)<1e-8);});
test('NavGPT literature → C05/I05-1 → same paper pending analysis → original tree is complete',()=>{let s=F.initial(d);const paths=M.pathsForPaper(model,'navgpt'),lp=paths.find(p=>p.key==='l'),cp=paths.find(p=>p.key==='c'&&p.nodeIds.includes('C05')&&p.nodeIds.includes('I05-1'));assert(lp&&cp);s=F.reduce(d,s,{type:'path',key:'l',id:lp.id});assert.equal(F.getGraph(d,s).by.get(F.view(d,s).selected).paperId,'navgpt');s=F.reduce(d,s,{type:'path',key:'c',id:cp.id});assert.deepEqual(F.getGraph(d,s).by.get(F.view(d,s).selected).path,cp.nodeIds);s=F.reduce(d,s,{type:'analysis',paper:'navgpt'});assert.equal(F.getGraph(d,s).analysis.answers.size,0);s=F.reduce(d,s,{type:'return'});assert.equal(s.tab,'c');assert.equal(F.getGraph(d,s).by.get(F.view(d,s).selected).paperId,'navgpt');});
test('explicit original-example DOM has a real common ancestor graph, three edges and one detail panel',()=>{const f=start();assert(f.window.FaithfulTreeApp.isActive());assert.equal(f.$$('[data-ft="node"]').length,4);assert.equal(f.$$('[data-ft-source]').length,3);assert.equal(f.$$('#ft-detail').length,1);assert(f.$('#faithful-map').textContent.includes('General goal'));assert(f.url().includes('#mindmap='));});
test('Back/Forward and Escape restore selection, camera and keyboard focus',()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="node"][data-id="ex:l"]');app.setCamera({x:31,y:42,k:.8});f.click('[data-ft="node"][data-id="ex:c"]');f.back();assert.equal(F.view(d,app.getState()).selected,'ex:l');assert.deepEqual(plain(F.view(d,app.getState()).camera),{x:31,y:42,k:.8});assert.equal(f.document.activeElement.dataset.id,'ex:l');f.forward();f.$('[data-ft="node"][data-id="ex:c"]').emit('keydown',{key:'Escape'});assert.equal(F.view(d,app.getState()).selected,'ex:goal');assert.equal(f.document.activeElement.dataset.id,'ex:goal');});
test('detail close/reopen and detail-tab history restore previous scroll',()=>{const f=start();f.$('#ft-detail-body').scrollTop=180;f.click('[data-ft="details"]');f.click('[data-ft="details"]');assert.equal(f.$('#ft-detail-body').scrollTop,180);f.click('[data-ft="detail-tab"][data-tab="original"]');f.back();assert.equal(f.$('#ft-detail-body').scrollTop,180);});
test('original-image modal resize and history stay synchronized for present or unavailable bytes',()=>{const f=start();f.click('[data-ft="node"][data-id="ex:l"]');f.click('[data-ft="image"]');assert.equal(f.$('#ft-image-dialog').hidden,false);if(F.SOURCE_IMAGES.dual.data){f.click('[data-ft="image-plus"]');assert(f.$('#ft-original-image'));}else{assert(f.$('#ft-image-dialog').textContent.includes('原图文件尚未恢复'));assert.equal(f.$('#ft-original-image'),null);}f.window.emit('resize');assert.equal(f.$('#ft-image-dialog').hidden,false);f.back();assert.equal(f.$('#ft-image-dialog').hidden,false);f.$('#ft-image-close').emit('keydown',{key:'Escape'});assert.equal(f.$('#ft-image-dialog').hidden,true);const vp=f.$('#ft-viewport');vp.getBoundingClientRect=()=>({left:0,top:0});const before=F.view(d,f.window.FaithfulTreeApp.getState()).camera.k;vp.emit('wheel',{deltaY:-40,clientX:200,clientY:100});assert(F.view(d,f.window.FaithfulTreeApp.getState()).camera.k>before);});
test('pointer pan works and pointercancel does not swallow the next real click',()=>{const f=start(),app=f.window.FaithfulTreeApp,vp=f.$('#ft-viewport'),before=F.view(d,app.getState()).camera;vp.emit('pointerdown',{button:0,pointerId:1,clientX:10,clientY:10});vp.emit('pointermove',{clientX:60,clientY:40});assert.equal(F.view(d,app.getState()).camera.x,before.x+50);assert.equal(F.view(d,app.getState()).camera.y,before.y+30);vp.emit('pointercancel',{pointerId:1});f.click('[data-ft="node"][data-id="ex:l"]');assert.equal(F.view(d,app.getState()).selected,'ex:l');});
test('fullscreen fallback has explicit exit and Escape',()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="fullscreen"]');assert(app.isFullscreen());assert(f.$('#ft-fullscreen').textContent.includes('退出'));f.$('#ft-viewport').emit('keydown',{key:'Escape'});assert(!app.isFullscreen());});
test('late fullscreen completion cannot re-enter after exit or leaving the page',async()=>{for(const leave of [false,true]){const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map');let resolve,exits=0;host.requestFullscreen=()=>new Promise(r=>resolve=()=>{f.document.fullscreenElement=host;f.document.emit('fullscreenchange');r();});f.document.exitFullscreen=async()=>{exits++;f.document.fullscreenElement=null;f.document.emit('fullscreenchange');};const request=app.toggleFullscreen();if(leave)f.click('[data-ft="legacy"]');else await app.toggleFullscreen();resolve();await request;assert(!app.isFullscreen());assert.notEqual(f.document.fullscreenElement,host);assert(exits>=1);if(leave)assert(!app.isActive());}});
test('latest fullscreen enter intent wins over an older pending completion',async()=>{const f=start(),app=f.window.FaithfulTreeApp,host=f.$('#faithful-map'),resolves=[];let exits=0;host.requestFullscreen=()=>new Promise(r=>resolves.push(()=>{f.document.fullscreenElement=host;f.document.emit('fullscreenchange');r();}));f.document.exitFullscreen=async()=>{exits++;f.document.fullscreenElement=null;f.document.emit('fullscreenchange');};const first=app.toggleFullscreen();await app.toggleFullscreen();const latest=app.toggleFullscreen();resolves[0]();await first;assert(app.isFullscreen());resolves[1]();await latest;assert(app.isFullscreen());assert.equal(f.document.fullscreenElement,host);assert.equal(exits,0);});
test('analysis gaps and answer backlinks stay in the unique detail pane',()=>{const f=start(),app=f.window.FaithfulTreeApp;app.dispatch({type:'mode',mode:'legacy'});app.dispatch({type:'analysis',paper:'navharness'});const a=[...app.getGraph().analysis.answers.values()].find(a=>a.sourceGapIds?.length);app.dispatch({type:'inspect',id:a.nodeId});const gap=f.$('[data-c2="gap"]'),id=gap.dataset.id;gap.emit('click');assert.equal(app.getState().detailTab,'unknown');assert.equal(f.document.activeElement.dataset.questionId,id);const back=f.$('[data-c2="inspect"]'),answerId=back.dataset.id;back.emit('click');assert.equal(F.view(d,app.getState()).selected,answerId);assert.equal(app.getState().detailTab,'evidence');assert.equal(f.$$('#ft-detail').length,1);assert(f.$('#ft-detail').textContent.includes('实际核读范围'));});
test('default source and analysis skeletons remain fully visible and at least 1x at three widths',()=>{for(const tab of ['l','a']){const s=F.reduce(d,F.initial(d),{type:'tab',tab});if(tab==='l')s.views[F.key(s)].expanded=['ex:root','ex:goal'];const g=F.getGraph(d,s),v=F.view(d,s);for(const [w,h]of [[1088,650],[684,600],[390,572]]){const sc=F.scene(g,v,false,w),c=F.readableCamera(g,v,sc,w,h);assert(c.k>=1);for(const n of sc.nodes)bounds(n,c,w,h);}}});
test('19-protocol branch stays readable and last child locate survives fit/Back/Forward',()=>{const f=start(),app=f.window.FaithfulTreeApp;f.click('[data-ft="mode"][data-mode="legacy"]');f.click('[data-ft="node"][data-id="nav:l"]');assert(F.view(d,app.getState()).camera.k>=1);assert.equal(app.getGraph().by.get('nav:l').children.length,19);assert.equal(f.$('.ft-child-directory').querySelectorAll('[data-ft="locate"]').length,19);f.click('[data-ft="fit"]');const full=plain(F.view(d,app.getState()).camera),expanded=plain(F.view(d,app.getState()).expanded);// Geometric sibling columns can now fit readably: assert completeness, not forced tiny text.
for(const n of F.scene(app.getGraph(),F.view(d,app.getState()),false,1088).nodes)bounds(n,full,1088,848);const last=app.getGraph().by.get('nav:l').children.at(-1);f.click('[data-ft="locate"][data-id="'+last+'"]');assert(F.view(d,app.getState()).camera.k>=1);assert.equal(f.document.activeElement.dataset.id,last);f.back();assert.deepEqual(plain(F.view(d,app.getState()).camera),full);assert.deepEqual(plain(F.view(d,app.getState()).expanded),expanded);f.forward();assert.equal(F.view(d,app.getState()).selected,last);assert(F.view(d,app.getState()).camera.k>=1);});
test('deep paper Escape parent stays visible and focus restores on Back/Forward',()=>{const f=start(),app=f.window.FaithfulTreeApp,p=M.pathsForPaper(model,'navgpt').find(p=>p.key==='l');app.dispatch({type:'path',key:'l',id:p.id});const leaf=F.view(d,app.getState()).selected,parent=app.getGraph().by.get(leaf).parent;f.$('[data-ft="node"][data-id="'+leaf+'"]').emit('keydown',{key:'Escape'});const v=F.view(d,app.getState()),sc=F.scene(app.getGraph(),v,false,1088);assert.equal(v.selected,parent);assert(v.camera.k>=1);bounds(sc.by.get(parent),v.camera,1088,848);assert.equal(f.document.activeElement.dataset.id,parent);f.back();assert.equal(F.view(d,app.getState()).selected,leaf);f.forward();assert.equal(F.view(d,app.getState()).selected,parent);});
test('legacy analysis deep links remain handled by their original controller',()=>{const f=fixture({url:'https://example.test/#analysis='+encodeURIComponent(JSON.stringify({paperId:'navgpt'}))});f.document.emit('DOMContentLoaded');assert(!f.window.FaithfulTreeApp.isActive());assert(f.c2.isOpen());assert.equal(f.c2.getModel().paperId,'navgpt');assert.equal(f.c2.getModel().answers.size,0);});
await Promise.all(pending);
console.log(JSON.stringify({passed:count,failed:0,browser:'NOT_RUN',source_images:Object.fromEntries(Object.entries(F.SOURCE_IMAGES).map(([k,v])=>[k,v.status]))}));
}finally{fs.rmSync(tmp,{recursive:true,force:true});}})().catch(error=>{console.error(error);process.exitCode=1;});
