'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const pageHTML=fs.readFileSync(__dirname+'/../artifacts/rpa-0062/v2/writing-close-reading.html','utf8'),units=JSON.parse(pageHTML.match(/<script type="application\/json" data-source-units id="reader-source-units">([\s\S]*?)<\/script>/)[1]);
function el(){return{listeners:{},attrs:{},textContent:'',hidden:false,classList:{v:new Set(),add(x){this.v.add(x)},remove(x){this.v.delete(x)},contains(x){return this.v.has(x)},toggle(x,on){on??=!this.v.has(x);on?this.v.add(x):this.v.delete(x);return on}},addEventListener(k,f){this.listeners[k]=f},setAttribute(k,v){this.attrs[k]=v},removeAttribute(k){delete this.attrs[k]},emit(k,e={}){this.listeners[k]?.(e)},focus(){},scrollIntoView(o){this.scrolled=o}}}
const fields=Object.fromEntries(['id','location','paraphrase','quote','open','previous','next'].map(k=>[k,el()]));const panel={querySelector:s=>fields[s.match(/data-source-([a-z]+)/)[1]]},rows=units.map(u=>Object.assign(el(),{dataset:{sourceRow:u.id}})),buttons=units.map(u=>Object.assign(el(),{dataset:{sourceUnit:u.id}})),toggle=el(),tocButton=el(),toast=el(),section=Object.assign(el(),{id:'one',getBoundingClientRect:()=>({top:160})}),tocLink=Object.assign(el(),{hash:'#one'}),toc=Object.assign(el(),{querySelectorAll:()=>[tocLink],querySelector:()=>tocLink,contains:()=>false});
const page=Object.assign(el(),{querySelector:s=>s==='[data-source-units]'?{textContent:JSON.stringify(units)}:s==='.reader-toc'?toc:s==='.reader-toc-toggle'?tocButton:s==='.reader-source-panel'?panel:s==='[data-source-toggle]'?toggle:s.startsWith('[data-source-row=')?rows.find(r=>s.includes('"'+r.dataset.sourceRow+'"')):null,querySelectorAll:s=>s.includes('section[id]')?[section]:s==='[data-source-row]'?rows:s==='[data-source-unit]'?buttons:[]});
const document=Object.assign(el(),{hidden:false,querySelector:s=>s==='.reader-page'?page:s==='.reader-toast'?toast:null}),window=el();let reduced=false;const context={document,window,innerWidth:1200,matchMedia:q=>({matches:q.includes('reduce')?reduced:false,addEventListener(){}}),getComputedStyle:()=>({scrollPaddingTop:'144px'}),requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout:()=>1,clearTimeout(){},CSS:{escape:s=>s},navigator:{}};
vm.runInNewContext(fs.readFileSync(__dirname+'/../assets/reader-v2.js','utf8'),context);
assert.equal(fields.id.textContent,units[0].id);assert(fields.previous.disabled);assert(!fields.next.disabled);
for(let n=0;n<100;n++){const i=n%units.length;buttons[i].emit('click');assert.equal(fields.id.textContent,units[i].id);assert.equal(fields.open.href,units[i].url);assert.equal(fields.quote.hidden,!units[i].quote);assert.equal(buttons.filter(b=>b.attrs['aria-pressed']==='true').length,1);assert.equal(rows.filter(r=>r.classList.contains('is-current')).length,1)}
buttons.at(-1).emit('click');assert(fields.next.disabled);fields.next.emit('click');assert.equal(fields.id.textContent,units.at(-1).id);assert.equal(rows.at(-1).scrolled.behavior,'smooth');
reduced=true;context.matchMedia=q=>({matches:q.includes('reduce'),addEventListener(){}}); // Existing media object reads static false; use a second reduced-motion run.
const c2={...context,matchMedia:q=>({matches:q.includes('reduce'),addEventListener(){}})};vm.runInNewContext(fs.readFileSync(__dirname+'/../assets/reader-v2.js','utf8'),c2);fields.next.emit('click');assert.equal(rows[1].scrolled.behavior,'auto');
toggle.emit('click');assert(page.classList.contains('reader-source-collapsed'));assert.equal(toggle.attrs['aria-pressed'],'false');toggle.emit('click');assert(!page.classList.contains('reader-source-collapsed'));
c2.innerWidth=500;buttons[12].emit('click');assert.equal(toast.textContent,units[12].location);assert.equal(fields.open.href,units[12].url);
console.log('PASS Stage2 source controls: 37 exact units, 100 rapid selections, page URLs/quotes/ARIA, bounds, reduced motion, narrow feedback and panel visibility');
