'use strict';
// Disclosure-aware DOM/model regressions from deployed-browser observations.
// This fixture does not establish browser geometry or human usability.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=process.env.RPA_PROTOCOL_SOURCE||path.resolve(__dirname,'..'),source=path.join(root,'previews/radar-c2-analysis');
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rpa-protocol-focus-'));fs.cpSync(source,temp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),temp,{recursive:true});const {fixture}=require(path.join(temp,'analysis/tests/dom_fixture.cjs'));
const json=x=>JSON.parse(JSON.stringify(x));
function visibleText(el){if(!el||el.hidden)return '';if(el.tagName==='DETAILS'&&el.getAttribute('open')===null)return visibleText(el.children.find(c=>c.tagName==='SUMMARY'));return el.children.length?el.children.map(visibleText).join(' '):el.textContent;}
const openRoot=(f,id,variant)=>f.app.dispatch({type:'root',key:'l',id,...(variant?{variant}:{})});
let pass=0,fail=0;function test(n,fn){try{fn();pass++;console.log('PASS '+n);}catch(e){fail++;console.error('FAIL '+n+'\n'+e.stack);}}
try{
test('HM3D entry prioritizes HM3D rather than stored-first LangMap and keeps all three method papers',()=>{const f=fixture();f.click('.task-family[data-id="goal"]');f.click('.protocol-card[data-id="task-object-open"]');const current=f.$('.protocol-current');assert(current);assert.equal(current.dataset.currentProtocol,'sap-nav-hm3d-ovon-val-unseen');assert(current.textContent.includes('每个 episode 一个场景级目标'));assert(!visibleText(f.$('.protocol-summary')).includes('SAP-Nav：LangMap 四粒度单目标'));assert.equal(f.app.getState().taskVariant,null);const papers=new Set(f.$$('.paper-chip').map(b=>f.app.model.trees.l.paths.find(p=>p.id===b.dataset.id).paperId));assert.equal(papers.size,3);assert(current.textContent.includes('本卡适用于：SAP-Nav'));});
test('known protocol conditions precede legacy generic rows for all four corrected task roots',()=>{for(const id of ['task-object-open','task-multigoal-object','task-imagegoal-multigoal','task-vln-iterative']){const f=fixture();openRoot(f,id);const panel=f.$('.protocol-summary'),current=f.$('.protocol-current'),legacy=f.$('.historical-source-context');assert(current);assert(legacy);assert.equal(legacy.getAttribute('open'),null);assert(legacy.querySelector('summary').textContent.includes('旧记录'));assert(!visibleText(panel).includes('此项尚未独立拆分'));assert.equal(current.querySelectorAll('.protocol-facts')[0].children.length,6);assert.equal(panel.querySelectorAll('.protocol-current').length,1);}});
test('old generic values and original source context remain intact inside the closed history disclosure',()=>{const f=fixture();openRoot(f,'task-object-open');const n=f.app.model.trees.l.nodes.get('task-object-open'),legacy=f.$('.historical-source-context');for(const key of ['goal_spec','action_regime','memory_regime','success_contract'])assert(legacy.textContent.includes(n[key]));assert(legacy.textContent.includes('此项尚未独立拆分'));assert(legacy.textContent.includes(n.origin.title));legacy.setAttribute('open','');assert(visibleText(legacy).includes(n.goal_spec));});
test('LangMap entry prioritizes LangMap, scopes methods to SAP and keeps HM3D separate',()=>{const f=fixture();f.click('.task-family[data-id="goal"]');f.click('.protocol-card[data-variant="sap-nav-langmap-single-goal"]');assert.equal(f.$('.protocol-current').dataset.currentProtocol,'sap-nav-langmap-single-goal');assert(f.$('#title-l').textContent.includes('LangMap'));const text=visibleText(f.$('.protocol-summary'));assert(text.includes('四粒度不是四个顺序子目标'));assert(!text.includes('SAP-Nav：HM3D-OVON Val Unseen'));assert.equal(f.$('.other-protocols').getAttribute('open'),null);for(const chip of f.$$('.paper-chip'))assert.equal(f.app.model.trees.l.paths.find(p=>p.id===chip.dataset.id).paperId,'sap-nav');});
test('other protocol selection and browser Back/Forward restore correct primary card and paper scope',()=>{const f=fixture();openRoot(f,'task-object-open');f.$('.other-protocols').querySelector('button[data-variant="sap-nav-langmap-single-goal"]').emit('click');assert.equal(f.$('.protocol-current').dataset.currentProtocol,'sap-nav-langmap-single-goal');f.back();assert.equal(f.$('.protocol-current').dataset.currentProtocol,'sap-nav-hm3d-ovon-val-unseen');assert.equal(f.app.getState().taskVariant,null);f.forward();assert.equal(f.$('.protocol-current').dataset.currentProtocol,'sap-nav-langmap-single-goal');});
test('all seven exact variant records remain accessible without changing their raw conditions',()=>{const f=fixture();for(const n of f.app.model.trees.l.nodes.values())for(const v of n.protocol_variants||[]){openRoot(f,n.id,v.id);const current=f.$('.protocol-current');assert.equal(current.dataset.currentProtocol,v.id);for(const k of ['goal_spec','goal_delivery','action_regime','environment_prior','memory_regime','success_contract'])assert(current.textContent.includes(v[k]));const link=current.querySelector('a');assert(link);assert(current.querySelectorAll('a').some(a=>a.getAttribute('href')===v.source_url));assert.equal(current.querySelector('.protocol-source-details').getAttribute('open'),null);}});
test('direct IVLN evidence click does not invent a module choice or change chosen method',()=>{const f=fixture();openRoot(f,'task-vln-iterative');const p=f.app.model.trees.l.paths.find(p=>p.nodeIds[0]==='task-vln-iterative'&&p.viewKind==='pipeline'&&p.paperId==='krantz2023ivln');f.app.dispatch({type:'enter',key:'l',id:p.nodeIds[1]});const before=json(f.app.getState().l),method=f.$('.focus-selection').textContent,route=f.$('.selected-task-route').textContent;f.click('.paper-chip[data-id="'+p.id+'"]');assert.deepEqual(json(f.app.getState().l),before);assert.equal(f.$('.focus-selection').textContent,method);assert.equal(f.$('.selected-task-route').textContent,route);assert.equal(f.app.getState().origin.preserveContext,true);assert.deepEqual(json(f.app.getState().origin.path),json(p.nodeIds));assert.equal(f.app.getState().tab,'evidence');assert.equal(f.document.activeElement.id,'paper-title');for(const id of p.nodeIds.filter(id=>f.app.model.trees.l.nodes.get(id).type==='module'))assert(f.$('#paper-panel').textContent.includes(f.app.model.trees.l.nodes.get(id).label));});
test('paper evidence close and Back/Forward retain reading prefix, exact provenance and clicked-chip focus',()=>{const f=fixture();openRoot(f,'task-vln-iterative');const chip=f.$('.paper-chip'),id=chip.dataset.id,before=json(f.app.getState().l);f.click('.paper-chip');const origin=json(f.app.getState().origin),paper=f.app.getState().paper;f.click('[data-action="closePaper"]');assert.deepEqual(json(f.app.getState().l),before);assert.equal(f.document.activeElement.dataset.action,'evidence');assert.equal(f.document.activeElement.dataset.id,id);f.back();assert.equal(f.app.getState().paper,paper);assert.deepEqual(json(f.app.getState().origin),origin);assert.deepEqual(json(f.app.getState().l),before);f.forward();assert.equal(f.app.getState().paper,null);assert.deepEqual(json(f.app.getState().l),before);});
test('explicit source-path navigation still locates complete original path rather than adopting evidence-click semantics',()=>{const f=fixture(),p=f.app.model.trees.l.paths.find(p=>p.nodeIds[0]==='task-vln-iterative'&&p.viewKind==='pipeline');f.app.dispatch({type:'path',key:'l',id:p.id});assert.deepEqual(json(f.app.getState().l),json(p.nodeIds.slice(0,-1)));assert.deepEqual(json(f.app.getState().origin.path),json(p.nodeIds));assert.notEqual(f.app.getState().origin.preserveContext,true);for(const id of p.nodeIds.slice(1))assert(f.$('.selected-task-route').textContent.includes(f.app.model.trees.l.nodes.get(id).label));});
test('evidence action cannot open an unrelated source path under the current selected protocol',()=>{const f=fixture();openRoot(f,'task-vln-iterative');const p=f.app.model.trees.l.paths.find(p=>p.nodeIds[0]==='task-multigoal-object'),before=JSON.stringify(f.app.getState());f.app.dispatch({type:'evidence',key:'l',id:p.id});assert.equal(JSON.stringify(f.app.getState()),before);});
}finally{fs.rmSync(temp,{recursive:true,force:true});}
console.log(JSON.stringify({passed:pass,failed:fail,browser:'NOT_RUN'}));if(fail)process.exitCode=1;
