'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.resolve(__dirname,'..'),data=JSON.parse(fs.readFileSync(path.join(root,'submit-preview/data/venues.json'),'utf8'));
function setup(){
 const nodes={};function get(id){if(!nodes[id])nodes[id]={value:'',textContent:'',_html:'',options:[],classList:{remove(){}},add(o){this.options.push(o)},set innerHTML(v){this._html=v;if(v.startsWith('<option')){this.options=[{value:''}];this.value=''}},get innerHTML(){return this._html}};return nodes[id]}
 const ctx=vm.createContext({document:{getElementById:get,querySelectorAll:()=>[]},URL,Option:function(text,value){this.text=text;this.value=value},location:{hash:''},history:{replaceState(){}},console});
 const src=fs.readFileSync(path.join(root,'submit-preview/app.js'),'utf8').split("fetch(new URL(")[0];vm.runInContext(src,ctx);ctx.fixture=data;vm.runInContext('data=fixture',ctx);get('p-yearmode').value='publication_year';return {ctx,get,run:s=>vm.runInContext(s,ctx)};
}
test('same-publication venue, year, forum, status and topic intersection',()=>{const {ctx,run}=setup();ctx.p=data.publications.find(p=>p.paper_id==='rpa-0052');assert.equal(run("matchesPublication(p,{venue:'ral',yearmode:'publication_year',year:'2025',forum:'journal',status:'published',topic:'wbc'})"),true);assert.equal(run("matchesPublication(p,{venue:'icra',forum:'workshop'})"),false);assert.equal(run("matchesPublication(p,{yearmode:'edition_year',year:'2025'})"),false);ctx.p=data.publications.find(p=>p.paper_id==='rpa-0012');assert.equal(run("matchesPublication(p,{yearmode:'edition_year',year:'2022',forum:'main_conference'})"),true);assert.equal(run("matchesPublication(p,{yearmode:'publication_year',year:'2023'})"),true);assert.equal(run("matchesPublication(p,{yearmode:'publication_year',year:'2022'})"),false)});
test('derived counts and journal rendering do not fabricate conference editions',()=>{const {get,run}=setup();run('renderPapers()');assert.match(get('paper-count').textContent,/8 篇匹配.*8 篇/);assert.match(get('migration-notice').textContent,/8 篇.*95.*87/);assert.match(get('paper-list').innerHTML,/IEEE RA-L · 期刊/);assert.match(get('paper-list').innerHTML,/AAAI · 主会/);assert.doesNotMatch(get('paper-list').innerHTML,/届次 null/);get('p-forum').value='journal';run('renderPapers()');assert.match(get('paper-count').textContent,/1 篇匹配/);assert.doesNotMatch(get('paper-list').innerHTML,/会议届次与出版年份不同/);get('p-forum').value='workshop';run('renderPapers()');assert.match(get('paper-count').textContent,/0 篇匹配/)});
test('year choices follow selected semantic mode and preserve valid selections',()=>{const {get,run}=setup();run('refreshYears()');assert.deepEqual(get('p-year').options.map(x=>x.value),['','2023','2024','2025','2026']);get('p-year').value='2023';get('p-yearmode').value='edition_year';run('refreshYears()');assert.equal(get('p-year').value,'');assert.deepEqual(get('p-year').options.map(x=>x.value),['','2022','2024','2025','2026']);get('p-year').value='2025';get('p-yearmode').value='publication_year';run('refreshYears()');assert.equal(get('p-year').value,'2025')});
test('historical identity never becomes a sixteenth recommendation or policy snapshot',()=>{const {get,run}=setup();run('renderList()');assert.equal(get('venue-count').textContent,'15 个渠道');assert.doesNotMatch(get('venue-list').innerHTML,/AAAI/);assert.equal(run("latest(data.venues.find(v=>v.id==='ral')).kind"),'journal_policy_snapshot');run("openVenue('aaai')");assert.match(get('detail').innerHTML,/渠道不存在/) });
