'use strict';
// Deterministic production-script/HTML DOM model. It does not claim browser rendering QA.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..');
const dataset=JSON.parse(fs.readFileSync(path.join(root,'submit-preview/data/venues.json'),'utf8'));
async function fixture(hash='',options={}){
 let document,url=new URL('https://example.org/RoboPaperAtlas/submit/index.html'+hash),index=0;const stack=[url.href],pending=[],fetches=[],copied=[],logs=[];
 const decode=s=>s.replace(/&(amp|lt|gt|quot|#39);/g,(_,x)=>({amp:'&',lt:'<',gt:'>',quot:'"','#39':"'"}[x]));
 class Element{
  constructor(tag){this.tagName=tag.toUpperCase();this.attributes={};this.children=[];this.parentElement=null;this.listeners={};this._text='';this._value='';this.disabled=false;this.dataset=new Proxy({},{get:(_,k)=>this.getAttribute('data-'+k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()))});}
  get id(){return this.getAttribute('id')||''}get hidden(){return this.hasAttribute('hidden')}set hidden(v){this.toggleAttribute('hidden',v)}get open(){return this.hasAttribute('open')}set open(v){this.toggleAttribute('open',v)}
  get isConnected(){let x=this;while(x){if(x===document)return true;x=x.parentElement}return false}
  get textContent(){return this._text+this.children.map(x=>x.textContent).join('')}set textContent(v){this.children.forEach(x=>x.parentElement=null);this.children=[];this._text=String(v)}
  get innerHTML(){return this._html||''}set innerHTML(v){this.textContent='';this._html=v;parse(v,this);if(this.tagName==='SELECT')this._value=this.options.find(x=>x.hasAttribute('selected'))?.getAttribute('value')||this.options[0]?.getAttribute('value')||''}
  get options(){return this.children.filter(x=>x.tagName==='OPTION')}get value(){return this._value}set value(v){this._value=this.tagName==='SELECT'&&!this.options.some(x=>x.getAttribute('value')===v)?'':String(v)}
  get selectedIndex(){return this.options.findIndex(x=>x.getAttribute('value')===this.value)}set selectedIndex(i){this.value=this.options[i]?.getAttribute('value')||''}
  add(el){this.append(el)}append(el){el.parentElement=this;this.children.push(el)}setAttribute(k,v){this.attributes[k]=String(v)}getAttribute(k){return this.attributes[k]??null}hasAttribute(k){return k in this.attributes}removeAttribute(k){delete this.attributes[k]}toggleAttribute(k,on){on?this.setAttribute(k,''):this.removeAttribute(k)}
  matches(sel){if(sel.includes(','))return sel.split(',').some(s=>this.matches(s.trim()));const bits=sel.trim().split(/\s+(?![^\[]*\])/);if(bits.length>1){const last=bits.pop();return this.matches(last)&&!!this.parentElement?.closest(bits.join(' '))}const attrs=[...sel.matchAll(/\[([^\]^=]+)(\^=|=)?["']?([^\]"']*)["']?\]/g)];if(!attrs.every(([,k,op,v])=>this.hasAttribute(k)&&(!op||(op==='^='?this.getAttribute(k).startsWith(v):this.getAttribute(k)===v))))return false;sel=sel.replace(/\[[^\]]+\]/g,'');const id=sel.match(/#([\w-]+)/);if(id&&id[1]!==this.id)return false;for(const [,c]of sel.matchAll(/\.([\w-]+)/g))if(!(this.getAttribute('class')||'').split(/\s+/).includes(c))return false;const tag=sel.match(/^[\w-]+/);return !tag||tag[0].toUpperCase()===this.tagName}
  querySelectorAll(sel){const result=[];const walk=n=>{for(const c of n.children){if(c.matches(sel))result.push(c);walk(c)}};walk(this);return result}querySelector(sel){return this.querySelectorAll(sel)[0]||null}closest(sel){let n=this;while(n){if(n.matches(sel))return n;n=n.parentElement}return null}
  addEventListener(type,fn,capture=false){(this.listeners[type]??=[]).push({fn,capture})}
  focus(o){document.activeElement=this;this.lastFocus=o;this.focused=true}scrollIntoView(o){this.scrolled=o}
  emit(type,input={}){const e={type,target:this,defaultPrevented:false,preventDefault(){this.defaultPrevented=true},...input};for(const h of document.listeners[type]||[])if(h.capture)h.fn(e);let n=this;while(n){n['on'+type]?.(e);for(const h of n.listeners[type]||[])if(!h.capture)h.fn(e);n=n.parentElement}return e}
 }
 function parse(html,parent){const nodes=[parent],voids=new Set(['meta','link','input','br','hr','img']);for(const m of html.matchAll(/<([^>]+)>|([^<]+)/g)){if(m[2]){nodes.at(-1)._text+=decode(m[2]);continue}const raw=m[1];if(raw.startsWith('!'))continue;if(raw.startsWith('/')){if(nodes.length>1)nodes.pop();continue}const tag=raw.split(/\s/)[0],el=new Element(tag);for(const a of raw.slice(tag.length).matchAll(/([^\s=\/]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s]+)))?/g))el.setAttribute(a[1],decode(a[2]??a[3]??a[4]??''));nodes.at(-1).append(el);if(!voids.has(tag))nodes.push(el)}for(const s of parent.querySelectorAll('select'))s._value=s.options.find(x=>x.hasAttribute('selected'))?.getAttribute('value')||s.options[0]?.getAttribute('value')||''}
 document=new Element('document');document.getElementById=id=>document.querySelector('#'+id);parse(fs.readFileSync(path.join(root,'submit-preview/index.html'),'utf8'),document);document.currentScript={src:'https://example.org/RoboPaperAtlas/submit-preview/app.js'};
 const window=new Element('window');const change=hash=>{const next=new URL(hash,url);if(next.href===url.href)return;url=next;stack.splice(++index);stack.push(url.href);window.emit('hashchange')};
 const location={get hash(){return url.hash},set hash(v){change(v.startsWith('#')?v:'#'+v)},get href(){return url.href}};
 const history={replaceState(_a,_b,v){url=new URL(v,url);stack[index]=url.href}};
 const ctx={document,window,location,history,URL,URLSearchParams,console:{error:e=>logs.push(e)},navigator:{clipboard:{writeText:t=>{copied.push(t);if(options.deferClipboard)return new Promise((resolve,reject)=>pending.push({resolve,reject}));return options.copyFails?Promise.reject(Error('Denied')):Promise.resolve()}}},Option:function(text,value){const n=new Element('option');n.textContent=text;n.setAttribute('value',value);return n},fetch:u=>{fetches.push(String(u));return Promise.resolve({ok:!(options.failFirst&&fetches.length===1),json:()=>Promise.resolve(dataset)})}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'submit-preview/app.js'),'utf8'),ctx);
 const flush=()=>new Promise(resolve=>setImmediate(resolve));await flush();
 return {document,window,location,history,stack,fetches,pending,copied,logs,ctx,flush,$:s=>document.querySelector(s),$$:s=>document.querySelectorAll(s),async navigate(h){change(h);await flush()},async click(sel){const el=document.querySelector(sel);assert.ok(el,'Missing '+sel);const e=el.emit('click');if(!e.defaultPrevented&&el.tagName==='A')change(el.getAttribute('href'));await flush();return el},async input(sel,value){const el=document.querySelector(sel);el.value=value;el.emit(el.tagName==='INPUT'?'input':'change');await flush()},async back(){if(index){url=new URL(stack[--index]);window.emit('hashchange')}await flush()},async forward(){if(index+1<stack.length){url=new URL(stack[++index]);window.emit('hashchange')}await flush()},async key(key,target=document){target.emit('keydown',{key});await flush()},run:s=>vm.runInNewContext(s,ctx)};
}
test('production bootstrap loads actual markup into a full unselected summary view',async()=>{const f=await fixture();assert.equal(f.logs.length,0);assert.equal(f.$$('.venue-card').length,15);assert.equal(f.$('#workspace').hidden,true);assert.equal(f.$('#venue-browse').hidden,false);assert.equal(f.$('#nav-venues').getAttribute('aria-current'),'page');assert.equal(f.$('#load-status').hidden,true);assert.match(f.fetches[0],/\/submit-preview\/data\/venues.json$/)});
test('filter → detail → return, Back and Forward preserve URL state and visible focus',async()=>{const f=await fixture();await f.input('#query','感知');await f.input('#kind','journal');assert.equal(f.$$('.venue-card').length,1);await f.click('[data-id="tro"]');assert.equal(f.$('#workspace').hidden,false);assert.equal(f.document.activeElement.id,'venue-title');assert.equal(f.$('#venue-title').lastFocus.preventScroll,true);assert.equal(f.$('#detail-actions').scrolled.block,'start');await f.click('.back');assert.equal(f.$('#query').value,'感知');assert.equal(f.$('#kind').value,'journal');assert.equal(f.document.activeElement.getAttribute('data-id'),'tro');await f.back();assert.equal(f.$('#venue-title').textContent,'IEEE T-RO');await f.back();assert.equal(f.$('#workspace').hidden,true);await f.forward();assert.equal(f.$('#workspace').hidden,false)});
test('fresh direct links restore experience filters, edition selection, and return destinations',async()=>{const e=await fixture('#experiences?ev=ral&et=first_person_self_report&eq=修订');assert.equal(e.$$('#experience-list .experience').length,1);assert.equal(e.$('#e-venue').value,'ral');const f=await fixture('#venues/corl?from=deadlines&dv=corl&edition=corl-2024');assert.equal(f.$('#edition').value,'corl-2024');assert.equal(f.document.activeElement.id,'venue-title');assert.equal(f.$('.back').getAttribute('href'),'#deadlines?dv=corl');await f.click('.back');assert.equal(f.$('#d-venue').value,'corl');assert.equal(f.document.activeElement.id,'page-title')});
test('route changes and repeated permalinks focus the new content without changing skip state',async()=>{const f=await fixture();await f.click('#nav-experiences');assert.equal(f.document.activeElement.id,'page-title');assert.equal(f.$('#page-title').scrolled.block,'start');assert.equal(f.$('#page-title').scrolled.behavior,'auto');await f.click('[href="#experiences/milford-robotics-paper-structure-2023"]');const card=f.$('#experience-milford-robotics-paper-structure-2023');assert.equal(card.querySelector('details').open,true);assert.equal(f.document.activeElement,card);await f.click('[href="#experiences/milford-robotics-paper-structure-2023"]');assert.equal(f.document.activeElement,f.$('#experience-milford-robotics-paper-structure-2023'));const before=f.location.href;await f.click('.skip');assert.equal(f.location.href,before);assert.equal(f.document.activeElement.id,'experience-milford-robotics-paper-structure-2023')});
test('Escape respects global overlays and select controls before leaving a venue',async()=>{const f=await fixture('#venues/rss');const button=f.document.querySelector('button');button.setAttribute('class','mobile-menu');button.setAttribute('aria-expanded','true');await f.key('Escape');assert.match(f.location.hash,/venues\/rss/);button.setAttribute('aria-expanded','false');await f.key('Escape',f.$('#edition'));assert.match(f.location.hash,/venues\/rss/);await f.key('Escape');assert.equal(f.location.hash,'#venues');assert.equal(f.$('#workspace').hidden,true)});
test('copy provides success/failure feedback and discards promises after navigation',async()=>{const f=await fixture('#venues/rss');await f.click('#copy-venue');assert.equal(f.copied[0],f.location.href);assert.match(f.$('#copy-status').textContent,/已复制/);const bad=await fixture('#venues/rss',{copyFails:true});await bad.click('#copy-venue');assert.match(bad.$('#copy-status').textContent,/复制不可用/);const pending=await fixture('#venues/rss',{deferClipboard:true});await pending.click('#copy-venue');await pending.navigate('#experiences');pending.pending[0].reject(Error('Late failure'));await pending.flush();assert.equal(pending.logs.length,0);assert.equal(pending.$('#experiences-view').hidden,false)});
test('load failure exposes one retry and successful retry installs working flows once',async()=>{const f=await fixture('',{failFirst:true});assert.equal(f.$('#retry-load').hidden,false);assert.match(f.$('#load-status').textContent,/暂时未加载成功/);await f.click('#retry-load');assert.equal(f.fetches.length,2);assert.equal(f.$('#retry-load').hidden,true);assert.equal(f.$$('.venue-card').length,15);await f.click('#nav-experiences');assert.equal(f.$$('#experience-list .experience').length,7);assert.equal(f.window.listeners.hashchange.length,1)});

test('one compact task bar replaces duplicate entries and each venue has one primary detail action',async()=>{const f=await fixture();assert.equal(f.$$('.submission-tabs').length,1);assert.equal(f.$$('.start-routes').length,0);assert.equal(f.$$('.venue-card').length,15);assert.equal(f.$$('.venue-card .primary-action').length,15);assert.equal(f.$$('.venue-card h3 a').length,0);assert.equal(f.$('#reset').disabled,true);await f.input('#query','RA-L');assert.equal(f.$('#reset').disabled,false);await f.click('[data-id="ral"]');assert.equal(f.$('#task-intro').hidden,true);assert.equal(f.$$('#detail [href="#experiences?ev=ral"]').length,1);assert.equal(f.$('#venue-title').tagName,'H1');await f.click('.skip');assert.equal(f.document.activeElement.id,'venue-title')});
test('task switches remember independent filters and reset updates the remembered destination',async()=>{const f=await fixture();await f.input('#query','感知');await f.input('#kind','journal');await f.click('#nav-experiences');await f.input('#e-venue','ral');await f.input('#e-type','first_person_self_report');await f.click('#nav-deadlines');await f.input('#d-venue','rss');await f.click('#nav-venues');assert.equal(f.$('#query').value,'感知');assert.equal(f.$('#kind').value,'journal');await f.click('#nav-experiences');assert.equal(f.$('#e-venue').value,'ral');assert.equal(f.$('#e-type').value,'first_person_self_report');await f.click('#e-reset');await f.click('#nav-deadlines');assert.equal(f.$('#d-venue').value,'rss');await f.click('#nav-experiences');assert.equal(f.$('#e-venue').value,'')});
test('single-source reading keeps its filtered return and shows a source outside the filter',async()=>{const f=await fixture('#experiences?ev=ral&et=first_person_self_report');await f.click('[href="#experiences/milford-robotics-paper-structure-2023?ev=ral&et=first_person_self_report"]');assert.equal(f.$$('#experience-list .experience').length,1);assert.equal(f.$('#experience-browse').hidden,true);assert.equal(f.$('#task-intro').hidden,true);assert.equal(f.$('#experience-back').hidden,false);assert.equal(f.$('#experience-back').getAttribute('href'),'#experiences?ev=ral&et=first_person_self_report');assert.equal(f.document.activeElement.id,'experience-milford-robotics-paper-structure-2023');await f.click('#experience-back');assert.equal(f.$('#experience-browse').hidden,false);assert.equal(f.$('#experience-back').hidden,true);assert.equal(f.$('#e-venue').value,'ral');assert.equal(f.$('#e-type').value,'first_person_self_report');assert.equal(f.$$('#experience-list .experience').length,3);await f.back();assert.equal(f.$$('#experience-list .experience').length,1);await f.forward();assert.equal(f.$$('#experience-list .experience').length,3)});

test('invalid detail links expose a visible recovery path without stranding focus',async()=>{const f=await fixture('#venues/missing?q=RA-L');assert.equal(f.$('#venue-title').textContent,'渠道不存在');assert.equal(f.document.activeElement.id,'venue-title');await f.click('.back');assert.equal(f.$('#query').value,'RA-L');assert.equal(f.$$('.venue-card').length,1);assert.equal(f.document.activeElement.id,'page-title');const e=await fixture('#experiences/missing?ev=ral');assert.equal(e.$('#experience-list').textContent.includes('经验不存在'),true);assert.equal(e.document.activeElement.id,'experience-back');await e.click('#experience-back');assert.equal(e.$$('#experience-list .experience').length,4)});
