'use strict';
// Deterministic source/runtime contracts with independently recorded local font
// advances. Actual glyph extents are additionally checked in the local SVG review.
// No browser-font or browser-layout acceptance is implied by these tests.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const base=path.resolve(__dirname,'../previews/radar-c2-analysis'),w={};
for(const file of ['data/catalog.js','data/literature.js','data/challenge.js','analysis/data/bundle.js'])vm.runInNewContext(fs.readFileSync(path.join(base,file),'utf8'),{window:w});
const M=require(path.join(base,'model.js')),A=require(path.join(base,'analysis/model.js')),m=M.buildModel(w.PAPER_CATALOG,w.LITERATURE_TREE,w.CHALLENGE_TREE),a=A.build(w.C2_DATA.schema,w.C2_DATA.mapping),trees=[M.atlas.paths(m,'l'),M.atlas.paths(m,'c'),M.atlas.analysis(a)],before=JSON.stringify(w);let checks=0;
// Noto Sans CJK SC Regular ASCII advances, independently read from the installed
// font's 1,000px metrics on 2026-10-06, ASCII U+0020 through U+007E. CJK uses 1em.
const ascii=[0.224, 0.323, 0.474, 0.555, 0.555, 0.921, 0.68, 0.278, 0.338, 0.338, 0.467, 0.555, 0.278, 0.347, 0.278, 0.392, 0.555, 0.555, 0.555, 0.555, 0.555, 0.555, 0.555, 0.555, 0.555, 0.555, 0.278, 0.278, 0.555, 0.555, 0.555, 0.474, 0.946, 0.608, 0.657, 0.638, 0.688, 0.589, 0.552, 0.689, 0.728, 0.293, 0.535, 0.646, 0.543, 0.812, 0.723, 0.742, 0.633, 0.742, 0.635, 0.596, 0.599, 0.721, 0.575, 0.878, 0.573, 0.531, 0.603, 0.338, 0.392, 0.338, 0.555, 0.559, 0.606, 0.563, 0.618, 0.51, 0.62, 0.554, 0.325, 0.564, 0.607, 0.275, 0.275, 0.552, 0.284, 0.926, 0.61, 0.606, 0.62, 0.62, 0.388, 0.468, 0.377, 0.607, 0.521, 0.802, 0.498, 0.521, 0.475, 0.338, 0.27, 0.338, 0.555];
function advance(text,font){return [...text].reduce((sum,c)=>sum+(ascii[c.codePointAt(0)-32]??1)*font,0);}
function test(name,fn){fn();checks++;console.log('PASS '+name);}
function bounds(lines,width,font){for(const line of lines){assert(advance(line,font)<=width-14+.001,'independent font advance exceeds padded box: '+line);assert(M.atlas.labelUnits(line)*font<=width-16+.001,'conservative wrap budget exceeded: '+line);}}
function contract(atlas,sourceId,mode){const t=trees[0],scene=atlas.layout(t,{mode,width:720}),n=scene.nodes.find(n=>n.sourceId===sourceId),source=t.by.get(n.id);assert(n);assert.equal(n.labelLines.join(''),source.label.replace(/\n/g,''));for(const line of n.labelLines)assert(advance(line,mode==='full'?14:13)<=n.w-14+.001,'measured-font overflow: '+line);return n;}
test('exact mixed-Latin/CJK EQA label is preserved and padded at the narrow 142px semantic column',()=>{const n=contract(M.atlas,'task-eqa-active-other','semantic');assert.equal(n.label,'主动EQA（HM-EQA/MT-HM3D/EXPRESS）');assert.equal(n.w,142);assert(n.labelLines.length>1);for(const name of ['HM-EQA','MT-HM3D','EXPRESS'])assert(n.labelLines.some(line=>line.includes(name)),'scientific component split: '+name);assert(!n.labelLines.join('').includes('…'));});
test('full-view EmbodiedQA label no longer exceeds its 230px box',()=>{const n=contract(M.atlas,'task-embodiedqa-classic','full');assert.equal(n.label,'EmbodiedQA：为回答问题而导航取证');assert.equal(n.w,230);});
test('all exported full/semantic node and fold labels fit with complete text at five widths',()=>{for(const t of trees)for(const mode of ['semantic','full'])for(const width of [220,366,560,720,1100]){const selected=t.kind==='a'?'method.module1.why':t.nodes.find(n=>n.paperId==='harnessvln')?.id||t.root,g=M.atlas.layout(t,{mode,width,selected});for(const n of g.nodes){assert.equal(n.labelLines.join(''),M.atlas.displayLabel(t,t.by.get(n.id)).replace(/\n/g,''));bounds(n.labelLines,n.w,mode==='full'?14:13);bounds(n.foldLines,n.w,10);if(n.hidden)assert.equal(n.foldLines.join(''),n.foldedLabel);assert(n.h>=n.labelLines.length*(mode==='full'?19:18)+n.foldLines.length*12+14);assert(n.y+n.h<=g.height);}const h=M.atlas.svg(t,selected,t.kind,{mode});assert(!/textLength=|lengthAdjust=|clip-path=/.test(h),'labels cannot be squeezed or clipped to pass');assert.equal((h.match(/class="atlas-node-label"/g)||[]).length,M.atlas.layout(t,{mode,selected}).nodes.reduce((sum,n)=>sum+n.labelLines.length,0));}});
test('all complete source labels and analysis subtitles stay padded in focused geometry',()=>{for(const t of trees){const items=t.nodes.map(n=>({...n,depth:M.atlas.route(t,n.id).length-1}));for(const width of [220,366,650,1100]){const g=M.atlas.readableLayout(items,t.root,{width});for(const n of g.nodes){assert.equal(n.labelLines.join(''),n.label.replace(/\n/g,''));bounds(n.labelLines,n.w-18,15);bounds(n.subLines,n.w-18,12);assert.equal(n.subLines.join(''),(n.contentTitle||'').replace(/\n/g,''));assert(n.h>=16+n.labelLines.length*21+n.subLines.length*17);assert(n.x+n.w<=g.width&&n.y+n.h<=g.height);}for(const depth of new Set(g.nodes.map(n=>n.depth))){const column=g.nodes.filter(n=>n.depth===depth).sort((a,b)=>a.y-b.y);for(let i=1;i<column.length;i++)assert(column[i-1].y+column[i-1].h<=column[i].y,'neighbor boxes overlap');}}}});
test('wide acronyms, mixed names and explicit paragraph breaks retain every character',()=>{for(const text of ['WWMMmwmw混合名称','HM-EQA/MT-HM3D/EXPRESS','EmbodiedQA：为回答问题而导航取证','OpenEQA · A-EQA','首行\n第二行 with ASCII', 'MW@%& + @@@'])for(const width of [90,106,142,155,230])for(const font of [10,13,14,15]){const lines=M.atlas.lines(text,width,font);assert.equal(lines.join(''),text.replace(/\n/g,''));bounds(lines,width,font);}});
test('negative controls reject both original overflows and text truncation',()=>{const source=fs.readFileSync(path.join(base,'model.js'),'utf8'),mutations=[source.replace(/function labelUnits\(text\)\{[^\n]+\}/,"function labelUnits(text){return [...String(text)].reduce((n,c)=>n+(/[\\u0020-\\u007e]/.test(c)?.52:1),0);}"),source.replace('labelLines=ls,','labelLines=ls.map(line=>line.slice(0,3)),')];for(const changed of mutations){assert.notEqual(changed,source);const context={module:{exports:{}}};vm.runInNewContext(changed,context);assert.throws(()=>contract(context.module.exports.atlas,'task-eqa-active-other','semantic'));if(changed===mutations[0])assert.throws(()=>contract(context.module.exports.atlas,'task-embodiedqa-classic','full'));}});
test('wrapping and layout leave source data, labels, order, IDs and hierarchy untouched',()=>{for(const t of trees){const snapshot=JSON.stringify(t.nodes);M.atlas.layout(t,{mode:'full'});M.atlas.svg(t);assert.equal(JSON.stringify(t.nodes),snapshot);}assert.equal(JSON.stringify(w),before);});
console.log(JSON.stringify({checks,kind:'source/runtime/font-advance regression contracts; not browser QA'}));
