'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const api=require('../previews/library-topic-preview/preview.js'),data=JSON.parse(fs.readFileSync(path.join(__dirname,'../previews/library-topic-preview/topics.json'))),fixtures=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/library-semantic-cases.json')));
let checks=0;function test(name,fn){fn();checks++;}
const find=s=>api.queryRecords(data,s),ids=(s,group='main')=>find(s)[group].map(x=>x.record.id),row=id=>data.records.find(r=>r.id===id);
for(const [i,fixture] of fixtures.entries())test('reference parity '+i,()=>{const r=find(fixture);for(const group of ['main','weak','uncertain'])assert.deepEqual(r[group].map(x=>x.record.id),fixture.expected[group],JSON.stringify(fixture));assert.equal(r.counts.unique_total,new Set([...r.main,...r.weak,...r.uncertain].map(x=>x.record.id)).size);});
test('all 95 default',()=>assert.equal(ids({}).length,95));
test('empty query all 95',()=>assert.equal(ids({q:' \t '}).length,95));
for(const r of data.records)test('every exact title retrievable '+r.id,()=>assert(ids({q:r.title}).includes(r.id),r.title));
for(const r of data.records)for(const alias of r.aliases)test('every alias retrievable '+r.id+alias,()=>assert(ids({q:alias}).includes(r.id),alias));
test('RL never substring world',()=>{assert.deepEqual(ids({q:'RL'}),ids({methods:['RL']}));assert(!ids({q:'RL'}).includes('rpa-0071'));assert(ids({q:'World Model'}).includes('rpa-0071'));});
test('case-insensitive exact semantic aliases',()=>assert.deepEqual(ids({q:'Reinforcement Learning'}),ids({q:'强化学习'})));
test('platform query equals platform filter',()=>{for(const [a,b] of [['四足','quadruped'],['足式','legged'],['双臂','dual_arm'],['固定基座','fixed_base']])assert.deepEqual(ids({q:a}),ids({platforms:[b]}));});
test('resource query equals resource filter',()=>{assert.deepEqual(ids({q:'数据集'}),ids({resources:['dataset']}));assert.deepEqual(ids({q:'data-collection'}),ids({resources:['data-collection']}));});
test('FAST mobile weak only',()=>{assert(ids({q:'移动操作'},'weak').includes('rpa-0016'));assert(!ids({q:'移动操作'}).includes('rpa-0016'));assert(ids({q:'操作'}).includes('rpa-0016'));assert(ids({q:'动作分词'}).includes('rpa-0016'));});
test('GeFF reason includes representation and quantitative nav',()=>assert.match(find({q:'导航'}).main.find(x=>x.record.id==='rpa-0027').reason,/场景表示.*导航.*成功率/));
test('NaVILA not inferred quadruped',()=>{assert(ids({platforms:['legged']}).includes('rpa-0041'));assert(!ids({platforms:['quadruped']}).includes('rpa-0041'));});
test('coupled simulation scope preserved',()=>assert.match(find({q:'移动操作'}).main.find(x=>x.record.id==='rpa-0069').reason,/仅在仿真.*实机.*分开/));
test('HoloAgent qualitative + adoption preserved',()=>assert.match(find({q:'移动操作'}).main.find(x=>x.record.id==='holoagent-0').reason,/定性演示.*已有操作后端/));
test('mobile subtype explicit',()=>assert.match(find({q:'操作'}).main.find(x=>x.record.id==='rpa-0027').reason,/移动操作属于操作任务.*不据此推断固定基座/));
test('unknown task stays separate',()=>{assert(ids({q:'移动操作'},'uncertain').includes('rpa-0051'));assert(!ids({q:'移动操作'}).includes('rpa-0051'));assert(ids({q:row('rpa-0051').title}).includes('rpa-0051'));});
test('unknown platform does not satisfy positive filter',()=>{for(const r of data.records.filter(x=>!x.platforms.length)){assert(ids({}).includes(r.id));assert(!ids({platforms:['legged']}).includes(r.id));}});
test('OR same dimension',()=>{assert.deepEqual(new Set(ids({methods:['RL','WBC']})),new Set([...ids({methods:['RL']}),...ids({methods:['WBC']})]));});
test('AND between dimensions',()=>{const methods=new Set(ids({methods:['RL']})),platforms=new Set(ids({platforms:['legged']}));assert.deepEqual(ids({methods:['RL'],platforms:['legged']}),data.records.filter(r=>methods.has(r.id)&&platforms.has(r.id)).map(r=>r.id));});
test('query term and method filter combine OR in method dimension',()=>assert.deepEqual(ids({q:'RL',methods:['WBC']}),ids({methods:['RL','WBC']})));
test('text search multiword order',()=>assert.deepEqual(ids({q:'UMI legs'}),ids({q:'legs UMI'})));
test('input trailing spaces retained',()=>assert.equal(api.normalizeState({q:'UMI '}).q,'UMI '));
test('URL round trip Unicode, facets and detail',()=>{const s={q:'移动操作 & UMI',methods:['rl','wbc'],platforms:['legged','mobile_manipulator'],resources:['dataset'],paper:'rpa-0062'};assert.deepEqual(api.stateFromSearch(api.stateToSearch(s)),s);});
test('URL detail preserves search filters',()=>{const s={q:'导航',methods:['rl'],platforms:[],resources:[],paper:'rpa-0027'};const parsed=api.stateFromSearch(api.stateToSearch(s));assert.equal(parsed.q,'导航');assert.deepEqual(parsed.methods,['rl']);parsed.paper='';assert(!api.stateToSearch(parsed).includes('paper'));});
test('one chip removal preserves others',()=>{const state={q:'导航',methods:['rl','wbc'],platforms:['legged'],resources:[],paper:''},next=api.toggleFilter(state,'methods','rl');assert.deepEqual(next.methods,['wbc']);assert.deepEqual(next.platforms,['legged']);assert.equal(next.q,'导航');assert.deepEqual(state.methods,['rl','wbc']);});
test('reset defaults excludes no record',()=>{assert.equal(api.stateToSearch(api.defaultState()),'');assert.equal(ids(api.defaultState()).length,95);});
test('URL duplicates deduplicated',()=>assert.deepEqual(api.stateFromSearch('?method=RL&method=rl&platform=quadruped&platform=四足').methods,['rl']));
test('displayed matching facets carry their actual evidence',()=>{for(const state of [{platforms:['quadruped']},{q:'四足'},{methods:['RL']},{q:'RL'},{resources:['dataset']},{q:'数据集'}])for(const item of find(state).main){for(const id of item.record.study_question_evidence_ids)assert(item.evidence_ids.includes(id));const query=find(state).query,ms=[...(state.methods||[])],ps=[...(state.platforms||[])],rs=[...(state.resources||[])];if(query.kind==='method')ms.push(query.value);if(query.kind==='platform')ps.push(query.value);if(query.kind==='resource')rs.push(query.value);const claims=[...item.record.methods.filter(m=>ms.map(api.canonicalMethod).includes(api.canonicalMethod(m.label))),...item.record.platforms.filter(p=>p.filter_keys.some(k=>ps.map(api.canonicalPlatform).includes(k))),...item.record.resources.filter(r=>rs.includes(r.kind))];for(const claim of claims)for(const id of claim.evidence_ids)assert(item.evidence_ids.includes(id),item.record.id+' '+id);}});
test('HTML escaping',()=>assert.equal(api.escapeHTML('<img src=x onerror="x"> & \'x\''),'&lt;img src=x onerror=&quot;x&quot;&gt; &amp; &#39;x&#39;'));
test('malicious text rendered inert',()=>{const fake={...row('rpa-0016'),title:'<img src=x onerror=alert(1)>',study_question:'<script>alert(1)</script>'};assert(!api.renderCard({record:fake,reason:fake.study_question}).includes('<script>'));assert(api.renderCard({record:fake,reason:'okay'}).includes('&lt;img'));});
test('source protocol rejects script, credentials, insecure URL',()=>{for(const url of ['javascript:alert(1)','http://example.com','https://u:p@example.com','file:///etc/passwd'])assert.equal(api.safeSourceURL(url),'');});
test('detail shows sources and full authors, no raw markup',()=>{const r=row('qwen-robotnav'),html=api.renderDetail(r);assert(html.includes('Xiong-Hui Chen'));assert(html.includes('查看来源与具体位置'));assert(html.includes('target="_blank" rel="noopener noreferrer"'));assert(!html.includes('undefined'));});
test('no default category wall; keyboard and dialog contract',()=>{const html=fs.readFileSync(path.join(__dirname,'../previews/library-topic-preview/index.html'),'utf8');assert(!html.includes('id="topics"'));assert.match(html,/id="filter-panel" hidden/);assert.equal((html.match(/data-query=/g)||[]).length,2);assert.match(html,/id="weak-section"[^>]+hidden/);assert.match(html,/id="paper-dialog" aria-labelledby="detail-title"/);assert.match(html,/独立方案预览/);});
test('type scale and compact controls meet readability floor',()=>{const css=fs.readFileSync(path.join(__dirname,'../previews/library-topic-preview/preview.css'),'utf8');for(const match of css.matchAll(/font-size:(\d+)px/g))assert(Number(match[1])>=14);assert(!css.includes('min-height:36px'));assert(css.includes('min-height:44px'));assert(css.includes('@media(prefers-reduced-motion:reduce)'));});
console.log('PASS: '+checks+' library preview checks, including '+fixtures.length+' exact independent-reference parity cases');

require("./test_library_preview_controller.cjs");
