'use strict';
// Each production HTML scenario gets a separate heap. No browser network access.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'..'),scenarios=['density-budget','retry-multiple','cold-clamp-c','cold-clamp-g','cold-clamp-g-scope','cold-clamp','cold-clamp-focus','cold-clamp-wheel','cold-clamp-scope','density','offline','retry-stability','retry-cancel','return-clamp','return-clamp-focus','return-clamp-wheel','return-clamp-scope','method-claim-typography','typography','coverage','entries','evidence','versions','summaries','async','failures','return','conditions','cold-restore','cold-focus','cold-key','cold-pointer','cold-click','cold-scope','cold-reader','cold-wheel','cold-touch','cold-pre-focus','cold-pre-key','settled-teardown','settled-teardown-failure','settled-teardown-error','settled-teardown-timeout'];
if(!process.env.NP_TASK_ROUTE_CASE){
 for(const name of scenarios)test('task route production contract: '+name,t=>{const env={...process.env,NP_TASK_ROUTE_CASE:name};delete env.NODE_TEST_CONTEXT;const result=cp.spawnSync(process.execPath,['--test',__filename],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(result.stdout)t.diagnostic(result.stdout);if(result.stderr)t.diagnostic(result.stderr);assert.ifError(result.error);assert.equal(result.signal,null);assert.equal(result.status,0,result.stdout+result.stderr);});
}else{
 const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),temp=fs.mkdtempSync(path.join(root,'.navigation-task-routes-'));
 cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;p.write_preview(Path('.').resolve(),Path(sys.argv[1]))",temp],{cwd:root});
 const output=path.join(temp,'research/navigation'),html=fs.readFileSync(path.join(output,'index.html'),'utf8');
 const scienceBytes=zlib.gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz'))),raw=JSON.parse(scienceBytes),taskIds=raw.directoryGroups.find(g=>g.id==='task').scopeIds,wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 test.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
 function scenario(name,fn){if(process.env.NP_TASK_ROUTE_CASE===name)test(name,fn);}
 async function frames(w){await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));}
 async function page(options={}){
  const calls=[],errors=[],queuedFrames=[];class Resources extends ResourceLoader{fetch(url){throw new Error('Unexpected external request '+url);}}
  const vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error.message));
  const d=new JSDOM(html,{url:'https://example.org/research/navigation/'+(options.hash||''),runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
   if(options.holdFrames)w.requestAnimationFrame=fn=>{queuedFrames.push(fn);return queuedFrames.length;};if(options.width)Object.defineProperty(w,'innerWidth',{value:options.width,configurable:true});w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});
   if(options.saved)w.history.replaceState(options.saved,'',w.location.href);w.fetch=url=>{calls.push(url);if(options.fetch)return options.fetch(url);if(options.offline)return new Promise(()=>{});return Promise.resolve({ok:true,arrayBuffer:async()=>fs.readFileSync(path.join(output,url))});};
  }});
  for(let i=0;i<150&&!d.window.NavigationProductApp;i++)await wait(10);assert.ok(d.window.NavigationProductApp);if(!options.holdFrames)await frames(d.window);return {w:d.window,doc:d.window.document,calls,errors,flushFrames:()=>{while(queuedFrames.length)queuedFrames.shift()();}};
 }
 // A loaded overview does not imply that the selected scope body has settled.
 // Observe only jobs already started by the UI, without starting idle packets or
 // handling their rejections. Give their real promise callbacks a turn to finish
 // before closing the JSDOM window, which removes window.document.
 async function closePage(x,timeoutMs=30000){
  const app=x.w.NavigationProductApp,content=app.getContent(),ids=Object.keys(app.getBundle().delivery.packets),loading=()=>ids.filter(id=>content.status(id)==='loading');let timer;
  try{
   await Promise.race([(async()=>{
    do{
     if(loading().length)await new Promise(resolve=>{function check(){if(!loading().length)resolve();}content.subscribe(check);check();});
     await new Promise(resolve=>setImmediate(resolve));await frames(x.w);
    }while(loading().length);
    assert.deepEqual(x.errors,[],'no late JSDOM errors during teardown');
   })(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Page teardown timed out; loading owners: '+loading().join(', '))),timeoutMs);})]);
  }finally{clearTimeout(timer);x.w.close();}
 }

 function scope(x,id,tree='l'){const a=x.w.NavigationProductApp;x.w.NavigationProductApp.navigate(x.w.NavigationProductModel.initialState(a.getBundle(),{scope:id,tree}).route);return x.doc.querySelector('[data-task-route-scope],[data-task-route-pending-scope]');}
 function below(ids){return ids.flatMap(id=>[raw.positions[id],...below(raw.positions[id].childIds)]);}
 function methods(id,tree='l'){return below(raw.forests[id][tree]).filter(p=>['pipeline_recipe','versioned_method_card'].includes(p.kind));}
 function partition(id){const children=raw.forests[id].l.flatMap(r=>raw.positions[r].childIds.map(id=>raw.positions[id]));return {groups:children.filter(p=>!['pipeline_recipe','versioned_method_card'].includes(p.kind)&&below([p.id]).some(q=>['pipeline_recipe','versioned_method_card'].includes(q.kind))),ungrouped:children.filter(p=>['pipeline_recipe','versioned_method_card'].includes(p.kind)),supplemental:children.filter(p=>!below([p.id]).some(q=>['pipeline_recipe','versioned_method_card'].includes(q.kind)))};}
 async function loaded(x){for(let i=0;i<150&&x.doc.querySelector('#np-task-route-canvas .np-content-pending');i++)await wait(10);assert.equal(x.doc.querySelector('#np-task-route-canvas .np-content-pending'),null);}
 function change(x,id){return x.doc.querySelector('#np-task-route-canvas button[data-task-change="'+(String(id).startsWith('methods:relation:')?id:'methods:relation:'+id)+'"]');}
 function relationDisclosure(x){return x.doc.getElementById('np-task-route-relations');}
 async function openRelations(x){const panel=relationDisclosure(x);assert.ok(panel);assert.equal(panel.tagName,'DETAILS');if(!panel.open){panel.querySelector(':scope > summary').click();await frames(x.w);}assert.equal(panel.open,true,'relations opened through the visible summary');return panel;}
 function relationReading(x){return x.doc.querySelector('#np-reader-summary [data-selected-task-relation]');}
 async function selectRelation(x,id){await openRelations(x);const control=change(x,id);assert.ok(control,'relation selector '+id);assert.equal(control.closest('details').open,true);control.click();await frames(x.w);const reading=relationReading(x);assert.ok(reading);assert.equal(reading.dataset.selectedTaskRelation,control.dataset.taskChange);assert.equal(x.doc.querySelectorAll('[data-selected-task-relation]').length,1);return reading;}
 function exposePosition(x,p){const app=x.w.NavigationProductApp,M=x.w.NavigationProductModel;for(const id of M.ancestors(app.getBundle(),p.id)){const node=x.doc.getElementById('np-node-'+id);assert.ok(node,'real ancestor '+id);if(node.getAttribute('aria-expanded')==='false')node.querySelector(':scope > .np-node-row > .np-node-toggle').click();}const node=x.doc.getElementById('np-node-'+p.id);assert.ok(node,'reachable real position '+p.id);assert.equal(node.closest('#np-tree'),x.doc.getElementById('np-tree'));assert.equal(node.dataset.position,p.id);assert.equal(node.dataset.parent,p.parentId||'');assert.equal(node.dataset.entity,p.entityId);assert.equal(node.dataset.tree,p.tree);assert.equal(node.dataset.association,p.association||'');assert.equal(node.closest('[hidden]'),null,p.id+' has no hidden ancestor');for(let at=node;at&&at!==x.doc.getElementById('np-tree-scroll');at=at.parentElement){assert.notEqual(x.w.getComputedStyle(at).display,'none',p.id+' has no CSS-hidden ancestor');assert.notEqual(x.w.getComputedStyle(at).visibility,'hidden',p.id+' is visible in its real forest');}assert.notEqual(x.w.getComputedStyle(node.querySelector(':scope > .np-node-row')).display,'none');return node;}
 async function visitPosition(x,p){const node=exposePosition(x,p);node.querySelector(':scope > .np-node-row > .np-node-label').click();const app=x.w.NavigationProductApp;for(let i=0;i<150&&['idle','loading'].includes(app.getContent().status(p.entityId));i++)await wait(10);await frames(x.w);assert.equal(app.getState().route.node,p.id);assert.equal(app.getState().route.tree,p.tree);assert.equal(app.getState().route.scope,p.scopeId);assert.equal(app.getState().route.paper,p.paperId||null);assert.equal(app.getState().route.version,p.versionId||null);return x.doc.getElementById('np-reader-summary');}
 function textOf(value){if(value==null)return '';if(typeof value==='string'||typeof value==='number')return String(value).replace(/\\n/g,'\n');if(Array.isArray(value))return value.map(textOf).filter(Boolean).join('；');return textOf(value.text||value.value||value.description||value.statement||'');}
 // Approved display-only exceptions: remove these complete leading editorial prefixes; keep the entire scientific tail.
 const conditionDisplayPrefixes=["编辑归纳绑定：direct_to_LH_VLN_method；需新增MGDM论文/版本后计数。","编辑归纳绑定：direct_to_v5_setting；新建paper/version绑定后才可计入覆盖。"];
 function assertMethodReading(x,p){const reader=x.doc.getElementById('np-reader-summary'),method=reader.querySelector('[data-mechanism-entity="'+p.entityId+'"]'),d=raw.entities[p.entityId].detail||{},flow=d.pipeline||d.pipeline_contract;assert.ok(method,p.id);assert.equal(reader.querySelectorAll('[data-mechanism-entity]').length,1);assert.equal(reader.querySelector('[data-task-change], [data-route-method], [data-route-group]'),null);if(flow){const dl=method.querySelector('.np-method-flow');assert.ok(dl,p.id);assert.equal(dl.closest('details'),null);for(const key of ['input','representation','decision','execution','feedback'])if(flow[key])assert.ok(dl.textContent.includes(textOf(flow[key])),p.id+' '+key);}else for(const cid of [...new Set([...(p.claimIds||[]),...(raw.entities[p.entityId].claimIds||[])])]){const c=raw.claims[cid];if(c&&c.paperId===p.paperId&&c.versionId===p.versionId){const claim=method.querySelector('[data-method-claim="'+cid+'"]');assert.ok(claim,cid);assert.ok(claim.textContent.includes(c.statement||c.label));}}
  for(const key of ['requiredDisplayConditions','condition','scope','limits','boundaries'])if(d[key]){const values=Array.isArray(d[key])?d[key]:[d[key]];for(const value of values){const original=textOf(value),prefix=key==='condition'&&conditionDisplayPrefixes.find(item=>original.startsWith(item)),expected=prefix?original.slice(prefix.length).trimStart():original;if(prefix)assert.ok(expected.length>0,p.id+' scientific condition tail is nonempty');assert.ok(method.textContent.includes(expected),p.id+' '+key+' complete scientific text');}}for(const prefix of conditionDisplayPrefixes)assert.equal(reader.textContent.includes(prefix),false,p.id+' internal editorial prefix is absent from the reader');if(p.condition)assert.ok(x.doc.getElementById('np-node-'+p.id).textContent.includes(textOf(p.condition)));return method;}
 function assertCanvas(x,id,tree='l'){const canvas=x.doc.getElementById('np-task-route-canvas'),reader=x.doc.getElementById('np-reader-summary'),forest=x.doc.querySelector('#np-tree [data-parallel-tree]');assert.equal(canvas.closest('#np-tree-scroll'),x.doc.getElementById('np-tree-scroll'));assert.equal(canvas.closest('#np-tree'),null);assert.ok(canvas.compareDocumentPosition(x.doc.getElementById('np-tree'))&x.w.Node.DOCUMENT_POSITION_FOLLOWING,'relation disclosure precedes the true tree');assert.equal(x.doc.getElementById('np-tree').closest('details'),null);assert.equal(canvas.querySelector('[role=tree], [role=treeitem], [data-route-method], [data-route-group]'),null);assert.equal(reader.querySelector('[data-task-change], [data-route-method], [data-route-group], [data-position]'),null);if(tree!=='g'){assert.ok(forest);assert.equal(forest.dataset.parallelTree,tree);assert.equal(forest.dataset.scopeId,id);assert.equal(x.doc.querySelectorAll('#np-tree [data-parallel-tree]').length,1);assert.equal(reader.querySelector('[data-task-reader-scope]').dataset.taskReaderScope,id);}for(const row of canvas.querySelectorAll('[data-task-change]')){const r=raw.relations[row.dataset.taskChange];assert.ok(r);assert.equal(row.tagName,'BUTTON');assert.equal(row.id,'np-task-change-'+id+'-'+r.id);assert.equal(row.dataset.relationType,r.relationType);assert.equal(row.dataset.fromEntity,r.from);assert.equal(row.dataset.toEntity,r.to);assert.equal(row.dataset.renderAsTree,'false');assert.equal(row.getAttribute('aria-controls'),'np-reader-summary');assert.equal(row.querySelector('[data-task-change-claim], [data-change-target]'),null);}const panel=relationDisclosure(x),summary=panel.querySelector(':scope > summary'),current=canvas.querySelectorAll('[data-change-scope="current-scope"]').length,outside=canvas.querySelectorAll('[data-change-scope="outside-scope"]').length;assert.equal(summary.id,'np-task-route-relations-summary');if(panel.dataset.taskRouteState==='loading'){assert.match(summary.textContent,/资料待载入/);assert.doesNotMatch(summary.textContent,/已核关系（0）/);assert.equal(panel.dataset.currentRelationCount,undefined);}else{assert.equal(panel.dataset.currentRelationCount,String(current));assert.equal(panel.dataset.outsideRelationCount,String(outside));if(panel.dataset.taskRouteState==='ready')assert.equal(summary.textContent,'方法之间的已核关系（'+current+'）'+(outside?' · 范围外关联（'+outside+'）':''));else{assert.match(summary.textContent,/部分资料未载入/);assert.ok(summary.textContent.includes('本范围已载入 '+current+' 条'));if(outside)assert.ok(summary.textContent.includes('范围外已载入 '+outside+' 条'));}}} 
 function assertRelationEvidence(x,id,scopeId){const row=relationReading(x),r=raw.relations[id],localMethods=methods(scopeId);assert.equal(row.dataset.selectedTaskRelation,id);assert.equal(row.dataset.relationType,r.relationType);assert.equal(row.dataset.fromEntity,r.from);assert.equal(row.dataset.toEntity,r.to);assert.equal(row.dataset.renderAsTree,'false');for(const cid of r.claimIds||r.detail&&r.detail.claimIds||[]){const c=raw.claims[cid],claim=row.querySelector('[data-task-change-claim="'+cid+'"]');assert.ok(claim,cid);assert.equal(claim.querySelector('.np-change-claim').textContent,c.statement||c.label);assert.equal(claim.dataset.evidenceVersion,c.versionId||'');assert.equal(claim.dataset.versionRelation,localMethods.some(p=>p.paperId===c.paperId&&p.versionId===c.versionId)?'same-version':'other-version');if(c.locator||c.detail&&c.detail.locator)assert.ok(claim.textContent.includes(textOf(c.locator||c.detail.locator)),cid+' locator');for(const ref of c.sourceRefs||[]){if(ref.url)assert.ok(claim.querySelector('a[href="'+ref.url+'"]'),cid+' source');if(typeof ref.locator==='string'&&ref.locator!=='unknown')assert.ok(claim.textContent.includes(ref.locator),cid+' source locator');}}for(const target of row.querySelectorAll('[data-change-target]')){const p=raw.positions[target.dataset.changeTarget];assert.ok(p);assert.ok([r.from,r.to].some(e=>raw.entities[e].paperId===p.paperId));const v=raw.versions[p.versionId];if(v){const label=v.label||v.descriptor||p.versionId;assert.ok(target.textContent.includes(label==='unknown'?'来源版本待核':label),p.id+' exact source version');}else{assert.equal(p.versionId||null,null,p.id+' source record is not silently missing');assert.ok(target.textContent.includes('来源版本待选择'),p.id+' unbound source remains explicit');}}return row;}

 function release(pending,url,bytes){assert.ok(pending.has(url),url);pending.get(url)({ok:true,arrayBuffer:async()=>bytes||fs.readFileSync(path.join(output,url))});pending.delete(url);}
 function ownerURL(x,id){return 'content/'+x.w.NavigationProductApp.getBundle().delivery.packets[id].sha256+'.json';}
 for(const mode of ['success','failure','error','timeout'])scenario(mode==='success'?'settled-teardown':'settled-teardown-'+mode,async t=>{
  let heldURL,releaseBody;
  const x=await page({fetch:url=>Promise.resolve({ok:true,arrayBuffer:()=>url===heldURL?new Promise(resolve=>{releaseBody=()=>resolve(mode==='failure'?Buffer.from('{}'):fs.readFileSync(path.join(output,url)));}):Promise.resolve(fs.readFileSync(path.join(output,url)))})});t.after(()=>x.w.close());
  heldURL=ownerURL(x,'task:imagenav');scope(x,'task:imagenav');await loaded(x);
  const content=x.w.NavigationProductApp.getContent();assert.equal(content.status('task:imagenav'),'loading');assert.ok(x.doc.querySelector('.np-detail-body .np-content-pending'));assert.ok(releaseBody);
  const close=closePage(x,mode==='timeout'?30:undefined),rejected=mode==='timeout'?assert.rejects(close,/Page teardown timed out; loading owners: task:imagenav/):mode==='error'?assert.rejects(close,/late teardown probe/):null;
  if(mode==='timeout'){await rejected;assert.equal(content.status('task:imagenav'),'loading');assert.equal(x.w.document,undefined);return;}
  await new Promise(resolve=>setImmediate(resolve));assert.equal(x.w.document,x.doc,'teardown waits while a selected scope body is pending');
  if(mode==='error'){const errorEvent=new Promise(resolve=>x.w.addEventListener('error',resolve,{once:true}));x.w.setTimeout(()=>{throw new Error('late teardown probe');},0);await errorEvent;}
  releaseBody();await (rejected||close);assert.equal(content.status('task:imagenav'),mode==='failure'?'failed':'ready');if(mode==='failure')assert.match(content.error('task:imagenav'),/正文字节长度不符/);assert.equal(x.w.document,undefined);if(mode!=='error')assert.deepEqual(x.errors,[]);
 });
 scenario('density-budget',async t=>{
  const x=await page();t.after(()=>closePage(x));scope(x,'task:imagenav');await loaded(x);assertCanvas(x,'task:imagenav');assert.equal(relationDisclosure(x).open,false,'new task relation disclosure starts closed');const control=change(x,95);assert.ok(control);assert.equal(control.querySelector('summary'),null);assert.equal(relationReading(x),null);const relation=await selectRelation(x,95),r=raw.relations['methods:relation:95'],labels=[r.from,r.to].map(e=>{const paper=raw.entities[e].paperId,ids=new Set(Object.values(raw.positions).filter(p=>p.kind==='pipeline_recipe'&&p.paperId===paper).map(p=>p.entityId));assert.equal(ids.size,1);return raw.entities[[...ids][0]].label.replace(/\s*输入到(?:执行)?反馈.*$/,'');});assert.ok(relation.querySelector('h2').textContent.startsWith(labels.join(' → ')+' ·'));assert.equal(relation.querySelector('.np-change-paper-identity').textContent,[r.from,r.to].map(e=>{const p=raw.papers[raw.entities[e].paperId];return p.label||p.title;}).join(' → ')+' · 有消融支持的结构发展');const claim=raw.claims['method-edge:94'],v=raw.versions[claim.versionId];assert.ok(relation.querySelector('.np-change-version').textContent.includes(v.label||v.descriptor));assert.match(relation.querySelector('.np-change-version').textContent,/未固定快照/);assertRelationEvidence(x,r.id,'task:imagenav');assert.equal(x.doc.querySelectorAll('#np-reader-summary [data-task-change-claim]').length,(r.claimIds||r.detail.claimIds).length);
  x.doc.getElementById('np-task-route-return').click();await frames(x.w);assert.equal(relationReading(x),null);assertCanvas(x,'task:imagenav');assert.equal(x.doc.activeElement,change(x,95));for(const p of methods('task:imagenav')){await visitPosition(x,p);assertMethodReading(x,p);}
  scope(x,'task:category-objectnav');await loaded(x);assert.equal(change(x,90).textContent,'SemExp → PONI · 复用组件并替换策略');const r90=await selectRelation(x,90);assert.equal(r90.querySelector('.np-change-paper-identity'),null);scope(x,'task:vln');await loaded(x);assert.ok(new Set(Object.values(raw.positions).filter(p=>p.kind==='pipeline_recipe'&&p.paperId==='duet').map(p=>p.entityId)).size>1);assert.match(change(x,97).textContent,/→ DUET ·/);assert.deepEqual(x.errors,[]);
 });
 scenario('offline',async t=>{
  const x=await page({offline:true});t.after(()=>x.w.close());assert.equal(x.calls.length,0);assert.equal(x.doc.querySelector('main').dataset.loadState,'ready');assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-task-open]')].map(n=>n.dataset.taskOpen)),new Set(taskIds));
  const panel=scope(x,'task:category-objectnav');await frames(x.w);assert.equal(panel.dataset.taskRoutePendingScope,'task:category-objectnav');assert.equal(panel.dataset.taskRouteScope,undefined);assert.equal(panel.dataset.taskRouteState,'loading');assert.equal(relationDisclosure(x).open,false);assertCanvas(x,'task:category-objectnav');assert.equal(x.doc.querySelector('[data-route-method]'),null);const node=x.doc.querySelector('#np-tree [role=treeitem]');assert.ok(node);node.focus();assert.equal(x.doc.activeElement,node);assert.equal(x.doc.querySelector('main').dataset.loadState,'ready');const app=x.w.NavigationProductApp,p=methods('task:category-objectnav')[0];exposePosition(x,p).querySelector(':scope > .np-node-row > .np-node-label').click();assert.equal(app.getState().route.node,p.id);assert.equal(app.getState().route.version,p.versionId);assert.ok(x.doc.querySelector('[data-mechanism-entity="'+p.entityId+'"]'));
 });
 scenario('density',async t=>{
  const x=await page();t.after(()=>closePage(x));let n=0;for(const entry of raw.scopes.filter(s=>s.id!=='scope:all')){scope(x,entry.id);await loaded(x);assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteState,'ready');assertCanvas(x,entry.id);const ids=[...x.doc.querySelectorAll('#np-task-route-canvas [data-task-change]')].map(n=>n.dataset.taskChange);for(const id of ids){await selectRelation(x,id);assertRelationEvidence(x,id,entry.id);assert.equal(x.doc.querySelectorAll('#np-reader-summary [data-selected-task-relation]').length,1);x.doc.getElementById('np-task-route-return').click();await frames(x.w);assert.equal(relationReading(x),null);}for(const p of methods(entry.id)){const node=exposePosition(x,p),stamp=node.querySelector(':scope > [data-route-association]');assert.ok(stamp);assert.equal(stamp.dataset.routeAssociation,p.association);assert.equal(stamp.dataset.routeVersion,p.versionId);await visitPosition(x,p);assertMethodReading(x,p);n++;}}
  assert.equal(n,81);assert.equal(n,raw.scopes.filter(s=>s.id!=='scope:all').reduce((sum,s)=>sum+methods(s.id).length,0));assert.deepEqual(x.errors,[]);
 });
 for(const cancel of [false,true])scenario(cancel?'retry-cancel':'retry-stability',async t=>{
  let badURL,retrying=false;const pending=new Map(),x=await page({fetch:url=>url===badURL?(retrying?new Promise(resolve=>pending.set(url,resolve)):Promise.resolve({ok:true,arrayBuffer:async()=>Buffer.from('{}')})):Promise.resolve({ok:true,arrayBuffer:async()=>fs.readFileSync(path.join(output,url))})});t.after(()=>closePage(x));badURL=ownerURL(x,'methods:pipeline-poni');scope(x,'task:category-objectnav');await loaded(x);const method=exposePosition(x,raw.positions['pos:l:98bc421b8bfd17d6699922']);await loaded(x);await openRelations(x);await frames(x.w);const panel=x.doc.querySelector('[data-task-route-scope]'),snapshot=panel.querySelector('.np-task-route-snapshot'),before=snapshot.innerHTML,retry=x.doc.querySelector('[data-retry-owner="methods:pipeline-poni"] button'),reader=x.doc.getElementById('np-detail-scroll'),canvas=x.doc.getElementById('np-tree-scroll'),app=x.w.NavigationProductApp;assert.equal(panel.dataset.taskRouteState,'partial');assertCanvas(x,'task:category-objectnav');assert.equal(retry.dataset.retryState,'failed');retrying=true;retry.focus();retry.click();await wait(10);assert.equal(retry.dataset.retryState,'loading');assert.equal(snapshot.innerHTML,before);method.focus();reader.scrollTop=147;canvas.scrollTop=211;
  if(cancel){scope(x,'task:aerial-visual-object-search');await loaded(x);await frames(x.w);const newer=JSON.stringify(app.getState().route),focus=x.doc.activeElement;reader.scrollTop=83;release(pending,badURL);await wait(60);assert.equal(JSON.stringify(app.getState().route),newer);assert.equal(x.doc.activeElement,focus);assert.equal(reader.scrollTop,83);retry.click();assert.equal(JSON.stringify(app.getState().route),newer);assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteScope,'task:aerial-visual-object-search');return;}
  release(pending,badURL);await wait(60);assert.equal(retry.dataset.retryState,'ready');assert.equal(snapshot.innerHTML,before);assert.equal(x.doc.getElementById(method.id),method);assert.equal(x.doc.activeElement,method);assert.equal(reader.scrollTop,147);assert.equal(canvas.scrollTop,211);assert.equal(app.getContent().attempts('methods:pipeline-poni'),2);assert.equal(retry.disabled,false);
  retry.focus();const oldTop=canvas.scrollTop;retry.getBoundingClientRect=()=>({top:snapshot.innerHTML===before?300:390});retry.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));retry.click();assert.equal(panel.dataset.taskRouteState,'ready');assert.equal(retry.dataset.retryState,'applied');assert.equal(x.doc.getElementById(retry.id),retry);assert.equal(x.doc.activeElement,retry);assert.equal(retry.disabled,false);assert.equal(reader.scrollTop,147,'relation retry does not move the reader');assert.equal(canvas.scrollTop,oldTop+90);assert.equal(x.w.NavigationProductModel.getBucket(app.getState()).treeScrollByTree.l,oldTop+90);const persisted=x.w.history.state[x.w.NavigationProductModel.KEY];assert.equal(x.w.NavigationProductModel.getBucket(persisted).treeScrollByTree.l,oldTop+90);const after=snapshot.innerHTML;retry.click();assert.equal(snapshot.innerHTML,after);assert.equal(x.doc.getElementById(method.id),method);assert.equal(snapshot.querySelector('[data-route-method], [data-mechanism-entity]'),null);await visitPosition(x,raw.positions['pos:l:98bc421b8bfd17d6699922']);assertMethodReading(x,raw.positions['pos:l:98bc421b8bfd17d6699922']);assert.deepEqual(x.errors,[]);
 });
 scenario('retry-multiple',async t=>{
  const bad=new Set();let retrying=false;const x=await page({fetch:url=>Promise.resolve({ok:true,arrayBuffer:async()=>bad.has(url)&&!retrying?Buffer.from('{}'):fs.readFileSync(path.join(output,url))})});t.after(()=>closePage(x));const ids=['methods:pipeline-poni','methods:pipeline-semexp'];for(const id of ids)bad.add(ownerURL(x,id));scope(x,'task:category-objectnav');await loaded(x);await openRelations(x);const snapshot=x.doc.querySelector('.np-task-route-snapshot'),before=snapshot.innerHTML,controls=ids.map(id=>x.doc.querySelector('[data-retry-owner="'+id+'"] button'));retrying=true;for(const control of controls)control.click();for(let i=0;i<100&&controls.some(c=>c.dataset.retryState!=='ready');i++)await wait(10);assert.ok(controls.every(c=>c.dataset.retryState==='ready'));assert.equal(snapshot.innerHTML,before);controls[0].focus();controls[0].click();for(const control of controls){assert.equal(x.doc.getElementById(control.id),control);assert.equal(control.dataset.retryState,'applied');assert.equal(control.disabled,false);assert.match(control.parentElement.textContent,/首次加载未成功/);}assert.equal(x.doc.activeElement,controls[0]);assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteState,'ready');assert.deepEqual(x.errors,[]);
 });
 scenario('coverage',async t=>{
  const x=await page();t.after(()=>closePage(x));assert.equal(x.calls.length,0);assert.equal(x.doc.querySelector('[data-task-route-scope]'),null);assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-task-open]')].map(n=>n.dataset.taskOpen)),new Set(taskIds));assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-directory-scope]')].map(n=>n.dataset.directoryScope)),new Set(raw.scopes.map(s=>s.id)));
  let seen=0,variantGroups=0,repeatedEntities=0;const visited={l:new Set(),c:new Set()};for(const entry of raw.scopes.filter(s=>s.id!=='scope:all')){for(const tree of ['l','c']){scope(x,entry.id,tree);await loaded(x);assertCanvas(x,entry.id,tree);const expected=below(raw.forests[entry.id][tree]);for(const p of expected)exposePosition(x,p);assert.equal(x.doc.querySelectorAll('#np-tree [data-position]').length,expected.length,'each real position occurs exactly once');assert.deepEqual(new Set([...x.doc.querySelectorAll('#np-tree [data-position]')].map(n=>n.dataset.position)),new Set(expected.map(p=>p.id)),'only real '+tree+' forest '+entry.id);const byPaper=new Map(),byEntity=new Map();for(const p of methods(entry.id,tree)){const node=exposePosition(x,p),stamp=node.querySelector(':scope > [data-route-association]');assert.ok(stamp,p.id);assert.equal(stamp.dataset.routeAssociation,p.association);assert.equal(stamp.dataset.routeVersion,p.versionId);const label=node.querySelector(':scope > .np-node-row > .np-node-label').textContent;if(p.kind==='pipeline_recipe'){const source=raw.entities[p.entityId].label.replace(/[：:]\s*输入到(?:执行)?反馈.*$/,'').replace(/\s*输入到(?:执行)?反馈.*$/,'');assert.equal(label.toLowerCase(),source.toLowerCase(),p.id+' source method label');if(!byPaper.has(p.paperId))byPaper.set(p.paperId,new Map());byPaper.get(p.paperId).set(p.entityId,label);if(!byEntity.has(p.entityId))byEntity.set(p.entityId,[]);byEntity.get(p.entityId).push({position:p.id,label});}await visitPosition(x,p);assertMethodReading(x,p);visited[tree].add(p.id);}for(const variants of byPaper.values())if(variants.size>1){variantGroups++;assert.equal(new Set(variants.values()).size,variants.size,'same-paper variants stay distinguishable');}for(const placements of byEntity.values())if(placements.length>1){repeatedEntities++;assert.equal(new Set(placements.map(p=>p.position)).size,placements.length);assert.equal(new Set(placements.map(p=>p.label)).size,1);}}seen++;}
  assert.ok(variantGroups>0,'raw export includes distinct same-paper variants');assert.ok(repeatedEntities>0,'raw export includes repeated same-entity positions');assert.equal(seen,63);assert.equal(seen,raw.scopes.length-1);assert.equal(visited.l.size,81);assert.equal(visited.c.size,61);assert.ok(!x.calls.some(url=>url.includes('product-data')));assert.equal(crypto.createHash('sha256').update(scienceBytes).digest('hex'),'9069c6a11ae9a867671522d04e6a24b4edcada660d03feb2f41340bfc395825c');assert.deepEqual(x.errors,[]);
 });
 scenario('entries',async t=>{
  const x=await page();t.after(()=>closePage(x));const app=x.w.NavigationProductApp,b=app.getBundle(),M=x.w.NavigationProductModel;
  scope(x,'task:category-objectnav','l');await loaded(x);await openRelations(x);scope(x,'task:category-objectnav','c');await loaded(x);assert.equal(relationDisclosure(x).open,false,'opening L does not open C');scope(x,'task:imagenav','l');await loaded(x);assert.equal(relationDisclosure(x).open,false,'opening one task does not open another');scope(x,'task:category-objectnav','l');await loaded(x);assert.equal(relationDisclosure(x).open,true,'return to the exact task/tree restores its open view');
  for(const id of taskIds){for(const tree of ['l','c']){scope(x,id,tree);await loaded(x);assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteScope,id);assertCanvas(x,id,tree);for(const p of methods(id,tree))exposePosition(x,p);assert.deepEqual(new Set([...x.doc.querySelectorAll('#np-tree [data-position]')].filter(n=>['pipeline_recipe','versioned_method_card'].includes(raw.positions[n.dataset.position].kind)).map(n=>n.dataset.position)),new Set(methods(id,tree).map(p=>p.id)));}app.navigate(M.routeForPosition(b,app.getState().route,b.researchMap.canonicalScopePositionIds[id]));await loaded(x);assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteScope,id);assertCanvas(x,id,'g');}
  scope(x,'scope:all');assert.equal(x.doc.querySelector('[data-task-route-scope]'),null);assert.deepEqual(x.errors,[]);
 });
 scenario('evidence',async t=>{
  const x=await page();t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);for(const p of [...partition('task:category-objectnav').groups,...partition('task:category-objectnav').supplemental])exposePosition(x,p);assert.ok(exposePosition(x,raw.positions['pos:l:8be2c09f4c65785416c820']));for(const p of methods('task:category-objectnav').filter(p=>p.kind==='versioned_method_card'))assert.match(exposePosition(x,p).textContent,/固定版本方法选段/);await loaded(x);assert.equal(change(x,90).dataset.changeScope,'current-scope');assert.equal(relationReading(x),null);const relation=await selectRelation(x,90),claim=relation.querySelector('[data-task-change-claim="method-edge:89"]');assert.ok(claim.textContent.includes(raw.claims['method-edge:89'].statement));assert.ok(claim.textContent.includes('§3.4–3.6'));assert.ok(claim.querySelector('a[href="'+raw.claims['method-edge:89'].sourceRefs[0].url+'"]'));assertRelationEvidence(x,'methods:relation:90','task:category-objectnav');assert.equal(change(x,89).dataset.changeScope,'outside-scope');assert.match(change(x,89).textContent,/不增加本任务解法归属/);const outside=await selectRelation(x,89);assert.match(outside.textContent,/不在当前任务的方法位置中/);const selected=await selectRelation(x,90),target=selected.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]');target.click();assert.equal(x.w.NavigationProductApp.getState().route.node,'pos:l:98bc421b8bfd17d6699922');assert.equal(x.w.NavigationProductApp.getState().route.version,'publication:poni:e83f98bb7132');assert.deepEqual(x.errors,[]);
 });
 scenario('versions',async t=>{
  const x=await page();t.after(()=>closePage(x));const relations=Object.values(raw.relations).filter(r=>/^methods:relation:(89|9\d|10[01])$/.test(r.id));
  for(const id of ['task:category-objectnav','task:imagenav','task:vln','setting:open-vocabulary-objectnav','task:goat','task:instanceimagenav','task:language-objectnav']){scope(x,id);await loaded(x);const papers=new Set(methods(id).map(p=>p.paperId)),expected=relations.filter(r=>[r.from,r.to].some(e=>papers.has(raw.entities[e].paperId)));assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-task-change]')].map(n=>n.dataset.taskChange)),new Set(expected.map(r=>r.id)),id);for(const r of expected){const row=change(x,r.id),local=[r.from,r.to].every(e=>papers.has(raw.entities[e].paperId));assert.equal(row.dataset.changeScope,local?'current-scope':'outside-scope');assert.equal(row.dataset.relationType,r.relationType);assert.equal(row.dataset.renderAsTree,'false');await selectRelation(x,r.id);assertRelationEvidence(x,r.id,id);}}
  scope(x,'task:vln');await loaded(x);const r99=await selectRelation(x,99),c99=r99.querySelector('[data-task-change-claim="method-edge:98"]');assert.equal(c99.dataset.versionRelation,'other-version');assert.equal(c99.dataset.evidenceVersion,raw.claims['method-edge:98'].versionId);assert.match(c99.textContent,/另项来源/);const env=methods('task:vln').find(p=>p.paperId==='envdrop');assert.equal(env.versionId,'arxiv:1904.04195v1');assert.ok(r99.querySelector('[data-change-target="'+env.id+'"]'));
  scope(x,'task:instanceimagenav');await loaded(x);const placements=methods('task:instanceimagenav').filter(p=>p.entityId==='methods:pipeline-modiin');assert.ok(placements.length>1);for(const p of placements){await visitPosition(x,p);assertMethodReading(x,p);}assert.deepEqual(x.errors,[]);
 });
 scenario('summaries',async t=>{
  const x=await page();t.after(()=>closePage(x));for(const id of ['task:category-objectnav','task:language-objectnav','task:pointnav','task:multistage-language-navigation','task:imagenav']){scope(x,id);await loaded(x);assertCanvas(x,id);for(const p of methods(id)){await visitPosition(x,p);assertMethodReading(x,p);}}
  scope(x,'task:imagenav');await loaded(x);for(const p of partition('task:imagenav').groups){const reader=await visitPosition(x,p),d=raw.entities[p.entityId].detail;for(const value of [d.scope,d.evidence,d.condition].filter(Boolean))assert.ok(reader.textContent.includes(textOf(value)),p.id+' group evidence');}assert.deepEqual(x.errors,[]);
 });
 scenario('async',async t=>{
  const pending=new Map(),x=await page({fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>x.w.close());scope(x,'task:category-objectnav');const method=exposePosition(x,raw.positions['pos:l:98bc421b8bfd17d6699922']);await frames(x.w);const panel=x.doc.querySelector('[data-task-route-pending-scope]'),tree=x.doc.querySelector('#np-tree [role=treeitem]');assert.ok(panel);assert.equal(x.doc.querySelector('[data-task-route-scope]'),null);assert.equal(panel.querySelector('[data-route-method]'),null);assert.ok(method.querySelector('.np-node-label'),'real method available while relation evidence is pending');tree.focus();tree.dispatchEvent(new x.w.MouseEvent('mousedown',{bubbles:true}));x.doc.getElementById('np-detail-scroll').scrollTop=122;await wait(5);release(pending,ownerURL(x,'methods:pipeline-poni'));await wait(30);assert.equal(change(x,90),null);assert.equal(x.doc.getElementById(method.id),method);
  const group=partition('task:category-objectnav').groups[0],held=ownerURL(x,group.entityId);for(const url of [...pending.keys()])if(url!==held)release(pending,url);await wait(30);assert.equal(panel.dataset.taskRouteState,'loading','groups also gate the atomic snapshot');release(pending,held);await loaded(x);assert.equal(x.doc.querySelector('[data-task-route-scope]'),panel);assert.equal(x.doc.activeElement,tree);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,122);assert.equal(panel.querySelector('.np-task-route-snapshot').firstElementChild.className,'np-task-route-changes');assert.equal(x.doc.getElementById(method.id),method);assertCanvas(x,'task:category-objectnav');const ids=[...panel.querySelectorAll('[data-task-change]')].map(n=>n.dataset.taskChange);assert.deepEqual(ids,[...ids].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})));await wait(30);assert.equal(x.doc.getElementById(method.id),method);await selectRelation(x,90);assertRelationEvidence(x,'methods:relation:90','task:category-objectnav');exposePosition(x,raw.positions['pos:l:98bc421b8bfd17d6699922']).querySelector(':scope > .np-node-row > .np-node-label').click();assert.equal(x.w.NavigationProductApp.getState().route.node,'pos:l:98bc421b8bfd17d6699922');scope(x,'task:vln');await wait(5);const oldURLs=[...pending.keys()];scope(x,'task:aerial-visual-object-search');await frames(x.w);const newer=x.doc.querySelector('[data-task-route-scope]'),route=JSON.stringify(x.w.NavigationProductApp.getState().route),focus=x.doc.activeElement;x.doc.getElementById('np-detail-scroll').scrollTop=77;for(const url of oldURLs)release(pending,url);await wait(60);assert.equal(x.doc.querySelector('[data-task-route-scope]'),newer);assert.equal(JSON.stringify(x.w.NavigationProductApp.getState().route),route);assert.equal(x.doc.activeElement,focus);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,77);assert.deepEqual(x.errors,[]);
 });
 scenario('failures',async t=>{
  const x=await page({fetch:()=>Promise.resolve({ok:true,arrayBuffer:async()=>Buffer.from('{}')})});t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);const p=raw.positions['pos:l:98bc421b8bfd17d6699922'],method=exposePosition(x,p);await loaded(x);await openRelations(x);assert.ok(method.querySelector('.np-node-label'));const content=x.w.NavigationProductApp.getContent(),retry=x.doc.querySelector('[data-retry-owner="methods:pipeline-poni"] button');assert.equal(content.status(p.entityId),'failed');for(let i=0;i<2;i++){assert.equal(retry.dataset.retryState,'failed');retry.click();await wait(30);}assert.equal(content.attempts('methods:pipeline-poni'),3);assert.equal(retry.dataset.retryState,'exhausted');assert.equal(x.doc.getElementById(method.id),method);method.querySelector(':scope > .np-node-row > .np-node-label').click();assert.equal(x.w.NavigationProductApp.getState().route.node,p.id);assert.equal(x.doc.querySelector('main').dataset.loadState,'ready');assert.equal(x.doc.querySelector('[data-mechanism-entity="'+p.entityId+'"] [data-content-state]').dataset.contentState,'failed');scope(x,'task:imagenav');await loaded(x);const failedMethod=methods('task:imagenav')[0],reader=await visitPosition(x,failedMethod),failed=reader.querySelector('[data-mechanism-entity="'+failedMethod.entityId+'"] [data-content-state]');assert.ok(failed);assert.equal(failed.dataset.contentState,'failed');assert.match(failed.textContent,/正文字节长度不符/);assert.ok([...failed.querySelectorAll('button')].some(n=>n.textContent==='重试此节点正文'));assert.deepEqual(x.errors,[]);
 });
 for(const action of ['none','focus','wheel','scope'])scenario(action==='none'?'return-clamp':'return-clamp-'+action,async t=>{
  const x=await page({width:1920});t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);await frames(x.w);const app=x.w.NavigationProductApp,reader=x.doc.getElementById('np-detail-scroll'),relation=await selectRelation(x,90),target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]'),targetId=target.id,origin=JSON.stringify(app.getState().route);let top=0;const writes=[];
  // JSDOM has no layout. Model a shorter pending/identity reader and a full
  // selected relation. Restoration must use the relation reader's geometry.
  Object.defineProperty(reader,'scrollTop',{configurable:true,get(){return top;},set(value){const current=relationReading(x),limit=current?1000:200;top=Math.max(0,Math.min(Number(value),limit));writes.push({requested:value,actual:top,selected:current&&current.dataset.selectedTaskRelation,route:app.getState().route.node});}});
  reader.scrollTop=300;target.focus();target.click();await frames(x.w);assert.equal(app.getState().originTrail.at(-1).bucket.detailScrollByTree.l,300);const nativeRAF=x.w.requestAnimationFrame,queued=[];x.w.requestAnimationFrame=fn=>{queued.push(fn);return queued.length;};writes.length=0;x.doc.querySelector('.np-return-previous').click();assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);
  let chosen=null;if(action==='focus'){chosen=x.doc.getElementById('np-node-search');chosen.focus();reader.scrollTop=117;}if(action==='wheel'){reader.scrollTop=117;reader.dispatchEvent(new x.w.WheelEvent('wheel',{deltaY:20,bubbles:true}));chosen=x.doc.activeElement;}if(action==='scope')scope(x,'task:aerial-visual-object-search');const newer=JSON.stringify(app.getState().route);writes.length=0;
  while(queued.length)queued.shift()();x.w.requestAnimationFrame=nativeRAF;await frames(x.w);
  if(action==='none'){assert.equal(JSON.stringify(app.getState().route),origin);assert.equal(reader.scrollTop,300);assert.equal(x.doc.activeElement.id,targetId);assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);assert.ok(writes.some(w=>w.requested===300&&w.actual===300&&w.selected==='methods:relation:90'));assert.ok(!writes.some(w=>w.requested===300&&!w.selected));}
  else if(action==='scope'){assert.equal(JSON.stringify(app.getState().route),newer);assert.equal(app.getState().route.scope,'task:aerial-visual-object-search');assert.ok(!writes.some(w=>w.requested===300));assert.equal(x.doc.getElementById(targetId),null);}
  else{assert.equal(JSON.stringify(app.getState().route),origin);assert.equal(reader.scrollTop,117);assert.equal(x.doc.activeElement,chosen);assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);assert.ok(!writes.some(w=>w.requested===300));}
  assert.deepEqual(x.errors,[]);
 });
 scenario('return',async t=>{
  const x=await page();t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);await frames(x.w);const app=x.w.NavigationProductApp,origin=app.getState().route,relation=await selectRelation(x,90),target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]');target.focus();target.click();await frames(x.w);x.w.history.back();await wait(80);await frames(x.w);assert.deepEqual(app.getState().route,origin);assert.equal(x.doc.activeElement.id,target.id);assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);const current=x.doc.getElementById(target.id);current.focus();current.click();await frames(x.w);x.doc.querySelector('.np-return-previous').click();await frames(x.w);assert.deepEqual(app.getState().route,origin);assert.equal(x.doc.activeElement.id,target.id);assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);const toggle=x.doc.getElementById('np-reader-toggle');if(!toggle.hidden){toggle.click();assert.equal(x.doc.getElementById('np-detail-scroll').hidden,true);toggle.click();assert.equal(x.doc.getElementById('np-detail-scroll').hidden,false);}x.doc.getElementById('np-task-route-return').click();await frames(x.w);assert.equal(relationReading(x),null);assert.equal(x.doc.activeElement,change(x,90));assert.deepEqual(app.getState().route,origin);relationDisclosure(x).querySelector(':scope > summary').click();await frames(x.w);assert.equal(relationDisclosure(x).open,false);const closedState=JSON.parse(JSON.stringify(x.w.history.state));await visitPosition(x,raw.positions['pos:l:98bc421b8bfd17d6699922']);x.w.history.back();await wait(80);await frames(x.w);assert.deepEqual(app.getState().route,origin);assert.equal(relationReading(x),null);assert.equal(relationDisclosure(x).open,false,'Back preserves a deliberately closed relation overview');const stored=x.w.NavigationProductModel.getBucket(closedState[x.w.NavigationProductModel.KEY]).relationOverviewByTree.l;assert.equal(stored.open,false);assert.deepEqual(stored.route,JSON.parse(JSON.stringify(origin)));assert.deepEqual(x.errors,[]);
 });
 scenario('method-claim-typography',async t=>{
  const x=await page({width:1440});t.after(()=>closePage(x));const selected=new Map();for(const entry of raw.scopes.filter(s=>s.id!=='scope:all'))for(const p of methods(entry.id)){const d=raw.entities[p.entityId].detail||{};if(!d.pipeline&&!d.pipeline_contract)selected.set(p.entityId,p);}assert.ok(selected.has('methods:pipeline-tap-rl'));assert.ok(selected.has('methods:pipeline-tap-llm'));const failures=[];let texts=0,sources=0;
  function cssValue(node,key){for(let at=node;at;at=at.parentElement){const value=x.w.getComputedStyle(at)[key];if(value&&value!=='normal'&&value!=='inherit')return value;}return '';}
  function px(value){return value.endsWith('rem')?parseFloat(value)*16:value.endsWith('px')?parseFloat(value):NaN;}
  for(const p of selected.values()){scope(x,p.scopeId);await loaded(x);await visitPosition(x,p);const app=x.w.NavigationProductApp;for(let i=0;i<150&&app.getContent().status(p.entityId)!=='ready';i++)await wait(10);await frames(x.w);assert.equal(app.getContent().status(p.entityId),'ready');const method=x.doc.querySelector('[data-mechanism-entity="'+p.entityId+'"]');assert.ok(method);assert.equal(method.querySelector('.np-method-flow'),null);const claims=Array.from(new Set([...(p.claimIds||[]),...(raw.entities[p.entityId].claimIds||[])])).map(id=>raw.claims[id]).filter(c=>c&&c.paperId===p.paperId&&c.versionId===p.versionId);for(const c of claims){const row=method.querySelector('[data-method-claim="'+c.id+'"]');assert.ok(row,c.id);assert.ok(row.textContent.includes(c.statement||c.label));}
   [...method.querySelectorAll('button')].find(n=>n.textContent==='核对固定版本与原文证据').click();const evidence=x.doc.querySelector('#np-evidence-panel .np-evidence');assert.ok(evidence);evidence.open=true;assert.equal(x.doc.getElementById('np-evidence-panel').open,true);for(const c of claims){const row=evidence.querySelector('[data-claim-id="'+c.id+'"]');assert.ok(row);assert.ok(row.textContent.includes(c.statement||c.label));for(const ref of c.sourceRefs||[]){if(ref.url){assert.ok(row.querySelector('a[href="'+ref.url+'"]'));sources++;}if(typeof ref.locator==='string')assert.ok(row.textContent.includes(ref.locator));if(ref.versionId&&raw.versions[ref.versionId]){const v=raw.versions[ref.versionId];assert.ok(row.textContent.includes(v.label||v.descriptor||ref.versionId));}}}
   for(const host of [method.querySelector('.np-method-claims'),method.querySelector(':scope>.np-note'),...evidence.querySelectorAll('.np-claim')])for(const node of [host,...host.querySelectorAll('*')])if([...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim())){texts++;const size=px(cssValue(node,'fontSize')),line=cssValue(node,'lineHeight'),ratio=line.endsWith('px')?parseFloat(line)/size:parseFloat(line);if(size<15||!Number.isFinite(size)||ratio<1.5)failures.push({entity:p.entityId,tag:node.tagName,className:node.className,text:node.textContent.slice(0,70),fontSize:cssValue(node,'fontSize'),lineHeight:line});}
  }
  await frames(x.w);assert.ok(texts>0);assert.ok(sources>0);if(failures.length)t.diagnostic(JSON.stringify(failures));assert.deepEqual(failures,[],'method claim body, scope, version, sources, locators and controls preserve the 15px reading floor');assert.deepEqual(x.errors,[]);
 });
 scenario('typography',async t=>{
  const css=fs.readFileSync(path.join(root,'assets/navigation-product.css'),'utf8'),floor=css.split('/* Task-root reading text keeps the 15px floor, including inherited legacy notes. */')[1];assert.ok(floor);for(const rule of floor.matchAll(/([^{}]+)\{([^{}]+)\}/g)){for(const selector of rule[1].split(','))assert.ok(selector.trim().startsWith('#navigation-product .np-task-route-overview'),'relation font floor stays inside its overview');assert.match(rule[2],/line-height:1\.55/);}assert.match(floor,/#navigation-product \.np-task-route-overview \.np-note/);assert.match(floor,/line-height:1\.55/);
  const x=await page();t.after(()=>closePage(x));let checked=0,slots=0;const violations=[];
  // Production reading DOM/CSS contract; real layout, zoom and scroll geometry
  // remain the separate browser capture gate. No hidden duplicate satisfies it.
  function value(node,key){for(let at=node;at;at=at.parentElement){const result=x.w.getComputedStyle(at)[key];if(result&&result!=='normal'&&result!=='inherit')return result;}return '';}
  function px(value){if(value.endsWith('px'))return parseFloat(value);if(value.endsWith('rem'))return parseFloat(value)*16;return NaN;}
  function check(host){assert.ok(host);assert.equal(host.closest('[hidden]'),null);for(const details of host.querySelectorAll('details'))if(!details.open)details.querySelector(':scope > summary').click();for(const n of [host,...host.querySelectorAll('*')])if([...n.childNodes].some(child=>child.nodeType===3&&child.textContent.trim())){const size=px(value(n,'fontSize')),height=value(n,'lineHeight'),ratio=height.endsWith('px')?parseFloat(height)/size:parseFloat(height);if(!(size>=15&&ratio>=1.5))violations.push({position:x.w.NavigationProductApp.getState().route.node,host:host.className,tag:n.tagName,className:n.className,text:n.textContent.slice(0,90),fontSize:value(n,'fontSize'),lineHeight:height});checked++;}for(const slot of host.querySelectorAll('.np-method-flow dd,.np-detail-block p,.np-change-claim,.np-sources')){const style=x.w.getComputedStyle(slot);assert.notEqual(style.overflow,'hidden');assert.notEqual(style.overflow,'auto');assert.notEqual(style.overflow,'scroll');assert.notEqual(style.height,'0px');assert.notEqual(style.maxHeight,'0px');slots++;}}
  for(const id of ['task:category-objectnav','task:imagenav','task:vln','task:language-objectnav','task:goat','task:aerial-visual-object-search']){scope(x,id);await loaded(x);await openRelations(x);check(x.doc.querySelector('#np-task-route-canvas .np-task-route-overview'));check(x.doc.querySelector('[data-task-reader-scope]'));for(const relation of [...x.doc.querySelectorAll('[data-task-change]')].map(n=>n.dataset.taskChange)){await selectRelation(x,relation);check(x.doc.querySelector('.np-task-relation-reading'));}for(const p of methods(id)){await visitPosition(x,p);check(x.doc.querySelector('[data-mechanism-entity="'+p.entityId+'"]'));}}
  await frames(x.w);assert.ok(checked>0);assert.ok(slots>0);if(violations.length)t.diagnostic(JSON.stringify(violations));assert.deepEqual(violations,[],'actual identity, relation and method reading text preserves the 15px / 1.5 line-height floor');assert.deepEqual(x.errors,[]);
 });
 scenario('conditions',async t=>{
  const x=await page();t.after(()=>closePage(x));const ids=raw.scopes.filter(s=>s.id!=='scope:all'&&partition(s.id).groups.some(p=>p.association==='condition')).map(s=>s.id);
  for(const id of ids){scope(x,id);await loaded(x);for(const p of partition(id).groups.filter(p=>p.association==='condition')){const reader=await visitPosition(x,p),slot=reader.querySelector('[data-reading-node="'+p.id+'"]');assert.ok(slot,p.id);assert.equal(slot.closest('details'),null);const d=raw.entities[p.entityId].detail||{},values=['condition','scope','evidence'].map(k=>d[k]).filter(Boolean);for(const value of values)assert.ok(slot.textContent.includes(textOf(value)),p.id);assert.match(slot.textContent,/条件关联/);}}
  scope(x,'task:imagenav');await loaded(x);const reactive=partition('task:imagenav').groups.find(p=>p.entityId==='methods:method-group:pg-image-reactive');const reader=await visitPosition(x,reactive);assert.match(reader.textContent,/scene-specific适应条件可见/);assert.deepEqual(x.errors,[]);
 });
 for(const [tree,action] of [['l','none'],['l','focus'],['l','wheel'],['l','scope'],['c','none'],['g','none'],['g','scope']])scenario(tree==='l'?(action==='none'?'cold-clamp':'cold-clamp-'+action):'cold-clamp-'+tree+(action==='none'?'':'-'+action),async t=>{
  const seed=await page();scope(seed,'task:category-objectnav',tree==='g'?'l':tree);if(tree==='g'){const a=seed.w.NavigationProductApp;seed.w.NavigationProductApp.navigate(seed.w.NavigationProductModel.routeForPosition(a.getBundle(),a.getState().route,a.getBundle().researchMap.canonicalScopePositionIds['task:category-objectnav']));}await loaded(seed);await frames(seed.w);const relation=await selectRelation(seed,90);const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]'),targetId=target.id;target.focus();seed.doc.getElementById('np-detail-scroll').scrollTop=300;seed.w.dispatchEvent(new seed.w.Event('pagehide'));const saved=JSON.parse(JSON.stringify(seed.w.history.state)),hash=seed.w.location.hash;await closePage(seed);
  const pending=new Map(),x=await page({saved,hash,holdFrames:true,fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>x.w.close());const reader=x.doc.getElementById('np-detail-scroll'),app=x.w.NavigationProductApp,M=x.w.NavigationProductModel;assert.equal(relationDisclosure(x).open,true,'saved disclosure restores while relation evidence is pending');let top=0;Object.defineProperty(reader,'scrollTop',{configurable:true,get(){return top;},set(value){const r=relationReading(x),limit=r?1000:0;top=Math.max(0,Math.min(Number(value),limit));}});
  x.w.dispatchEvent(new x.w.Event('pagehide'));assert.equal(M.getBucket(app.getState()).detailScrollByTree[tree],300,'pre-frame capture keeps the pending saved offset');assert.equal(M.getBucket(app.getState()).focusTarget,targetId);x.flushFrames();assert.equal(reader.scrollTop,0,'short pending page clamps the DOM offset');x.w.dispatchEvent(new x.w.Event('pagehide'));assert.equal(M.getBucket(app.getState()).detailScrollByTree[tree],300);assert.equal(M.getBucket(x.w.history.state[M.KEY]).detailScrollByTree[tree],300);
  let chosen=x.doc.activeElement;if(action==='focus'){chosen=x.doc.getElementById('np-node-search');chosen.focus();}if(action==='wheel')reader.dispatchEvent(new x.w.WheelEvent('wheel',{deltaY:20,bubbles:true}));if(action==='scope'){if(tree==='g')app.navigate(M.routeForPosition(app.getBundle(),app.getState().route,app.getBundle().researchMap.canonicalScopePositionIds['task:aerial-visual-object-search']));else scope(x,'task:aerial-visual-object-search');x.flushFrames();chosen=x.doc.activeElement;}const newer=JSON.stringify(app.getState().route);if(action!=='none'){x.w.dispatchEvent(new x.w.Event('pagehide'));assert.notEqual(M.getBucket(app.getState()).focusTarget,targetId);}
  for(const url of [...pending.keys()])release(pending,url);await loaded(x);await wait(40);x.flushFrames();assert.equal(JSON.stringify(app.getState().route),newer);
  if(action==='none'){assert.equal(reader.scrollTop,300);assert.equal(x.doc.activeElement.id,targetId);assert.equal(relationReading(x).dataset.selectedTaskRelation,'methods:relation:90');assert.equal(relationDisclosure(x).open,true);assert.equal(M.getBucket(app.getState()).detailScrollByTree[tree],300);assert.equal(M.getBucket(x.w.history.state[M.KEY]).detailScrollByTree[tree],300);}
  else{assert.equal(reader.scrollTop,0);assert.equal(x.doc.activeElement,chosen);if(relationReading(x))assert.notEqual(x.doc.activeElement.id,targetId);}assert.deepEqual(x.errors,[]);
 });
 for(const mode of ['restore','focus','key','pointer','click','scope','reader','wheel','touch','pre-focus','pre-key'])scenario('cold-'+mode,async t=>{
  const seed=await page();scope(seed,'task:category-objectnav');await loaded(seed);await frames(seed.w);const relation=await selectRelation(seed,90);const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]'),targetId=target.id;target.focus();seed.w.dispatchEvent(new seed.w.Event('pagehide'));const saved=JSON.parse(JSON.stringify(seed.w.history.state)),hash=seed.w.location.hash;assert.equal(seed.w.NavigationProductModel.getBucket(seed.w.NavigationProductApp.getState()).focusTarget,targetId);await closePage(seed);
  const pending=new Map(),x=await page({saved,hash,holdFrames:mode.startsWith('pre-'),width:mode==='reader'?1440:undefined,fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>x.w.close());assert.equal(x.doc.getElementById(targetId),null);assert.equal(relationDisclosure(x).open,true,'saved open relation disclosure restores before evidence');const fallback=x.doc.activeElement;
  if(mode==='pre-focus')x.doc.querySelector('#np-tree [role=treeitem]').focus();
  if(mode==='pre-key')x.doc.body.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
  if(mode==='focus'){x.doc.getElementById('np-node-search').focus();fallback.focus();}
  if(mode==='key')fallback.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Shift',bubbles:true}));
  if(mode==='pointer')fallback.dispatchEvent(new x.w.MouseEvent('mousedown',{bubbles:true}));
  if(mode==='click')fallback.dispatchEvent(new x.w.MouseEvent('click',{bubbles:true}));
  if(mode==='wheel')fallback.dispatchEvent(new x.w.WheelEvent('wheel',{deltaY:20,bubbles:true}));
  if(mode==='touch')fallback.dispatchEvent(new x.w.Event('touchstart',{bubbles:true}));
  if(mode==='scope')scope(x,'task:aerial-visual-object-search');
  if(mode==='reader'){x.w.NavigationProductApp.navigate(x.w.NavigationProductModel.routeForPosition(x.w.NavigationProductApp.getBundle(),x.w.NavigationProductApp.getState().route,'pos:l:98bc421b8bfd17d6699922'));await frames(x.w);const toggle=x.doc.getElementById('np-reader-toggle');assert.equal(toggle.hidden,false);toggle.click();toggle.click();}
  if(mode.startsWith('pre-')){const chosen=x.doc.activeElement;x.flushFrames();assert.equal(x.doc.activeElement,chosen,'initial delayed frame must not steal newer focus');}else await frames(x.w);const expectedFocus=x.doc.activeElement;const beforeRoute=JSON.stringify(x.w.NavigationProductApp.getState().route);x.doc.getElementById('np-detail-scroll').scrollTop=93;
  for(const url of [...pending.keys()])release(pending,url);await loaded(x);await wait(50);const restored=x.doc.getElementById(targetId);
  if(mode==='restore'){assert.ok(restored);assert.equal(x.doc.activeElement,restored);assert.equal(restored.closest('[data-selected-task-relation]').dataset.selectedTaskRelation,'methods:relation:90');}
  else{assert.equal(x.doc.activeElement,expectedFocus);if(restored)assert.notEqual(x.doc.activeElement,restored);}
  assert.equal(JSON.stringify(x.w.NavigationProductApp.getState().route),beforeRoute);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,mode==='restore'?saved[x.w.NavigationProductModel.KEY].contexts[x.w.NavigationProductModel.contextKey(x.w.NavigationProductApp.getState().route)].detailScrollByTree.l:93);assert.deepEqual(x.errors,[]);
 });

}
