'use strict';
// Each production HTML scenario gets a separate heap. No browser network access.
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'..'),scenarios=['return-clamp','return-clamp-focus','return-clamp-wheel','return-clamp-scope','method-claim-typography','typography','coverage','entries','evidence','versions','summaries','async','failures','return','conditions','cold-restore','cold-focus','cold-key','cold-pointer','cold-click','cold-scope','cold-reader','cold-wheel','cold-touch','cold-pre-focus','cold-pre-key','settled-teardown','settled-teardown-failure','settled-teardown-error','settled-teardown-timeout'];
if(!process.env.NP_TASK_ROUTE_CASE){
 for(const name of scenarios)test('task route production contract: '+name,t=>{const env={...process.env,NP_TASK_ROUTE_CASE:name};delete env.NODE_TEST_CONTEXT;const result=cp.spawnSync(process.execPath,['--test',__filename],{cwd:root,env,encoding:'utf8',maxBuffer:8*1024*1024});if(result.stdout)t.diagnostic(result.stdout);if(result.stderr)t.diagnostic(result.stderr);assert.ifError(result.error);assert.equal(result.signal,null);assert.equal(result.status,0,result.stdout+result.stderr);});
}else{
 const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),temp=fs.mkdtempSync(path.join(root,'.navigation-task-routes-'));
 cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;p.write_preview(Path('.').resolve(),Path(sys.argv[1]))",temp],{cwd:root});
 const output=path.join(temp,'research/navigation'),html=fs.readFileSync(path.join(output,'index.html'),'utf8');
 const scienceBytes=zlib.gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz'))),raw=JSON.parse(scienceBytes),taskIds=raw.directoryGroups.find(g=>g.id==='task').scopeIds,wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 test.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
 function scenario(name,fn){if(process.env.NP_TASK_ROUTE_CASE===name)test(name,fn);}
 async function frames(w){await new Promise(resolve=>w.requestAnimationFrame(()=>w.requestAnimationFrame(resolve)));}
 async function page(options={}){
  const calls=[],errors=[],queuedFrames=[];class Resources extends ResourceLoader{fetch(url){throw new Error('Unexpected external request '+url);}}
  const vc=new VirtualConsole();vc.on('jsdomError',error=>errors.push(error.message));
  const d=new JSDOM(html,{url:'https://example.org/research/navigation/'+(options.hash||''),runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
   if(options.holdFrames)w.requestAnimationFrame=fn=>{queuedFrames.push(fn);return queuedFrames.length;};if(options.width)Object.defineProperty(w,'innerWidth',{value:options.width,configurable:true});w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});
   if(options.saved)w.history.replaceState(options.saved,'',w.location.href);w.fetch=url=>{calls.push(url);if(options.fetch)return options.fetch(url);if(options.offline)return new Promise(()=>{});return Promise.resolve({ok:true,arrayBuffer:async()=>fs.readFileSync(path.join(output,url))});};
  }});
  for(let i=0;i<150&&!d.window.NavigationProductApp;i++)await wait(10);assert.ok(d.window.NavigationProductApp);if(!options.holdFrames)await frames(d.window);return {w:d.window,doc:d.window.document,calls,errors,flushFrames:()=>{while(queuedFrames.length)queuedFrames.shift()();}};
 }
 // A loaded overview does not imply that the selected scope body has settled.
 // Observe only jobs already started by the UI, without starting idle packets or
 // handling their rejections. Give their real promise callbacks a turn to finish
 // before closing the JSDOM window, which removes window.document.
 async function closePage(x,timeoutMs=30000){
  const app=x.w.NavigationProductApp,content=app.getContent(),ids=Object.keys(app.getBundle().delivery.packets),loading=()=>ids.filter(id=>content.status(id)==='loading');let timer;
  try{
   await Promise.race([(async()=>{
    do{
     if(loading().length)await new Promise(resolve=>{function check(){if(!loading().length)resolve();}content.subscribe(check);check();});
     await new Promise(resolve=>setImmediate(resolve));await frames(x.w);
    }while(loading().length);
    assert.deepEqual(x.errors,[],'no late JSDOM errors during teardown');
   })(),new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error('Page teardown timed out; loading owners: '+loading().join(', '))),timeoutMs);})]);
  }finally{clearTimeout(timer);x.w.close();}
 }

 function scope(x,id,tree='l'){const a=x.w.NavigationProductApp;x.w.NavigationProductApp.navigate(x.w.NavigationProductModel.initialState(a.getBundle(),{scope:id,tree}).route);return x.doc.querySelector('[data-task-route-scope]');}
 function below(ids){return ids.flatMap(id=>[raw.positions[id],...below(raw.positions[id].childIds)]);}
 function methods(id){return below(raw.forests[id].l).filter(p=>['pipeline_recipe','versioned_method_card'].includes(p.kind));}
 function partition(id){const children=raw.forests[id].l.flatMap(r=>raw.positions[r].childIds.map(id=>raw.positions[id]));return {groups:children.filter(p=>!['pipeline_recipe','versioned_method_card'].includes(p.kind)&&below([p.id]).some(q=>['pipeline_recipe','versioned_method_card'].includes(q.kind))),ungrouped:children.filter(p=>['pipeline_recipe','versioned_method_card'].includes(p.kind)),supplemental:children.filter(p=>!below([p.id]).some(q=>['pipeline_recipe','versioned_method_card'].includes(q.kind)))};}
 async function loaded(x){for(let i=0;i<150&&x.doc.querySelector('.np-task-route-overview .np-content-pending');i++)await wait(10);assert.equal(x.doc.querySelector('.np-task-route-overview .np-content-pending'),null);}
 function change(x,id){return x.doc.querySelector('[data-task-change="methods:relation:'+id+'"]');}
 function release(pending,url,bytes){assert.ok(pending.has(url),url);pending.get(url)({ok:true,arrayBuffer:async()=>bytes||fs.readFileSync(path.join(output,url))});pending.delete(url);}
 function ownerURL(x,id){return 'content/'+x.w.NavigationProductApp.getBundle().delivery.packets[id].sha256+'.json';}
 for(const mode of ['success','failure','error','timeout'])scenario(mode==='success'?'settled-teardown':'settled-teardown-'+mode,async t=>{
  let heldURL,releaseBody;
  const x=await page({fetch:url=>Promise.resolve({ok:true,arrayBuffer:()=>url===heldURL?new Promise(resolve=>{releaseBody=()=>resolve(mode==='failure'?Buffer.from('{}'):fs.readFileSync(path.join(output,url)));}):Promise.resolve(fs.readFileSync(path.join(output,url)))})});t.after(()=>x.w.close());
  heldURL=ownerURL(x,'task:imagenav');scope(x,'task:imagenav');await loaded(x);
  const content=x.w.NavigationProductApp.getContent();assert.equal(content.status('task:imagenav'),'loading');assert.ok(x.doc.querySelector('.np-detail-body .np-content-pending'));assert.ok(releaseBody);
  const close=closePage(x,mode==='timeout'?30:undefined),rejected=mode==='timeout'?assert.rejects(close,/Page teardown timed out; loading owners: task:imagenav/):mode==='error'?assert.rejects(close,/late teardown probe/):null;
  if(mode==='timeout'){await rejected;assert.equal(content.status('task:imagenav'),'loading');assert.equal(x.w.document,undefined);return;}
  await new Promise(resolve=>setImmediate(resolve));assert.equal(x.w.document,x.doc,'teardown waits while a selected scope body is pending');
  if(mode==='error'){const errorEvent=new Promise(resolve=>x.w.addEventListener('error',resolve,{once:true}));x.w.setTimeout(()=>{throw new Error('late teardown probe');},0);await errorEvent;}
  releaseBody();await (rejected||close);assert.equal(content.status('task:imagenav'),mode==='failure'?'failed':'ready');if(mode==='failure')assert.match(content.error('task:imagenav'),/正文字节长度不符/);assert.equal(x.w.document,undefined);if(mode!=='error')assert.deepEqual(x.errors,[]);
 });
 scenario('coverage',async t=>{
  const x=await page({offline:true});t.after(()=>x.w.close());assert.equal(x.calls.length,0);assert.equal(x.doc.querySelector('[data-task-route-scope]'),null);assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-task-open]')].map(n=>n.dataset.taskOpen)),new Set(taskIds));
  assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-directory-scope]')].map(n=>n.dataset.directoryScope)),new Set(raw.scopes.map(s=>s.id)));
  let seen=0;for(const entry of raw.scopes.filter(s=>s.id!=='scope:all')){const panel=scope(x,entry.id),expected=partition(entry.id);assert.ok(panel,entry.id);assert.deepEqual([...panel.querySelectorAll('[data-route-group]')].map(n=>n.dataset.routeGroup),expected.groups.map(p=>p.id));assert.deepEqual(new Set([...panel.querySelectorAll('[data-route-method]')].map(n=>n.dataset.routeMethod)),new Set(methods(entry.id).map(p=>p.id)));assert.deepEqual([...panel.querySelectorAll('[data-route-supplemental]')].map(n=>n.dataset.routeSupplemental),expected.supplemental.map(p=>p.id));for(const p of methods(entry.id)){const row=panel.querySelector('[data-route-method="'+p.id+'"]');assert.equal(row.dataset.routeParent,p.parentId);assert.equal(row.querySelector('[data-route-association]').dataset.routeAssociation,p.association);assert.equal(row.querySelector('[data-route-version]').dataset.routeVersion,p.versionId);}if(!methods(entry.id).length)assert.match(panel.textContent,/当前文献树未整理可比较的方法结构/);seen++;}
  // Distinct recipe variants sharing a paper keep their source method labels;
  // repeat placements of the same entity remain separate controls with one label.
  let variantGroups=0,repeatedEntities=0;
  for(const entry of raw.scopes.filter(s=>s.id!=='scope:all')){const panel=scope(x,entry.id),byPaper=new Map(),byEntity=new Map();for(const p of methods(entry.id).filter(p=>p.kind==='pipeline_recipe')){const label=panel.querySelector('[data-route-method="'+p.id+'"]>button').textContent,source=raw.entities[p.entityId].label.replace(/[：:]\s*输入到(?:执行)?反馈.*$/,'').replace(/\s*输入到(?:执行)?反馈.*$/,'');assert.ok(label.trim(),p.id);assert.equal(label.toLowerCase(),source.toLowerCase(),p.id+' source method label');if(!byPaper.has(p.paperId))byPaper.set(p.paperId,new Map());byPaper.get(p.paperId).set(p.entityId,label);if(!byEntity.has(p.entityId))byEntity.set(p.entityId,[]);byEntity.get(p.entityId).push({position:p.id,label});}for(const variants of byPaper.values())if(variants.size>1){variantGroups++;assert.equal(new Set(variants.values()).size,variants.size,'same-paper variants stay distinguishable');}for(const placements of byEntity.values())if(placements.length>1){repeatedEntities++;assert.equal(new Set(placements.map(p=>p.position)).size,placements.length);assert.equal(new Set(placements.map(p=>p.label)).size,1);}}
  assert.ok(variantGroups>0,'raw export includes distinct same-paper variants');assert.ok(repeatedEntities>0,'raw export includes repeated same-entity positions');
  assert.equal(seen,raw.scopes.length-1);assert.ok(!x.calls.some(url=>url.includes('product-data')));assert.equal(crypto.createHash('sha256').update(scienceBytes).digest('hex'),'9069c6a11ae9a867671522d04e6a24b4edcada660d03feb2f41340bfc395825c');assert.deepEqual(x.errors,[]);
 });
 scenario('entries',async t=>{
  const x=await page({offline:true});t.after(()=>x.w.close());const app=x.w.NavigationProductApp,b=app.getBundle(),M=x.w.NavigationProductModel;
  for(const id of taskIds){for(const tree of ['l','c']){const panel=scope(x,id,tree);assert.equal(panel.dataset.taskRouteScope,id);assert.deepEqual(new Set([...panel.querySelectorAll('[data-route-method]')].map(n=>n.dataset.routeMethod)),new Set(methods(id).map(p=>p.id)));}app.navigate(M.routeForPosition(b,app.getState().route,b.researchMap.canonicalScopePositionIds[id]));assert.equal(x.doc.querySelector('[data-task-route-scope]').dataset.taskRouteScope,id);}
  scope(x,'scope:all');assert.equal(x.doc.querySelector('[data-task-route-scope]'),null);assert.deepEqual(x.errors,[]);
 });
 scenario('evidence',async t=>{
  const x=await page();t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);const panel=x.doc.querySelector('[data-task-route-scope]');assert.equal(panel.querySelectorAll('[data-route-group]').length,partition('task:category-objectnav').groups.length);assert.ok(panel.querySelector('[data-route-supplemental="pos:l:8be2c09f4c65785416c820"]'));
  for(const p of methods('task:category-objectnav').filter(p=>p.kind==='versioned_method_card'))assert.match(panel.querySelector('[data-route-method="'+p.id+'"]').textContent,/固定版本方法选段/);
  const relation=change(x,90);assert.equal(relation.dataset.changeScope,'current-scope');assert.equal(relation.open,false);relation.querySelector('summary').click();assert.equal(relation.open,true);const claim=relation.querySelector('[data-task-change-claim="method-edge:89"]');assert.ok(claim.textContent.includes(raw.claims['method-edge:89'].statement));assert.ok(claim.textContent.includes('§3.4–3.6'));assert.ok(claim.querySelector('a[href="'+raw.claims['method-edge:89'].sourceRefs[0].url+'"]'));
  assert.equal(change(x,89).dataset.changeScope,'outside-scope');assert.match(change(x,89).textContent,/不在当前任务的方法位置中/);assert.ok(change(x,89).closest('.np-task-route-outside'));const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]');target.click();assert.equal(x.w.NavigationProductApp.getState().route.node,'pos:l:98bc421b8bfd17d6699922');assert.equal(x.w.NavigationProductApp.getState().route.version,'publication:poni:e83f98bb7132');assert.deepEqual(x.errors,[]);
 });
 scenario('versions',async t=>{
  const x=await page();t.after(()=>closePage(x));const relations=Object.values(raw.relations).filter(r=>/^methods:relation:(89|9\d|10[01])$/.test(r.id));
  for(const id of ['task:category-objectnav','task:imagenav','task:vln','setting:open-vocabulary-objectnav','task:goat','task:instanceimagenav','task:language-objectnav']){scope(x,id);await loaded(x);const papers=new Set(methods(id).map(p=>p.paperId)),expected=relations.filter(r=>[r.from,r.to].some(e=>papers.has(raw.entities[e].paperId)));assert.deepEqual(new Set([...x.doc.querySelectorAll('[data-task-change]')].map(n=>n.dataset.taskChange)),new Set(expected.map(r=>r.id)),id);for(const r of expected){const row=x.doc.querySelector('[data-task-change="'+r.id+'"]'),local=[r.from,r.to].every(e=>papers.has(raw.entities[e].paperId));assert.equal(row.dataset.changeScope,local?'current-scope':'outside-scope');assert.equal(row.dataset.relationType,r.relationType);assert.equal(row.dataset.renderAsTree,'false');}}
  scope(x,'task:vln');await loaded(x);const r99=change(x,99),c99=r99.querySelector('[data-task-change-claim="method-edge:98"]');assert.equal(c99.dataset.versionRelation,'other-version');assert.equal(c99.dataset.evidenceVersion,raw.claims['method-edge:98'].versionId);assert.match(c99.textContent,/另项来源/);const env=methods('task:vln').find(p=>p.paperId==='envdrop');assert.equal(env.versionId,'arxiv:1904.04195v1');assert.ok(r99.querySelector('[data-change-target="'+env.id+'"]'));
  scope(x,'task:instanceimagenav');await loaded(x);const placements=methods('task:instanceimagenav').filter(p=>p.entityId==='methods:pipeline-modiin');assert.ok(placements.length>1);for(const p of placements)assert.ok(x.doc.querySelector('[data-route-method="'+p.id+'"]'));assert.deepEqual(x.errors,[]);
 });
 scenario('summaries',async t=>{
  const x=await page();t.after(()=>closePage(x));for(const id of ['task:category-objectnav','task:language-objectnav','task:pointnav','task:multistage-language-navigation']){scope(x,id);await loaded(x);for(const p of methods(id)){const d=raw.entities[p.entityId].detail||{},flow=d.pipeline||d.pipeline_contract||{},row=x.doc.querySelector('[data-route-method="'+p.id+'"]'),details=row.querySelector('.np-route-method-summary');assert.equal(details.open,false);details.querySelector('summary').click();for(const key of ['representation','decision'])assert.ok(details.textContent.includes(flow[key]||'未记录'),p.id+' '+key);if(!flow.representation&&!flow.decision)for(const cid of p.claimIds||[]){const c=raw.claims[cid];if(c&&c.paperId===p.paperId&&c.versionId===p.versionId)assert.ok(details.textContent.includes(c.statement||c.label));}}}
  scope(x,'task:imagenav');await loaded(x);assert.match(x.doc.querySelector('[data-task-route-scope]').textContent,/条件关联/);for(const p of methods('task:imagenav')){const input=x.doc.querySelector('[data-route-condition-input=\"'+p.id+'\"]');assert.ok(input);assert.ok(input.textContent.includes(raw.entities[p.entityId].detail.pipeline.input));assert.equal(input.closest('details'),null);}for(const p of partition('task:imagenav').groups)assert.ok(x.doc.querySelector('[data-route-group="'+p.id+'"]').textContent.includes(raw.entities[p.entityId].detail.scope||'范围：未记录'));assert.deepEqual(x.errors,[]);
 });
 scenario('async',async t=>{
  const pending=new Map(),x=await page({fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>x.w.close());scope(x,'task:category-objectnav');await frames(x.w);const panel=x.doc.querySelector('[data-task-route-scope]'),method=x.doc.getElementById('np-task-route-method-pos:l:98bc421b8bfd17d6699922'),summary=x.doc.getElementById('np-task-route-summary-pos:l:98bc421b8bfd17d6699922');summary.click();method.focus();method.dispatchEvent(new x.w.MouseEvent('mousedown',{bubbles:true}));x.doc.getElementById('np-detail-scroll').scrollTop=122;await wait(5);release(pending,ownerURL(x,'methods:pipeline-poni'));await wait(30);assert.equal(change(x,90),null);
  for(const url of [...pending.keys()])release(pending,url);await loaded(x);assert.equal(x.doc.querySelector('[data-task-route-scope]'),panel);assert.equal(x.doc.getElementById(method.id),method);assert.equal(x.doc.getElementById(summary.id),summary);assert.equal(summary.parentElement.open,true);assert.equal(x.doc.activeElement,method);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,122);assert.equal(panel.lastElementChild.className,'np-task-route-changes');assert.match(fs.readFileSync(path.join(root,'assets/navigation-product.css'),'utf8'),/height:14rem;overflow:auto;overscroll-behavior:contain/);const relation=change(x,90),relationSummary=relation.querySelector('summary');relationSummary.click();relationSummary.focus();assert.equal(relation.open,true);
  for(const host of [x.doc.querySelector('.np-task-route-changes>div'),x.doc.querySelector('.np-task-route-outside>div')]){const ids=[...host.children].map(n=>n.dataset.taskChange);assert.deepEqual(ids,[...ids].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true})));}
  method.dispatchEvent(new x.w.MouseEvent('mouseup',{bubbles:true}));method.click();assert.equal(x.w.NavigationProductApp.getState().route.node,'pos:l:98bc421b8bfd17d6699922');scope(x,'task:vln');await wait(5);const oldURLs=[...pending.keys()];scope(x,'task:aerial-visual-object-search');await frames(x.w);const newer=x.doc.querySelector('[data-task-route-scope]'),route=JSON.stringify(x.w.NavigationProductApp.getState().route),focus=x.doc.activeElement;x.doc.getElementById('np-detail-scroll').scrollTop=77;for(const url of oldURLs)release(pending,url);await wait(60);assert.equal(x.doc.querySelector('[data-task-route-scope]'),newer);assert.equal(JSON.stringify(x.w.NavigationProductApp.getState().route),route);assert.equal(x.doc.activeElement,focus);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,77);assert.deepEqual(x.errors,[]);
 });
 scenario('failures',async t=>{
  const x=await page({fetch:()=>Promise.resolve({ok:true,arrayBuffer:async()=>Buffer.from('{}')})});t.after(()=>x.w.close());scope(x,'task:category-objectnav');await wait(60);const method=x.doc.getElementById('np-task-route-method-pos:l:98bc421b8bfd17d6699922'),row=method.parentElement;assert.equal(row.querySelector('[data-content-state]').dataset.contentState,'failed');const content=x.w.NavigationProductApp.getContent();for(let i=0;i<2;i++){[...row.querySelectorAll('button')].find(n=>n.textContent==='重试此节点正文').click();await wait(30);}assert.equal(content.attempts('methods:pipeline-poni'),3);assert.ok(![...row.querySelectorAll('button')].some(n=>n.textContent==='重试此节点正文'));assert.equal(x.doc.getElementById(method.id),method);method.click();assert.equal(x.w.NavigationProductApp.getState().route.node,'pos:l:98bc421b8bfd17d6699922');assert.equal(x.doc.querySelector('main').dataset.loadState,'ready');scope(x,'task:imagenav');await wait(50);assert.match(x.doc.querySelector('[data-route-condition-input]').textContent,/暂未载入/);assert.deepEqual(x.errors,[]);
 });
 for(const action of ['none','focus','wheel','scope'])scenario(action==='none'?'return-clamp':'return-clamp-'+action,async t=>{
  const x=await page({width:1920});t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);await frames(x.w);const app=x.w.NavigationProductApp,reader=x.doc.getElementById('np-detail-scroll'),relation=change(x,90);relation.open=true;const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]'),targetId=target.id,origin=JSON.stringify(app.getState().route);let top=0;const writes=[];
  // JSDOM has no layout. This synthetic range models a shorter closed disclosure;
  // it proves restoration order, not any particular real Chrome scroll geometry.
  Object.defineProperty(reader,'scrollTop',{configurable:true,get(){return top;},set(value){const current=change(x,90),limit=current&&!current.open?200:1000;top=Math.max(0,Math.min(Number(value),limit));writes.push({requested:value,actual:top,open:current&&current.open,route:app.getState().route.node});}});
  reader.scrollTop=300;target.focus();target.click();await frames(x.w);assert.equal(app.getState().originTrail.at(-1).bucket.detailScrollByTree.l,300);
  const nativeRAF=x.w.requestAnimationFrame,queued=[];x.w.requestAnimationFrame=fn=>{queued.push(fn);return queued.length;};writes.length=0;x.doc.querySelector('.np-return-previous').click();assert.equal(change(x,90).open,false);
  let chosen=null;if(action==='focus'){chosen=x.doc.querySelector('[data-route-method] button');chosen.focus();reader.scrollTop=117;}if(action==='wheel'){reader.scrollTop=117;reader.dispatchEvent(new x.w.WheelEvent('wheel',{deltaY:20,bubbles:true}));chosen=x.doc.activeElement;}if(action==='scope')scope(x,'task:aerial-visual-object-search');const newer=JSON.stringify(app.getState().route);writes.length=0;
  while(queued.length)queued.shift()();x.w.requestAnimationFrame=nativeRAF;await frames(x.w);
  if(action==='none'){assert.equal(JSON.stringify(app.getState().route),origin);assert.equal(reader.scrollTop,300);assert.equal(x.doc.activeElement.id,targetId);assert.equal(change(x,90).open,true);assert.ok(writes.some(w=>w.requested===300&&w.actual===300&&w.open===true));assert.ok(!writes.some(w=>w.requested===300&&w.open===false));}
  else if(action==='scope'){assert.equal(JSON.stringify(app.getState().route),newer);assert.equal(app.getState().route.scope,'task:aerial-visual-object-search');assert.ok(!writes.some(w=>w.requested===300));assert.equal(x.doc.getElementById(targetId),null);}
  else{assert.equal(JSON.stringify(app.getState().route),origin);assert.equal(reader.scrollTop,117);assert.equal(x.doc.activeElement,chosen);assert.equal(change(x,90).open,false);assert.ok(!writes.some(w=>w.requested===300));}
  assert.deepEqual(x.errors,[]);
 });
 scenario('return',async t=>{
  const x=await page();t.after(()=>closePage(x));scope(x,'task:category-objectnav');await loaded(x);await frames(x.w);const app=x.w.NavigationProductApp,origin=app.getState().route,relation=change(x,90);relation.querySelector('summary').click();const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]');target.focus();target.click();await frames(x.w);x.w.history.back();await wait(80);await frames(x.w);assert.deepEqual(app.getState().route,origin);assert.equal(x.doc.activeElement.id,target.id);assert.equal(x.doc.activeElement.closest('details').open,true);const current=x.doc.getElementById(target.id);current.focus();current.click();await frames(x.w);x.doc.querySelector('.np-return-previous').click();await frames(x.w);assert.deepEqual(app.getState().route,origin);assert.equal(x.doc.activeElement.id,target.id);assert.equal(x.doc.activeElement.closest('details').open,true);const toggle=x.doc.getElementById('np-reader-toggle');if(!toggle.hidden){toggle.click();assert.equal(x.doc.getElementById('np-detail-scroll').hidden,true);toggle.click();assert.equal(x.doc.getElementById('np-detail-scroll').hidden,false);}assert.deepEqual(x.errors,[]);
 });
 scenario('method-claim-typography',async t=>{
  const x=await page({width:1440});t.after(()=>closePage(x));const selected=new Map();for(const entry of raw.scopes.filter(s=>s.id!=='scope:all'))for(const p of methods(entry.id)){const d=raw.entities[p.entityId].detail||{};if(!d.pipeline&&!d.pipeline_contract)selected.set(p.entityId,p);}assert.ok(selected.has('methods:pipeline-tap-rl'));assert.ok(selected.has('methods:pipeline-tap-llm'));const failures=[];let texts=0,sources=0;
  function cssValue(node,key){for(let at=node;at;at=at.parentElement){const value=x.w.getComputedStyle(at)[key];if(value&&value!=='normal'&&value!=='inherit')return value;}return '';}
  function px(value){return value.endsWith('rem')?parseFloat(value)*16:value.endsWith('px')?parseFloat(value):NaN;}
  for(const p of selected.values()){scope(x,p.scopeId);const app=x.w.NavigationProductApp;app.navigate(x.w.NavigationProductModel.routeForPosition(app.getBundle(),app.getState().route,p.id));for(let i=0;i<150&&app.getContent().status(p.entityId)!=='ready';i++)await wait(10);await frames(x.w);assert.equal(app.getContent().status(p.entityId),'ready');const method=x.doc.querySelector('[data-mechanism-entity="'+p.entityId+'"]');assert.ok(method);assert.equal(method.querySelector('.np-method-flow'),null);const claims=Array.from(new Set([...(p.claimIds||[]),...(raw.entities[p.entityId].claimIds||[])])).map(id=>raw.claims[id]).filter(c=>c&&c.paperId===p.paperId&&c.versionId===p.versionId);for(const c of claims){const row=method.querySelector('[data-method-claim="'+c.id+'"]');assert.ok(row,c.id);assert.ok(row.textContent.includes(c.statement||c.label));}
   [...method.querySelectorAll('button')].find(n=>n.textContent==='核对固定版本与原文证据').click();const evidence=x.doc.querySelector('#np-evidence-panel .np-evidence');assert.ok(evidence);evidence.open=true;assert.equal(x.doc.getElementById('np-evidence-panel').open,true);for(const c of claims){const row=evidence.querySelector('[data-claim-id="'+c.id+'"]');assert.ok(row);assert.ok(row.textContent.includes(c.statement||c.label));for(const ref of c.sourceRefs||[]){if(ref.url){assert.ok(row.querySelector('a[href="'+ref.url+'"]'));sources++;}if(typeof ref.locator==='string')assert.ok(row.textContent.includes(ref.locator));if(ref.versionId&&raw.versions[ref.versionId]){const v=raw.versions[ref.versionId];assert.ok(row.textContent.includes(v.label||v.descriptor||ref.versionId));}}}
   for(const host of [method.querySelector('.np-method-claims'),method.querySelector(':scope>.np-note'),...evidence.querySelectorAll('.np-claim')])for(const node of [host,...host.querySelectorAll('*')])if([...node.childNodes].some(child=>child.nodeType===3&&child.textContent.trim())){texts++;const size=px(cssValue(node,'fontSize')),line=cssValue(node,'lineHeight'),ratio=line.endsWith('px')?parseFloat(line)/size:parseFloat(line);if(size<15||!Number.isFinite(size)||ratio<1.5)failures.push({entity:p.entityId,tag:node.tagName,className:node.className,text:node.textContent.slice(0,70),fontSize:cssValue(node,'fontSize'),lineHeight:line});}
  }
  await frames(x.w);assert.ok(texts>0);assert.ok(sources>0);if(failures.length)t.diagnostic(JSON.stringify(failures));assert.deepEqual(failures,[],'method claim body, scope, version, sources, locators and controls preserve the 15px reading floor');assert.deepEqual(x.errors,[]);
 });
 scenario('typography',async t=>{
  const css=fs.readFileSync(path.join(root,'assets/navigation-product.css'),'utf8'),floor=css.split('/* Task-root reading text keeps the 15px floor, including inherited legacy notes. */')[1];assert.ok(floor);for(const rule of floor.matchAll(/([^{}]+)\{([^{}]+)\}/g)){for(const selector of rule[1].split(','))assert.ok(selector.trim().startsWith('#navigation-product .np-task-route-overview'),'font floor stays inside task overview');assert.match(rule[2],/line-height:1\.55/);}assert.match(floor,/#navigation-product \.np-task-route-overview \.np-note/);
  const x=await page();t.after(()=>closePage(x));let checked=0,slots=0;
  // This checks the production DOM/CSS contract. Real layout, zoom and scroll
  // geometry are checked separately by the browser capture gate.
  function value(node,key){for(let at=node;at;at=at.parentElement){const result=x.w.getComputedStyle(at)[key];if(result&&result!=='normal'&&result!=='inherit')return result;}return '';}
  function px(value){if(value.endsWith('px'))return parseFloat(value);if(value.endsWith('rem'))return parseFloat(value)*16;return NaN;}
  for(const id of ['task:category-objectnav','task:imagenav','task:vln','task:language-objectnav','task:goat','task:aerial-visual-object-search']){const panel=scope(x,id);await loaded(x);panel.querySelectorAll('details').forEach(n=>n.open=true);for(const n of panel.querySelectorAll('*'))if([...n.childNodes].some(child=>child.nodeType===3&&child.textContent.trim())){const size=px(value(n,'fontSize')),height=value(n,'lineHeight'),ratio=height.endsWith('px')?parseFloat(height)/size:parseFloat(height);assert.ok(size>=15,n.tagName+' '+n.className+' font='+value(n,'fontSize'));assert.ok(ratio>=1.5,n.tagName+' '+n.className+' line-height='+height);checked++;}for(const slot of panel.querySelectorAll('.np-route-group-disclosure>div,.np-route-method-summary>div,.np-route-condition-input,.np-route-group-condition')){const style=x.w.getComputedStyle(slot);assert.equal(style.overflow,'auto');assert.ok(px(style.height)>0);assert.equal(style.boxSizing,'border-box');assert.equal(style.scrollbarGutter,'stable');slots++;}}
  await frames(x.w);assert.ok(checked>0);assert.ok(slots>0);assert.deepEqual(x.errors,[]);
 });
 scenario('conditions',async t=>{
  const x=await page();t.after(()=>closePage(x));const ids=raw.scopes.filter(s=>s.id!=='scope:all'&&partition(s.id).groups.some(p=>p.association==='condition')).map(s=>s.id);
  for(const id of ids){scope(x,id);await loaded(x);for(const p of partition(id).groups.filter(p=>p.association==='condition')){const slot=x.doc.querySelector('[data-route-group-condition="'+p.id+'"]');assert.ok(slot,p.id);assert.equal(slot.closest('details'),null);const d=raw.entities[p.entityId].detail||{},values=['condition','scope','evidence'].map(k=>d[k]).filter(Boolean);if(values.length)for(const value of values)assert.ok(slot.textContent.includes(value),p.id);else assert.match(slot.textContent,/未记录/);}}
  scope(x,'task:imagenav');await loaded(x);const reactive=partition('task:imagenav').groups.find(p=>p.entityId==='methods:method-group:pg-image-reactive');assert.match(x.doc.querySelector('[data-route-group-condition="'+reactive.id+'"]').textContent,/scene-specific适应条件可见/);assert.deepEqual(x.errors,[]);
 });
 for(const mode of ['restore','focus','key','pointer','click','scope','reader','wheel','touch','pre-focus','pre-key'])scenario('cold-'+mode,async t=>{
  const seed=await page();scope(seed,'task:category-objectnav');await loaded(seed);await frames(seed.w);const relation=change(seed,90);relation.open=true;const target=relation.querySelector('[data-change-target="pos:l:98bc421b8bfd17d6699922"]'),targetId=target.id;target.focus();seed.w.dispatchEvent(new seed.w.Event('pagehide'));const saved=JSON.parse(JSON.stringify(seed.w.history.state)),hash=seed.w.location.hash;assert.equal(seed.w.NavigationProductModel.getBucket(seed.w.NavigationProductApp.getState()).focusTarget,targetId);await closePage(seed);
  const pending=new Map(),x=await page({saved,hash,holdFrames:mode.startsWith('pre-'),width:mode==='reader'?1440:undefined,fetch:url=>new Promise(resolve=>pending.set(url,resolve))});t.after(()=>x.w.close());assert.equal(x.doc.getElementById(targetId),null);const fallback=x.doc.activeElement;
  if(mode==='pre-focus')x.doc.querySelector('[data-route-method] button').focus();
  if(mode==='pre-key')x.doc.body.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
  if(mode==='focus'){x.doc.querySelector('[data-route-method] button').focus();fallback.focus();}
  if(mode==='key')fallback.dispatchEvent(new x.w.KeyboardEvent('keydown',{key:'Shift',bubbles:true}));
  if(mode==='pointer')fallback.dispatchEvent(new x.w.MouseEvent('mousedown',{bubbles:true}));
  if(mode==='click')fallback.dispatchEvent(new x.w.MouseEvent('click',{bubbles:true}));
  if(mode==='wheel')fallback.dispatchEvent(new x.w.WheelEvent('wheel',{deltaY:20,bubbles:true}));
  if(mode==='touch')fallback.dispatchEvent(new x.w.Event('touchstart',{bubbles:true}));
  if(mode==='scope')scope(x,'task:aerial-visual-object-search');
  if(mode==='reader'){x.doc.getElementById('np-task-route-method-pos:l:98bc421b8bfd17d6699922').click();await frames(x.w);const toggle=x.doc.getElementById('np-reader-toggle');assert.equal(toggle.hidden,false);toggle.click();toggle.click();}
  if(mode.startsWith('pre-')){const chosen=x.doc.activeElement;x.flushFrames();assert.equal(x.doc.activeElement,chosen,'initial delayed frame must not steal newer focus');}else await frames(x.w);const expectedFocus=x.doc.activeElement;const beforeRoute=JSON.stringify(x.w.NavigationProductApp.getState().route);x.doc.getElementById('np-detail-scroll').scrollTop=93;
  for(const url of [...pending.keys()])release(pending,url);await loaded(x);await wait(50);const restored=x.doc.getElementById(targetId);
  if(mode==='restore'){assert.ok(restored);assert.equal(x.doc.activeElement,restored);for(let at=restored.parentElement;at;at=at.parentElement)if(at.tagName==='DETAILS')assert.equal(at.open,true);}
  else{assert.equal(x.doc.activeElement,expectedFocus);if(restored)assert.equal(restored.closest('details').open,false);}
  assert.equal(JSON.stringify(x.w.NavigationProductApp.getState().route),beforeRoute);assert.equal(x.doc.getElementById('np-detail-scroll').scrollTop,93);assert.deepEqual(x.errors,[]);
 });

}
