'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),{JSDOM,VirtualConsole}=require('jsdom');
const root=path.resolve(__dirname,'..'),html=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();print(p.render(r,p.payloads(r)[1]))"],{cwd:root,encoding:'utf8',maxBuffer:14e6});
const wait=ms=>new Promise(r=>setTimeout(r,ms)),clean=x=>JSON.parse(JSON.stringify(x));
async function page(hash='',saved=null){const errors=[],calls=[],v=new VirtualConsole();v.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(html,{url:'https://example.org/research/navigation/'+hash,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:v,beforeParse(w){if(saved)w.history.replaceState(saved,'',w.location.href);w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=(x,y)=>{Object.defineProperty(w,'scrollY',{value:y,configurable:true});};w.HTMLElement.prototype.scrollIntoView=function(){};Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.fetch=url=>{calls.push(url);return new Promise(()=>{});};}});for(let i=0;i<100&&!d.window.NavigationProductApp;i++)await wait(20);assert.ok(d.window.NavigationProductApp);await frames(d.window);return {w:d.window,calls,errors};}
async function frames(w){await new Promise(r=>w.requestAnimationFrame(()=>w.requestAnimationFrame(r)));}
async function openOriginalMap(w){const home=w.document.querySelector('#np-reading-landing');if(home&&!home.hidden){w.document.querySelector('#np-overview-toggle').click();await frames(w);}assert.equal(w.document.querySelector('.np-panels').hidden,false);}
function visible(w){return [...w.document.querySelectorAll('#np-tree [role=treeitem]')].map(n=>n.dataset.position);}
test('default reading overview exposes all task entries while the preserved global structure retains exact roles and benchmark links',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,b=a.getBundle(),d=w.document;assert.equal(a.getState().route.tree,'g');assert.equal(d.querySelector('#np-reading-landing').hidden,false);assert.equal(d.querySelector('.np-panels').hidden,true);assert.equal(d.querySelectorAll('[data-task-open]').length,22);assert.equal(d.querySelectorAll('[data-reading-branch]').length,2);assert.equal(x.calls.length,0);await openOriginalMap(w);const nodes=visible(w).map(id=>b.positions[id]);for(const eid of ['legacy:nav:goal','legacy:nav:l','legacy:nav:c','task:pointnav','task:category-objectnav','task:goat'])assert.ok(nodes.some(p=>p.entityId===eid),eid);assert.ok(nodes.filter(p=>p.sourceRootPositionIds).length>=20);assert.equal(d.querySelectorAll('[data-scope-entry]').length,0);assert.equal(d.querySelector('#np-scope-map-section').getAttribute('href'),'branches/directory.html');assert.equal(d.querySelector('#np-common'),null);assert.ok(d.querySelectorAll('#np-tree .np-task-benchmark').length>=20);const target=d.querySelector('[data-scope-benchmarks="task:category-objectnav"] button');assert.ok(target);target.click();assert.equal(a.getState().route.scope,'task:category-objectnav');assert.ok(b.scopes.find(s=>s.id==='task:category-objectnav').benchmarkIds.includes(a.getState().route.bench));assert.equal(d.querySelector('#np-task-conditions').open,true);assert.deepEqual(x.errors,[]);});
test('global task focus, equivalent outline, zoom and return retain the exact reading context',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),d=w.document,initial=visible(w);await openOriginalMap(w);d.querySelector('#np-zoom-out').click();assert.equal(M.getBucket(a.getState()).graphScale,.9);const row=b.researchMap.scopeEntries.find(r=>r.scopeId==='task:goat');d.getElementById('np-node-'+row.canonicalPositionId).querySelector('.np-node-label').click();assert.equal(a.getState().route.node,row.canonicalPositionId);const before=visible(w);d.querySelector('#np-layout-toggle').click();assert.equal(a.getState().route.mode,'outline');assert.deepEqual(visible(w),before);d.querySelector('[data-tree-tab=g]').click();assert.equal(a.getState().route.node,b.researchMap.roots[0]);assert.deepEqual(visible(w),initial);const route=clean(a.getState().route);d.querySelector('#np-graph-fullscreen').click();assert.deepEqual(clean(a.getState().route),route,'unsupported fullscreen preserves reading context');assert.deepEqual(x.errors,[]);});
test('an explicit historical version selected from a global work opens that version without borrowing another',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),d=w.document,p=Object.values(b.researchMap.positions).find(p=>p.paperId==='vlfm'&&p.versionId&&b.papers.vlfm.versionIds.length>1);assert.ok(p);a.navigate(M.routeForPosition(b,a.getState().route,p.id));const next=b.papers.vlfm.versionIds.find(v=>v!==p.versionId);d.querySelector('#np-version').value=next;d.querySelector('#np-version').dispatchEvent(new w.Event('change'));assert.equal(a.getState().route.tree,'l');assert.equal(a.getState().route.paper,'vlfm');assert.equal(a.getState().route.version,next);assert.equal(d.querySelector('#np-navigation-error').hidden,true);});

test('cold explicit overview links seed the same concrete task and challenge layer as an ordinary fresh entry',async t=>{const a=await page();t.after(()=>a.w.close());const first=a.w.NavigationProductApp,M=a.w.NavigationProductModel,expected=visible(a.w),hash=M.encodeRoute(first.getState().route);assert.ok(expected.length>20);const b=await page(hash);t.after(()=>b.w.close());assert.deepEqual(visible(b.w),expected);assert.equal(b.calls.length,0);});
test('a valid saved overview keeps its deliberate collapse rather than reseeding defaults on reload',async t=>{const a=await page();t.after(()=>a.w.close());const w=a.w,app=w.NavigationProductApp,M=w.NavigationProductModel,b=app.getBundle(),task=Object.values(b.researchMap.positions).find(p=>p.kind==='editorial_directory_group'&&p.sourceDirectoryGroupId==='task');await openOriginalMap(w);w.document.getElementById('np-node-'+task.id).querySelector('.np-node-toggle').click();const expected=visible(w),saved=clean(w.history.state),hash=M.encodeRoute(app.getState().route);assert.ok(!M.getBucket(app.getState()).expandedByTree.g.includes(task.id));const again=await page(hash,saved);t.after(()=>again.w.close());assert.deepEqual(visible(again.w),expected);assert.ok(!again.w.NavigationProductModel.getBucket(again.w.NavigationProductApp.getState()).expandedByTree.g.includes(task.id));const bare=await page('',saved);t.after(()=>bare.w.close());assert.deepEqual(visible(bare.w),expected,'already-global no-hash history keeps deliberate collapse');});

const publishedHistory=require('./fixtures/navigation-pr53-history.json');
for(const [name,fixture] of Object.entries(publishedHistory.states)){
 test('ordinary no-hash boot migrates actual published '+name+' history to overview without losing its reading snapshot',async t=>{const x=await page('',fixture.history);t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),old=fixture.history[M.KEY],s=a.getState();assert.equal(s.route.tree,'g');assert.equal(s.route.node,b.researchMap.roots[0]);assert.ok(visible(w).length>20);const retained=clean(s.contexts[M.contextKey(old.route)]),original=old.contexts[M.contextKey(old.route)];if(M.contextKey(old.route)===M.contextKey(s.route))['selectedByTree','expandedByTree','treeScrollByTree','detailScrollByTree','treeScrollLeftByTree'].forEach(field=>{if(!original[field])delete retained[field];else delete retained[field].g;});if(M.contextKey(old.route)===M.contextKey(s.route)){retained.windowScroll=original.windowScroll;assert.equal(retained.originalMapOpen,false,'the shared context records the new overview presentation explicitly');delete retained.originalMapOpen;}assert.deepEqual(retained,original);assert.equal(w.scrollY,0,'a fresh overview must not inherit the old page deep scroll');assert.deepEqual(clean(s.originTrail.at(-1)),{route:old.route,bucket:old.contexts[M.contextKey(old.route)]});assert.equal(w.history.state.unrelatedOwnerField,'preserve-me');const restored=M.restoreOrigin(b,s,s.originTrail.length-1);assert.deepEqual(clean(M.snapshot(restored)),{route:old.route,bucket:old.contexts[M.contextKey(old.route)]});w.history.replaceState(fixture.history,'',w.location.pathname);w.dispatchEvent(new w.PopStateEvent('popstate',{state:fixture.history}));await frames(w);assert.deepEqual(clean(a.getState().route),old.route,'a later no-hash Back/popstate restores the original reader, not a second migration');assert.equal(w.document.querySelector('#np-tree-scroll').scrollTop,123);assert.equal(w.document.querySelector('#np-detail-scroll').scrollTop,570);assert.equal(w.scrollY,1750);assert.deepEqual(x.errors,[]);});
 test('explicit published '+name+' deep links retain the exact legacy scope and version',async t=>{const x=await page(fixture.urlHash,fixture.history);t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel;assert.deepEqual(clean(a.getState().route),fixture.history[M.KEY].route);assert.equal(w.document.querySelector('#np-tree-scroll').scrollTop,123);assert.equal(w.document.querySelector('#np-detail-scroll').scrollTop,570);assert.equal(w.scrollY,1750);assert.deepEqual(x.errors,[]);});
}

const originalScience=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(root,'data/navigation-product/model.json.gz')))),plainModel=require('../assets/navigation-product-model.js');
const coldVlnPosition=Object.values(originalScience.positions).find(p=>p.tree==='l'&&p.scopeId==='task:vln'&&p.paperId&&p.versionId&&p.kind==='pipeline_recipe');
for(const [name,hash,saved] of [['PONI ablation',publishedHistory.states.analysis.urlHash,null],['VLN method',plainModel.encodeRoute(plainModel.routeForPosition(originalScience,{scope:'task:vln'},coldVlnPosition.id)),null],['old scope-all index',publishedHistory.states.index.urlHash,publishedHistory.states.index.history]])test('cold '+name+' can open the full overview and return to its exact evidence',async t=>{const x=await page(hash,saved);t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,start=clean(a.getState().route);w.document.querySelector('[data-tree-tab=g]').click();await frames(w);assert.equal(a.getState().route.tree,'g');assert.equal(visible(w).length,45);const origin=w.document.querySelectorAll('#np-origin-trail button');assert.ok(origin.length);origin[origin.length-1].click();await frames(w);assert.deepEqual(clean(a.getState().route),start);w.history.back();await frames(w);assert.equal(a.getState().route.tree,'g');assert.equal(visible(w).length,45);w.history.forward();await frames(w);assert.deepEqual(clean(a.getState().route),start);assert.deepEqual(x.errors,[]);});
test('overview fallback without an origin restores an existing deliberately collapsed global bucket',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),rootId=b.researchMap.roots[0];await openOriginalMap(w);w.document.getElementById('np-node-'+rootId).querySelector('.np-node-toggle').click();await frames(w);w.document.querySelector('#np-tree-scroll').scrollTop=123;w.scrollTo(0,650);w.dispatchEvent(new w.Event('pagehide'));a.navigate(M.parseRoute(b,publishedHistory.states.analysis.urlHash),{cross:true});await frames(w);const saved=clean(w.history.state);saved[M.KEY].originTrail=[];const y=await page(publishedHistory.states.analysis.urlHash,saved);t.after(()=>y.w.close());y.w.document.querySelector('[data-tree-tab=g]').click();await frames(y.w);assert.equal(visible(y.w).length,1,'active collapse is not a missing global context');assert.equal(y.w.document.querySelector('#np-tree-scroll').scrollTop,123);assert.equal(y.w.scrollY,650);assert.deepEqual(y.errors,[]);});

test('the General goal breadcrumb from a cold paper uses the same first-overview expansion',async t=>{const x=await page(publishedHistory.states.analysis.urlHash);t.after(()=>x.w.close());const w=x.w;w.document.querySelector('#np-global-context .np-crumb').click();await frames(w);assert.equal(w.NavigationProductApp.getState().route.tree,'g');assert.equal(visible(w).length,45);assert.deepEqual(x.errors,[]);});
