'use strict';
// Deterministic contracts only; browser CSS geometry/zoom acceptance is separate.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const root=process.env.RPA_LAYOUT_SOURCE||path.resolve(__dirname,'..'),source=path.join(root,'previews/radar-c2-analysis'),T=require(path.join(source,'model.js')).atlas,M=require(path.join(source,'analysis/model.js')),UI=require(path.join(source,'analysis/c2.js'));
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(source,'analysis/data/bundle.js'),'utf8'),ctx);const bundle=ctx.window.C2_DATA;
let count=0,failures=0;function test(name,fn){try{fn();console.log('PASS',name);count++;}catch(error){failures++;console.error('FAIL',name,error.message);}}
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rpa-layout-'));fs.cpSync(source,temp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),temp,{recursive:true});const {fixture}=require(path.join(temp,'analysis/tests/dom_fixture.cjs'));
try{
 test('five source branches have a separate permanent locator for filled and pending papers',()=>{for(const id of ['harnessvln','navharness','navgpt']){const f=fixture({width:1180,height:757});f.c2.open(id,f.app.getContext());const model=f.c2.getModel(),map=f.$('.c2-location-map');assert(map,'persistent locator absent');assert.equal(map.querySelectorAll('.c2-skeleton-branch').length,5);assert.deepEqual(map.querySelectorAll('.c2-skeleton-branch').map(n=>n.dataset.id),JSON.parse(JSON.stringify(M.children(model,M.ROOT).map(n=>n.id))));assert.equal(map.querySelector('.atlas-fit'),null);assert.equal(map.querySelector('.atlas-svg'),null);assert.equal(map.querySelector('.c2-skeleton-root').textContent,'论文解析树');assert.equal(model.schema.nodes.length,59);}});
 test('compact locator preserves source order in two connected mobile rows',()=>{const f=fixture({width:390,height:844});f.c2.open('navharness',f.app.getContext());const rows=f.$('.c2-location-map').querySelectorAll('.c2-skeleton-row');assert.equal(rows.length,2);assert.deepEqual(rows.map(row=>row.querySelectorAll('.c2-skeleton-branch').length),[3,2]);const css=fs.readFileSync(path.join(source,'analysis/c2.css'),'utf8');assert(css.includes('.c2-skeleton-row{display:contents}'));assert(css.includes('.c2-skeleton-head{position:relative;border-left:1px solid'));assert(css.includes('.c2-skeleton-branches{display:block;border-top:0;border-left:1px solid'));assert(css.includes('.c2-skeleton-row .c2-skeleton-branch:before{display:block}'));});
 test('full expansion keeps separate skeleton and current branch without changing model or focus',()=>{const f=fixture();f.c2.open('navharness',f.app.getContext());f.c2.dispatch({type:'enter',id:'abstract.task'});const state=JSON.stringify(f.c2.getState()),data=JSON.stringify([...f.c2.getModel().nodes]);for(let i=0;i<4;i++){f.click('[data-atlas-mode="analysis"]');const map=f.$('.c2-location-map');assert(map);assert.equal(map.querySelectorAll('.c2-skeleton-branch').length,5);assert.equal(map.querySelector('[aria-current="location"]').dataset.id,'abstract');assert(map.textContent.includes('Task'));assert.equal(JSON.stringify(f.c2.getState()),state);assert.equal(JSON.stringify([...f.c2.getModel().nodes]),data);}});
 test('all149 filled nodes fit their available focus width, retaining labels and true parent edges',()=>{for(const id of ['harnessvln','navharness']){const model=M.fromBundle(bundle,id);for(const width of [220,296,340,390,500,550,580,820,1160])for(const node of model.nodes.values()){const state=M.locate(model,M.initial(model),node.id),g=M.layout(model,state,width);assert.equal(g.width,width,`${id}/${node.id} overflows ${width}`);assert(g.nodes.some(n=>n.id===node.id));for(const n of g.nodes){assert(n.x>=0&&n.x+n.w<=width+.01);assert(n.y>=0&&n.y+n.h<=g.height+.01);assert.equal(n.labelLines.join(''),model.nodes.get(n.id).label.replace(/\n/g,''));}for(const e of g.edges)assert.equal(model.nodes.get(e.target).parent,e.source);for(let i=0;i<g.nodes.length;i++)for(let j=i+1;j<g.nodes.length;j++){const a=g.nodes[i],b=g.nodes[j];assert(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'overlapping focus nodes');}}}});
 test('shared field focus layout also fits220px with unchanged connected hierarchy',()=>{const items=[{id:'root',depth:0,label:'任务定义',children:['method']},{id:'method',depth:1,label:'完整的研究方法标签',children:['module','paper']},{id:'module',depth:2,label:'关键模块',children:[]},{id:'paper',depth:2,label:'A long paper name without truncation',children:[]}];for(const width of [220,340,500,820]){const g=T.readableLayout(items,'root',{width});assert.equal(g.width,width);assert.equal(g.nodes.length,4);assert.equal(g.edges.length,3);for(const n of g.nodes)assert(n.x+n.w<=width+.01);}});
 test('native locator branch navigation, evidence close and history retain selected paper and path',()=>{const f=fixture({width:390,height:844});f.c2.open('navharness',f.app.getContext());f.click('.c2-skeleton-branch[data-id="method"]');assert.equal(f.c2.getState().focus,'method');f.click('.c2-node[data-id="method.module1"]');f.click('.c2-node[data-id="method.module1.why"]');assert.equal(f.c2.getState().drawer,'evidence');f.click('[data-c2="close"]');assert.equal(f.document.activeElement.dataset.id,'method.module1.why');f.click('.c2-skeleton-branch[data-id="experiments"]');f.back();assert.equal(f.c2.getState().selected,'method.module1.why');assert.equal(f.$('.c2-location-map').querySelector('[aria-current="location"]').dataset.id,'method');assert.equal(f.c2.getState().paperId,'navharness');});
 test('all31 NavHarness ledger records display attribution and false reproduction plainly without altering raw values',()=>{const f=fixture();f.c2.open('navharness',f.app.getContext());f.c2.dispatch({type:'enter',id:'abstract.task'});f.c2.dispatch({type:'drawer',drawer:'evidence'});for(const id of ['E01','E05']){const record=f.$('[data-evidence-id="'+id+'"]');assert(record);assert(record.textContent.includes('作者报告或论文定义'));assert(record.textContent.includes('未独立复现'));assert(!record.textContent.includes('author_report_or_paper_definition'));assert(!record.textContent.includes('false'));}const m=f.c2.getModel(),html=UI.ledgerHtml(m);assert.equal((html.match(/data-raw-value="false"/g)||[]).length,31);assert(m.ledger.records.every(r=>r.independentlyReproduced===false));});
 test('unselected field roots use the empty focus column and restore it after selection',()=>{const f=fixture();assert(f.$('#tree-workspace').classList.contains('is-root-overview'));f.click('.atlas-root[data-atlas-view="l"]');assert(!f.$('#tree-workspace').classList.contains('is-root-overview'));f.click('[data-atlas-reset="l"]');assert(f.$('#tree-workspace').classList.contains('is-root-overview'));f.click('[data-action="globalTree"][data-key="a"]');assert(!f.$('#tree-workspace').classList.contains('is-root-overview'));f.app.dispatch({type:'globalTree',key:'c'});assert(f.$('#tree-workspace').classList.contains('is-root-overview'));f.app.dispatch({type:'view',view:'catalog'});assert(!f.$('#tree-workspace').classList.contains('is-root-overview'));f.app.dispatch({type:'paper',id:'navharness'});f.app.dispatch({type:'view',view:'trees'});assert.equal(f.app.getState().paper,'navharness');assert(!f.$('#tree-workspace').classList.contains('is-root-overview'));assert.equal(f.$('#paper-panel').hidden,false);f.app.dispatch({type:'closePaper'});assert(f.$('#tree-workspace').classList.contains('is-root-overview'));});
 test('full expansion wording explicitly separates stored topology from simultaneous visibility',()=>{const m=M.fromBundle(bundle,'harnessvln');T.setMode('analysis','full');assert(UI.overviewHtml(m,M.initial(m)).includes('并非同时全部可见'));T.setMode('analysis','semantic');});
}finally{fs.rmSync(temp,{recursive:true,force:true});}
console.log(JSON.stringify({passed:count,failed:failures,realBrowser:'NOT_RUN'}));if(failures)process.exitCode=1;
