'use strict';
// Source-model, serialized SVG, and in-memory DOM contracts. Not browser QA.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),base=path.join(root,'previews/radar-c2-analysis'),w={};
for(const file of ['data/catalog.js','data/literature.js','data/challenge.js','analysis/data/bundle.js'])vm.runInNewContext(fs.readFileSync(path.join(base,file),'utf8'),{window:w});
const M=require(path.join(base,'model.js')),A=require(path.join(base,'analysis/model.js')),m=M.buildModel(w.PAPER_CATALOG,w.LITERATURE_TREE,w.CHALLENGE_TREE),a=A.build(w.C2_DATA.schema,w.C2_DATA.mapping),trees=[M.atlas.paths(m,'l'),M.atlas.paths(m,'c'),M.atlas.analysis(a)],names={l:'文献脉络',c:'挑战与思路',a:'论文解析'};let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
function rootGroup(html,t){return [...html.matchAll(/<g class="atlas-vertex [^"]*"[^>]*>[\s\S]*?<\/g>/g)].map(x=>x[0]).find(x=>x.includes('data-atlas-id="'+t.root+'"'));}
function rootContract(atlas,t,mode='semantic',width=720){const g=atlas.layout(t,{mode,width}),r=g.nodes.find(n=>n.id===t.root),h=atlas.svg(t,t.root,t.kind,{mode}),markup=rootGroup(h,t),font=mode==='full'?14:13;
 assert.equal(r.labelLines.join(''),names[t.kind]);assert(!r.labelLines.join('').includes('…'));assert.equal(r.label,names[t.kind]);
 assert(r.x>=8&&r.y>=8&&r.x+r.w<=g.width-8&&r.y+r.h<=g.height-8,'root including focus padding stays in viewport');
 for(const line of r.labelLines)assert([...line].length*font+14<=r.w,'full root text stays inside its box');
 assert(r.labelLines.length*(mode==='full'?19:18)+14<=r.h);assert(markup.includes('<rect class="atlas-label-bg"'));
 assert(markup.includes('aria-label="'+names[t.kind]+'，全树起点，'));assert(markup.includes('<title>'+names[t.kind]+'</title>'));
 assert(markup.includes('tabindex="0"'));assert(markup.includes('aria-current="true"'));assert(!/>UI<|>根<|UI 根/.test(markup));
 assert.equal([...markup.matchAll(/<text[^>]*>([^<]*)<\/text>/g)].map(x=>x[1]).join(''),names[t.kind]);
 for(const child of g.nodes.filter(n=>t.by.get(n.id).parent===t.root))assert(child.x>=r.x+r.w+16,'root label has an independent padded column');
 for(const edge of g.edges.filter(e=>e.source===t.root)){const child=g.nodes.find(n=>n.id===edge.target);assert(atlas.edge(r,child).startsWith('M'+(r.x+r.w)+','),'edge starts at the label boundary');}
 return g;
}
for(const t of trees)test(t.kind+': exact root name, padded bounds, complete text, edges and accessible focus in both modes',()=>{for(const mode of ['semantic','full'])for(const width of [220,366,560,720,1100])rootContract(M.atlas,t,mode,width);});
test('all original source labels, IDs, child order and scientific data remain untouched',()=>{const before=JSON.stringify(w);for(const t of trees){const source=t.kind==='a'?a.nodes:m.trees[t.kind].nodes;for(const n of t.nodes){if(n.sourceId){assert.equal(n.label,source.get(n.sourceId).label);assert.equal(n.sourceId,source.get(n.sourceId).id);}const snapshot=JSON.stringify(t.nodes);M.atlas.layout(t);M.atlas.svg(t);M.atlas.html(t);assert.equal(JSON.stringify(t.nodes),snapshot);}}assert.equal(JSON.stringify(w),before);});
test('negative controls reject generic visible roots, undersized boxes and ambiguous accessible labels',()=>{const source=fs.readFileSync(path.join(base,'model.js'),'utf8');const mutations=[source.replace("l:'文献脉络'","l:'UI'"),source.replace('rootWidth=90','rootWidth=18'),source.replace("+(pos.depth===0?'，全树起点':'')","+(pos.depth===0?'，UI':'')")];for(const changed of mutations){assert.notEqual(changed,source);const context={module:{exports:{}}};vm.runInNewContext(changed,context);assert.throws(()=>rootContract(context.module.exports.atlas,trees[0]));}});
test('wrap helper preserves complete long text without truncation and current root does not overlap any node',()=>{for(const t of trees){for(const mode of ['semantic','full']){const g=M.atlas.layout(t,{mode,width:560}),r=g.nodes.find(n=>n.id===t.root);for(const n of g.nodes.filter(n=>n.id!==t.root))assert(r.x+r.w<=n.x||n.x+n.w<=r.x||r.y+r.h<=n.y||n.y+n.h<=r.y);}const long='挑战与思路的完整总览名称',ls=M.atlas.lines(long,90,13);assert(ls.length>1);assert.equal(ls.join(''),long);assert(ls.every(line=>line.length*13+14<=90));}});
test('literature native group/protocol controls and C/A atlas roots preserve accessible navigation',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'rpa-root-labels-'));try{fs.cpSync(base,temp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),temp,{recursive:true});const {fixture}=require(path.join(temp,'tests/entry_dom_fixture.cjs'));for(const t of trees){const f=fixture();assert.deepEqual(f.errors,[]);f.click('#global-tab-'+t.kind);if(t.kind==='l'){const groups=f.$('#global-panel-l').querySelectorAll('.task-family');assert.equal(groups.length,3);assert.equal(f.$('#global-panel-l').getAttribute('aria-labelledby'),'global-tab-l');const seen=new Set();for(const group of M.taskMap.groups){const el=f.$('.task-family[data-id="'+group.id+'"]');assert.equal(el.tagName,'BUTTON');assert.equal(el.getAttribute('type'),'button');assert(el.textContent.includes(group.label));el.focus();el.emit('click');assert.equal(f.$('.task-family[data-id="'+group.id+'"]').getAttribute('aria-pressed'),'true');for(const id of group.sections.flatMap(s=>s.ids)){const protocol=f.$('.protocol-card[data-id="'+id+'"]');assert(protocol,id);assert.equal(protocol.tagName,'BUTTON');assert.equal(protocol.getAttribute('type'),'button');protocol.focus();protocol.emit('click');assert.equal(f.app.getState().l[0],id);assert.equal(f.$('.protocol-card[data-id="'+id+'"]').getAttribute('aria-pressed'),'true');assert.equal(f.$('#body-l').getAttribute('aria-label'),'协议条件与代表方法');assert.equal(f.$('#body-l').getAttribute('tabindex'),'0');assert(f.$('#tree-l').querySelector('.protocol-summary').querySelector('summary'));seen.add(id);}}assert.equal(seen.size,19);assert.deepEqual(f.errors,[]);continue;}const view=t.kind==='a'?'entry-a':t.kind,rootSelector='[data-atlas-view="'+view+'"][data-atlas-id="'+t.root+'"]';let el=f.$(rootSelector);assert(el,'root attached');assert(el.getAttribute('aria-label').startsWith(names[t.kind]+'，全树起点，'));el.emit('mouseover');assert.equal(f.$('[data-atlas-caption="'+view+'"]').textContent,names[t.kind]);el.emit('keydown',{key:'ArrowRight'});const child=f.document.activeElement;assert.equal(child.dataset.atlasId,t.by.get(t.root).children[0]);child.emit('keydown',{key:'Home'});assert.equal(f.document.activeElement,f.$(rootSelector));assert.equal(f.$('[data-atlas-caption="'+view+'"]').textContent,names[t.kind]);f.document.activeElement.emit('keydown',{key:'Enter'});el=f.$(rootSelector);assert.equal(el.getAttribute('tabindex'),'0');assert.equal(el.getAttribute('aria-current'),'true');assert.deepEqual(f.errors,[]);}}finally{fs.rmSync(temp,{recursive:true,force:true});}});
console.log(JSON.stringify({checks:count,kind:'deterministic root-label/SVG/in-memory DOM contracts, not browser QA'}));
