'use strict';
// Deterministic layout and negative gates; actual font/visual acceptance is separate.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),src=path.join(root,'previews/radar-c2-analysis'),F=require(path.join(src,'analysis/c2.js')).FaithfulTree,M=require(path.join(src,'model.js')),A=require(path.join(src,'analysis/model.js'));
const data=file=>{const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(src,file),'utf8'),ctx);return ctx.window;};
const model=M.buildModel(data('data/catalog.js').PAPER_CATALOG,data('data/literature.js').LITERATURE_TREE,data('data/challenge.js').CHALLENGE_TREE),d={M,A,model,bundle:data('analysis/data/bundle.js').C2_DATA};
let passed=0;const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const overlap=(a,b,pad=0)=>a.x-pad<b.x+b.w&&a.x+a.w+pad>b.x&&a.y-pad<b.y+b.h&&a.y+a.h+pad>b.y;
function points(d){let p,all=[];for(const[,op,raw]of d.matchAll(/([MHVC])([^MHVC]+)/g)){const n=raw.trim().split(/[ ,]+/).map(Number);if(op==='M')p=n;else if(op==='H')p=[n[0],p[1]];else if(op==='V')p=[p[0],n[0]];else {const a=p;for(let i=1;i<=20;i++){const t=i/20,u=1-t;all.push([u*u*u*a[0]+3*u*u*t*n[0]+3*u*t*t*n[2]+t*t*t*n[4],u*u*u*a[1]+3*u*u*t*n[1]+3*u*t*t*n[3]+t*t*t*n[5]]);}p=[n[4],n[5]];continue;}all.push(p);}return all;}
function clear(sc,padding=2){
 for(let i=0;i<sc.nodes.length;i++)for(let j=i+1;j<sc.nodes.length;j++)assert(!overlap(sc.nodes[i],sc.nodes[j]),'cards overlap '+sc.nodes[i].id+' / '+sc.nodes[j].id);
 for(const edge of sc.edges){const a=sc.by.get(edge.source),b=sc.by.get(edge.target),ps=points(F.pathD(a,b));assert.equal(b.parent,a.id,'synthetic parent');for(let i=1;i<ps.length;i++){const p=ps[i-1],q=ps[i];for(const n of sc.nodes){if(n.id===a.id||n.id===b.id)continue;const x0=n.x-padding,x1=n.x+n.w+padding,y0=n.y-padding,y1=n.y+n.h+padding;
  // Exact for orthogonal gutters; cubic segments are conservatively bounded.
  let t0=0,t1=1,dx=q[0]-p[0],dy=q[1]-p[1],hit=true;
  for(const [p0,v,min,max] of [[p[0],dx,x0,x1],[p[1],dy,y0,y1]]){if(Math.abs(v)<1e-9){if(p0<=min||p0>=max){hit=false;break;}}else {let u=(min-p0)/v,w=(max-p0)/v;if(u>w)[u,w]=[w,u];t0=Math.max(t0,u);t1=Math.min(t1,w);if(t0>=t1){hit=false;break;}}}
  assert(!hit,edge.source+' → '+edge.target+' crosses '+n.id);
 }}}
}
const sourceState=F.initial(d),navState=F.reduce(d,sourceState,{type:'mode',mode:'navigation'}),analysisState=F.reduce(d,sourceState,{type:'tab',tab:'a'});
test('complete titles keep14px typography with no clamp or flex shrink',()=>{const css=fs.readFileSync(path.join(src,'analysis/c2.css'),'utf8'),rule=css.match(/\.ft-node > span \{([^}]+)\}/)[1];assert(rule.includes('font-size:14px'));assert(rule.includes('flex-shrink:0'));assert(!/line-clamp|overflow:hidden|text-overflow:ellipsis/.test(rule));const long={id:'long',label:'General goal：在视觉与语言目标下完成可验证的具身导航，并研究支撑它的环境记忆、主动取证与任务执行。'};assert(F.nodeHeight(long,210,true)>78);assert(F.nodeHeight(long,160,true)>F.nodeHeight(long,300,true));});
test('branch counts have a separate non-shrinking visible slot',()=>{const s=F.reduce(d,navState,{type:'node',id:'nav:l'}),html=F.renderHtml(d,s,{width:1189,height:536}),css=fs.readFileSync(path.join(src,'analysis/c2.css'),'utf8');assert(html.includes('<b class="ft-node-count">− 19</b>'));assert(/\.ft-node-count \{[^}]*flex:none/.test(css));assert(/\.ft-node-role \{[^}]*min-width:0/.test(css));});
test('measured label heights override estimates at final card width',()=>{const g=F.getGraph(d,sourceState),v=F.view(d,sourceState);const sc=F.scene(g,v,false,840,(n,width,selected)=>n.id==='ex:goal'?173:78);assert.equal(sc.by.get('ex:goal').h,173);clear(sc);assert(sc.by.get('ex:goal').y>=24);});
test('variable subtree extents prevent a tall parent overlapping its siblings',()=>{const g=F.getGraph(d,sourceState),v=F.view(d,sourceState);v.expanded=g.nodes.filter(n=>n.children.length).map(n=>n.id);const sc=F.scene(g,v,false,1189,(n,w)=>n.id==='ex:l-simple'?500:F.nodeHeight(n,w));clear(sc);assert.equal(sc.by.get('ex:l-simple').h,500);});
test('all19 exact siblings keep ordering, parents and a shared explicit header gutter',()=>{const s=F.reduce(d,navState,{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s),siblings=g.by.get('nav:l').children;for(const width of [620,684,840,1088,1189]){const sc=F.scene(g,v,false,width),peers=sc.nodes.filter(n=>n.gridParent);assert.deepEqual(peers.map(n=>n.id),siblings);assert(peers.every(n=>n.parent==='nav:l'&&n.gridLane===250&&n.gridHeader===8&&n.columnLane===n.x-12));assert.equal(peers.length,19);clear(sc);}const sc=F.scene(g,v,false,1189),cam=F.readableCamera(g,v,sc,1189,536);assert(cam.k>=1);for(const n of sc.nodes)assert(n.y*cam.k+cam.y+n.h*cam.k<=536&&n.x*cam.k+cam.x+n.w*cam.k<=1189);});
test('expanded deep original navigation and analysis trees have clear true-depth narrow gutters',()=>{for(const state of [sourceState,navState,analysisState]){const g=F.getGraph(d,state),v=F.view(d,state);v.expanded=g.nodes.filter(n=>n.children.length).map(n=>n.id);for(const width of [280,320,390,500,619]){const sc=F.scene(g,v,false,width);assert.equal(sc.nodes.length,g.nodes.length);clear(sc);for(const n of sc.nodes)assert(n.h>=F.nodeHeight(n,n.w,n.id===v.selected));}}});
test('row heights follow their tallest measured label instead of fixed94px increments',()=>{const s=F.reduce(d,navState,{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s),first=g.by.get('nav:l').children[0],sc=F.scene(g,v,false,1189,n=>n.id===first?220:78),peers=sc.nodes.filter(n=>n.gridParent);assert.equal(peers[4].y,peers[0].y+220+16);clear(sc);});
test('negative controls reject shortened heights, fixed narrow rows and synthetic parents',()=>{const s=F.reduce(d,navState,{type:'node',id:'nav:l'}),g=F.getGraph(d,s),v=F.view(d,s),sc=F.scene(g,v,false,1189,n=>n.id===g.by.get('nav:l').children[0]?220:78);const bad=sc.nodes.filter(n=>n.gridParent);bad[4].y=bad[0].y+94;assert.throws(()=>clear(sc),/overlap|crosses/);const g2=F.getGraph(d,sourceState),v2=F.view(d,sourceState);v2.expanded=g2.nodes.filter(n=>n.children.length).map(n=>n.id);const nsc=F.scene(g2,v2,false,320);nsc.nodes.forEach((n,i)=>n.y=24+i*86);assert.throws(()=>clear(nsc),/overlap|crosses/);const c=F.scene(g,v,false,1189);c.by.get(g.by.get('nav:l').children[0]).parent='invented-grid-parent';assert.throws(()=>clear(c),/synthetic parent/);});
test('highlighted original ancestry paths are painted after background paths',()=>{const s=F.reduce(d,navState,{type:'node',id:'nav:l'}),html=F.renderHtml(d,s,{width:1189,height:536}),matches=[...html.matchAll(/<path class="([^"]*)" data-ft-source=/g)].map(m=>m[1]);let active=false;for(const name of matches){if(name==='ft-active-edge')active=true;else assert(!active);}assert(active);});
console.log(JSON.stringify({passed,browser:'NOT_RUN'}));
