'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom'),root=path.resolve(__dirname,'..');
const out=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();p.write_preview(r,r/'dist');print('done')"],{cwd:root,encoding:'utf8'});
const html=fs.readFileSync(path.join(root,'dist/research/navigation/index.html'),'utf8'),wait=ms=>new Promise(r=>setTimeout(r,ms));
async function page(options={}){
 const calls=[],external=[],errors=[];class Resources extends ResourceLoader{fetch(url){external.push(url);const p=new Promise(()=>{});p.abort=()=>{};return p;}}
 const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const d=new JSDOM(options.html||html,{url:'https://example.org/research/navigation/'+(options.hash||''),runScripts:'dangerously',resources:new Resources(),pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.scrollTo=(x,y)=>Object.defineProperty(w,'scrollY',{value:y,configurable:true});w.HTMLElement.prototype.scrollIntoView=function(){};
  const timer=w.setTimeout.bind(w);w.setTimeout=(fn,ms,...args)=>timer(fn,ms===30000||ms===20000?250:ms,...args);
  Object.defineProperty(w.crypto,'subtle',{value:{digest:(...args)=>options.hashPending?new Promise(()=>{}):crypto.webcrypto.subtle.digest(...args)}});
  w.fetch=url=>{calls.push(url);if(options.fetch)return options.fetch(url,w,calls.length);if(options.offline)return new Promise(()=>{});const p=path.join(root,'dist/research/navigation',url);return Promise.resolve({ok:fs.existsSync(p),status:404,arrayBuffer:async()=>fs.readFileSync(p)});};
  if(options.saved)w.history.replaceState(options.saved,'',w.location.href);
 }});
 for(let i=0;i<100&&d.window.document.querySelector('main').dataset.loadState==='loading';i++)await wait(20);if(d.window.document.querySelector('main').dataset.loadState==='ready')await new Promise(resolve=>d.window.requestAnimationFrame(()=>d.window.requestAnimationFrame(resolve)));return {d,w:d.window,calls,external,errors};
}
function pick(w,paper,scope='task:category-objectnav',kind='pipeline_recipe'){const b=w.NavigationProductApp.getBundle(),p=Object.values(b.positions).find(p=>p.paperId===paper&&p.scopeId===scope&&p.kind===kind);assert.ok(p);w.NavigationProductApp.navigate(w.NavigationProductModel.routeForPosition(b,{scope},p.id));return p;}
async function loaded(x){for(let i=0;i<30&&x.w.document.querySelector('#np-detail-content .np-content-pending');i++)await wait(20);}
test('current production boots real global trees with all external requests permanently unavailable',async t=>{const x=await page({offline:true});t.after(()=>x.w.close());assert.equal(x.w.document.querySelector('main').dataset.loadState,'ready');assert.equal(x.calls.length,0);assert.equal(x.external.length,0);assert.ok(x.w.document.querySelectorAll('#np-tree [role=treeitem]').length>1);const rootNode=x.w.document.querySelector('#np-tree [role=treeitem]');rootNode.querySelector('.np-node-toggle').click();assert.equal(x.w.document.querySelectorAll('#np-tree [role=treeitem]').length,1);rootNode.querySelector('.np-node-toggle').click();assert.deepEqual(x.errors,[]);});
test('disabled JavaScript preserves actual native hierarchy and explicit fixed-version analysis',()=>{const d=new JSDOM(html);try{const doc=d.window.document;assert.equal(doc.querySelectorAll('[data-native-position]').length,123);assert.equal(doc.querySelectorAll('[data-native-tree="l"]').length,33);assert.equal(doc.querySelectorAll('[data-native-tree="c"]').length,31);assert.equal(doc.querySelectorAll('[data-original-node]').length,59);assert.equal(doc.querySelectorAll('[data-native-answer="answered"]').length,22);assert.equal(doc.querySelector('.np-native-analysis-choice').open,false);assert.match(doc.querySelector('#np-native-reading').textContent,/ObjectNav/);}finally{d.window.close();}});
test('only selected body packet is requested and a pending body never blocks task or tree changes',async t=>{const x=await page({offline:true});t.after(()=>x.w.close());pick(x.w,'poni');await wait(30);assert.equal(x.calls.length,1);assert.match(x.calls[0],/^content\/[a-f0-9]{64}\.json$/);assert.match(x.w.document.querySelector('#np-detail-content').textContent,/按需加载/);x.w.NavigationProductApp.navigate({scope:'task:goat',tree:'l'});assert.equal(x.w.NavigationProductApp.getState().route.scope,'task:goat');assert.ok(x.w.document.querySelectorAll('#np-tree [role=treeitem]').length);assert.equal(x.w.document.querySelector('main').dataset.loadState,'ready');assert.ok(!x.calls.some(u=>u.includes('product-data')));});
test('exact packet renders PONI source and keeps canonical claim and version identity',async t=>{const x=await page();t.after(()=>x.w.close());const p=pick(x.w,'poni');await loaded(x);assert.match(x.w.document.querySelector('#np-detail-content').textContent,/方法如何运行/);assert.equal(x.w.NavigationProductApp.getState().route.version,p.versionId);const claim=x.w.document.querySelector('#np-detail-content [data-claim-id]');assert.ok(claim);x.w.NavigationProductApp.navigate({...x.w.NavigationProductApp.getState().route,claim:claim.dataset.claimId});assert.equal(x.w.document.querySelector('#np-detail-content .np-evidence').open,true);});
test('late verified PONI response cannot replace a later SemExp node or scroll',async t=>{let release;const x=await page({fetch:(url,w,n)=>{const raw=fs.readFileSync(path.join(root,'dist/research/navigation',url));return Promise.resolve({ok:true,arrayBuffer:()=>n===1?new Promise(r=>release=()=>r(raw)):Promise.resolve(raw)});}});t.after(()=>x.w.close());pick(x.w,'poni');await wait(20);const p=pick(x.w,'semexp');await loaded(x);x.w.document.querySelector('#np-detail-scroll').scrollTop=321;const before=JSON.stringify(x.w.NavigationProductApp.getState());release();await wait(80);assert.equal(JSON.stringify(x.w.NavigationProductApp.getState()),before);assert.equal(x.w.NavigationProductApp.getState().route.node,p.id);assert.equal(x.w.document.querySelector('#np-detail-scroll').scrollTop,321);});
test('wrong body bytes fail locally while the real tree remains usable and retry stays bounded',async t=>{const x=await page({fetch:()=>Promise.resolve({ok:true,arrayBuffer:async()=>Buffer.from('{}')})});t.after(()=>x.w.close());pick(x.w,'vlfm');await wait(50);assert.equal(x.w.document.querySelector('main').dataset.loadState,'ready');assert.equal(x.w.document.querySelector('#np-detail-content .np-content-pending').dataset.contentState,'failed');for(let i=0;i<2;i++){[...x.w.document.querySelectorAll('#np-detail-content button')].find(b=>b.textContent==='重试此节点正文').click();await wait(30);}assert.equal(x.calls.length,3);assert.ok(![...x.w.document.querySelectorAll('#np-detail-content button')].some(b=>b.textContent==='重试此节点正文'));});
test('index hash stall preserves native trees and reports exact phase without private context',async t=>{const x=await page({hashPending:true});t.after(()=>x.w.close());await wait(300);assert.equal(x.w.document.querySelector('main').dataset.loadState,'failed');assert.equal(x.w.document.querySelector('#np-static-reading').hidden,false);const diagnostic=JSON.parse(x.w.document.querySelector('#np-load-diagnostic').textContent);assert.equal(diagnostic.phase,'index_hash');assert.ok(diagnostic.receivedBytes>0);assert.ok(diagnostic.elapsedMs>=250);assert.equal(diagnostic.attempt,1);assert.doesNotMatch(JSON.stringify(diagnostic),/example\.org|scope|paper|history|userAgent/);});
test('missing inline index fails closed with native tree available rather than fetching the full model',async t=>{const modified=html.replace(/<script type="application\/json" id="np-navigation-index">[\s\S]*?<\/script>/,'');const x=await page({html:modified});t.after(()=>x.w.close());assert.equal(x.w.NavigationProductApp,undefined);assert.equal(x.calls.length,0);assert.equal(x.w.document.querySelector('#np-static-reading').hidden,false);assert.match(x.w.document.querySelector('#np-load-message').textContent,/索引缺失/);});
test('unread explicit paper version retains a complete zero-answer reference while packets are offline',async t=>{const x=await page({offline:true});t.after(()=>x.w.close());const b=x.w.NavigationProductApp.getBundle(),version=Object.values(b.versions).find(v=>v.paperId==='harnessvln'&&/2609\.15195v1/.test(v.id));assert.ok(version);x.w.NavigationProductApp.navigate({scope:'task:vln-ce',tree:'a',paper:'harnessvln',version:version.id,template:'1'});assert.equal(x.w.NavigationProductApp.getState().route.version,version.id);assert.match(x.w.document.querySelector('#np-tree-caption').textContent,/0答案/);assert.equal(x.w.NavigationProductModel.descendants(b,b.template.roots).length,59);assert.ok(!x.w.document.querySelector('#np-detail-content [data-claim-id]'));});
// Packet failures must be atomic even if a test deliberately re-pins the mutated bytes.
const vm=require('node:vm'),indexText=html.match(/<script type="application\/json" id="np-navigation-index">([\s\S]*?)<\/script>/)[1],originalIndex=JSON.parse(indexText),owner=Object.keys(originalIndex.delivery.packets).find(id=>originalIndex.entities[id].paperId==='poni'&&originalIndex.entities[id].kind==='pipeline_recipe'),packetBytes=fs.readFileSync(path.join(root,'dist/research/navigation/content',originalIndex.delivery.packets[owner].sha256+'.json')),packetValue=JSON.parse(packetBytes),contentCode=fs.readFileSync(path.join(root,'assets/navigation-content.js'),'utf8');
function packetRuntime(mutate,repin,transport){const bundle=JSON.parse(indexText),packet=JSON.parse(packetBytes);if(mutate)mutate(packet);const bytes=Buffer.from(JSON.stringify(packet));if(repin){bundle.delivery.packets[owner].sha256=crypto.createHash('sha256').update(bytes).digest('hex');bundle.delivery.packets[owner].bytes=bytes.length;}const w={crypto:crypto.webcrypto,AbortController,fetch:transport||(()=>Promise.resolve({ok:true,arrayBuffer:async()=>bytes}))};vm.runInNewContext(contentCode,{window:w,TextDecoder,Uint8Array,setTimeout:(fn,ms)=>setTimeout(fn,ms===20000?100:ms),clearTimeout});return {bundle,content:w.NavigationContent.create(bundle)};}
for(const [name,mutate,repin] of [
 ['wrong SHA',p=>p.entities[owner].detail.pipeline.decision+=' changed',false],
 ['wrong source model',p=>p.sourceModelSha256='0'.repeat(64),true],
 ['wrong owner',p=>p.ownerId='task:pointnav',true],
 ['wrong paper',p=>p.entities[owner].paperId='semexp',true],
 ['wrong version',p=>p.entities[owner].versionIds=['unknown-version'],true],
 ['missing declared claim',p=>delete p.claims[Object.keys(p.claims)[0]],true],
 ['extra entity',p=>p.entities.extra={id:'extra'},true]
])test('atomic content validation rejects '+name,async()=>{const x=packetRuntime(mutate,repin),before=JSON.stringify({entities:x.bundle.entities,claims:x.bundle.claims});await assert.rejects(x.content.request(owner));assert.equal(x.content.status(owner),'failed');assert.equal(JSON.stringify({entities:x.bundle.entities,claims:x.bundle.claims}),before);});
test('a timed-out body reports its phase and late bytes cannot mutate a successful retry',async()=>{let release,calls=0;const x=packetRuntime(null,false,()=>Promise.resolve({ok:true,arrayBuffer:()=>++calls===1?new Promise(r=>release=r):Promise.resolve(packetBytes)}));await assert.rejects(x.content.request(owner),/超时/);const diagnostic=x.content.diagnostics(owner);assert.equal(diagnostic.phase,'body');assert.equal(diagnostic.receivedBytes,0);assert.equal(diagnostic.expectedBytes,packetBytes.length);await x.content.request(owner,true);const stable=JSON.stringify(x.bundle);release(packetBytes);await wait(30);assert.equal(JSON.stringify(x.bundle),stable);assert.equal(x.content.status(owner),'ready');assert.equal(x.content.attempts(owner),2);});
test('a successful packet is exact original data, not a summarized replacement',async()=>{const x=packetRuntime();await x.content.request(owner);assert.deepEqual(JSON.parse(JSON.stringify(x.bundle.entities[owner])),packetValue.entities[owner]);});
for(const mode of ['missing','syntax'])test('inline app '+mode+' keeps precise module phase on manual retry',async t=>{const modified=html.replace(/<script data-navigation-module="module_app">[\s\S]*?<\/script>/,mode==='missing'?'':'<script data-navigation-module="module_app">not valid javascript ]</script>'),x=await page({html:modified});t.after(()=>x.w.close());assert.equal(x.w.document.querySelector('main').dataset.loadState,'failed');assert.equal(x.w.NavigationProductLoader.diagnostics().phase,'module_app');x.w.document.querySelector('#np-retry').click();assert.equal(x.w.document.querySelector('main').dataset.loadState,'failed');assert.equal(x.w.NavigationProductLoader.diagnostics().phase,'module_app');assert.match(x.w.document.querySelector('#np-load-message').textContent,/刷新/);assert.equal(x.w.document.querySelectorAll('[data-native-position]').length,123);const n=x.w.document.querySelector('.np-native-node');n.querySelector('summary').click();assert.equal(n.open,false);});
test('actual deepest native hierarchy retains a readable 329px mobile text budget',()=>{const d=new JSDOM(html),w=d.window;try{const mobile=[];for(const sheet of [...w.document.styleSheets])for(const rule of [...sheet.cssRules])if(rule.type===4){const q=rule.conditionText,max=q.match(/max-width:\s*(\d+)px/),min=q.match(/min-width:\s*(\d+)px/);if((max||min)&&(!max||329<=Number(max[1]))&&(!min||329>=Number(min[1])))mobile.push(...[...rule.cssRules].map(r=>r.cssText));}const style=w.document.createElement('style');style.textContent=mobile.join('\n');w.document.head.appendChild(style);const px=v=>v.endsWith('rem')?parseFloat(v)*16:parseFloat(v)||0;let deepest=0,minimum=Infinity;for(const node of w.document.querySelectorAll('.np-native-node>summary')){let width=329,depth=0;for(let at=node.parentElement;at&&at!==w.document.body;at=at.parentElement){const s=w.getComputedStyle(at);width-=px(s.paddingLeft)+px(s.paddingRight)+px(s.borderLeftWidth)+px(s.borderRightWidth);if(at.classList.contains('np-native-node'))depth++;}deepest=Math.max(deepest,depth);minimum=Math.min(minimum,width-16);}assert.ok(deepest>=6);assert.ok(minimum>=220,'deepest native label budget including marker: '+minimum);}finally{w.close();}});
