'use strict';
const fs=require('fs'),assert=require('assert'),path=require('path');
const source=path.join(__dirname,'../previews/radar-trees-c');
const G=require(path.join(source,'graph.js')),data=JSON.parse(fs.readFileSync(path.join(source,'data/graph-data.json'),'utf8'));
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const fresh=()=>{const s=G.initialState();s.selected={kind:'paper',canonical:'navharness'};s.expandedChallenges.add('navharness');return s;}; // Explicit focused fixture for the existing selection regressions.
test('public graph contract: unique data-derived baseline, candidate snapshot, zero academic edges',()=>{assert(data.tasks.length>0);assert(data.routes.length>0);assert(data.papers.length>0);assert.equal(new Set(data.papers.map(p=>p.canonical_id)).size,data.papers.length);assert.equal(data.candidates.length,6);assert.deepEqual(data.academic_edges,[]);assert.equal(data.public_only,true);});
test('periods stay separate: today 0; previous weekly 238 / 11 / 6 / 5',()=>{assert.equal(data.daily.date,'2026-10-05');assert.equal(data.daily.candidate_count,0);assert.equal(data.weekly.date,'2026-10-04');assert.equal(data.weekly.candidate_count,238);assert.equal(data.weekly.abstract_count,11);assert.equal(data.weekly.mapping_ids.length,6);assert.equal(data.weekly.unmapped_abstracts.length,5);});
test('explicitly selected scene is graphical and contains all task / route main branches',()=>{const s=G.buildScene(data,fresh());assert.equal(s.nodes.filter(n=>n.kind==='task').length,data.tasks.length);assert.equal(s.nodes.filter(n=>n.kind==='route').length,data.routes.length);assert(s.nodes.some(n=>n.kind==='insight'));assert(s.nodes.some(n=>n.kind==='evidence'));assert(s.edges.some(e=>e.cross&&e.active));assert(s.nodes.some(n=>n.dim));});
test('explicit selection shows one canonical NavHarness with multiple route memberships',()=>{const s=G.buildScene(data,fresh());assert.equal(s.nodes.filter(n=>n.kind==='paper'&&n.canonical==='navharness').length,1);assert(s.nodes.some(n=>n.id==='challenge-memory-validity-navharness'&&n.active));});
test('all visible edge endpoints exist and all bridges are same paper',()=>{for(const mode of ['baseline','weekly']){const state=fresh();state.mode=mode;const s=G.buildScene(data,state);const nodes=Object.fromEntries(s.nodes.map(n=>[n.id,n]));assert.equal(Object.keys(nodes).length,s.nodes.length);s.edges.forEach(e=>{assert(nodes[e.source]);assert(nodes[e.target]);assert.equal(e.attribution,'curator_organization');if(e.cross){assert.equal(nodes[e.source].canonical,nodes[e.target].canonical);assert.equal(e.same_paper,nodes[e.source].canonical);}});}});
test('synthetic multi-group paper keeps proxy IDs unique and every same-paper bridge',()=>{const modified=JSON.parse(JSON.stringify(data));modified.papers.find(p=>p.canonical_id==='navharness').groups.push('evidence-and-action');const state=fresh();const scene=G.buildScene(modified,state);assert.equal(new Set(scene.nodes.map(n=>n.id)).size,scene.nodes.length);const challenges=scene.nodes.filter(n=>n.kind==='challenge'&&n.canonical==='navharness');assert.equal(challenges.length,2);const papers=scene.nodes.filter(n=>n.kind==='paper'&&n.canonical==='navharness');const bridges=scene.edges.filter(e=>e.same_paper==='navharness');assert.equal(bridges.length,challenges.length*papers.length);assert(bridges.every(e=>challenges.some(n=>n.id===e.target)));});
test('all baseline identities reachable through progressive route expansion',()=>{const state=fresh();data.routes.forEach(r=>state.expandedRoutes.add(r.id));data.groups.forEach(g=>state.expandedGroups.add(g.id));const s=G.buildScene(data,state);assert.equal(s.uniqueVisible,data.papers.length);assert.equal(new Set(s.nodes.filter(n=>n.kind==='challenge').map(n=>n.canonical)).size,data.papers.length);});
test('weekly mode reaches exactly 6 candidate identities, not entire pool',()=>{const state=fresh();state.mode='weekly';data.routes.forEach(r=>state.expandedRoutes.add(r.id));const s=G.buildScene(data,state);assert.equal(s.uniqueVisible,6);assert(s.nodes.filter(n=>n.kind==='paper').every(n=>n.candidate));assert(!s.nodes.some(n=>n.kind==='paper'&&n.paper.read_scope==='section'));});
test('two NavHarness papers remain distinct canonical IDs',()=>{const both=data.candidates.filter(p=>p.short_name.startsWith('NavHarness'));assert.equal(both.length,2);assert.notEqual(both[0].canonical_id,both[1].canonical_id);assert.equal(both.find(p=>p.existing_paper_id).canonical_id,'navharness');});
test('candidate source URLs pinned; all scope flags stay false',()=>{data.candidates.forEach(p=>{assert(p.source_url.endsWith(p.versioned_id));assert.equal(p.full_paper_read,false);assert.equal(p.version_comparison_performed,false);assert.equal(p.experiments_independently_verified,false);});data.papers.forEach(p=>{const u=new URL(p.source_url);assert.equal(u.protocol,'https:');if(u.hostname==='arxiv.org')assert(/v\d+(?:#.*)?$/.test(p.source_url));else{assert(['aclanthology.org','proceedings.mlr.press','proceedings.iclr.cc','www.ecva.net','openaccess.thecvf.com','roboticsproceedings.org'].includes(u.hostname));assert(u.pathname.endsWith('.pdf'));assert(p.source_provenance?.read_version);}});});
test('partial placement is visually encoded; proposals do not become graph branches',()=>{const state=fresh();state.mode='weekly';data.routes.forEach(r=>state.expandedRoutes.add(r.id));const s=G.buildScene(data,state);assert(s.edges.some(e=>e.partial));const branches=s.nodes.filter(n=>n.kind==='route'||n.kind==='task');assert.equal(branches.length,data.tasks.length+data.routes.length);assert(!branches.some(n=>n.label.includes('研究空白')));});
test('search matches paper content and no-result is explicit',()=>{const state=fresh();state.search='NavHarness';assert(G.filteredPapers(data,state).some(p=>p.canonical_id==='navharness'));assert(G.filteredPapers(data,state).every(p=>[p.short_name,p.title,p.challenge,p.insight,p.overview_zh,p.abstract_summary_zh,p.harness_relation?.basis].join(' ').toLowerCase().includes('navharness')));state.search='unlikely-no-paper-xyz';assert(G.buildScene(data,state).empty);});
test('task filtering preserves actual paper task membership',()=>{const state=fresh();state.task='task-continual';const s=G.buildScene(data,state);assert(s.papers.every(p=>p.tasks.includes('task-continual')));assert.equal(s.nodes.filter(n=>n.kind==='task').length,1);});
test('click route expands and collapses repeatedly; challenge does likewise',()=>{const state=fresh(),node={kind:'route',id:'route-runtime'};G.applyAction(state,{type:'toggle',node});assert(state.expandedRoutes.has(node.id));G.applyAction(state,{type:'toggle',node});assert(!state.expandedRoutes.has(node.id));const ch={kind:'challenge',canonical:'navharness'};G.applyAction(state,{type:'toggle',node:ch});assert(!state.expandedChallenges.has('navharness'));G.applyAction(state,{type:'toggle',node:ch});assert(state.expandedChallenges.has('navharness'));});
test('zoom clamps at 65–400%; mode clears stale search and expansion',()=>{const state=fresh();G.applyAction(state,{type:'zoom',value:99});assert.equal(state.zoom,4);G.applyAction(state,{type:'zoom',value:0});assert.equal(state.zoom,.65);state.search='test';state.expandedRoutes.add('route-context');G.applyAction(state,{type:'mode',mode:'weekly'});assert.equal(state.search,'');assert.equal(state.expandedRoutes.size,0);assert.equal(state.selected,null);});
test('fit geometry contains default, weekly and expanded scenes in desktop/mobile viewports',()=>{for(const mode of ['baseline','weekly']){for(const expanded of [false,true]){const state=fresh();state.mode=mode;if(expanded){data.routes.forEach(r=>state.expandedRoutes.add(r.id));data.groups.forEach(g=>state.expandedGroups.add(g.id));G.activePapers(data,state).forEach(p=>state.expandedChallenges.add(p.canonical_id));}const scene=G.buildScene(data,state);for(const [w,h] of [[1334,535],[1050,510],[390,450]]){const zoom=G.computeFitZoom(w,h,scene.width,scene.height),renderedWidth=w*zoom,renderedHeight=renderedWidth*scene.height/scene.width;assert(renderedWidth<=w+.001);assert(renderedHeight<=h+.001);assert(scene.nodes.every(n=>n.y+n.h<=scene.height));}}}});
test('focus off leaves nodes undimmed without changing underlying graph',()=>{const state=fresh();state.focus=false;const s=G.buildScene(data,state);assert(!s.nodes.some(n=>n.dim));assert(s.edges.some(e=>e.active));});
// Minimal in-memory DOM contract; deliberately not a browser or rendering test.
class Element {
 constructor(tag,doc){this.tagName=tag;this.doc=doc;this.children=[];this.attrs={};this.dataset={};this.style={};this.events={};this.hidden=false;this.value='';this.innerHTML='';this.textContent='';this.scrollTop=0;this.scrollLeft=0;}
 setAttribute(k,v){this.attrs[k]=String(v);if(k==='id'){this.id=v;this.doc.ids[v]=this;}if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}
 getAttribute(k){return this.attrs[k];} appendChild(c){this.children.push(c);c.parent=this;return c;} removeChild(c){this.children.splice(this.children.indexOf(c),1);} get lastChild(){return this.children.at(-1)||null;} addEventListener(k,fn){(this.events[k]??=[]).push(fn);} fire(k,event={}){this.events[k]?.forEach(fn=>fn({target:this,preventDefault(){},...event}));} focus(){this.doc.focused=this;} scrollIntoView(){this.scrolled=true;}
}
function fakeDocument(){const doc={ids:{},createElementNS(ns,t){return new Element(t,this);},createElement(t){return new Element(t,this);},getElementById(id){return this.ids[id];},querySelectorAll(selector){if(selector==='[data-mode]')return [this.ids['mode-baseline'],this.ids['mode-weekly']];if(selector==='[data-tab]')return ['overview','evidence','conditions'].map(x=>this.ids['tab-'+x]);return [];}};const html=fs.readFileSync(path.join(source,'index.html'),'utf8');for(const match of html.matchAll(/<([\w-]+)\b[^>]*\bid="([^"]+)"[^>]*>/g)){const el=new Element(match[1],doc);el.setAttribute('id',match[2]);for(const a of match[0].matchAll(/(data-[\w-]+)="([^"]*)"/g))el.setAttribute(a[1],a[2]);}return doc;}
function mountFocused(doc,data){const app=G.mount(doc,data);app.selectPaper('navharness');return app;}
const doc=fakeDocument(),app=mountFocused(doc,data),$=id=>doc.getElementById(id);
test('mounted explicit selection has real SVG nodes, canonical IDs, accessible controls',()=>{assert.equal($('research-graph').getAttribute('viewBox').split(' ')[2],'1280');assert.equal($('node-task-vln').getAttribute('role'),'button');assert.equal($('expand-challenge-memory-validity-navharness').getAttribute('aria-expanded'),'true');assert($('selection-summary').innerHTML.includes('统一论文 ID：navharness'));});
test('mounted click & repeated click really expand / collapse route DOM',()=>{$('expand-route-runtime').fire('click');assert(app.getState().expandedRoutes.has('route-runtime'));assert.equal($('expand-route-runtime').getAttribute('aria-expanded'),'true');$('expand-route-runtime').fire('click');assert(!app.getState().expandedRoutes.has('route-runtime'));});
test('mounted keyboard works for node expansion and evidence tab',()=>{$('expand-challenge-memory-validity-navharness').fire('keydown',{key:'Enter'});assert.equal($('expand-challenge-memory-validity-navharness').getAttribute('aria-expanded'),'false');$('expand-challenge-memory-validity-navharness').fire('keydown',{key:' '});$('node-evidence-memory-validity-navharness').fire('click');assert.equal(app.getState().tab,'evidence');assert($('detail-content').innerHTML.includes('§3.3–3.5'));$('tab-evidence').fire('keydown',{key:'ArrowRight'});assert.equal(app.getState().tab,'conditions');});
test('weekly toggle resets cleanly and never inherits baseline body evidence',()=>{$('mode-weekly').fire('click');assert.equal(app.getState().mode,'weekly');assert.equal(app.getState().selected,null);app.selectPaper('navharness');assert($('selection-summary').innerHTML.includes(data.weekly.date+' 周窗'));assert($('detail-content').innerHTML.includes('本轮未读全文'));$('tab-evidence').fire('click');assert($('detail-content').innerHTML.includes('Abstract'));assert(!$('detail-content').innerHTML.includes('§3.3–3.5'));assert($('detail-content').innerHTML.includes('2609.34276v1'));});
test('weekly partial fit and conditions are displayed on selected candidate',()=>{app.selectPaper('arxiv:2609.39166');$('tab-evidence').fire('click');assert($('detail-content').innerHTML.includes('部分贴合'));$('tab-conditions').fire('click');assert($('detail-content').innerHTML.includes('未创建'));assert($('detail-content').innerHTML.includes('非研究空白'));});
test('mounted search, Escape reset, no-result, task filter and clear filter',()=>{$('graph-search').value='unlikely-no-paper-xyz';$('graph-search').fire('input');assert.equal($('graph-empty').hidden,false);$('graph-search').fire('keydown',{key:'Escape'});assert.equal($('graph-empty').hidden,true);$('task-filter').value='task-vln';$('task-filter').fire('change');assert(app.getScene().papers.every(p=>p.tasks.includes('task-vln')));$('clear-filters').fire('click');assert.equal(app.getState().task,'all');});
test('mounted focus toggle, zoom, fit, reset, scope and clear controls',()=>{$('focus-path').checked=false;$('focus-path').fire('change');assert(!app.getScene().nodes.some(n=>n.dim));$('zoom-in').fire('click');assert.equal(app.getState().zoom,1.15);$('zoom-fit').fire('click');assert.equal(app.getState().zoom,1);$('scope-details').fire('click');assert.equal($('scope-notes').open,true);$('clear-selection').fire('click');assert.equal(app.getState().selected,null);$('graph-reset').fire('click');assert.equal(app.getState().mode,'weekly');assert.equal(app.getState().selected,null);assert.equal(app.getState().focus,true);});
test('mounted fit preserves readable scale and resets both scroll axes',()=>{const viewport=$('graph-viewport');viewport.clientWidth=1334;viewport.clientHeight=535;viewport.scrollTop=75;viewport.scrollLeft=40;$('zoom-fit').fire('click');const expected=Math.max(G.computeFitZoom(1334,535,1280,app.getScene().height),1280*.95/1334);assert.equal(app.getState().zoom,expected);assert.equal($('research-graph').style.minWidth,'0');assert.equal(viewport.scrollLeft,0);assert.equal(viewport.scrollTop,0);$('mode-baseline').fire('click');assert.equal(app.getState().zoom,Math.max(G.computeFitZoom(1334,535,1280,app.getScene().height),1280*.95/1334));});
test('search excluding selected NavHarness clears selection and stale sidebar',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id);e('graph-search').value='HarnessVLN';e('graph-search').fire('input');assert.equal(a.getState().selected,null);assert.deepEqual(a.getScene().papers.map(p=>p.canonical_id),['harnessvln']);assert(!e('selection-summary').innerHTML.includes('NavHarness'));assert(!e('detail-content').innerHTML.includes('§3.3–3.5'));assert(e('detail-content').innerHTML.includes('筛选变更已清除原选中论文'));assert.equal(e('detail-tabs').hidden,true);a.selectPaper('harnessvln');assert.equal(a.getState().selected.canonical,'harnessvln');assert.equal(a.getState().selectionNotice,'');});
test('task filter excluding selected NavHarness clears selection; retained matching selection stays valid',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id);e('task-filter').value='task-continual';e('task-filter').fire('change');assert.equal(a.getState().selected.canonical,'navharness');assert.equal(a.getState().selectionNotice,'');e('task-filter').value='task-vln';e('task-filter').fire('change');assert.equal(a.getState().selected,null);assert(!e('selection-summary').innerHTML.includes('NavHarness'));assert(e('detail-content').innerHTML.includes('选择已随筛选更新'));assert(a.getScene().papers.every(p=>p.tasks.includes('task-vln')));e('clear-filters').fire('click');assert.equal(a.getState().selected,null);assert.equal(a.getState().task,'all');});
test('mobile fit/reset preserves readable 13.3px text and zoom still reaches native SVG scale',()=>{for(const width of [720,360]){const d=fakeDocument(),e=id=>d.getElementById(id);e('graph-viewport').clientWidth=width;e('graph-viewport').clientHeight=450;const a=mountFocused(d,data);assert.equal(a.getState().zoom,Math.max(G.computeFitZoom(width,450,1280,a.getScene().height),1280*.95/width));assert.equal(e('zoom-in').disabled,false);let steps=0;while(!e('zoom-in').disabled&&steps++<40)e('zoom-in').fire('click');assert.equal(a.getState().zoom,4);assert.equal(e('zoom-in').disabled,true);assert(width*a.getState().zoom>=1280);assert(14*(width*a.getState().zoom/1280)>=14);e('zoom-out').fire('click');assert.equal(a.getState().zoom,3.85);assert.equal(e('zoom-in').disabled,false);e('zoom-fit').fire('click');assert(width*a.getState().zoom>=1280*.95-.001);e('zoom-in').fire('click');e('graph-reset').fire('click');assert.equal(a.getState().zoom,Math.max(G.computeFitZoom(width,450,1280,a.getScene().height),1280*.95/width));assert.equal(a.getState().selected,null);assert.equal(e('zoom-in').disabled,false);}});
test('source data loads without fetch and relative text routes match integration',()=>{const js=fs.readFileSync(path.join(source,'graph.js'),'utf8'),html=fs.readFileSync(path.join(source,'index.html'),'utf8');assert(!/\bfetch\s*\(/.test(js));assert(html.includes('data/graph-data.js'));assert(html.includes('href="literature.html"'));assert(html.includes('href="challenge.html"'));assert(html.includes('href="weekly-2026-10-04.html"'));assert(!html.includes('../literature.html'));assert(html.includes('<noscript>'));});

test('view card does not toggle expansion; explicit control toggles repeatedly',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id);e('node-route-runtime').fire('click');assert(!a.getState().expandedRoutes.has('route-runtime'));assert.equal(e('node-route-runtime').getAttribute('aria-expanded'),undefined);e('expand-route-runtime').fire('click');assert(a.getState().expandedRoutes.has('route-runtime'));assert.equal(a.getState().selected.kind,'route');e('node-route-runtime').fire('click');assert(a.getState().expandedRoutes.has('route-runtime'));e('expand-route-runtime').fire('click');assert(!a.getState().expandedRoutes.has('route-runtime'));});
test('AgenticNav has one canonical node, two incoming routes, correct memberships and readable reveal',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id);e('graph-viewport').clientWidth=820;e('graph-viewport').clientHeight=510;e('expand-route-runtime').fire('click');const id='paper-agenticnav-tool-harness';e('node-'+id).fire('click');const scene=a.getScene(),cards=scene.nodes.filter(n=>n.canonical==='agenticnav-tool-harness'&&n.kind==='paper');assert.equal(cards.length,1);assert.equal(cards[0].routeCount,2);assert.equal(cards.filter(n=>n.selected).length,1);assert.equal(scene.edges.filter(x=>x.target===id&&x.source.startsWith('route-')).length,2);assert.equal(a.getState().selected.id,id);assert(e('selection-summary').innerHTML.includes('所属路线（2）：运行与反馈闭环 / 上下文分配'));assert.equal(e('detail-title').textContent,'选中论文');assert(e('current-path').textContent.includes('AgenticNav · 论文；所属路线：运行与反馈闭环 / 上下文分配'));assert(e('visible-count').textContent.includes('篇独立论文'));assert(e('visible-count').textContent.includes('次论文与路线归属'));assert.equal(e('graph-viewport').scrollTop,0);e('locate-selection').fire('click');assert(e('graph-viewport').scrollTop>0);const scale=820*a.getState().zoom/1280,targets=scene.nodes.filter(n=>n.canonical==='agenticnav-tool-harness'&&['challenge','insight','evidence'].includes(n.kind));assert(Math.max(...targets.map(n=>(n.y+n.h)*scale))<=e('graph-viewport').scrollTop+510);e('graph-viewport').scrollTop=0;e('locate-selection').fire('click');assert(e('graph-viewport').scrollTop>0);a.getState().zoom=4;e('locate-selection').fire('click');assert(a.getState().zoom<4);assert(820*a.getState().zoom/1280>=.95);e('clear-selection').fire('click');assert.equal(e('locate-selection').disabled,true);});
test('selected problem card opens detail without hiding insight; expansion remains explicit',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id),id='challenge-memory-validity-navharness';e('node-'+id).fire('click');assert(a.getState().expandedChallenges.has('navharness'));assert.equal(e('detail-title').textContent,'选中本文问题');e('expand-'+id).fire('click');assert(!a.getState().expandedChallenges.has('navharness'));});
test('context text is not faded and controls have visible verb labels',()=>{const css=fs.readFileSync(path.join(source,'graph.css'),'utf8'),html=fs.readFileSync(path.join(source,'index.html'),'utf8');assert(css.includes('.graph-node.dim{opacity:1}'));assert(!css.includes('.graph-node.dim{opacity:.25}'));assert(html.includes('定位选中'));assert(html.includes('点卡片查看'));});
test('Escape restores graph keyboard focus after redraw',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id),id='node-paper-navharness';e('graph-viewport').fire('keydown',{key:'Escape',target:e(id)});assert.equal(a.getState().selected,null);assert.equal(d.focused,e(id));});
test('all mode/filter/search/expansion combinations keep canonical papers unique and applicable route edges complete',()=>{for(const mode of ['baseline','weekly'])for(const task of ['all',...data.tasks.map(t=>t.id)])for(const search of ['', 'NavHarness', 'AgenticNav', 'no-match-xyz'])for(const expanded of [false,true]){const state=fresh();Object.assign(state,{mode,task,search});if(expanded)data.routes.forEach(r=>state.expandedRoutes.add(r.id));G.reconcileSelection(data,state);const scene=G.buildScene(data,state),papers=scene.nodes.filter(n=>n.kind==='paper'),routes=scene.nodes.filter(n=>n.kind==='route');assert.equal(new Set(papers.map(n=>n.canonical)).size,papers.length);assert.equal(scene.uniqueVisible,papers.length);for(const n of papers){assert.equal(n.id,'paper-'+n.canonical);const expected=routes.filter(r=>n.paper.routes.includes(r.id)).map(r=>r.id).sort();assert.deepEqual(scene.edges.filter(e=>e.target===n.id&&!e.cross).map(e=>e.source).sort(),expected);assert.deepEqual(n.routeIds.slice().sort(),expected);}assert.equal(scene.routeLinks,scene.edges.filter(e=>e.source.startsWith('route-')&&e.target.startsWith('paper-')).length);}});
test('multi-task memberships survive filtering and route expansion without duplicate cards',()=>{const p=data.papers.find(p=>p.tasks.length>1&&p.routes.length>1);assert(p);for(const task of p.tasks){const state=fresh();state.task=task;state.selected={kind:'paper',canonical:p.canonical_id};const scene=G.buildScene(data,state);assert.equal(scene.nodes.filter(n=>n.kind==='paper'&&n.canonical===p.canonical_id).length,1);assert(scene.nodes.some(n=>n.kind==='task'&&n.id===task));assert(scene.papers.every(n=>n.tasks.includes(task)));}});
test('repeated expansion/collapse keeps one selected AgenticNav with two incoming routes',()=>{const state=fresh();state.selected={kind:'paper',canonical:'agenticnav-tool-harness'};for(let i=0;i<6;i++){G.applyAction(state,{type:'toggle',node:{kind:'route',id:'route-runtime'}});G.applyAction(state,{type:'select',node:{kind:'paper',id:'paper-agenticnav-tool-harness',canonical:'agenticnav-tool-harness'}});const scene=G.buildScene(data,state);assert.equal(scene.nodes.filter(n=>n.kind==='paper'&&n.canonical==='agenticnav-tool-harness').length,1);assert.equal(scene.edges.filter(e=>e.target==='paper-agenticnav-tool-harness').length,2);}});
test('aggregated paper cards do not overlap when all routes expand',()=>{for(const mode of ['baseline','weekly']){const state=fresh();state.mode=mode;data.routes.forEach(r=>state.expandedRoutes.add(r.id));const scene=G.buildScene(data,state),nodes=scene.nodes.filter(n=>n.kind==='paper').sort((a,b)=>a.y-b.y);nodes.slice(1).forEach((n,i)=>assert(n.y>=nodes[i].y+nodes[i].h+12));assert(nodes.every(n=>n.y+n.h<=scene.height));}});


test('expansion controls preserve selected paper and evidence tab',()=>{const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id);a.selectPaper('agenticnav-tool-harness');e('tab-evidence').fire('click');const selected=JSON.stringify(a.getState().selected);e('expand-route-runtime').fire('click');assert.equal(JSON.stringify(a.getState().selected),selected);assert.equal(a.getState().tab,'evidence');assert(e('detail-title').textContent==='选中论文');e('expand-challenge-context-allocation-agenticnav-tool-harness').fire('click');assert.equal(JSON.stringify(a.getState().selected),selected);assert.equal(a.getState().tab,'evidence');});


test('collapsing selected child returns details to its parent and keeps collapse-button focus',()=>{for(const kind of ['insight','evidence']){const d=fakeDocument(),a=mountFocused(d,data),e=id=>d.getElementById(id),group='memory-validity-navharness';e('node-'+kind+'-'+group).fire('click');assert.equal(a.getState().selected.kind,kind);e('expand-challenge-'+group).fire('keydown',{key:'Enter'});assert.equal(a.getState().selected.kind,'challenge');assert.equal(a.getState().selected.id,'challenge-'+group);assert.equal(a.getState().tab,'overview');assert.equal(e('detail-title').textContent,'选中本文问题');assert.equal(d.focused,e('expand-challenge-'+group));assert(!a.getScene().nodes.some(n=>n.kind===kind&&n.canonical==='navharness'));e('expand-challenge-'+group).fire('click');assert.equal(a.getState().selected.kind,'challenge');}});


test('entry is an unselected overview with readable context and representative mode explained',()=>{const state=G.initialState(),scene=G.buildScene(data,state);assert.equal(state.selected,null);assert.equal(state.context,null);assert.equal(state.expandedChallenges.size,0);assert(!scene.nodes.some(n=>n.dim||n.selected));assert(scene.uniqueVisible<scene.papers.length);const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);assert.equal(e('detail-title').textContent,'研究总览');assert(e('selection-summary').innerHTML.includes('从一个方向开始'));assert(e('coverage-note').textContent.includes('因折叠暂未显示'));assert.equal(e('locate-selection').disabled,true);assert.equal(e('back-to-direction').hidden,true);});
test('total / matched / visible counts are unique canonical counts derived from the actual data',()=>{for(const mode of ['baseline','weekly']){const state=G.initialState();state.mode=mode;const scene=G.buildScene(data,state),c=G.coverageCounts(data,state,scene);assert.equal(c.total,new Set(G.activePapers(data,state).map(p=>p.canonical_id)).size);assert.equal(c.matched,scene.papers.length);assert.equal(c.visible,scene.nodes.filter(n=>n.kind==='paper').length);assert.equal(c.collapsed,c.matched-c.visible);assert.equal(c.excluded,0);assert.equal(scene.methodRoutes,scene.nodes.filter(n=>n.kind==='route').length);}});
test('hidden representatives remain collected and expansion never changes source records',()=>{const original=JSON.stringify(data),state=G.initialState(),before=G.coverageCounts(data,state,G.buildScene(data,state));G.applyAction(state,{type:'showAll',data});const after=G.coverageCounts(data,state,G.buildScene(data,state));assert.equal(after.total,before.total);assert.equal(after.matched,before.matched);assert.equal(after.visible,after.matched);assert.equal(after.collapsed,0);G.applyAction(state,{type:'collapse'});assert.deepEqual(G.coverageCounts(data,state,G.buildScene(data,state)),before);assert.equal(JSON.stringify(data),original);});
test('filtering and collapsing affect distinct counts',()=>{const state=G.initialState();state.task='task-vln';const c=G.coverageCounts(data,state,G.buildScene(data,state));assert(c.excluded>0);G.applyAction(state,{type:'showAll',data});const expanded=G.coverageCounts(data,state,G.buildScene(data,state));assert.equal(expanded.excluded,c.excluded);assert.equal(expanded.total,c.total);assert.equal(expanded.matched,c.matched);assert.equal(expanded.visible,expanded.matched);G.applyAction(state,{type:'clearFilters'});const cleared=G.coverageCounts(data,state,G.buildScene(data,state));assert.equal(cleared.excluded,0);assert.equal(cleared.matched,cleared.total);assert.equal(cleared.visible,cleared.total);});
test('show all repeated clicks and collapse repeated clicks are idempotent and preserve selected evidence',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);a.selectPaper('agenticnav-tool-harness');e('tab-evidence').fire('click');const sel=JSON.stringify(a.getState().selected);for(let i=0;i<3;i++)e('show-all-papers').fire('click');assert.equal(a.getScene().uniqueVisible,a.getScene().papers.length);for(let i=0;i<3;i++)e('collapse-papers').fire('click');assert.equal(JSON.stringify(a.getState().selected),sel);assert.equal(a.getState().tab,'evidence');assert.equal(a.getScene().nodes.filter(n=>n.kind==='paper'&&n.canonical==='agenticnav-tool-harness').length,1);assert(e('coverage-note').textContent.includes('仍在本范围收录'));});
test('repeated selection preserves the same evidence tab and does not toggle expansion',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);a.selectPaper('navharness');e('tab-evidence').fire('click');const routes=[...a.getState().expandedRoutes];for(let i=0;i<3;i++)e('node-paper-navharness').fire('click');assert.equal(a.getState().tab,'evidence');assert.deepEqual([...a.getState().expandedRoutes],routes);assert(e('detail-content').innerHTML.includes('指定原文证据'));});
test('direction → paper → evidence → return restores the chosen direction with context',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('node-route-runtime').fire('click');a.selectPaper('agenticnav-tool-harness');assert.equal(a.getState().context.id,'route-runtime');assert.equal(e('back-to-direction').hidden,false);e('tab-evidence').fire('click');e('back-to-direction').fire('click');assert.equal(a.getState().selected.kind,'route');assert.equal(a.getState().selected.id,'route-runtime');assert.equal(a.getState().tab,'overview');assert(e('detail-content').innerHTML.includes('当前范围内的论文'));assert.equal(d.focused,e('node-route-runtime'));});
test('one-click overview resets filters, branches and selection while preserving chosen data range',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('mode-weekly').fire('click');a.selectPaper('navharness');e('show-all-papers').fire('click');e('graph-search').value='NavHarness';e('graph-search').fire('input');e('tab-evidence').fire('click');e('return-overview').fire('click');const s=a.getState();assert.equal(s.mode,'weekly');assert.equal(s.search,'');assert.equal(s.task,'all');assert.equal(s.selected,null);assert.equal(s.context,null);assert.equal(s.expandedRoutes.size,0);assert.equal(s.expandedGroups.size,0);assert.equal(s.expandedChallenges.size,0);assert.equal(e('detail-title').textContent,'研究总览');e('return-overview').fire('click');assert.equal(a.getState().selected,null);});
test('clear filters is independent from overview and retains valid selected paper / evidence / branches',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('show-all-papers').fire('click');a.selectPaper('navharness');e('graph-search').value='NavHarness';e('graph-search').fire('input');e('tab-evidence').fire('click');e('clear-filters-toolbar').fire('click');assert.equal(a.getState().selected.canonical,'navharness');assert.equal(a.getState().tab,'evidence');assert.equal(a.getState().expandedRoutes.size,data.routes.length);assert.equal(e('clear-filters-toolbar').disabled,true);assert.equal(a.getScene().papers.length,data.papers.length);});
test('empty result retains total count, shows zero matched / visible and offers clear filters',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('graph-search').value='no-match-xyz';e('graph-search').fire('input');assert.equal(e('count-total').textContent,data.papers.length+' 篇');assert.equal(e('count-matched').textContent,'0 篇');assert.equal(e('count-visible').textContent,'0 篇');assert.equal(e('show-all-papers').disabled,true);assert.equal(e('clear-filters-toolbar').disabled,false);e('clear-filters').fire('click');assert.equal(a.getScene().papers.length,data.papers.length);assert.equal(a.getState().selected,null);});
test('overview direction buttons open complete filtered paper list without expanding the canvas',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);const target={closest:selector=>selector==='[data-direction-id]'?{dataset:{directionId:'route-runtime'}}:null};e('detail-content').fire('click',{target});assert.equal(a.getState().selected.id,'route-runtime');assert.equal(a.getState().expandedRoutes.size,0);const ids=[...e('detail-content').innerHTML.matchAll(/data-paper-id="([^"]+)"/g)].map(x=>x[1]);assert.deepEqual(ids,data.papers.filter(p=>p.routes.includes('route-runtime')).map(p=>p.canonical_id));});
test('route expansion controls sit below labels, keep independent accessible roles and show visible / matched counts',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);for(const n of a.getScene().nodes.filter(n=>['route','group'].includes(n.kind)&&n.canExpand)){const button=e('expand-'+n.id);assert.equal(button.getAttribute('role'),'button');assert.equal(button.getAttribute('transform'),`translate(${n.x+n.w-68} ${n.y+n.h-30})`);assert(button.getAttribute('aria-label').includes('当前显示'));assert(n.h-30>62);assert(!e('node-'+n.id).getAttribute('aria-expanded'));}});
test('choosing a paper preserves the canvas position; locating and opening details are explicit',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id),v=e('graph-viewport');v.clientWidth=820;v.clientHeight=510;v.scrollLeft=30;v.scrollTop=1000;a.selectPaper('agenticnav-tool-harness');assert.equal(v.scrollLeft,30);assert.equal(v.scrollTop,1000);e('node-paper-agenticnav-tool-harness').fire('click');assert.equal(v.scrollLeft,30);assert.equal(v.scrollTop,1000);e('locate-selection').fire('click');assert(v.scrollTop<1000);e('show-details').fire('click');assert(e('detail-panel').scrolled);assert.equal(d.focused,e('detail-content'));});
test('clicking already-active mode does not reset search, evidence, zoom or scroll',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);a.selectPaper('navharness');e('graph-search').value='NavHarness';e('graph-search').fire('input');e('tab-evidence').fire('click');a.getState().zoom=2;e('graph-viewport').scrollTop=120;e('mode-baseline').fire('click');assert.equal(a.getState().selected.canonical,'navharness');assert.equal(a.getState().search,'NavHarness');assert.equal(a.getState().tab,'evidence');assert.equal(a.getState().zoom,2);assert.equal(e('graph-viewport').scrollTop,120);});
test('new canonical paper and new task are supported without hardcoded counts or branch limits',()=>{const d=JSON.parse(JSON.stringify(data)),p={...d.papers[0],canonical_id:'synthetic-distinct-paper',paper_id:'synthetic-distinct-paper',tasks:['task-synthetic']};d.tasks.push({id:'task-synthetic',label:'新增任务',subtitle:'测试',full_label:'测试任务'});d.task_routes.push({source:'task-synthetic',target:p.routes[0]});d.papers.push(p);const state=G.initialState();G.applyAction(state,{type:'showAll',data:d});const scene=G.buildScene(d,state);assert.equal(G.coverageCounts(d,state,scene).total,data.papers.length+1);assert.equal(scene.uniqueVisible,d.papers.length);assert(scene.nodes.some(n=>n.id==='task-synthetic'));state.task='task-synthetic';assert.deepEqual(G.filteredPapers(d,state).map(p=>p.canonical_id),['synthetic-distinct-paper']);});
test('reading scope uses explicit source fields and never assumes all baseline records are body-read',()=>{assert.equal(G.readingScope({read_scope:'section'}),'指定正文段落');assert.equal(G.readingScope({read_scope:'abstract'}),'完整摘要');assert.equal(G.readingScope({source_scope:'primary_complete_abstract'}),'完整摘要');assert.equal(G.readingScope({read_scope:'metadata'}),'书目线索');assert.equal(G.readingScope({}),'证据范围待说明');const d=JSON.parse(JSON.stringify(data));d.papers[0].read_scope='metadata';const state=G.initialState(),scene=G.buildScene(d,state);assert(scene.nodes.find(n=>n.canonical===d.papers[0].canonical_id&&n.kind==='paper').subtitle.includes('书目线索'));});
test('count labels, return and clear affordances are visible native buttons outside the canvas',()=>{const html=fs.readFileSync(path.join(source,'index.html'),'utf8'),js=fs.readFileSync(path.join(source,'graph.js'),'utf8');for(const text of ['本范围总收录','当前筛选匹配','左树可见论文','回到总览','清除筛选'])assert(html.includes(text));for(const id of ['show-all-papers','return-overview','clear-filters-toolbar'])assert(new RegExp('<button[^>]+id="'+id+'"').test(html));assert(!/\b(?:10|28|50)\s*篇/.test(js));});


test('every actual baseline and weekly record opens all three detail tabs without undefined fields or scope promotion',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);for(const mode of ['baseline','weekly']){e('mode-'+mode).fire('click');for(const paper of G.activePapers(data,a.getState())){a.selectPaper(paper.canonical_id);for(const tab of ['overview','evidence','conditions']){e('tab-'+tab).fire('click');assert(!e('detail-content').innerHTML.includes('undefined'),paper.canonical_id+' '+tab);assert(e('detail-content').innerHTML.includes('https://'),paper.canonical_id+' source link');}e('tab-overview').fire('click');if(paper.abstract_summary_zh){assert(e('detail-content').innerHTML.includes('摘要中文概述'));assert(e('detail-content').innerHTML.includes('编辑归纳'));}assert(!e('selection-summary').innerHTML.includes('全文精读'));}}});
test('combined-scope unique count is explicit in scope notes without summing duplicate papers',()=>{const d=fakeDocument();G.mount(d,data);const count=new Set([...data.papers,...data.candidates].map(p=>p.canonical_id)).size;assert(d.getElementById('scope-note-content').innerHTML.includes('按论文 ID 去重共 '+count+' 篇'));assert(d.getElementById('scope-note-content').innerHTML.includes('两个数量不能直接相加'));});

test('section-based research overview is distinct from complete-abstract summary in details',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);for(const p of data.papers.filter(p=>p.overview_zh)){a.selectPaper(p.canonical_id);e('tab-overview').fire('click');assert(e('detail-content').innerHTML.includes('研究概述'));assert(e('detail-content').innerHTML.includes('不是完整摘要或全文翻译'));assert(!e('detail-content').innerHTML.includes('摘要中文概述'));}});
test('Chinese overview and abstract-summary vocabulary are searchable without inventing source claims',()=>{const d=JSON.parse(JSON.stringify(data));d.papers[0].overview_zh='专用概述检索词甲';d.papers[1].abstract_summary_zh='专用摘要检索词乙';for(const [term,p] of [['专用概述检索词甲',d.papers[0]],['专用摘要检索词乙',d.papers[1]]]){const state=G.initialState();state.search=term;assert.deepEqual(G.filteredPapers(d,state).map(x=>x.canonical_id),[p.canonical_id]);}});
test('zero matching papers means zero matching routes while retained structure is explicit',()=>{const state=G.initialState();state.search='nonexistent-special-paper';const scene=G.buildScene(data,state);assert.equal(scene.methodRoutes,0);assert.equal(scene.structuralRoutes,scene.nodes.filter(n=>n.kind==='route').length);const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('graph-search').value=state.search;e('graph-search').fire('input');assert(e('visible-count').textContent.includes('0 条有匹配论文的方法路线'));assert(e('visible-count').textContent.includes('主干 '+scene.structuralRoutes));});

test('details direction and paper buttons retain keyboard focus without moving the canvas',()=>{const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id),v=e('graph-viewport');v.scrollTop=123;v.scrollLeft=17;const direction={closest:s=>s==='[data-direction-id]'?{dataset:{directionId:'route-runtime'}}:null};e('detail-content').fire('click',{target:direction});assert.equal(d.focused,e('detail-content'));assert.equal(a.getState().selected.id,'route-runtime');const paper={closest:s=>s==='[data-paper-id]'?{dataset:{paperId:'harnessvln'}}:null};e('detail-content').fire('click',{target:paper});assert.equal(d.focused,e('detail-content'));assert.equal(a.getState().selected.canonical,'harnessvln');assert.equal(v.scrollTop,123);assert.equal(v.scrollLeft,17);});

test('left paper visibility and all-tree identity coverage stay distinct when only the right tree expands',()=>{for(const mode of ['baseline','weekly']){const state=G.initialState();state.mode=mode;const before=G.buildScene(data,state);assert.equal(before.allTreeUniqueVisible,new Set(before.nodes.filter(n=>n.canonical).map(n=>n.canonical)).size);data.groups.forEach(g=>state.expandedGroups.add(g.id));const after=G.buildScene(data,state);assert.equal(after.uniqueVisible,before.uniqueVisible);assert.equal(after.allTreeUniqueVisible,new Set(after.nodes.filter(n=>n.canonical).map(n=>n.canonical)).size);assert(after.allTreeUniqueVisible>=before.allTreeUniqueVisible);assert.equal(after.allTreeUniqueVisible,G.filteredPapers(data,state).length);const c=G.coverageCounts(data,state,after);assert.equal(c.visible,after.uniqueVisible);assert.equal(c.acrossTrees,after.allTreeUniqueVisible);assert.equal(c.collapsed,c.matched-after.uniqueVisible);}const d=fakeDocument(),a=G.mount(d,data),e=id=>d.getElementById(id);e('mode-weekly').fire('click');assert(a.getScene().allTreeUniqueVisible>a.getScene().uniqueVisible);assert(e('visible-count').textContent.includes('左树 '+a.getScene().uniqueVisible));assert(e('visible-count').textContent.includes('全图涉及 '+a.getScene().allTreeUniqueVisible));assert(e('coverage-note').textContent.includes('左树因折叠'));});

test('historical daily and weekly dates are labeled snapshots rather than today',()=>{const d=fakeDocument();G.mount(d,data);for(const id of ['period-counts','scope-note-content']){const text=d.getElementById(id).textContent+d.getElementById(id).innerHTML;assert(text.includes('日报快照 '+data.daily.date));assert(text.includes('周窗快照 '+data.weekly.date));assert(!text.includes('今日 '+data.daily.date));}});

const report={checks:count,status:'passed',coverage:'Pure graph/data model and in-memory DOM contracts only. No browser, server, screenshots or visual acceptance.',baseline_visible_nodes:G.buildScene(data,fresh()).nodes.length,baseline_core_papers:data.papers.length,candidate_count:data.candidates.length,academic_edges:data.academic_edges.length};

console.log(`\n${count} checks passed. Not browser-rendered or visually accepted.`);
