'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const js=fs.readFileSync(__dirname+'/../assets/reader-v2.js','utf8');
let focused=null;
function el(){return{listeners:{},attrs:{},hidden:false,isConnected:true,textContent:'',classList:{v:new Set(),add(x){this.v.add(x)},remove(x){this.v.delete(x)},contains(x){return this.v.has(x)},toggle(x,on){if(on===undefined)on=!this.v.has(x);on?this.v.add(x):this.v.delete(x);return on}},addEventListener(k,f){this.listeners[k]=f},setAttribute(k,v){this.attrs[k]=v},removeAttribute(k){delete this.attrs[k]},focus(){focused=this},emit(k,e={}){return this.listeners[k]?.(e)}}}
let tops=[160,600,1100];const sections=tops.map((_,i)=>({...el(),id:'section-'+i,getBoundingClientRect(){return{top:tops[i]}}}));const tocLinks=sections.map(s=>({...el(),hash:'#'+s.id})),toc={...el(),contains:target=>tocLinks.includes(target),querySelectorAll:()=>tocLinks,querySelector:()=>tocLinks.find(l=>l.classList.contains('is-current'))},tocButton=el(),toast=el();
const copyButtons=[el(),el()],focusButtons=[el(),el()],holders=copyButtons.map((button,i)=>({...el(),querySelectorAll:()=>[{textContent:'    def f():'},{textContent:'        return "x"'}],querySelector:s=>s==='pre'?{clientHeight:300,scrollTo(opts){holders[i].scrolled=opts}}:{offsetTop:230}}));copyButtons.forEach((b,i)=>b.closest=()=>holders[i]);focusButtons.forEach((b,i)=>b.closest=()=>holders[i]);
const page={querySelector:s=>s==='.reader-toc'?toc:s==='.reader-toc-toggle'?tocButton:null,querySelectorAll:s=>s.includes('section')?sections:s==='[data-copy-code]'?copyButtons:focusButtons};
const document={...el(),hidden:false,dialogOpen:false,querySelector(s){return s==='.reader-page'?page:s==='.reader-toast'?toast:this.dialogOpen?{}:null},getElementById:id=>sections.find(s=>s.id===id)};
const media={reduced:false,mobile:false};function matchMedia(q){return{get matches(){return q.includes('reduce')?media.reduced:media.mobile}}}
const raf=new Map(),timers=new Map();let seq=0;const pending=[];const navigator={clipboard:{writeText(text){return new Promise((resolve,reject)=>pending.push({text,resolve,reject}))}}};
const window={...el()};const context={document,window,navigator,matchMedia,requestAnimationFrame:f=>{raf.set(++seq,f);return seq},cancelAnimationFrame:id=>raf.delete(id),setTimeout:f=>{timers.set(++seq,f);return seq},clearTimeout:id=>timers.delete(id),CSS:{escape:x=>x},innerWidth:1200,console};vm.runInNewContext(js,context);
assert(tocLinks[0].classList.contains('is-current'));tops=[-900,130,900];window.emit('scroll');assert.equal(raf.size,1);window.emit('scroll');assert.equal(raf.size,1);for(const f of raf.values())f();raf.clear();assert(tocLinks[1].classList.contains('is-current'));
tocButton.emit('click');assert.equal(tocButton.attrs['aria-expanded'],'true');assert.equal(focused,tocLinks[1]);let prevented=false;document.emit('keydown',{key:'Escape',preventDefault(){prevented=true}});assert(prevented);assert.equal(focused,tocButton);assert.equal(tocButton.attrs['aria-expanded'],'false');
tocButton.emit('click');media.mobile=true;tocLinks[2].emit('click');assert.equal(focused,sections[2]);assert(!toc.classList.contains('is-open'));
tocButton.emit('click');document.dialogOpen=true;document.emit('keydown',{key:'Escape',preventDefault(){throw Error('Must not intercept higher dialog')}});assert(toc.classList.contains('is-open'));document.dialogOpen=false;
document.emit('focusin',{target:tocLinks[2]});assert(toc.classList.contains('is-open'));document.emit('focusin',{target:tocButton});assert(toc.classList.contains('is-open'));const outside=copyButtons[0];focused=outside;document.emit('focusin',{target:outside});assert(!toc.classList.contains('is-open'));assert.equal(focused,outside,'outside keyboard focus remains on uncovered control');assert.equal(tocButton.attrs['aria-expanded'],'false');tocButton.emit('click');document.emit('keydown',{key:'Escape',preventDefault(){}});assert.equal(focused,tocButton);
for(let i=0;i<40;i++)focusButtons[0].emit('click');assert.equal(focusButtons[0].attrs['aria-pressed'],'false');media.reduced=true;focusButtons[0].emit('click');assert.equal(holders[0].scrolled.behavior,'auto');assert.equal(holders[0].scrolled.top,130);
window.emit('scroll');document.hidden=true;document.emit('visibilitychange');assert.equal(raf.size,0);document.hidden=false;document.emit('visibilitychange');assert.equal(raf.size,1);
(async()=>{const first=copyButtons[0].emit('click'),second=copyButtons[0].emit('click');assert.equal(pending[0].text,'    def f():\n        return "x"');pending[1].resolve();await second;assert.equal(toast.textContent,'代码片段已复制，未包含行号');pending[0].reject();await first;assert.equal(toast.textContent,'代码片段已复制，未包含行号','stale failure cannot replace latest success');const denied=copyButtons[1].emit('click');pending[2].reject();await denied;assert(toast.textContent.includes('手动选择复制'));assert.equal(timers.size,1);for(const f of timers.values())f();assert(toast.hidden);console.log('PASS reader controls: active TOC, coalesced scroll, mobile focus/close, topmost-dialog Escape, interrupted key-line focus, reduced motion, clipboard exactness/failure and stale-promise protection. DOM model.');})().catch(e=>{console.error(e);process.exitCode=1});
