'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const {JSDOM,VirtualConsole}=require('jsdom'),root=path.resolve(__dirname,'..');
const html=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;r=Path('.').resolve();print(p.render(r,p.payloads(r)[1]))"],{cwd:root,encoding:'utf8',maxBuffer:20e6});
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function page(width=1440){const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));const d=new JSDOM(html,{url:'https://example.org/research/navigation/',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.innerWidth=width;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;Object.defineProperty(w.crypto,'subtle',{value:crypto.webcrypto.subtle});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};w.fetch=()=>new Promise(()=>{});}});for(let i=0;i<100&&!d.window.NavigationProductApp;i++)await wait(15);assert.ok(d.window.NavigationProductApp);await frames(d.window);const home=d.window.document.querySelector('#np-reading-landing');if(home&&!home.hidden){d.window.document.querySelector('#np-overview-toggle').click();await frames(d.window);}return {d,w:d.window,doc:d.window.document,errors};}
async function frames(w){await new Promise(r=>w.requestAnimationFrame(()=>w.requestAnimationFrame(r)));}
function box(row){return {x:parseFloat(row.style.left),y:parseFloat(row.style.top),w:parseFloat(row.style.width),h:parseFloat(row.style.height)};}
function overlap(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;}
test('explicit original spatial map retains every concrete task and direct challenge, separate from the new reading overview',async t=>{const x=await page();t.after(()=>x.w.close());const a=x.w.NavigationProductApp,b=a.getBundle(),d=x.doc,rootId=b.researchMap.roots[0],heads=b.positions[rootId].childIds,lit=heads.find(id=>b.positions[id].entityId==='legacy:nav:l'),ci=heads.find(id=>b.positions[id].entityId==='legacy:nav:c'),task=b.positions[lit].childIds.find(id=>b.positions[id].sourceDirectoryGroupId==='task');assert.equal(b.positions[task].childIds.length,22);assert.equal(b.positions[ci].childIds.length,13);for(const id of [rootId,...heads,...b.positions[lit].childIds,...b.positions[task].childIds,...b.positions[ci].childIds]){const row=d.getElementById('np-node-'+id)?.querySelector(':scope > .np-node-row');assert.ok(row,id);assert.ok(parseFloat(row.style.width)>190,id);assert.ok(row.querySelector('.np-node-label').getAttribute('aria-label').startsWith(row.querySelector('.np-node-label').textContent));}assert.equal(d.querySelectorAll('#np-tree [role=treeitem]').length,45);assert.equal(a.getState().contexts[x.w.NavigationProductModel.contextKey(a.getState().route)].graphScale,1,'default never silently shrinks the labels');assert.deepEqual(x.errors,[]);});
test('explicit original desktop map adapts its geometry to both target widths without shrinking or overlapping scientific labels',async t=>{for(const width of [1440,1920]){const x=await page(width);t.after(()=>x.w.close());const d=x.doc,rows=[...d.querySelectorAll('#np-tree .np-node-row')],boxes=rows.map(box),tree=d.querySelector('#np-tree'),available=width-62-24;assert.equal(Number(tree.dataset.canvasWidth),available);for(let i=0;i<boxes.length;i++){assert.ok(boxes[i].x>=0&&boxes[i].x+boxes[i].w<=available,rows[i].textContent);for(let j=i+1;j<boxes.length;j++)assert.equal(overlap(boxes[i],boxes[j]),false,rows[i].textContent+' / '+rows[j].textContent);}assert.equal(tree.style.getPropertyValue('--np-label-size'),'15px');for(const row of rows){const label=row.querySelector('.np-node-label'),style=x.w.getComputedStyle(label);assert.equal(style.whiteSpace,'normal');assert.equal(style.overflow,'visible');assert.equal(style.maxHeight,'none');}assert.equal(d.querySelectorAll('#np-tree .np-task-definition').length,22,'all definitions retained in source, not printed across the graph');assert.equal(x.w.getComputedStyle(d.querySelector('#np-tree .np-task-definition')).display,'none');}});
test('every rendered edge is an actual unchanged parent relation and every node exposes its true child count',async t=>{const x=await page();t.after(()=>x.w.close());const b=x.w.NavigationProductApp.getBundle(),d=x.doc;for(const path of d.querySelectorAll('.np-graph-edges path')){const child=b.positions[path.dataset.child];assert.equal(child.parentId,path.dataset.parent);assert.equal(child.relationType||'',path.dataset.relationType);assert.ok(d.getElementById('np-node-'+path.dataset.parent));}for(const item of d.querySelectorAll('#np-tree [role=treeitem]')){const count=item.querySelector(':scope > .np-node-row .np-child-count'),expected=b.positions[item.dataset.position].childIds.length;assert.equal(count?Number(count.textContent):0,expected);}assert.equal(d.querySelectorAll('.np-graph-edges path').length,44);});
test('fit has a readable floor, supports all tree types, and pointer pan does not navigate or alter evidence identity',async t=>{const x=await page();t.after(()=>x.w.close());const d=x.doc,w=x.w,a=w.NavigationProductApp,M=w.NavigationProductModel,view=d.querySelector('#np-tree-scroll'),before=JSON.stringify(a.getState().route);Object.defineProperty(view,'clientWidth',{value:400});Object.defineProperty(view,'clientHeight',{value:300});d.querySelector('#np-zoom-fit').click();assert.equal(M.getBucket(a.getState()).graphScale,.9);assert.match(d.querySelector('#np-status').textContent,/90%/);view.dispatchEvent(new w.MouseEvent('pointerdown',{bubbles:true,button:0,clientX:250,clientY:200}));view.dispatchEvent(new w.MouseEvent('pointermove',{bubbles:true,clientX:150,clientY:150}));view.dispatchEvent(new w.MouseEvent('pointerup',{bubbles:true,clientX:150,clientY:150}));assert.equal(view.scrollLeft,100);assert.equal(view.scrollTop,50);assert.equal(JSON.stringify(a.getState().route),before);assert.equal(M.getBucket(a.getState()).treeScrollLeftByTree.g,100);assert.equal(view.classList.contains('np-panning'),false);});
test('focused paper has an independent reader and accurate return path; outline preserves exact visible identities',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),M=w.NavigationProductModel,p=Object.values(b.positions).find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='vlfm'&&p.kind==='pipeline_recipe');a.navigate(M.routeForPosition(b,{scope:p.scopeId},p.id),{cross:true});await frames(w);assert.ok(d.querySelector('.np-reading-pane .np-method-mechanism'));assert.equal(d.querySelector('#np-tree .np-method-mechanism'),null);assert.match(d.querySelector('#np-global-context').textContent,/General goal/);const rows=()=>[...d.querySelectorAll('#np-tree [role=treeitem]')].map(n=>n.dataset.position),before=rows();d.querySelector('#np-layout-toggle').click();assert.deepEqual(rows(),before);assert.equal(d.querySelector('.np-graph-edges'),null);assert.equal(d.querySelector('#np-tree').style.width,'');d.querySelector('#np-layout-toggle').click();assert.deepEqual(rows(),before);assert.equal(a.getState().route.version,p.versionId);assert.deepEqual(x.errors,[]);});

test('history capture is bound to the actual independently scrolling reader, not its non-scrolling evidence body',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),p=Object.values(b.positions).find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='poni'&&p.kind==='pipeline_recipe');a.navigate(M.routeForPosition(b,{scope:p.scopeId},p.id),{cross:true});await frames(w);const reader=d.querySelector('.np-reading-pane');assert.equal(reader.id,'np-detail-scroll');assert.notEqual(reader,d.querySelector('.np-detail-scroll'));reader.scrollTop=420;w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,420);d.querySelector('[data-tree-tab=g]').click();await frames(w);assert.equal(reader.scrollTop,0);w.history.back();await frames(w);assert.equal(a.getState().route.node,p.id);assert.equal(reader.scrollTop,420);});

test('expanding a closed overview task moves to its real focus instead of an offscreen extension lane, with an exact return',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),initial=a.getState().route,task=Object.values(b.researchMap.positions).find(p=>p.sourceScopeId==='task:pointnav'&&p.sourceRootPositionIds);const start=[...d.querySelectorAll('#np-tree [role=treeitem]')].map(n=>n.dataset.position);d.getElementById('np-node-'+task.id).querySelector('.np-node-toggle').click();await frames(w);assert.equal(a.getState().route.node,task.id);assert.equal(d.querySelector('#np-tree').dataset.graphLayout,'focus');for(const id of task.childIds)assert.ok(d.getElementById('np-node-'+id));assert.ok(a.getState().originTrail.some(x=>x.route.node===initial.node));d.querySelector('[data-tree-tab=g]').click();await frames(w);assert.equal(a.getState().route.node,initial.node);assert.deepEqual([...d.querySelectorAll('#np-tree [role=treeitem]')].map(n=>n.dataset.position),start);});
test('zoom preserves the exact focused control and reading DOM instead of rebuilding the tree',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),p=Object.values(b.researchMap.positions).find(p=>p.sourceScopeId==='task:pointnav'&&p.sourceRootPositionIds),item=d.getElementById('np-node-'+p.id),label=item.querySelector('.np-node-label'),view=d.querySelector('#np-tree-scroll');item.focus();const oldTree=d.querySelector('#np-tree > ul');view.dispatchEvent(new w.WheelEvent('wheel',{bubbles:true,cancelable:true,ctrlKey:true,deltaY:100,clientX:300,clientY:200}));assert.equal(d.activeElement,item);assert.equal(d.getElementById('np-node-'+p.id),item);assert.equal(item.querySelector('.np-node-label'),label);assert.equal(d.querySelector('#np-tree > ul'),oldTree);assert.equal(d.querySelector('#np-zoom-value').textContent,'90%');});

test('fullscreen includes the reading desk, ancestor navigation and graph rather than stranding selected content outside',async t=>{const x=await page();t.after(()=>x.w.close());const d=x.doc,workspace=d.querySelector('#np-workspace');let requested=null;workspace.requestFullscreen=function(){requested=this;return Promise.resolve();};d.querySelector('#np-graph-fullscreen').click();assert.equal(requested,workspace);for(const selector of ['.np-reading-pane','#np-tree','.np-tabs','#np-global-context'])assert.ok(requested.contains(d.querySelector(selector)));});
test('return from a task restores the prior overview focus and its single roving tab stop',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),p=Object.values(b.researchMap.positions).find(p=>p.sourceScopeId==='task:hierarchical-objectnav'&&p.sourceRootPositionIds)||Object.values(b.researchMap.positions).find(p=>p.label.startsWith('HieraNav')&&p.sourceRootPositionIds),label=d.getElementById('np-node-'+p.id).querySelector('.np-node-label');label.focus();label.click();await frames(w);d.querySelector('[data-tree-tab=g]').click();await frames(w);assert.equal(d.activeElement.dataset.position,p.id);assert.equal(d.activeElement.tabIndex,0);assert.equal(d.querySelectorAll('#np-tree [role=treeitem][tabindex="0"]').length,1);});

test('restored preexisting overview expansions are retained, disclosed and still navigable to a focused branch',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,b=a.getBundle(),s=a.getState(),p=Object.values(b.researchMap.positions).find(p=>p.sourceScopeId==='task:pointnav'&&p.sourceRootPositionIds);M.getBucket(s).expandedByTree.g.push(p.id);w.history.replaceState(M.mergeHistory(w.history.state,s),'',w.location.href);w.dispatchEvent(new w.PopStateEvent('popstate'));await frames(w);assert.match(d.querySelector('#np-canvas-count').textContent,/已有额外展开分枝/);for(const id of p.childIds)assert.ok(d.getElementById('np-node-'+id));d.getElementById('np-node-'+p.childIds[0]).querySelector('.np-node-label').click();await frames(w);assert.equal(a.getState().route.node,p.childIds[0]);d.querySelector('[data-tree-tab=g]').click();await frames(w);assert.ok(M.getBucket(a.getState()).expandedByTree.g.includes(p.id));});

test('direct method navigation prioritizes its exact version, scope and mechanism before ancillary comparison',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),M=w.NavigationProductModel,p=Object.values(b.positions).find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='vlfm'&&p.kind==='pipeline_recipe');a.navigate(M.routeForPosition(b,{scope:p.scopeId},p.id),{cross:true});await frames(w);const summary=d.querySelector('#np-reader-summary'),method=summary.querySelector('.np-method-mechanism');assert.equal(summary.firstElementChild,method);assert.equal(d.querySelector('#navigation-product').dataset.readingLayout,'reading');assert.match(d.querySelector('#np-tree-heading').textContent,/VLFM.*层级来路/);assert.match(method.querySelector('.np-method-context').textContent,/ObjectNav/);assert.match(method.querySelector('.np-note').textContent,/未固定/);assert.ok(method.querySelector('.np-content-pending'),'pending content stays in its first-position mechanism section');assert.equal(d.querySelector('#np-reading-context-wrap').open,false);assert.equal(d.querySelector('#np-detail-scroll').scrollTop,0);assert.equal(d.querySelector('#np-tree').style.width,'');for(const row of d.querySelectorAll('#np-tree .np-node-row')){assert.equal(row.style.left,'');assert.equal(row.style.height,'');}assert.equal(a.getState().route.version,p.versionId);});

test('natural focus fit resets zoom and origin while keeping a usable fullscreen exit control',async t=>{const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),M=w.NavigationProductModel,p=Object.values(b.positions).find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId==='vlfm'&&p.kind==='pipeline_recipe');a.navigate(M.routeForPosition(b,{scope:p.scopeId},p.id),{cross:true});await frames(w);d.querySelector('#np-zoom-in').click();const view=d.querySelector('#np-tree-scroll');view.scrollTop=100;view.scrollLeft=60;d.querySelector('#np-zoom-fit').click();assert.equal(M.getBucket(a.getState()).graphScale,1);assert.equal(view.scrollTop,0);assert.equal(view.scrollLeft,0);const workspace=d.querySelector('#np-workspace');Object.defineProperty(d,'fullscreenElement',{configurable:true,value:workspace});d.dispatchEvent(new w.Event('fullscreenchange'));const exit=d.querySelector('#np-graph-fullscreen');assert.equal(exit.textContent,'退出全屏');assert.notEqual(w.getComputedStyle(exit).display,'none');let exited=false;d.exitFullscreen=()=>{exited=true;return Promise.resolve();};exit.click();assert.ok(exited);});

// Desktop space controls change only presentation; the existing navigation snapshots stay authoritative.
function selectDesktopMethod(x,paper){const a=x.w.NavigationProductApp,b=a.getBundle(),p=Object.values(b.positions).find(p=>p.tree==='l'&&p.scopeId==='task:category-objectnav'&&p.paperId===paper&&p.kind==='pipeline_recipe');assert.ok(p);a.navigate(x.w.NavigationProductModel.routeForPosition(b,{scope:p.scopeId},p.id),{cross:true});return p;}
for(const width of [1440,1920])test('desktop '+width+' reader collapse preserves identity, DOM, expansion, scale and scroll with a keyboard recovery target',async t=>{
 const x=await page(width);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,p=selectDesktopMethod(x,'vlfm');await frames(w);
 const toggle=d.querySelector('#np-reader-toggle'),reader=d.querySelector('#np-detail-scroll'),tree=d.querySelector('#np-tree-scroll'),forest=d.querySelector('#np-tree'),selected=d.getElementById('np-node-'+p.id),method=d.querySelector('.np-method-mechanism');
 assert.equal(toggle.hidden,false);assert.equal(toggle.getAttribute('aria-controls'),reader.id);d.querySelector('#np-zoom-in').click();tree.scrollTop=130;tree.scrollLeft=45;reader.scrollTop=420;d.querySelector('#np-evidence-panel').open=true;reader.querySelector('button').focus();
 const route=JSON.stringify(a.getState().route),hash=w.location.hash,historyLength=w.history.length,expansion=JSON.stringify(M.getBucket(a.getState()).expandedByTree),scale=M.getBucket(a.getState()).graphScale;
 toggle.click();assert.equal(reader.hidden,true);assert.equal(d.activeElement,toggle);assert.equal(toggle.getAttribute('aria-expanded'),'false');assert.equal(toggle.textContent,'展开所选节点正文');assert.equal(d.querySelector('#np-tree'),forest);assert.equal(d.getElementById('np-node-'+p.id),selected);assert.equal(d.querySelector('.np-method-mechanism'),method);assert.equal(tree.scrollTop,130);assert.equal(tree.scrollLeft,45);
 reader.scrollTop=0;w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,420,'a hidden DOM zero must not erase the reader anchor');
 toggle.click();assert.equal(reader.hidden,false);assert.equal(reader.scrollTop,420);assert.equal(d.activeElement,reader);assert.equal(reader.tabIndex,-1);assert.equal(toggle.getAttribute('aria-expanded'),'true');assert.equal(d.querySelector('#np-evidence-panel').open,true);assert.equal(tree.scrollTop,130);assert.equal(tree.scrollLeft,45);assert.equal(JSON.stringify(a.getState().route),route);assert.equal(w.location.hash,hash);assert.equal(w.history.length,historyLength);assert.equal(JSON.stringify(M.getBucket(a.getState()).expandedByTree),expansion);assert.equal(M.getBucket(a.getState()).graphScale,scale);assert.deepEqual(x.errors,[]);
});
test('collapse and reopen compensate the selected row pixel anchor without rebuilding the tree',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const d=x.doc,p=selectDesktopMethod(x,'vlfm');await frames(x.w);const toggle=d.querySelector('#np-reader-toggle'),reader=d.querySelector('#np-detail-scroll'),tree=d.querySelector('#np-tree-scroll'),row=d.getElementById('np-node-'+p.id).firstElementChild;
 tree.scrollTop=200;tree.scrollLeft=60;row.getBoundingClientRect=()=>({left:100-tree.scrollLeft,top:(reader.hidden?230:300)-tree.scrollTop});const before=row.getBoundingClientRect();toggle.click();assert.equal(tree.scrollTop,130);assert.deepEqual(row.getBoundingClientRect(),before);toggle.click();assert.equal(tree.scrollTop,200);assert.deepEqual(row.getBoundingClientRect(),before);assert.equal(d.getElementById('np-node-'+p.id).firstElementChild,row);
});
test('collapsed reader survives navigation and Back without exposing hidden focus or losing the saved reading offset',async t=>{
 const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,p=selectDesktopMethod(x,'poni');await frames(w);const reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle');reader.scrollTop=570;reader.focus();toggle.click();reader.scrollTop=0;selectDesktopMethod(x,'vlfm');await frames(w);assert.equal(reader.hidden,true);assert.match(toggle.textContent,/展开所选节点正文/);assert.equal(d.activeElement.dataset.position,a.getState().route.node);w.history.back();await wait(35);await frames(w);assert.equal(a.getState().route.node,p.id);assert.equal(reader.hidden,true);assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,570);assert.equal(reader.contains(d.activeElement),false);toggle.click();assert.equal(reader.scrollTop,570);assert.equal(d.activeElement,reader);assert.deepEqual(x.errors,[]);
});
test('returning to an entry whose saved focus was inside the now-collapsed reader focuses its visible recovery button',async t=>{
 const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,p=selectDesktopMethod(x,'poni');await frames(w);d.querySelector('#np-detail-scroll').scrollTop=245;d.querySelector('#np-detail-title').focus();selectDesktopMethod(x,'vlfm');await frames(w);d.querySelector('#np-reader-toggle').click();w.history.back();await wait(35);await frames(w);assert.equal(a.getState().route.node,p.id);assert.equal(d.querySelector('#np-detail-scroll').hidden,true);assert.equal(d.activeElement,d.querySelector('#np-reader-toggle'));d.querySelector('#np-reader-toggle').click();assert.equal(d.querySelector('#np-detail-scroll').scrollTop,245);assert.deepEqual(x.errors,[]);
});
test('rapid newer navigation and late verified content cannot open the collapsed reader or change the latest selection',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,pending=new Map();w.fetch=url=>new Promise(resolve=>pending.set(url,resolve));const older=selectDesktopMethod(x,'poni');await frames(w);d.querySelector('#np-reader-toggle').click();const queue=[],raf=w.requestAnimationFrame.bind(w);w.requestAnimationFrame=fn=>{queue.push(fn);return queue.length;};selectDesktopMethod(x,'vlfm');const latest=selectDesktopMethod(x,'semexp');while(queue.length)queue.shift()();w.requestAnimationFrame=raf;await wait(20);const selected=d.getElementById('np-node-'+latest.id),route=JSON.stringify(a.getState().route),url='content/'+a.getBundle().delivery.packets[older.entityId].sha256+'.json';assert.ok(pending.has(url));
 // Render the generator's exact verified packet locally, without depending on a build order.
 const raw=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;from navigation_transport import project;r=Path('.').resolve();d=project(p.payloads(r)[1],p.MODEL_SHA256);sys.stdout.buffer.write(d['files'][sys.argv[1]])",path.basename(url)],{cwd:root,maxBuffer:20e6});pending.get(url)({ok:true,arrayBuffer:async()=>raw});for(let i=0;i<50&&!a.getContent().ready(older.entityId);i++)await wait(10);assert.equal(a.getContent().ready(older.entityId),true);assert.equal(d.querySelector('#np-detail-scroll').hidden,true);assert.equal(JSON.stringify(a.getState().route),route);assert.equal(a.getState().route.node,latest.id);assert.equal(d.getElementById('np-node-'+latest.id),selected);assert.equal(d.querySelector('#np-detail-scroll').contains(d.activeElement),false);assert.deepEqual(x.errors,[]);
});
test('hidden reader zeros from pagehide, beforeunload and delayed scroll saves retain the current bucket anchor',async t=>{
 const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel;selectDesktopMethod(x,'poni');await frames(w);const reader=d.querySelector('#np-detail-scroll');reader.scrollTop=570;reader.dispatchEvent(new w.Event('scroll'));d.querySelector('#np-reader-toggle').click();reader.scrollTop=0;reader.dispatchEvent(new w.Event('scroll'));w.dispatchEvent(new w.Event('beforeunload'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,570);reader.dispatchEvent(new w.Event('scroll'));await wait(150);assert.equal(w.history.state[M.KEY].contexts[M.contextKey(a.getState().route)].detailScrollByTree.l,570);w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,570);d.querySelector('#np-reader-toggle').click();assert.equal(reader.scrollTop,570);
});
test('collapsed cross-scope Back and Forward keep independent Audio and GOAT reader anchors',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,b=a.getBundle(),M=w.NavigationProductModel,reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle');
 function pick(scope){const p=Object.values(b.positions).find(p=>p.scopeId===scope&&p.tree==='l'&&p.paperId&&['pipeline_recipe','versioned_method_card'].includes(p.kind));assert.ok(p,scope);a.navigate(M.routeForPosition(b,{scope},p.id),{cross:true});return p;}
 const audio=pick('task:audiogoal');await frames(w);reader.scrollTop=321;toggle.click();const goat=pick('task:goat');await frames(w);assert.equal(reader.hidden,true);toggle.click();reader.scrollTop=654;toggle.click();reader.scrollTop=0;w.history.back();await wait(35);await frames(w);assert.equal(a.getState().route.node,audio.id);assert.equal(reader.hidden,true);assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,321);w.history.forward();await wait(35);await frames(w);assert.equal(a.getState().route.node,goat.id);assert.equal(reader.hidden,true);assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,654);toggle.click();assert.equal(reader.scrollTop,654);assert.deepEqual(x.errors,[]);
});
test('same-node content arriving while collapsed keeps its saved offset and never steals focus or reopens the reader',async t=>{
 const x=await page();t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,pending=new Map();w.fetch=url=>new Promise(resolve=>pending.set(url,resolve));const p=selectDesktopMethod(x,'poni');await frames(w);const reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle');reader.scrollTop=480;toggle.click();reader.scrollTop=0;const url='content/'+a.getBundle().delivery.packets[p.entityId].sha256+'.json',raw=cp.execFileSync('python3',['-c',"import sys;from pathlib import Path;sys.path.insert(0,'scripts');import navigation_product as p;from navigation_transport import project;r=Path('.').resolve();d=project(p.payloads(r)[1],p.MODEL_SHA256);sys.stdout.buffer.write(d['files'][sys.argv[1]])",path.basename(url)],{cwd:root,maxBuffer:20e6});pending.get(url)({ok:true,arrayBuffer:async()=>raw});for(let i=0;i<50&&!a.getContent().ready(p.entityId);i++)await wait(10);assert.equal(a.getContent().ready(p.entityId),true);assert.equal(reader.hidden,true);assert.equal(reader.scrollTop,0);assert.equal(d.activeElement,toggle);w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,480);toggle.click();assert.equal(reader.scrollTop,480);assert.ok(d.querySelector('.np-method-flow dd'));assert.deepEqual(x.errors,[]);
});
test('rapid toggles use the final visible state and clamp pixel anchoring only to the legal scroll range',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel,p=selectDesktopMethod(x,'vlfm');await frames(w);const reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle'),tree=d.querySelector('#np-tree-scroll'),row=d.getElementById('np-node-'+p.id).firstElementChild;let scroll=200;Object.defineProperty(tree,'scrollTop',{configurable:true,get:()=>Math.min(scroll,reader.hidden?90:400),set:v=>{scroll=Math.max(0,Math.min(v,reader.hidden?90:400));}});row.getBoundingClientRect=()=>({left:0,top:(reader.hidden?230:300)-tree.scrollTop});toggle.click();assert.equal(tree.scrollTop,90);assert.equal(reader.hidden,true);toggle.click();assert.equal(tree.scrollTop,160);toggle.click();toggle.click();toggle.click();assert.equal(reader.hidden,true);await frames(w);assert.equal(reader.hidden,true);assert.equal(d.activeElement,toggle);assert.equal(M.getBucket(a.getState()).graphScale,1);assert.equal(d.getElementById('np-node-'+p.id).firstElementChild,row);assert.deepEqual(x.errors,[]);
});
for(const intent of ['open','close'])test('a newer reader '+intent+' keeps focus after an earlier navigation animation frame completes',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel;selectDesktopMethod(x,'poni');await frames(w);const reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle');if(intent==='open')toggle.click();const queue=[],raf=w.requestAnimationFrame.bind(w);w.requestAnimationFrame=fn=>{queue.push(fn);return queue.length;};const target=selectDesktopMethod(x,'vlfm');toggle.click();const expected=intent==='open'?reader:toggle;assert.equal(d.activeElement,expected);while(queue.length)queue.shift()();w.requestAnimationFrame=raf;assert.equal(d.activeElement,expected,'the earlier route RAF must not override the latest explicit reader focus');assert.equal(reader.hidden,intent==='close');assert.equal(a.getState().route.node,target.id);assert.equal(d.getElementById('np-node-'+target.id).getAttribute('aria-selected'),'true');assert.equal(reader.scrollTop,0);reader.scrollTop=77;w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,intent==='open'?77:0,'restoring cleanup must still finish when only its obsolete focus step is suppressed');assert.deepEqual(x.errors,[]);
});
test('a newer reader focus survives an older pending workspace jump while its scroll and cleanup still finish',async t=>{
 const x=await page(1920);t.after(()=>x.w.close());const w=x.w,d=x.doc,a=w.NavigationProductApp,M=w.NavigationProductModel;selectDesktopMethod(x,'poni');await frames(w);const reader=d.querySelector('#np-detail-scroll'),toggle=d.querySelector('#np-reader-toggle');toggle.click();const queue=[],raf=w.requestAnimationFrame.bind(w);w.requestAnimationFrame=fn=>{queue.push(fn);return queue.length;};const target=selectDesktopMethod(x,'vlfm');let workspaceJumps=0;d.querySelector('#np-workspace').scrollIntoView=()=>{workspaceJumps++;};d.querySelector('.np-skip').click();toggle.click();assert.equal(d.activeElement,reader);while(queue.length)queue.shift()();w.requestAnimationFrame=raf;assert.equal(d.activeElement,reader);assert.equal(workspaceJumps,1,'the older workspace action still scrolls, without stealing newer focus');assert.equal(a.getState().route.node,target.id);assert.equal(reader.hidden,false);reader.scrollTop=123;w.dispatchEvent(new w.Event('pagehide'));assert.equal(M.getBucket(a.getState()).detailScrollByTree.l,123);toggle.click();d.querySelector('.np-skip').click();await frames(w);assert.equal(workspaceJumps,2,'a newly requested skip still performs its workspace scroll');assert.equal(d.activeElement,d.querySelector('#np-tree-heading'),'a skip requested after the toggle keeps its original focus behavior');assert.equal(reader.hidden,true);assert.deepEqual(x.errors,[]);
});
