'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=process.argv[2]||path.resolve(__dirname,'..'),base=root+'/previews/radar-c2-analysis';
const F=require(base+'/analysis/c2.js').FaithfulTree,make=require('./research_dom_fixture.cjs'),visibleText=make.visibleText,plain=x=>JSON.parse(JSON.stringify(x));
const outputDir=process.argv[3]||require('node:os').tmpdir(),results=[];function test(name,fn){try{fn();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message,stack:e.stack});}}
let f,app,g,snapshots={};
function snap(name){const panel=f.$('#ft-detail-body'),text=visibleText(panel).replace(/\s+/g,' ').trim();snapshots[name]={selected:F.view({M:f.window.TreeModel,A:f.window.AnalysisModel,model:f.window.NavigationPrototype.model,bundle:f.window.C2_DATA,R:f.window.ResearchGraph,research:g,reference:f.window.REFERENCE_COMPLETE,scopedAnalyses:f.window.SCOPED_RESEARCH_ANALYSES},app.getState()).selected,visibleChars:text.length,text};}
function boot(options={}){f=make(root,options);f.document.emit('DOMContentLoaded');app=f.window.FaithfulTreeApp;g=app.getGraph();assert.equal(f.errors.length,0);return f;}
test('actual HTML loads reviewed graph by default, with one detail panel and map',()=>{boot();assert(app.isActive());assert(g.research);assert.equal(f.$$('#ft-detail').length,1);assert.equal(app.getState().mode,'navigation');assert(f.$('[data-ft="layout"][data-layout="map"]').getAttribute('aria-pressed')==='true');snap('overview');assert(g.raw.overview.sentences.length>=3&&g.raw.overview.sentences.length<=5);for(const s of g.raw.overview.sentences.slice(0,3))assert(snapshots.overview.text.includes(s));assert(snapshots.overview.text.includes('选择性核读'));});
test('initial approved example action opens target question, not catalog',()=>{const action=f.$('.rg-primary-start');assert(action);const id=action.dataset.id;assert(g.by.has(id));action.emit('click');assert.equal(app.getState().views['navigation:dual'].selected,id);assert(g.by.get(id).plain_language_question);snap('first-question');});
test('guided original hierarchy reaches PONI and gives 22 scoped answers; back restores source/outline/scroll',()=>{const placements=g.nodes.filter(n=>n.paperId==='poni');assert(placements.length);const n=placements[0];app.dispatch({type:'locate',id:n.id});snap('poni-work');const parent=g.by.get(n.parent);app.dispatch({type:'locate',id:parent.id});snap('poni-parent');app.dispatch({type:'locate',id:n.id});app.dispatch({type:'layout',layout:'outline'});f.$('#ft-detail-body').scrollTop=137;f.$('#ft-viewport').scrollTop=111;const claim=f.$('[data-ft="claim"]');assert(claim);claim.emit('click');const sourceLink=f.$('#ft-detail-body').querySelector('a[href]');assert(sourceLink&&/^https:\/\//.test(sourceLink.getAttribute('href')));const state=plain(app.getState());app.dispatch({type:'analysis',paper:n.paperId,version:n.fixed_version,origin:'research'});assert.equal(app.getGraph().analysis.answers.size,22);assert.equal(app.getGraph().nodes.length,59);assert.equal(app.getGraph().analysis.partialSource.status,'partial_selected_section_analysis');app.dispatch({type:'return'});assert.equal(app.getState().views['navigation:dual'].selected,n.id);assert.equal(app.getState().views['navigation:dual'].layout,'outline');assert.equal(app.getState().claimId,state.claimId);assert.equal(app.getState().detailTab,'evidence');assert.equal(app.getState().views['navigation:dual'].outlineScroll,111);});
test('actual current paper analysis tab never chooses old default identity',()=>{for(const n of g.nodes.filter(n=>n.paperId)){app.dispatch({type:'mode',mode:'navigation'});app.dispatch({type:'tab',tab:'l'});app.dispatch({type:'locate',id:n.id});app.dispatch({type:'tab',tab:'a'});assert.equal(app.getState().paper,n.paperId,n.id);assert.equal(app.getState().paperVersion,n.fixed_version,n.id);if(n.paperId!=='poni')assert.equal(app.getGraph().analysis.answers.size,0,n.id);}});
test('Back/Forward maintains actual hierarchy, paper and view mode',()=>{boot();const work=g.nodes.find(n=>n.paperId==='poni');app.dispatch({type:'locate',id:work.id});app.dispatch({type:'layout',layout:'outline'});const origin=plain(app.getState());app.dispatch({type:'analysis',paper:'poni',version:work.fixed_version,origin:'research'});f.back();assert.equal(app.getState().tab,origin.tab);assert.equal(app.getState().views['navigation:dual'].selected,work.id);assert.equal(app.getState().views['navigation:dual'].layout,'outline');f.forward();assert.equal(app.getState().paper,'poni');assert.equal(app.getGraph().analysis.answers.size,22);});
test('unknown paper hash stays honest and independent',()=>{boot({url:'https://example.test/#mindmap='+encodeURIComponent(JSON.stringify({version:2,mode:'navigation',tab:'a',paper:'unknown-canonical-paper',paperVersion:'v999',analysisOrigin:'research'}))});assert.equal(app.getState().paper,'unknown-canonical-paper');assert.equal(app.getGraph().analysis.answers.size,0);assert(f.$('#ft-detail-body').textContent.includes('没有替换成其他论文'));});
test('actual context card can show primary claim and return to a new node',()=>{boot();const context=[...g.contextBy.values()].find(n=>n.evidence_refs.length);assert(context);app.dispatch({type:'context',id:context.id});const b=f.$('#ft-detail-body').querySelector('[data-ft="claim"]');assert(b);b.emit('click');assert(f.$('#ft-detail-body').querySelector('a[href]'));const n=g.nodes.find(n=>n.paperId);app.dispatch({type:'node',id:n.id});assert(!f.$('#ft-detail-body').textContent.includes('这是相关条件索引'));});
test('all role detail screens render without machine undefined/null placeholders',()=>{boot();for(const n of g.nodes){app.dispatch({type:'locate',id:n.id});const text=visibleText(f.$('#ft-detail-body'));assert(!/\b(undefined|null|NaN)\b/.test(text),n.id);if(['pipeline_or_representation','improvement_idea','insight'].includes(n.semantic_role)&&!snapshots[n.semantic_role])snap(n.semantic_role);}});
test('approved category-branch rationale is visible instead of a false missing statement',()=>{boot();app.dispatch({type:'locate',id:'category-objectnav'});const n=g.by.get('category-objectnav'),text=visibleText(f.$('#ft-detail-body'));assert(text.includes(n.why_important));});
test('default role panels use human display labels instead of raw schema enums',()=>{boot();for(const id of ['category-objectnav','method:work:poni@semantic-map-search-fmm','challenge:insight:search_unknown_target:semexp2020']){app.dispatch({type:'locate',id});const text=visibleText(f.$('#ft-detail-body'));assert(!/\b(?:work_realizing_this_improvement|goal_predicate_restriction|editorial_containment_supported_by_separately_attributed_primary_definitions|primary_full_text_methods_and_selected_experiments_read|route_scope|paper_scope|reported_evidence)\b/.test(text),id+': raw schema key or enum is shown');}});
test('PONI answer panels lead with answer and keep exhaustive coverage behind controls',()=>{boot();const work=g.nodes.find(n=>n.paperId==='poni');app.dispatch({type:'locate',id:work.id});app.dispatch({type:'analysis',paper:'poni',version:work.fixed_version,origin:'research'});const m=app.getGraph().analysis;for(const a of [...m.answers.values()].slice(0,3)){app.dispatch({type:'node',id:a.nodeId});const text=visibleText(f.$('#ft-detail-body')).replace(/\s+/g,' ').trim();assert(text.includes(a.answer));assert(!text.includes('论文有三个运行时组件'));assert(!text.includes('逐句写作逻辑精读'));if(text.includes('尚未完成'))assert(text.indexOf(a.answer)<text.indexOf('尚未完成'));snapshots['poni-answer-'+a.nodeId]={selected:a.nodeId,visibleChars:text.length,text};}});
test('PONI work source-owned scope is shown without false missing-scope claim',()=>{boot();const work=g.nodes.find(n=>n.paperId==='poni');app.dispatch({type:'locate',id:work.id});const text=visibleText(f.$('#ft-detail-body')).replace(/\s+/g,' ').trim();assert(!/适用边界\s*当前核读范围未建立这一项/.test(text));snapshots['poni-final-work']={selected:work.id,visibleChars:text.length,text};});
test('long improvement mechanism is not repeated as title, definition and answer',()=>{boot();const n=g.nodes.find(n=>n.id==='method:improvement:offline-frontier-potentials');app.dispatch({type:'locate',id:n.id});const text=visibleText(f.$('#ft-detail-body'));const phrase=n.mechanism;assert(text.split(phrase).length-1<=1,'Same full mechanism repeats in default panel');});
test('compiled reader data keeps private compilation metadata out and claim conditions render as text',()=>{boot();const forbidden=new Set(['renav_mapping','source_snapshot_sha256','snapshot_sha256','source_pointer','source_artifact','source_artifacts','artifact','review_basis']);function check(v){if(!v||typeof v!=='object')return;if(Array.isArray(v)){v.forEach(check);return;}for(const [k,x]of Object.entries(v)){assert(!forbidden.has(k),k);check(x);}}check(g.raw);for(const c of g.claims.values()){const html=f.window.ResearchGraph.claimHtml(g,c.id);assert(!html.includes('[object Object]'),c.id);}const reference=f.window.REFERENCE_COMPLETE;assert(!JSON.stringify(reference).includes('libfile_'));assert(!JSON.stringify(reference).includes('/workspace/'));});
test('every visible paper-selector option has a deterministic research context or legacy destination',()=>{boot();const ids=f.$('#ft-paper').querySelectorAll('option').map(o=>o.getAttribute('value')).filter(Boolean);assert(ids.includes('poni')&&ids.includes('lmnav'));for(const pid of ids){app.dispatch({type:'mode',mode:'navigation'});app.dispatch({type:'tab',tab:'l'});const select=f.$('#ft-paper');select.value=pid;select.emit('change');assert.equal(app.getState().paper,pid,pid+' did not navigate');assert(!app.getState().unresolvedPaper,pid);}assert(ids.length<new Set([...f.window.NavigationPrototype.model.papers.keys(),...g.papers.keys()]).size,'bibliographic-only sources should remain evidence, not broken selector choices');});
test('actual ECROM insight keeps the primary p_det notation in its node details',()=>{boot();const n=g.nodes.find(n=>(n.source_paper_id==='ecrom2026'||(n.paper_refs||[]).includes('ecrom2026'))&&JSON.stringify(n).includes('p_det'));assert(n,'reviewed ECROM node with p_det must exist');app.dispatch({type:'locate',id:n.id});const text=f.$('#ft-detail-body').textContent;assert(text.includes('p_det'));assert(!text.includes('p det'));});
const output={kind:'independent actual-HTML deterministic DOM workflows',passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results,snapshots,browser:'NOT_RUN; deterministic fixture, no actual layout/paint/native interaction tested'};
fs.writeFileSync(outputDir+'/research-workflows-results.json',JSON.stringify(output,null,2));console.log(JSON.stringify({...output,snapshots:Object.fromEntries(Object.entries(snapshots).map(([k,v])=>[k,{selected:v.selected,visibleChars:v.visibleChars}]))},null,2));process.exitCode=output.failed?1:0;
