'use strict';
// Deterministic DOM/model contracts. No browser geometry or human-usability claim.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),vm=require('node:vm');
const root=process.env.RPA_TASK_MAP_SOURCE||path.resolve(__dirname,'..'),source=path.join(root,'previews/radar-c2-analysis'),M=require(path.join(source,'model.js'));
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'rpa-task-map-'));fs.cpSync(source,tmp,{recursive:true});fs.cpSync(path.join(root,'tests/fixtures/radar-c2-analysis'),tmp,{recursive:true});const {fixture}=require(path.join(tmp,'analysis/tests/dom_fixture.cjs'));
let passed=0,failed=0;const test=(n,fn)=>{try{fn();passed++;console.log('PASS '+n);}catch(e){failed++;console.error('FAIL '+n+'\n'+e.stack);}};
try{
test('first screen has two task-spec roots plus associated output branch; no nineteen-card clutter',()=>{const f=fixture();assert.deepEqual(f.errors,[]);assert.equal(f.$$('.task-family').length,3);assert.equal(f.$$('.protocol-card').length,0);assert.equal(f.$$('.task-family').filter(x=>x.getAttribute('aria-pressed')==='true').length,0);assert.deepEqual(f.$$('.task-family').map(x=>x.dataset.id),['route','goal','related']);assert(f.$('.task-map-bridge').textContent.includes('LMEE'));assert(f.$('.task-map').textContent.includes('两条导航主线'));});
test('every original task contract is grouped once, and LangMap is an explicit scoped protocol card',()=>{const f=fixture(),model=f.app.model,ids=M.taskMap.groups.flatMap(g=>g.sections.flatMap(s=>s.ids)),actual=[...model.trees.l.nodes.values()].filter(n=>n.type==='task_contract').map(n=>n.id);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(ids.slice().sort(),actual.sort());for(const g of M.taskMap.groups){f.app.dispatch({type:'taskGroup',id:g.id});assert.equal(f.$$('.task-family').filter(x=>x.getAttribute('aria-pressed')==='true').length,1);for(const id of g.sections.flatMap(s=>s.ids))assert(f.$('.protocol-card[data-id="'+id+'"]'));}f.app.dispatch({type:'taskGroup',id:'goal'});assert(f.$('.protocol-card[data-variant="sap-nav-langmap-single-goal"]'));});
test('all source paths and all unique papers remain reachable without inventing scientific nodes',()=>{const f=fixture(),model=f.app.model;for(const p of model.trees.l.paths){f.app.dispatch({type:'path',key:'l',id:p.id});assert.equal(f.app.getState().paper,p.paperId);assert.deepEqual(JSON.parse(JSON.stringify(f.app.getState().origin.path)),JSON.parse(JSON.stringify(p.nodeIds)));assert.equal(f.$('#paper-panel').hidden,false);assert(f.$('#paper-body').textContent.length>30);assert.equal(f.$$('.task-family').filter(x=>x.getAttribute('aria-pressed')==='true').length,1);}const stats=M.taskMap.stats(model);assert.equal(stats.nodes,model.trees.l.raw.nodes.length);assert.equal(stats.paths,model.trees.l.raw.paths.length);assert.equal(stats.edges,model.trees.l.raw.edges.length);assert.equal(stats.papers,model.papers.size);assert.deepEqual(M.validate(model),[]);});
test('representative methods expose paper evidence before optionally opened mechanisms',()=>{const f=fixture();f.app.dispatch({type:'root',key:'l',id:'task-vln-graph'});assert(f.$$('.method-comparison').length);assert(f.$$('.paper-chip').length);assert(f.$$('.mechanism-detail').every(x=>x.getAttribute('open')===null));const path=f.$('.paper-chip').dataset.id;f.click('.paper-chip');assert.equal(f.app.getState().origin.path.at(-1),f.app.model.trees.l.paths.find(p=>p.id===path).nodeIds.at(-1));assert(f.$('.selected-task-route'));});
test('switching methods, returning globally, repeated selection and browser history preserve state',()=>{const f=fixture();f.click('[data-action="taskGroup"][data-id="goal"]');f.click('[data-action="root"][data-id="task-imagegoal-multigoal"]');const task=JSON.stringify(f.app.getState());f.click('[data-action="facet"][data-facet="representation"]');assert.equal(f.app.getState().lFacet,'representation');f.back();assert.equal(JSON.stringify(f.app.getState()),task);f.forward();assert.equal(f.app.getState().lFacet,'representation');for(let i=0;i<3;i++){f.app.dispatch({type:'global'});assert.equal(f.$$('.protocol-card').length,0);assert.equal(f.app.getState().taskGroup,null);f.app.dispatch({type:'root',key:'l',id:'task-imagegoal-multigoal'});assert.equal(f.app.getState().taskGroup,'goal');}assert(f.$('.bounded-development').textContent.includes('不证明'));});
test('old hash bookmarks still resolve without a path migration or history rewrite',()=>{const f=fixture(),model=f.app.model,p=model.trees.l.paths[10],old={...M.initialState(),l:p.nodeIds.slice(0,-1),paper:p.paperId,origin:{key:'l',path:p.nodeIds}};delete old.taskGroup;delete old.taskVariant;const restored=M.deserialize(model,M.serialize(old));assert.equal(JSON.stringify(restored.l),JSON.stringify(p.nodeIds.slice(0,-1)));assert.equal(restored.paper,p.paperId);assert.equal(restored.taskGroup,M.taskMap.groupFor(p.nodeIds[0]));assert.equal(JSON.stringify(restored.origin.path),JSON.stringify(p.nodeIds));});
test('empty-coverage tasks stay empty and do not absorb nearby protocols',()=>{for(const id of ['task-multion','task-embodiedqa-classic']){const f=fixture();f.app.dispatch({type:'root',key:'l',id});assert.equal(f.$$('.paper-chip').length,0);assert(f.$('.empty-coverage'));assert(f.$('.protocol-summary'));}});
test('protocol variants are paper scoped, versioned, and expose all six independent conditions',()=>{const f=fixture();assert([...f.app.model.trees.l.nodes.values()].flatMap(n=>n.protocol_variants||[]).length>=7);for(const n of f.app.model.trees.l.nodes.values())for(const v of n.protocol_variants||[]){f.app.dispatch({type:'root',key:'l',id:n.id,variant:v.id});assert(f.$('[data-protocol-variant="'+v.id+'"]'));assert.equal(f.$('.protocol-facts').children.length,6);for(const chip of f.$$('.paper-chip')){const p=f.app.model.trees.l.paths.find(p=>p.id===chip.dataset.id);assert(v.paper_ids.includes(p.paperId));}}});
test('analysis original schema and all filled/pending papers still open with five original branches',()=>{for(const id of ['harnessvln','navharness','navgpt']){const f=fixture({width:390,height:844});f.c2.open(id,f.app.getContext());assert.equal(f.c2.getModel().schema.nodes.length,59);assert.equal(f.$$('.c2-skeleton-branch').length,5);assert(f.$('.c2-location-map'));}});
test('definition sources do not masquerade as method pipelines, and evidence close restores its chip',()=>{const f=fixture();f.app.dispatch({type:'root',key:'l',id:'task-object-category'});assert(f.$('.protocol-source-records'));for(const el of f.$$('.method-comparison'))assert.notEqual(f.app.model.trees.l.nodes.get(el.dataset.methodId).type,'protocol');const chip=f.$('.paper-chip'),id=chip.dataset.id;f.click('.paper-chip');f.click('[data-action="closePaper"]');assert.equal(f.document.activeElement.dataset.action,'path');assert.equal(f.document.activeElement.dataset.id,id);});
test('variant selection clears when locating an unrelated paper instead of silently filtering it out',()=>{const f=fixture();f.app.dispatch({type:'root',key:'l',id:'task-object-open',variant:'sap-nav-langmap-single-goal'});const p=f.app.model.trees.l.paths.find(p=>p.nodeIds[0]==='task-object-open'&&p.paperId!=='sap-nav');f.app.dispatch({type:'path',key:'l',id:p.id});assert.equal(f.app.getState().paper,p.paperId);assert.equal(f.app.getState().taskVariant,null);assert(f.$$('.paper-chip').length);});
test('responsive guardrails use real text and native wrapping without hidden/clipped labels',()=>{const css=fs.readFileSync(path.join(source,'style.css'),'utf8');assert(css.includes('.task-family-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr))'));assert(css.includes('.protocol-facts>div,.protocol-versions .protocol-facts>div{grid-template-columns:1fr'));for(const width of [220,296,340,390,820]){const items=[{id:'root',depth:0,label:'任务与协议',children:['method']},{id:'method',depth:1,label:'代表方法与完整来源标签',children:[]}],g=M.atlas.readableLayout(items,'root',{width});assert.equal(g.width,width);assert(g.nodes.every(n=>n.x+n.w<=width+.01));}});
}finally{fs.rmSync(tmp,{recursive:true,force:true});}
console.log(JSON.stringify({passed,failed,realBrowser:'NOT_RUN',humanUsability:'NOT_RUN'}));if(failed)process.exitCode=1;
