const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const program=require('./program.cjs'),M=program.model,D=program.data,{fixture}=require('./dom_fixture.cjs');
test('95 unique canonical records have stable, finite, distinct coordinates independent of input order',()=>{assert.equal(D.papers.length,95);assert.equal(new Set(D.papers.map(p=>p.id)).size,95);const a=M.layout(D.papers),b=M.layout([...D.papers].reverse());assert.deepEqual(a,b);assert.equal(new Set(a.map(p=>p.x+','+p.y)).size,95);assert(a.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)&&M.colors[p.category]));});
test('all titles, Chinese task/method names, authors and outside-pilot papers searchable',()=>{for(const p of D.papers)assert(M.search(p,p.title,'',''));for(const p of D.papers.filter(p=>p.methods.includes('RL')))assert(M.search(p,'强化学习','',''));assert.equal(D.papers.filter(p=>M.search(p,'ODYSSEY','','')).length,1)});
test('11 typed verified records retain 8 directed pairs and exact evidence',()=>{const n=M.neighborhood('rpa-0062',D.relations.edges);assert.equal(n.records.length,11);assert.equal(n.ids.size,9);assert.equal(M.pairs(n.records).length,8);assert(n.records.every(e=>e.directed&&e.evidence.every(v=>v.url.startsWith('https://')&&v.pdf_page>0)));assert.equal(n.records.filter(e=>e.type==='uses_method_or_resource').length,3)});
test('initial DOM renders all95 with no mandatory selected paper and no inferred edges',()=>{const f=fixture();assert.equal(f.$$('.node').length,95);assert.equal(f.$$('.edge').length,0);assert(f.$('#detail').hidden);assert.equal(f.window.AtlasDebug.getState().selected,null);assert.equal(f.$('#results').children.length,95)});
test('all95 initial projected coordinates fit desktop and mobile viewport',()=>{for(const opt of [{width:1440,height:900},{width:1024,height:768},{mobile:true,width:390,height:844}]){const f=fixture(opt),dbg=f.window.AtlasDebug;for(const p of dbg.nodes){const q=dbg.project(p);assert(q.x>0&&q.x<opt.width&&q.y>0&&q.y<opt.height,p.id+' '+JSON.stringify(q))}}});
test('selection retains95 nodes and yields8 evidence pairs, then unknown paper has honest empty state',()=>{const f=fixture();f.window.AtlasDebug.select('rpa-0062');f.step(600);assert.equal(f.$$('.node').length,95);assert.equal(f.$$('.edge').length,8);assert.equal(f.$$('.evidence').length,12);assert.match(f.$('#detail').textContent,/采用方法或资源/);f.window.AtlasDebug.select('rpa-0042');f.step(600);assert.equal(f.$$('.node').length,95);assert.equal(f.$$('.edge').length,0);assert.match(f.$('#detail').textContent,/关系尚未索引/)});
test('search dims nonmatching context, keeps selected exception, and overview clears state',()=>{const f=fixture();f.window.AtlasDebug.select('rpa-0062');f.input('ODYSSEY');assert.equal(f.$('#results').children.length,1);assert.equal(f.$$('.node').length,95);assert.match(f.$('#detail').textContent,/不符合筛选/);f.click('#overview');f.step(600);assert.equal(f.window.AtlasDebug.getState().selected,null);assert.equal(f.window.AtlasDebug.getState().matching.length,95);assert.equal(f.$$('.edge').length,0);assert(f.$('#detail').hidden);assert.equal(f.window.AtlasDebug.getState().camera.k,1)});
test('rapid selection, zoom interruption, and reset do not leave stale animations',()=>{const f=fixture();for(let i=0;i<10;i++){f.window.AtlasDebug.select('rpa-0062');f.window.AtlasDebug.select('rpa-0042')}assert.equal(f.raf.size,1);f.click('#plus');assert.equal(f.raf.size,0);f.click('#overview');f.step(600);assert.equal(f.raf.size,0);assert.equal(f.$$('.node').length,95)});
test('reduced-motion selection is immediate; input remains functional',()=>{const f=fixture({reduced:true,mobile:true});f.window.AtlasDebug.select('rpa-0062');assert.equal(f.raf.size,0);assert.equal(f.window.AtlasDebug.getState().camera.k,1.15);assert(f.$('#controls').classList.contains('collapsed'));f.click('#collapse');assert(!f.$('#controls').classList.contains('collapsed'));f.click('#collapse');assert(f.$('#controls').classList.contains('collapsed'))});
test('no external scripts, WebGL, copied reference assets, private paths or network calls ship',()=>{const html=program.html;assert(!/WebGL|THREE\.|googolstars|\/workspace\/|2026-09-30 21-48-59|<script[^>]+src=|\bfetch\s*\(|localStorage|XMLHttpRequest/.test(html));assert(!/\/\*(?:APP|DATA|MODEL|STYLE)\*\//.test(html))});

test('clicking a relation exposes its source details without changing the selected paper',()=>{const f=fixture();f.window.AtlasDebug.select('rpa-0062');f.step(600);f.click('.edge');assert(f.$$('.evidence').some(e=>e.open));assert.equal(f.window.AtlasDebug.getState().selected,'rpa-0062');assert.equal(f.$$('.node').length,95)});

test('Close and Escape restore keyboard focus to the selected visible star, or Overview',()=>{const f=fixture();f.window.AtlasDebug.select('rpa-0062');const close=f.$('#detail').querySelector('button');close.focus();close.emit('click');assert(f.$('#detail').hidden);assert.equal(f.document.activeElement.dataset.id,'rpa-0062');f.window.AtlasDebug.select('rpa-0042');f.$('#detail').querySelector('button').focus();const event=f.window.emit('keydown',{key:'Escape'});assert(event.defaultPrevented);assert.equal(f.document.activeElement.dataset.id,'rpa-0042');assert(f.$('#detail').hidden);f.window.emit('keydown',{key:'Escape'});assert.equal(f.document.activeElement.id,'overview')});
test('Relation role button supports Space without scrolling the page',()=>{const f=fixture();f.window.AtlasDebug.select('rpa-0062');f.step(600);const event=f.$('.edge').emit('keydown',{key:' '});assert(event.defaultPrevented);assert(f.$$('.evidence').some(e=>e.open));assert.equal(f.window.AtlasDebug.getState().selected,'rpa-0062')});

test('four broad Chinese groups cover all95 with transparent overlaps and no primary reassignment',()=>{const expected={'navigation-space':29,'motion-manipulation':46,'robot-learning':48,'methods-resources':29};assert.equal(Object.keys(D.browseLabels).length,4);for(const[key,n]of Object.entries(expected))assert.equal(D.papers.filter(p=>M.search(p,'',key,'')).length,n);assert(D.papers.every(p=>p.navigation.groups.length));const od=D.papers.find(p=>p.label.includes('ODYSSEY'));assert.equal(od.classification.direction,'mobile-manipulation');assert(od.navigation.groups.includes('motion-manipulation'));for(const id of ['rpa-0008','rpa-0018','rpa-0046','rpa-0058'])assert.deepEqual(D.papers.find(p=>p.id===id).navigation.groups,['methods-resources'])});
test('browse and source-backed method filtering intersect without hiding all95 context',()=>{const f=fixture();f.$('#task').value='motion-manipulation';f.$('#method').value='WBC';f.window.AtlasDebug.filter();assert.equal(f.$$('.node').length,95);const state=f.window.AtlasDebug.getState();assert(state.matching.includes('rpa-0062'));state.matching.forEach(id=>assert(D.papers.find(p=>p.id===id).methods.includes('WBC')));assert.equal(f.$('#task').options.length,5)});

test('optional methods and resources form independent axes and clear together',()=>{const f=fixture();assert.equal(f.$('#commonMethods').children.length,6);const chip=f.$('#commonMethods').children.find(b=>b.dataset.method==='WBC');chip.emit('click');assert.equal(f.$('#method').value,'WBC');assert.equal(chip.getAttribute('aria-pressed'),'true');f.$('#resource').value='dataset';f.window.AtlasDebug.filter();f.window.AtlasDebug.getState().matching.forEach(id=>{const p=D.papers.find(p=>p.id===id);assert(p.methods.includes('WBC'));assert(p.classification.resourceKinds.includes('dataset'))});f.click('#clear');assert.equal(f.$('#resource').value,'');assert.equal(f.$('#method').value,'');assert.equal(f.window.AtlasDebug.getState().matching.length,95)});

test('null-primary resources remain resources in detail, not research directions',()=>{const f=fixture();for(const id of ['rpa-0022','rpa-0032','rpa-0039','rpa-0045','savva2019habitat','ramakrishnan2021hm3d','yadav2023hm3dsem']){const p=D.papers.find(p=>p.id===id);assert.equal(p.classification.direction,null);f.window.AtlasDebug.select(id);assert.match(f.$('#detail').textContent,/跨领域资源/)}f.window.AtlasDebug.select('holoagent-0');assert.match(f.$('#detail').textContent,/跨领域研究/)});
test('global text search uses order-independent AND terms like Library',()=>{const p=D.papers.find(p=>p.id==='rpa-0062');assert(M.search(p,'legs umi','',''));assert(M.search(p,'  umi   legs  ','',''));assert(!M.search(p,'umi nonexistentword','',''))});

test('UMI abbreviation includes original UMI without losing existing family matches',()=>{
 const matches=D.papers.filter(p=>M.search(p,'UMI','','')).map(p=>p.id);assert.equal(matches.length,3);
 for(const id of ['rpa-0064','rpa-0062','rpa-0017'])assert(matches.includes(id),id+' should match UMI');
 const f=fixture();f.input('UMI');for(const id of ['rpa-0064','rpa-0062','rpa-0017'])assert(f.window.AtlasDebug.getState().matching.includes(id));
});
test('narrow selection shows only selected and hovered or focused labels, retaining all relation evidence',()=>{
 const f=fixture({mobile:true,width:390,height:844,reduced:true});f.window.AtlasDebug.select('rpa-0062');
 const labels=()=>f.$$('.node-label').filter(n=>n.textContent);
 assert.equal(labels().length,1);assert.equal(labels()[0].parentElement.dataset.id,'rpa-0062');
 assert.equal(f.$$('.node').length,95);assert.equal(f.$$('.edge').length,8);assert.equal(f.$$('.relation').length,8);assert.equal(f.$$('.evidence').length,12);
 const other=f.$('.node[data-id="rpa-0064"]');other.emit('pointerenter',{clientX:150,clientY:200});assert.equal(labels().length,2);other.emit('pointerleave');assert.equal(labels().length,1);
 other.focus();assert.equal(labels().length,2);other.emit('blur',{bubbles:false});assert.equal(labels().length,1);
 f.context.innerWidth=1440;f.context.innerHeight=900;f.window.emit('resize');assert.equal(labels().length,9);
 f.context.innerWidth=390;f.context.innerHeight=844;f.window.emit('resize');assert.equal(labels().length,1);assert.equal(f.$$('.edge').length,8);
});
