"""Regenerate the three text alternatives from the reviewed public graph snapshot.

This opt-in maintenance command does not read new sources, alter evidence or
update the frozen publication manifest. Review generated bytes before resealing.
"""
from pathlib import Path
from html import escape
import argparse
import json
import ipaddress
from urllib.parse import urlsplit
import re

ROOT=Path(__file__).resolve().parents[1]
CLASS_LABELS={'direct_harness':'直接harness / 运行框架','supporting_method':'支撑方法','benchmark_protocol':'任务与评测协议','unclassified_candidate':'分类待核'}
ATTR_LABELS={'author_claim':'作者主张','direct_observation':'原文核读','curator_summary':'编辑归纳','curator_inference':'编辑推断','curator_organization':'编辑组织'}

def e(value):return escape(str(value),quote=True)
def para(value,cls=''):return '<p'+(' class="'+e(cls)+'"' if cls else '')+'>'+e(value)+'</p>'
def safe_link(url):
    if not isinstance(url,str) or not url or any(ord(c)<32 or ord(c)==127 for c in url) or '\\' in url:
        raise ValueError('Unsafe Radar text URL')
    u=urlsplit(url)
    if u.scheme or u.netloc:
        if u.scheme!='https' or not u.hostname or u.username is not None or u.password is not None:
            raise ValueError('External Radar text URLs require credential-free HTTPS')
        if u.port not in (None,443) or u.hostname in {'localhost','localhost.localdomain'} or u.hostname.endswith(('.localhost','.local','.internal','.invalid')):
            raise ValueError('External Radar text URLs must be public')
        try:
            if not ipaddress.ip_address(u.hostname).is_global:raise ValueError('Non-public IP URL')
        except ValueError as exc:
            if str(exc)=='Non-public IP URL':raise
            # A DNS hostname is allowed; literal non-public addresses are rejected above.
            if re.fullmatch(r'[0-9.]+',u.hostname):raise ValueError('Invalid IP URL') from exc
    elif u.path.startswith('/') or '..' in u.path.split('/') or not re.fullmatch(r'[A-Za-z0-9_./-]*',u.path):
        raise ValueError('Internal Radar text URLs require safe relative paths')
    return url

def link(url,label):return '<a href="'+e(safe_link(url))+'">'+e(label)+'</a>' 
def paper_link(p):return link('challenge.html#paper-'+p['canonical_id'],p['short_name'])
def overview(p):
    if p.get('abstract_summary_zh'):
        return '<b>摘要中文概述 · 编辑归纳</b>'+para(p['abstract_summary_zh'])
    if p.get('overview_zh'):
        return '<b>'+e(p.get('overview_label_zh','研究概述'))+' · 编辑归纳</b>'+para(p['overview_zh'])+para(p.get('overview_scope_note_zh',''),'muted')
    return para('研究概述待补；请以已列原文证据与来源范围为准。','muted')
def source_details(p):
    evidence=''.join('<li><b>'+e(ATTR_LABELS.get(x['attribution'],x['attribution']))+' · '+e(x['locator'])+'</b>'+para(x['statement'])+'</li>' for x in p['evidence'])
    return ('<details><summary>原文证据、阅读范围与限制</summary>'+link(p['source_url'],p['version'])+
        para('实际核读：'+'；'.join(p['read_locations']))+para('未核：'+'；'.join(p['not_read']))+
        '<ol>'+evidence+'</ol>'+para(p['limits'])+
        '<ul>'+''.join('<li>'+e(c)+'</li>' for c in p.get('conditions',[]))+'</ul></details>')
def navigation(current):
    items=[('index.html','双树入口'),('reading-overview.html','阅读总览'),('literature.html','文献脉络'),('challenge.html','问题与解法'),('weekly-2026-10-04.html','原周窗快照')]
    return '<nav aria-label="研究双树">'+''.join('<a href="'+u+'"'+(' aria-current="page"' if current==u else '')+'>'+label+'</a>' for u,label in items)+'</nav>'
def footer(data):
    return '<footer>'+e('隔离预览 · 内容核查 '+data['checked_at']+' · 图 revision '+str(data['graph_revision']))+'<br>'+e('数据基线 main '+data['expansion_provenance']['baseline_commit'])+'<br>'+e('既有日报、周报、正式目录与阅读阶段未改；本页不代表全文精读、独立复现或正式阅读档案登记。')+'</footer>'
def scope(data):
    c=data['coverage'];counts=c['classification_counts']
    return ('<aside class="note" data-baseline-count="'+str(c['baseline_unique_papers'])+'">'+
        '<b>'+e(f"当前基线收录 {c['baseline_unique_papers']} 篇；旧周窗定位 {c['weekly_unique_papers']} 篇；跨范围按论文 ID 去重 {c['all_scopes_unique_papers']} 篇。")+'</b>'+
        para(f"基线分类：直接harness / 运行框架 {counts.get('direct_harness',0)}；支撑方法 {counts.get('supporting_method',0)}；任务与评测协议 {counts.get('benchmark_protocol',0)}。均为有边界的编辑组织。")+
        para('基线仅核指定正文范围；论文数、筛选匹配数与图中可见数不同，折叠项仍已收录。')+
        para('原候选池未完整恢复，历史28条声明不作当前分母；未宣称全领域覆盖或全池核验。学术边为0，同论文跨树连线不表示引用或继承。')+'</aside>')
def envelope(base,name,title,body):
    source=(base/name).read_text()
    head=source.split('<body>',1)[0]
    head=re.sub(r'<title>.*?</title>','<title>'+e(title)+' · Radar</title>',head,flags=re.S)
    return head+'<body><main>'+navigation(name)+'<div class="eyebrow">RADAR / RESEARCH TREES · ISOLATED PREVIEW</div><h1>'+e(title)+'</h1>'+body+'</main></body></html>\n'

def render(base):
    data=json.loads((base/'data/graph-data.json').read_text());papers=data['papers'];routes={x['id']:x for x in data['routes']};tasks={x['id']:x for x in data['tasks']}
    intro=para('从已核公开记录理解任务、方法和证据；直接运行框架、支撑方法与评测协议分别标注。缺少分支不是研究空白。','lead')
    intro+=para(data['method_reference']['note'],'muted')+link(data['method_reference']['url'],data['method_reference']['label'])
    # Task → route memberships, with one stable paper evidence anchor per identity.
    parts=[intro,scope(data)];used_routes=set()
    for task in data['tasks']:
        matched=[p for p in papers if task['id'] in p['tasks']]
        parts.append('<section id="'+e(task['id'])+'" class="branch"><h2>'+e(task['full_label'])+'</h2>'+para(f'{len(matched)} 篇独立论文；多任务归属可重叠。','muted')+'<div class="paths">')
        for route in data['routes']:
            matches=[p for p in matched if route['id'] in p['routes']]
            if not matches:continue
            anchor=route['id'] if route['id'] not in used_routes else task['id']+'-'+route['id'];used_routes.add(route['id'])
            parts.append('<details class="pathitem" id="'+e(anchor)+'" open><summary>'+e(route['full_label'])+' · '+str(len(matches))+' 篇</summary>')
            for p in matches:
                parts.append('<div data-paper-id="'+e(p['canonical_id'])+'"><p>'+paper_link(p)+' · '+e(p['pipeline'])+'</p><small>'+e(CLASS_LABELS[p['harness_relation']['kind']]+'；模块 / 表示：'+p['module']+'；'+p['representation'])+'</small></div>')
            parts.append('</details>')
        parts.append('</div></section>')
    parts.append('<aside class="note">'+e('周窗仍独立保留原摘要范围；后来增加基线正文记录不会倒改过去的阅读范围。')+' '+link('weekly-2026-10-04.html','查看原周窗定位')+'</aside>'+footer(data))
    output={'literature.html':envelope(base,'literature.html','文献脉络：任务如何连接方法',''.join(parts))}
    # Canonical evidence cards, never inferred citation edges or full-read states.
    parts=[para('逐篇看研究问题、解释线索、实现路线与原文证据。作者主张、原文核读和编辑归纳分别显示；原文核读不代表独立验证作者实验。','lead'),scope(data)]
    for p in papers:
        parts.append('<article id="paper-'+e(p['canonical_id'])+'" class="paper" data-paper-id="'+e(p['canonical_id'])+'"><h2>'+e(p['short_name'])+'</h2>'+para(p['title'],'muted')+overview(p))
        parts.append('<p><span class="badge">'+e(CLASS_LABELS[p['harness_relation']['kind']])+'</span><span class="badge">指定正文段落</span></p>'+para(p['harness_relation']['basis'],'muted'))
        pairs=[('Challenge · 编辑问题',p['challenge']),('Insight · 编辑归纳',p['insight']),('Approach · 方法路线',p['pipeline']),('Open question · 待核问题',p['open_question'])]
        parts.append('<ol class="chain">'+''.join('<li><b>'+e(label)+'</b>'+para(value)+'</li>' for label,value in pairs)+'</ol>')
        parts.append(source_details(p)+'<p>'+link('index.html','返回交互双树')+' · '+link('literature.html#'+p['tasks'][0],'查看所属任务')+'</p></article>')
    parts.append(para('旧周窗只按原摘要证据解释；与基线同身份的论文仍保留各自版本、时间和阅读范围。','warn')+footer(data))
    output['challenge.html']=envelope(base,'challenge.html','问题与解法：让每条思路接上证据',''.join(parts))
    # Reading overview includes all current identities and unchanged historical windows.
    parts=[intro,scope(data),'<div class="cards">']
    for task in data['tasks']:
        n=sum(task['id'] in p['tasks'] for p in papers)
        parts.append('<article class="card"><h2>'+link('literature.html#'+task['id'],task['label'])+'</h2>'+para(task['full_label'])+para(f'{n} 篇当前基线论文；跨任务归属不作简单相加。','muted')+'</article>')
    parts.append('</div><h2>当前基线论文与研究概述</h2><div class="cards">')
    for p in papers:
        parts.append('<article class="card" data-paper-id="'+e(p['canonical_id'])+'"><h3>'+paper_link(p)+'</h3>'+overview(p)+'<p><span class="badge">'+e(CLASS_LABELS[p['harness_relation']['kind']])+'</span></p>'+link(p['source_url'],p['version'])+'</article>')
    parts.append('</div>')
    for key,label in [('daily','原日报'),('weekly','原周报')]:
        p=data[key];parts.append('<aside class="note"><b>'+e(label+' '+p['date']+'：'+str(p['candidate_count'])+' 条候选')+'</b>'+para(p['window']['start']+' → '+p['window']['end']+'（UTC）；保持原观察窗口，不称本日新增。'))
        if key=='weekly':parts.append(para(f"{p['abstract_count']} 条完整摘要；{len(p['mapping_ids'])} 篇原摘要定位，{len(p['unmapped_abstracts'])} 篇未映射。")+link('weekly-2026-10-04.html','原周窗证据与定位'))
        else:parts.append(link('https://chunhui-lab.github.io/RoboPaperAtlas/frontier/briefs/'+p['date']+'/','原日报'))
        parts.append('</aside>')
    parts.append(footer(data));output['reading-overview.html']=envelope(base,'reading-overview.html','从领域脉络，看见问题与解法',''.join(parts))
    return output

def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args();base=ROOT/'previews/radar-trees-c'
    output=render(base)
    if args.check:
        mismatches=[name for name,content in output.items() if (base/name).read_text()!=content]
        if mismatches:raise SystemExit('Stale text alternatives: '+', '.join(mismatches))
        print('Three Radar text alternatives match the same reviewed graph snapshot')
    else:
        for name,content in output.items():(base/name).write_text(content)
        print('Generated three text alternatives; review before updating the frozen manifest')
if __name__=='__main__':main()
