(function(){'use strict';
const M=window.TreeModel,$=id=>document.getElementById(id),e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeLabel={task_contract:'任务 / 契约',pipeline:'Pipeline',representation:'Representation',module:'Module',protocol:'任务 / 协议来源',paper_ref:'具体论文',challenge:'共同 Challenge',insight:'不同 Insight'};
const attribution={author_method_paraphrase:'作者方法的定向转述',author_claim:'作者主张',direct_observation:'原文核读',curator_summary:'编辑归纳',curator_organization:'编辑组织',curator_summary_of_reviewed_sections:'已读段落的编辑归纳',editorial_synthesis:'跨文献编辑归纳',editorial_synthesis_of_distinct_author_methods:'不同作者方法的编辑归纳'};
let model,state,opener=null;const scrollPositions={},branchScroll={};
const scope=p=>p.read_scope==='section'?'指定正文段落':p.read_scope==='abstract'||p.source_scope==='primary_complete_abstract'?'完整摘要':'来源范围见记录';
const list=xs=>'<ul>'+(xs||[]).map(x=>'<li>'+e(x)+'</li>').join('')+'</ul>';
const sourceLink=(url,label)=>/^https:\/\//.test(url||'')?'<a href="'+e(url)+'" target="_blank" rel="noopener noreferrer">'+e(label||'固定版本原文')+' ↗</a>':'<span>来源链接待补</span>';
const notice=s=>'<div class="notice">'+e(s)+'</div>';
function evidenceCard(ev,paper){return '<article class="evidence-card"><div class="evidence-kind">'+e(attribution[ev.attribution]||'指定证据记录')+'</div><p>'+e(ev.statement||ev.claim||'')+'</p><div class="locator">'+e(ev.locator||'精确位置待补')+'</div>'+sourceLink(ev.source_url||paper?.source_url,'阅读来源')+'<div class="provenance">'+e(ev.newly_checked||ev.verification_origin?.startsWith('primary_')?'本轮定向核查；不代表全文通读':ev.verification_origin?.includes('finer')?'复用既有概述；该主张定位仍待细化':'复用既有已读范围；未独立复现实验')+'</div></article>';}
// Render existing definition records, never infer firstness from a nonempty scope string.
function taskOriginRecords(node){
 const o=node.origin||{},hasText=x=>typeof x==='string'&&x.trim().length>0;
 return [o,...(Array.isArray(o.milestones)?o.milestones:[])].filter(r=>r&&(hasText(r.title)||hasText(r.name)||hasText(r.task_definition)||hasText(r.task_definition?.summary)));
}
function statusLabel(node){if(node.type==='task_contract')return taskOriginRecords(node).length?'有任务 / 协议来源记录 · 首创未核实':'起源 / 首创待核';if(node.type==='paper_ref')return '';if(node.status==='pending')return '待核候选';return '';}
function taskOriginHtml(n){
 const records=taskOriginRecords(n),o=n.origin||{};
 let html=records.length?records.map(r=>{
  let row='<p><b>任务 / 协议来源记录：</b>'+e(r.title||r.name||'定义记录')+'</p>';
  const definition=typeof r.task_definition==='string'?r.task_definition:r.task_definition?.summary;
  if(definition)row+='<p>'+e(definition)+'</p>';
  if(r.benchmark_origin?.summary)row+='<p>'+e(r.benchmark_origin.summary)+'</p>';
  if(r.firstness?.supported)row+='<p><b>原记录支持范围：</b>'+e(r.firstness.supported)+'</p>';
  if(r.firstness?.not_supported?.length)row+='<p><b>不支持的首创扩展：</b></p>'+list(r.firstness.not_supported);
  if(r.boundary)row+='<p>'+e(r.boundary)+'</p>';
  const sourceIds=[...new Set([r.task_definition?.source_id,r.benchmark_origin?.source_id].filter(Boolean))];
  const evidence=sourceIds.map(id=>model?.trees.l.evidence.get('root-source-'+id)).filter(Boolean);
  const links=[r.formal_url,r.read_url,...evidence.map(ev=>ev.source_url)].filter(url=>/^https:\/\//.test(url||''));
  const locators=[...new Set([r.locator,r.task_definition?.locator,r.benchmark_origin?.locator,...evidence.map(ev=>ev.locator)].filter(Boolean))];
  if(locators.length)row+='<div class="locator">'+locators.map(e).join('；')+'</div>';
  row+=[...new Set(links)].map(url=>sourceLink(url,'任务 / 协议原始来源')).join(' ')||'<p>来源链接待补；不可据此确认首创</p>';
  return row;
 }).join(''):'<p><b>任务来源：</b>原始定义来源待核</p>';
 if(o.first_claim_scope)html+='<p><b>原记录的首创范围说明（含限制）：</b>'+e(o.first_claim_scope)+'</p>';
 html+='<p><b>全领域优先权：</b>尚未核实；任务或 benchmark 定义来源不等于全领域首创证明</p>';
 if(o.caveat)html+='<p>'+e(o.caveat)+'</p>';
 return html;
}
function contractHtml(n){if(!n)return '';let html='';if(n.type==='task_contract'){html='<dl class="contract">'+[['目标',n.goal_spec],['动作',n.action_regime],['记忆',n.memory_regime],['成功',n.success_contract]].filter(x=>x[1]).map(([k,v])=>'<dt>'+e(k)+'</dt><dd>'+e(v)+'</dd>').join('')+'</dl>'+taskOriginHtml(n);}else{if(n.task_conditions?.length)html+='<p><b>任务条件</b></p>'+list(n.task_conditions);if(n.testable_difficulty)html+='<p>'+e(n.testable_difficulty)+'</p>';if(n.conditions?.length)html+=list(n.conditions);if(n.comparison_guardrails?.length)html+='<p><b>比较边界</b></p>'+list(n.comparison_guardrails);if(n.distinction_from_siblings)html+='<p>'+e(n.distinction_from_siblings)+'</p>';}return html;}
function renderTree(key){const b=M.branch(model,state,key),isL=key==='l',title=isL?'文献脉络树':'Challenge–Insight 树',treeName=isL?'文献树':'Challenge 树';
 const breadcrumbs='<nav class="breadcrumbs" aria-label="'+treeName+'当前路径"><button type="button" data-action="crumb" data-key="'+key+'" data-depth="0">总览</button>'+b.prefix.map((id,i)=>'<span class="crumb-separator" aria-hidden="true">›</span><button type="button" '+(i===b.prefix.length-1?'class="current" aria-current="page" ':'')+'data-action="crumb" data-key="'+key+'" data-depth="'+(i+1)+'">'+e(b.tree.nodes.get(id)?.label||id)+'</button>').join('')+'</nav>';
 const p=b.parent,concept=p?.concept_id?b.tree.raw.concept_catalog?.find(c=>c.concept_id===p.concept_id):null,rootLabel=isL?'从一个明确的任务契约开始':'先选一个领域共同困难',pLabel=p?.label||rootLabel;
 const containsSelected=!!state.paper&&M.matchingPaths(b.tree,b.prefix,key==='l'?state.lFacet:undefined).some(path=>path.paperId===state.paper);
 let parent='<div class="parent-node '+(!isL?'challenge':'')+(containsSelected?' selected-path':'')+'"><div class="node-type">'+e(p?typeLabel[p.type]:'总览')+(p&&statusLabel(p)?'<span class="status">'+e(statusLabel(p))+'</span>':'')+'</div><h3>'+e(pLabel)+'</h3>';
 if(concept?.common_property)parent+='<p class="node-summary">'+e(concept.common_property)+'</p><p class="scope-small">'+(concept.shared_across_papers?'共享比较轴；下层保留各论文实现差异':'当前语料中的具体实现；不据此声称领域首创')+'</p>';
 if(p?.key_recognition)parent+='<p class="node-summary"><b>关键认识：</b>'+e(p.key_recognition)+'</p>';if(p?.why_it_addresses_challenge)parent+='<p class="node-summary"><b>为什么：</b>'+e(p.why_it_addresses_challenge)+'</p><p class="scope-small">'+(p.rationale?.author_rationale_anchors?.length?'编者综合；有部分作者论证锚点，逐篇见依据':'编者解释 · 作者是否如此论证待核')+'</p>';if(p?.mechanism)parent+='<details><summary>实现机制</summary><p>'+e(p.mechanism)+'</p></details>';
 if(!p)parent+='<p class="node-summary">'+(isL?'目标、动作、记忆跨度和成功契约决定任务边界。每次只展开下一层。':'同一困难下保留不同解决原则，以及各论文具体机制与适用条件。')+'</p>';
 const contract=contractHtml(p);if(contract)parent+='<details><summary>'+(p.type==='task_contract'?'任务条件、定义来源与首创范围':'任务条件与比较边界')+'</summary>'+contract+'</details>';
 parent+='</div>';
 if(!isL&&!p&&b.tree.raw.coverage?.insights_with_editorial_rationale_pending_author_check)parent+='<p class="legend-mini">'+b.tree.raw.coverage.distinct_insight_nodes+' 条候选 insight；其中 '+b.tree.raw.coverage.insights_with_editorial_rationale_pending_author_check+' 条 why 为编者解释，仍待作者论证核对</p>';
 let body=parent;if(b.all.length>1)body+='<label class="layer-jump">本层完整目录（'+b.total+' 项）<select data-layer-jump="'+key+'"><option value="">直接选择任意子项…</option>'+b.all.map(item=>'<option value="'+e(item.node.id)+'">'+e(item.node.label)+' · '+item.paperIds.length+' 篇</option>').join('')+'</select></label>';
 if(!b.items.length)body+='<div class="empty">'+(b.tree.paths.length?'当前39篇尚无此分支的方法挂载；上方保留任务契约及来源状态。':'已审路径尚未接入，此树不以旧宽泛分类占位。')+'</div>';
 else body+='<ol class="branch-list '+(containsSelected?'selected-path':'')+'">'+b.items.map(item=>{const n=item.node,isPaper=n.type==='paper_ref',paper=isPaper?model.papers.get(n.paper_id):null,selected=isPaper&&state.paper===n.paper_id;let summary=isPaper?(item.paths[0]?.variant?.method_claim||item.paths[0]?.implementationVariant?.modules_original||item.paths[0]?.implementationVariant?.label||paper.version+' · '+scope(paper)):n.type==='task_contract'?[n.goal_spec,n.action_regime].filter(Boolean).join(' · '):n.key_recognition||n.mechanism||'';const precision=item.paths.some(p=>p.status?.includes('finer_locator'))?'部分定位待细化':'';return '<li class="'+(item.paperIds.includes(state.paper)?'selected-path':'')+'"><button class="node '+(selected?'active':item.paperIds.includes(state.paper)?'related':'')+'" type="button" data-action="enter" data-key="'+key+'" data-id="'+e(n.id)+'" '+(selected?'aria-current="true"':'')+'><span class="node-type">'+e(typeLabel[n.type]||n.type)+(precision?'<span class="status pending">'+precision+'</span>':'')+'</span><strong>'+e(n.label)+'</strong>'+(summary?'<span class="node-summary">'+e(summary)+'</span>':'')+'<span class="node-footer"><span>'+(isPaper?'读证据':item.paperIds.length+' 篇候选归属 · 展开下一层')+'</span><span class="node-arrow" aria-hidden="true">'+(isPaper?'↗':'→')+'</span></span></button></li>';}).join('')+'</ol>';
 const evs=(p?.evidence_ids||[]).map(id=>b.tree.evidence.get(id)).filter(Boolean);if(evs.length)body+='<details class="node-evidence"><summary>当前节点依据（'+evs.length+' 条）</summary>'+evs.map(ev=>evidenceCard(ev)).join('')+'</details>';
 const controls='<div class="pager"><div class="panel-back"><button type="button" data-action="back" data-key="'+key+'" '+(!b.prefix.length?'disabled':'')+' aria-label="'+treeName+'返回上一层">← 返回</button></div><span>当前分支 '+b.paperCount+' 篇<br>本层 '+(b.total?b.page*M.PAGE_SIZE+1:0)+'–'+Math.min(b.total,(b.page+1)*M.PAGE_SIZE)+' / '+b.total+' 项 · 其余 '+Math.max(0,b.total-b.items.length)+' 项</span><div class="panel-back"><button type="button" data-action="page" data-key="'+key+'" data-page="'+(b.page-1)+'" '+(!b.page?'disabled':'')+' aria-label="'+treeName+'上一页">‹</button><button type="button" data-action="page" data-key="'+key+'" data-page="'+(b.page+1)+'" '+(b.page>=b.maxPage?'disabled':'')+' aria-label="'+treeName+'下一页">›</button></div></div>';
 $('tree-'+key).innerHTML='<header class="panel-head"><h2 id="title-'+key+'"><span class="tree-symbol" aria-hidden="true">'+(isL?'⌑':'♧')+'</span>'+title+'</h2><p>'+(isL?'milestone task → pipeline / representation → module → 论文':'领域共同 challenge → 不同 insight → 论文证据')+'</p>'+(isL?'<div class="facet-controls" aria-label="文献树查看切面">'+[['pipeline','按 Pipeline'],['representation','按 Representation']].map(([id,label])=>'<button type="button" data-action="facet" data-facet="'+id+'" aria-pressed="'+(state.lFacet===id)+'" class="'+(state.lFacet===id?'active':'')+'">'+label+'</button>').join('')+'</div>':'')+'</header>'+breadcrumbs+'<div class="tree-body" id="body-'+key+'" tabindex="0" role="region" aria-label="'+treeName+'当前层">'+body+'</div>'+controls;
}
function pathContext(){if(!state.origin)return null;const tree=model.trees[state.origin.key];return tree.paths.find(p=>p.paperId===state.paper&&p.nodeIds.length===state.origin.path.length&&M.startsWith(p.nodeIds,state.origin.path));}
function pathGroups(items,key){if(!items.length)return '<p>此树尚未接入该论文的已整理路径；记录仍在全量列表中。</p>';const groups=new Map();for(const p of items){const root=p.nodeIds[0];if(!groups.has(root))groups.set(root,[]);groups.get(root).push(p);}return [...groups.entries()].map(([root,paths])=>{const label=model.trees[key].nodes.get(root)?.label||root;const buttons=paths.map(path=>'<button type="button" class="path-button" data-action="path" data-key="'+key+'" data-id="'+e(path.id)+'"><span class="path-tree">'+(key==='l'?(path.viewKind==='representation'?'Representation 切面':path.viewKind==='protocol'?'任务 / 协议来源':'Pipeline 切面'):'Challenge → Insight')+' · 展开此路径 →</span>'+path.labels.map(e).join(' › ')+'</button>').join('');return paths.length>1?'<details class="membership-group"><summary>'+e(label)+' · 全部 '+paths.length+' 条归属</summary>'+buttons+'</details>':buttons;}).join('');}
function renderPaper(){const p=model.papers.get(state.paper);if(!p){$('paper-panel').innerHTML='<div class="read-start"><p class="eyebrow">论文证据</p><h2 id="paper-title">两棵树，共用一份证据</h2><p>逐层选择后，这里打开具体论文。不会在左右两侧各放一个相隔很远的副本。</p><ol><li>选择任务，进入 pipeline、representation 和 module</li><li>或选择共同 challenge，对照不同 insight</li><li>读论文证据，并查看同篇的其他归属</li></ol><p>也可直接搜索全部 39 篇，包括尚未完成结构审核的记录。</p><a href="all-papers.html">打开全量文字替代 ↗</a></div>';return;}
 const origin=state.origin?(state.origin.key==='l'?'文献树':'Challenge 树')+' · '+state.origin.path.slice(0,-1).map(id=>model.trees[state.origin.key].nodes.get(id)?.label||id).join(' › '):'来自全量论文列表';
 let content='',ctx=pathContext();const supplements=[];const supplementKeys=new Set();for(const tree of Object.values(model.trees)){const refs=new Set(tree.paths.filter(path=>path.paperId===p.canonical_id).flatMap(path=>path.evidenceIds));for(const ev of tree.evidence.values()){if((ev.paper_id===p.canonical_id||refs.has(ev.evidence_id))&&(ev.newly_checked||ev.verification_origin?.startsWith('primary_'))){const id=[ev.source_url,ev.locator,ev.statement||ev.claim].join('|');if(!supplementKeys.has(id)){supplementKeys.add(id);supplements.push(ev);}}}}
 if(state.tab==='analysis'){content=notice(p.canonical_id==='harnessvln'?'C2 · 总览与焦点树 · 本地样例':'本篇论文解析树待建立')+'<section class="detail-section"><h3>'+e(p.canonical_id==='harnessvln'?'HarnessVLN 原方法解析样例':'可先查看原模板结构')+'</h3><p>'+(p.canonical_id==='harnessvln'?'59个原模板节点与13个论文实例。证据回答、作者主张及6项未答分别保留；没有改变原有Stage。':'当前只有原目录及已读范围，尚无本篇全文解析。不会复制HarnessVLN的答案。')+'</p><a class="quiet c2-open-link" href="analysis/reading.html#paper-'+e(p.canonical_id)+'" data-open-analysis="'+e(p.canonical_id)+'">'+(p.canonical_id==='harnessvln'?'打开C2解析树 →':'打开原模板（本篇待建立） →')+'</a></section>';}
 if(state.tab==='overview'){content='<section class="detail-section"><h3>'+e(p.overview_label_zh||'研究概述')+'</h3><p>'+e(p.overview_zh||p.abstract_summary_zh||'此记录尚无概述；请查看证据。')+'</p><p class="scope-small">'+e(p.overview_scope_note_zh||'编辑归纳；并非全文翻译')+'</p></section><section class="detail-section"><h3>原记录的方法概述</h3><p><b>Pipeline：</b>'+e(p.pipeline)+'</p><p><b>Representation：</b>'+e(p.representation)+'</p><p><b>Module：</b>'+e(p.module)+'</p></section><section class="detail-section"><h3>适用条件与局限</h3>'+list(p.conditions||[])+'<p>'+e(p.limits)+'</p></section>';}
 if(state.tab==='evidence'){
  content=notice(scope(p)+'；'+(p.evidence||[]).length+' 条原记录证据。全文通读、代码运行与独立复现均不能由这些记录推定。');
  if(supplements.length)content+='<section class="detail-section"><h3>本轮结构核查补充</h3>'+supplements.map(ev=>evidenceCard(ev,p)).join('')+'</section>';
  if(ctx?.implementationVariant){const v=ctx.implementationVariant;content+='<section class="detail-section"><h3>此路径对应的论文实现</h3><p><b>'+e(v.label)+'</b></p>'+(v.kind==='named_baseline_comparison_variant'?'<p>'+e(v.pipeline)+'</p>':'')+'<p>'+e(v.representation_original||v.representation)+'</p><p>'+e(v.modules_original||(v.modules||[]).join('；'))+'</p><p><b>角色 / 边界：</b>'+e(v.scope_note)+'</p></section>';}
  if(ctx?.variant){const v=ctx.variant;content+='<section class="detail-section"><h3>当前 insight 下的具体方法变体</h3><p>'+e(v.method_claim||v.mechanism_variant)+'</p><p><b>适用边界：</b>'+e(v.boundary)+'</p>'+(v.rationale_status?'<p><b>此论文的 why 依据：</b>'+e(v.rationale_anchor_refs?.length?'有作者论证锚点；共同表述仍为编辑综合':'作者论证待核，当前为编辑解释')+'</p>':'')+'<p><b>与共同问题的关系：</b>'+e({direct:'直接处理该问题',adjacent:'相邻问题或不同表示；不可直接同协议比较',protocol:'协议 / 评测依据'}[v.relation_to_challenge]||v.relation_to_challenge)+'</p></section>';}
  if(ctx?.evidenceIds.length){content+='<section class="detail-section"><h3>当前归属的定位依据</h3>'+ctx.evidenceIds.map(id=>model.trees[state.origin.key].evidence.get(id)).filter(Boolean).map(ev=>evidenceCard(ev,p)).join('')+'</section>';}
  content+='<section class="detail-section"><h3>原记录全部证据</h3>'+(p.evidence||[]).map(ev=>evidenceCard(ev,p)).join('')+'</section><section class="detail-section"><h3>读到哪里 / 尚未核什么</h3>'+list(p.read_locations||[])+list(p.not_read||[])+'</section>';
 }
 if(state.tab==='paths'){const paths=M.pathsForPaper(model,p.canonical_id);content=notice('同篇可同时服务多个任务或共同问题。以下只导航既有合法完整路径，不表示学术继承。');for(const key of ['l','c']){const items=paths.filter(x=>x.key===key);content+='<section class="detail-section"><h3>'+(key==='l'?'文献脉络树':'Challenge–Insight 树')+' · '+items.length+' 个归属</h3>'+pathGroups(items,key)+'</section>';}}
 $('paper-panel').innerHTML='<header class="paper-head"><div class="node-type">同一 canonical 论文</div><h2 id="paper-title" tabindex="-1">'+e(p.short_name)+'</h2><button type="button" class="close" data-action="closePaper" aria-label="关闭论文证据并返回原位置">×</button><p class="full-title">'+e(p.title)+'</p><div class="meta">'+e(p.version)+' · '+e(scope(p))+'</div><p class="origin-label">'+e(origin)+'</p></header><div class="paper-tabs" role="tablist" aria-label="论文内容">'+[['evidence','证据'],['overview','概述'],['paths','其他归属'],['analysis','论文解析树']].map(([id,label])=>'<button type="button" role="tab" id="tab-'+id+'" aria-controls="paper-body" aria-selected="'+(state.tab===id)+'" tabindex="'+(state.tab===id?'0':'-1')+'" class="'+(state.tab===id?'active':'')+'" data-action="tab" data-tab="'+id+'">'+label+'</button>').join('')+'</div><div class="paper-body" id="paper-body" role="tabpanel" tabindex="0" aria-labelledby="tab-'+e(state.tab)+'">'+content+sourceLink(p.source_url,'打开固定版本论文')+'</div>';
}
function renderCatalog(){const results=M.catalogResults(model,state.query),maxPage=Math.max(0,Math.ceil(results.length/M.CATALOG_PAGE_SIZE)-1),page=Math.min(state.pages.catalog,maxPage),items=results.slice(page*M.CATALOG_PAGE_SIZE,(page+1)*M.CATALOG_PAGE_SIZE);$('catalog-panel').innerHTML='<header class="catalog-head"><h2 id="catalog-title" tabindex="-1">全部论文</h2><p>总收录 '+model.papers.size+' 篇 · 搜索结果 '+results.length+' 篇'+(state.query?' · “'+e(state.query)+'”':'')+'</p>'+(state.query?'<button class="inline-back" type="button" data-action="clearSearch">清空搜索，恢复全部记录</button>':'')+'</header><div id="catalog-list" class="catalog-list" tabindex="0" role="region" aria-label="论文搜索结果">'+(items.length?items.map(p=>{const paths=M.pathsForPaper(model,p.canonical_id),l=paths.filter(x=>x.key==='l').length,c=paths.filter(x=>x.key==='c').length;return '<button type="button" class="paper-row '+(state.paper===p.canonical_id?'active':'')+'" data-action="paper" data-id="'+e(p.canonical_id)+'"><strong>'+e(p.short_name)+'</strong><span class="meta">'+e(p.version)+' · '+e(scope(p))+'</span><p class="paper-summary">'+e(p.overview_zh||p.abstract_summary_zh||p.title)+'</p><span class="mapping">文献树 '+l+' 条候选路径 · Challenge 树 '+c+' 条候选路径 · 读证据 →</span></button>';}).join(''):'<div class="empty"><h3>没有匹配结果</h3><p>试试论文简称、具体机制或证据里的词。清空搜索不会删除任何收录记录。</p><button type="button" class="quiet" data-action="clearSearch">恢复全部 '+model.papers.size+' 篇</button></div>')+'</div><div class="pager"><button type="button" data-action="page" data-key="catalog" data-page="'+(page-1)+'" '+(!page?'disabled':'')+'>上一页</button><span>结果 '+(results.length?page*M.CATALOG_PAGE_SIZE+1:0)+'–'+Math.min(results.length,(page+1)*M.CATALOG_PAGE_SIZE)+' / '+results.length+'</span><button type="button" data-action="page" data-key="catalog" data-page="'+(page+1)+'" '+(page>=maxPage?'disabled':'')+'>下一页</button></div>';}
function scrollKey(id){return id+'|'+(id==='body-l'?state.lFacet+'|'+state.l.join('>')+'|'+state.pages.l:id==='body-c'?state.c.join('>')+'|'+state.pages.c:id==='paper-body'?state.paper+'|'+state.tab+'|'+JSON.stringify(state.origin):state.query+'|'+state.pages.catalog);}
function saveScroll(){for(const id of ['body-l','body-c','paper-body','catalog-list'])if($(id)){scrollPositions[id]=$(id).scrollTop;branchScroll[scrollKey(id)]=$(id).scrollTop;}}
function render(action={}){const c=M.coverage(model);$('coverage').innerHTML='<span>总收录 <strong>'+c.catalog+'</strong> 篇</span><span>文献树候选挂载 <strong>'+c.literature+'</strong> 篇</span><span>Challenge 候选挂载 <strong>'+c.challenge+'</strong> 篇</span><span class="scope-note">结构候选与原有证据分开计数；不是 '+c.catalog+' 篇全文重读或首创审核完成</span>';$('tree-l').hidden=$('tree-c').hidden=state.view!=='trees';$('catalog-panel').hidden=state.view!=='catalog';$('navigation').classList.toggle('catalog-mode',state.view==='catalog');$('view-trees').classList.toggle('active',state.view==='trees');$('view-catalog').classList.toggle('active',state.view==='catalog');$('view-trees').setAttribute('aria-pressed',String(state.view==='trees'));$('view-catalog').setAttribute('aria-pressed',String(state.view==='catalog'));$('search').value=state.query;
 renderTree('l');renderTree('c');renderCatalog();renderPaper();
 const resets=new Set(action.resetScroll||[]);for(const id of ['body-l','body-c','paper-body','catalog-list'])if($(id))$(id).scrollTop=resets.has(id)?0:(branchScroll[scrollKey(id)]||0);
}
function dispatch(action,historyMode='push'){
 saveScroll();const before=state;state=M.reduce(model,state,action);if(state===before)return;
 const resets=[];if(action.type==='facet')resets.push('body-l');if(['enter','path'].includes(action.type))resets.push('body-'+action.key);if(['search','clearSearch','overview'].includes(action.type)||action.type==='page'&&action.key==='catalog')resets.push('catalog-list');if(['paper','enter','path','tab'].includes(action.type)&&(state.paper!==before.paper||state.tab!==before.tab||JSON.stringify(state.origin)!==JSON.stringify(before.origin)))resets.push('paper-body');if(action.type==='overview')resets.push('body-l','body-c','paper-body');
 if(historyMode)try{window.history[historyMode==='replace'?'replaceState':'pushState']({navigationState:state},'',M.serialize(state));}catch{}render({resetScroll:resets});
 $('announcement').textContent=action.type==='search'?M.catalogResults(model,state.query).length+' 篇搜索结果':state.paper?'已选择 '+model.papers.get(state.paper)?.short_name:'当前层已更新';
 if(['enter','paper','path'].includes(action.type)&&state.paper&&(state.paper!==before.paper||action.type==='paper'||action.type==='path')){$('paper-title')?.focus({preventScroll:true});if(window.matchMedia('(max-width:1250px)').matches)$('paper-panel').scrollIntoView({behavior:'auto',block:'start'});}
}
function restoreFocus(target){if(!target)return;const found=[...document.querySelectorAll('[data-action]')].find(el=>el.dataset.action===target.action&&el.dataset.id===target.id&&el.dataset.key===target.key&&el.dataset.depth===target.depth&&el.dataset.page===target.page);if(found&&!found.disabled){found.focus({preventScroll:true});}else if(state.view==='catalog')$('catalog-title')?.focus({preventScroll:true});else $('body-'+(target.key==='c'?'c':'l'))?.focus({preventScroll:true});}
try{
 model=M.buildModel(window.PAPER_CATALOG,window.LITERATURE_TREE,window.CHALLENGE_TREE);const errs=M.validate(model);if(errs.length)throw new Error(errs.join('; '));state=M.deserialize(model,window.location.hash);render();
 document.addEventListener('change',event=>{if(event.target.matches('[data-layer-jump]')&&event.target.value){const key=event.target.dataset.layerJump,id=event.target.value,items=M.branch(model,state,key).all,index=items.findIndex(item=>item.node.id===id),isPaper=model.trees[key].nodes.get(id)?.type==='paper_ref';dispatch({type:'page',key,page:Math.max(0,Math.floor(index/M.PAGE_SIZE))},'replace');if(isPaper)opener={action:'enter',key,id};dispatch({type:'enter',key,id});if(!isPaper)$('body-'+key)?.focus({preventScroll:true});}});
 document.addEventListener('click',event=>{const b=event.target.closest('button[data-action]');if(!b||b.disabled)return;const target={...b.dataset},action={...target,type:target.action};if(target.page!==undefined)action.page=Number(target.page);if(target.depth!==undefined)action.depth=Number(target.depth);const opensPaper=action.type==='paper'||action.type==='enter'&&model.trees[action.key]?.nodes.get(action.id)?.type==='paper_ref';if(opensPaper)opener=target;if(action.type==='path'){const p=model.trees[action.key].paths.find(path=>path.id===action.id);if(p)opener={action:'enter',key:action.key,id:p.nodeIds.at(-1)};}dispatch(action);if(action.type==='closePaper')restoreFocus(opener);else if(!['paper','path'].includes(action.type)&&!opensPaper)restoreFocus(target);});
 $('search-form').addEventListener('submit',event=>{event.preventDefault();dispatch({type:'search',query:$('search').value});$('search').focus({preventScroll:true});});
 $('search').addEventListener('search',()=>{if(!$('search').value)dispatch({type:'clearSearch'});});
 document.addEventListener('keydown',event=>{if($('c2-app')&&!$('c2-app').hidden)return;if(event.key==='Escape'&&state.paper){event.preventDefault();dispatch({type:'closePaper'});restoreFocus(opener);}const tab=event.target.closest('[role="tab"]');if(tab&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=['evidence','overview','paths','analysis'],i=tabs.indexOf(state.tab),idx=event.key==='Home'?0:event.key==='End'?tabs.length-1:(i+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length;dispatch({type:'tab',tab:tabs[idx]},'replace');$('tab-'+tabs[idx]).focus({preventScroll:true});}});
 window.addEventListener('popstate',()=>{if(window.location.hash.startsWith('#analysis='))return;saveScroll();state=M.deserialize(model,window.location.hash);render();$('announcement').textContent='已恢复浏览历史中的路径与选中论文';});
 window.NavigationPrototype={model,getState:()=>state,dispatch,render,getContext:()=>{saveScroll();return {state:JSON.parse(JSON.stringify(state)),branchScroll:{...branchScroll},scrollPositions:{...scrollPositions},windowY:window.scrollY||0};},restoreContext:context=>{state=M.sanitizeState(model,context.state);Object.assign(branchScroll,context.branchScroll||{});Object.assign(scrollPositions,context.scrollPositions||{});render();window.scrollTo?.(0,context.windowY||0);$('paper-title')?.focus({preventScroll:true});}};
}catch(err){$('load-error').hidden=false;console.error(err);}
})();
