(function(){'use strict';
const M=window.TreeModel,$=id=>document.getElementById(id),e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const typeLabel={task_contract:'任务 / 协议',pipeline:'方法流程 · Pipeline',representation:'信息表示 · Representation',module:'关键模块 · Module',protocol:'任务 / 协议来源',paper_ref:'具体论文',challenge:'共同难点 · Challenge',insight:'解法思路 · Insight'};
const attribution={author_method_paraphrase:'作者方法的定向转述',author_claim:'作者主张',direct_observation:'原文核读',curator_summary:'编辑归纳',curator_organization:'编辑组织',curator_summary_of_reviewed_sections:'已读段落的编辑归纳',editorial_synthesis:'跨文献编辑归纳',editorial_synthesis_of_distinct_author_methods:'不同作者方法的编辑归纳'};
let model,state,opener=null,atlases={};const scrollPositions={},branchScroll={},documentPositions={};
const scope=p=>p.read_scope==='section'?'指定正文段落':p.read_scope==='abstract'||p.source_scope==='primary_complete_abstract'?'完整摘要':'来源范围见记录';
const list=xs=>'<ul>'+(xs||[]).map(x=>'<li>'+e(x)+'</li>').join('')+'</ul>';
const sourceLink=(url,label)=>/^https:\/\//.test(url||'')?'<a href="'+e(url)+'" target="_blank" rel="noopener noreferrer">'+e(label||'固定版本原文')+' ↗</a>':'<span>来源链接待补</span>';
const notice=s=>'<div class="notice">'+e(s)+'</div>';
function evidenceCard(ev,paper){return '<article class="evidence-card"><div class="evidence-kind">'+e(attribution[ev.attribution]||'指定证据记录')+'</div><p>'+e(ev.statement||ev.claim||'')+'</p><div class="locator">'+e(ev.locator||'精确位置待补')+'</div>'+sourceLink(ev.source_url||paper?.source_url,'阅读来源')+'<div class="provenance">'+e(ev.newly_checked||ev.verification_origin?.startsWith('primary_')?'本轮定向核查；不代表全文通读':ev.verification_origin?.includes('finer')?'复用既有概述；该主张定位仍待细化':'复用既有已读范围；未独立复现实验')+'</div></article>';}
// Render existing definition records, never infer firstness from a nonempty scope string.
function taskOriginRecords(node){
 const o=node.origin||{},hasText=x=>typeof x==='string'&&x.trim().length>0;
 return [o,...(Array.isArray(o.milestones)?o.milestones:[])].filter(r=>r&&(hasText(r.title)||hasText(r.name)||hasText(r.task_definition)||hasText(r.task_definition?.summary)));
}
function statusLabel(node){if(node.type==='task_contract')return taskOriginRecords(node).length?'有任务 / 协议来源记录 · 首创未核实':'起源 / 首创待核';if(node.type==='paper_ref')return '';if(node.status==='pending')return '待核候选';return '';}
function taskOriginHtml(n){
 const records=taskOriginRecords(n),o=n.origin||{};
 let html=records.length?records.map(r=>{
  let row='<p><b>任务 / 协议来源记录：</b>'+e(r.title||r.name||'定义记录')+'</p>';
  const definition=typeof r.task_definition==='string'?r.task_definition:r.task_definition?.summary;
  if(definition)row+='<p>'+e(definition)+'</p>';
  if(r.benchmark_origin?.summary)row+='<p>'+e(r.benchmark_origin.summary)+'</p>';
  if(r.firstness?.supported)row+='<p><b>原记录支持范围：</b>'+e(r.firstness.supported)+'</p>';
  if(r.firstness?.not_supported?.length)row+='<p><b>不支持的首创扩展：</b></p>'+list(r.firstness.not_supported);
  if(r.boundary)row+='<p>'+e(r.boundary)+'</p>';
  const sourceIds=[...new Set([r.task_definition?.source_id,r.benchmark_origin?.source_id].filter(Boolean))];
  const evidence=sourceIds.map(id=>model?.trees.l.evidence.get('root-source-'+id)).filter(Boolean);
  const links=[r.formal_url,r.read_url,...evidence.map(ev=>ev.source_url)].filter(url=>/^https:\/\//.test(url||''));
  const locators=[...new Set([r.locator,r.task_definition?.locator,r.benchmark_origin?.locator,...evidence.map(ev=>ev.locator)].filter(Boolean))];
  if(locators.length)row+='<div class="locator">'+locators.map(e).join('；')+'</div>';
  row+=[...new Set(links)].map(url=>sourceLink(url,'任务 / 协议原始来源')).join(' ')||'<p>来源链接待补；不可据此确认首创</p>';
  return row;
 }).join(''):'<p><b>任务来源：</b>原始定义来源待核</p>';
 if(o.first_claim_scope)html+='<p><b>原记录的首创范围说明（含限制）：</b>'+e(o.first_claim_scope)+'</p>';
 html+='<p><b>全领域优先权：</b>尚未核实；任务或 benchmark 定义来源不等于全领域首创证明</p>';
 if(o.caveat)html+='<p>'+e(o.caveat)+'</p>';
 return html;
}
function contractHtml(n){if(!n)return '';let html='';if(n.type==='task_contract'){html='<dl class="contract">'+[['目标',n.goal_spec],['动作',n.action_regime],['记忆',n.memory_regime],['成功',n.success_contract]].filter(x=>x[1]).map(([k,v])=>'<dt>'+e(k)+'</dt><dd>'+e(v)+'</dd>').join('')+'</dl>'+taskOriginHtml(n);}else{if(n.task_conditions?.length)html+='<p><b>任务条件</b></p>'+list(n.task_conditions);if(n.testable_difficulty)html+='<p>'+e(n.testable_difficulty)+'</p>';if(n.conditions?.length)html+=list(n.conditions);if(n.comparison_guardrails?.length)html+='<p><b>比较边界</b></p>'+list(n.comparison_guardrails);if(n.distinction_from_siblings)html+='<p>'+e(n.distinction_from_siblings)+'</p>';}return html;}
function analysisPreview(){if(!window.AnalysisModel||!window.C2_DATA)return null;return M.atlas.analysis(window.AnalysisModel.fromBundle(window.C2_DATA,state.analysisPaper));}
function analysisEntryHtml(){
 const A=window.AnalysisModel,bundle=window.C2_DATA,chosen=model.papers.get(state.analysisPaper),mapping=A?.mappingFor(bundle,chosen.canonical_id),filled=!!mapping,t=analysisPreview(),counts=bundle&&A?A.counts(A.fromBundle(bundle,chosen.canonical_id)):null,supported=[...model.papers.keys()].filter(id=>A?.mappingFor(bundle,id)).length;
 return '<section id="global-panel-a" class="global-tree analysis-entry" role="tabpanel" aria-labelledby="global-tab-a" tabindex="0" '+(state.globalTree!=='a'?'hidden':'')+'><header><h2>单篇解析树</h2><span>'+(counts?.original||59)+' 原题'+(filled?'＋'+counts.instances+' 实例':' · pending')+'</span></header><div class="analysis-entry-layout"><div>'+(t?M.atlas.html(t,{view:'entry-a'}):'<p>解析树载入中…</p>')+'</div><div class="analysis-entry-lens"><label class="analysis-picker-label" for="analysis-paper-select">选择论文</label><select id="analysis-paper-select" data-analysis-picker="true">'+[...model.papers.values()].map(p=>'<option value="'+e(p.canonical_id)+'" '+(p.canonical_id===chosen.canonical_id?'selected':'')+'>'+e(p.short_name)+' · '+(A?.mappingFor(bundle,p.canonical_id)?'有解析内容':'解析待填')+'</option>').join('')+'</select><h3>'+e(chosen.short_name)+'</h3><p class="analysis-entry-state">'+(filled?counts.answers+' 回答 · '+counts.unknowns+' 项未答。节点图保留'+counts.original+'原题＋'+counts.instances+'实例；可滚动核对，点节点在支路窗读完整原题与定位。':'解析 pending。全图保留原59节点模板，无样例答案；原有Stage不变。')+'</p>'+(counts?.implementationUnknown?'<p>'+counts.implementationUnknown+' 条实现未知 · '+counts.implementationVerified+' 条实现核验；未独立复现</p>':'')+'<button type="button" class="quiet" data-open-analysis="'+e(chosen.canonical_id)+'">'+(filled?'打开可读支路':'打开待填模板')+' →</button><p>'+supported+' 篇有解析内容 · '+(model.papers.size-supported)+' 篇解析 pending</p></div></div></section>';
}
// Editorial view context only: no scientific node, edge, path or state migration.
function goalContextHtml(){
 return {shared:'<section class="shared-goal" aria-labelledby="shared-goal-title"><h2 id="shared-goal-title">General goal · 领域共同目标</h2><p id="shared-goal-scope">在视觉与语言目标下完成可验证的具身导航，并研究支撑它的环境记忆、主动取证与任务执行。</p><p class="goal-boundary">导航领域范围 · 编者整理</p><ul class="goal-siblings" aria-label="共同目标下的两棵兄弟树"><li>Literature tree · 文献脉络</li><li>Challenge–Insight tree · 难点与解法</li></ul></section>',single:'<section class="single-paper-context" aria-labelledby="single-paper-context-title"><h2 id="single-paper-context-title">独立阅读模板 · 单篇解析</h2><p id="single-paper-scope">Abstract · Introduction · Method · Experiments · Limitation</p></section>'};
}

function protocolVariant(n,id){return (n?.protocol_variants||[]).find(v=>v.id===id)||null;}
function groupPapers(group){return new Set(model.trees.l.paths.filter(p=>group.sections.some(s=>s.ids.includes(p.nodeIds[0]))).map(p=>p.paperId)).size;}
function protocolButton(id,variant=null){const n=model.trees.l.nodes.get(id),v=protocolVariant(n,variant),selected=state.l[0]===id&&(state.taskVariant||null)===(variant||null),paths=model.trees.l.paths.filter(p=>p.nodeIds[0]===id&&(!v?.paper_ids||v.paper_ids.includes(p.paperId))),count=new Set(paths.map(p=>p.paperId)).size;
 return '<button type="button" class="protocol-card '+(selected?'is-current':'')+'" data-action="root" data-key="l" data-id="'+e(id)+'" '+(variant?'data-variant="'+e(variant)+'" ':'')+'aria-pressed="'+selected+'"><strong>'+e(variant==='sap-nav-langmap-single-goal'?'LangMap · 一个目标，四种指代粒度':M.taskMap.label(id))+'</strong><span>'+count+' 篇'+(!count?' · 当前语料尚无方法挂载':' · 查看协议与方法')+'</span></button>';
}
function taskMapHtml(){
 const chosen=M.taskMap.group(state.taskGroup),stats=M.taskMap.stats(model),path=state.origin?.key==='l'?state.origin.path:state.l;
 let html='<section id="global-panel-l" role="tabpanel" tabindex="0" '+(state.globalTree!=='l'?'hidden ':'')+'class="global-tree task-map" aria-labelledby="global-tab-l"><header><h2 id="global-title-l">先看任务怎样给定</h2><span>'+stats.papers+' 篇当前文献</span></header><p class="task-map-caption">两条导航主线；问答与复合执行另作关联入口。同篇论文可跨入口出现，分组篇数不能相加。</p><div class="task-family-grid">';
 for(const g of M.taskMap.groups)html+='<button type="button" data-action="taskGroup" data-id="'+g.id+'" class="task-family '+(chosen?.id===g.id?'is-current':'')+'" aria-pressed="'+(chosen?.id===g.id)+'"><small>'+e(g.role)+'</small><strong>'+e(g.label)+'</strong><span>'+e(g.question)+'</span><em>'+e(g.example)+'</em><span class="task-family-count">'+groupPapers(g)+' 篇 · 点开协议与方法 →</span></button>';
 html+='</div><p class="task-map-bridge"><button type="button" data-action="root" data-key="l" data-id="task-lmee">桥梁：LMEE 先多目标导航，再进行记忆问答 ↗</button></p>';
 if(chosen){html+='<div class="protocol-directory"><div class="directory-heading"><h3>'+e(chosen.label)+'</h3><button class="quiet" type="button" data-action="global">← 回全局</button></div>';
 for(const section of chosen.sections)html+='<section class="protocol-section"><h4>'+e(section.label)+'</h4><p>'+e(section.note)+'</p><div class="protocol-grid">'+section.ids.map(id=>protocolButton(id)).join('')+(chosen.id==='goal'&&section.ids.includes('task-language-map-goal')?protocolButton('task-object-open','sap-nav-langmap-single-goal'):'')+'</div></section>';
 html+='</div>';}
 if(path.length)html+='<nav class="selected-task-route" aria-label="当前选中路径"><span>当前路径</span><strong>'+e(chosen?.label||'')+'</strong>'+path.map((id,i)=>'<span class="route-step">'+e(i===0&&state.taskVariant==='sap-nav-langmap-single-goal'?'LangMap 单目标协议':i===0?M.taskMap.label(id):model.trees.l.nodes.get(id)?.label||id)+'</span>').join('')+'</nav>';
 return html+'<details class="task-map-boundaries"><summary>任务条件与收录边界</summary><p>目标输入、目标发放顺序、动作空间、地图先验和记忆重置边界可以交叉。这里的协议入口不是互斥分类。</p><p>'+stats.contracts+' 个原协议 ID、'+stats.nodes+' 个来源节点、'+stats.edges+' 条来源边、'+stats.paths+' 条论文路径保留。入口分组是阅读投影，不是新学术节点。</p><p>仅整理当前 '+stats.papers+' 篇文献；不声称覆盖整个领域。代表方法不等于首作，连线不表示排名或学术继承。</p></details></section>';
}
function protocolFields(n){const fields=[['目标如何给定',n.goal_spec],['目标发放与顺序',n.goal_delivery],['怎样移动',n.action_regime],['是否预先有地图',n.environment_prior],['记忆何时重置',n.memory_regime],['怎样判成功',n.success_contract]];
 return '<dl class="protocol-facts">'+fields.map(([k,v])=>'<div><dt>'+e(k)+'</dt><dd>'+e(v||'此项尚未独立拆分，见协议原始来源')+'</dd></div>').join('')+'</dl>';
}
function variantSupplement(v){const rows=[['评测基准',v.benchmark],['评测划分',v.split],['评测范围',v.evaluation_scope],['oracle 转场',v.oracle_phase],['tour 排序',v.tour_ordering],['适用协议',v.protocol_scope],['不能扩大的结论',v.boundary],['适用范围',v.scope_note]];return '<dl class="protocol-facts version-boundaries">'+rows.filter(x=>x[1]).map(([k,val])=>'<div><dt>'+e(k)+'</dt><dd>'+e(val)+'</dd></div>').join('')+'</dl>'+((v.supporting_sources||[]).map(src=>'<p>'+sourceLink(src.source_url,'版本边界对照原文')+'<span class="locator"> '+e(src.version)+' · '+e(src.locator)+'</span></p>').join(''));}
function variantHtml(v){return '<article class="protocol-version" data-protocol-variant="'+e(v.id)+'"><h4>'+e(v.title||v.label||v.id)+'</h4>'+protocolFields(v)+variantSupplement(v)+(v.paper_ids?'<p class="scope-small">此版本记录仅挂载：'+v.paper_ids.map(id=>e(model.papers.get(id)?.short_name||id)).join('、')+'；不自动推广给同一任务下其他方法</p>':'')+'<p class="locator">'+e(v.locator||'')+'</p>'+sourceLink(v.source_url,'核对该版本原文')+'</article>';}
function renderLiteratureFocus(){
 const tree=model.trees.l,n=tree.nodes.get(state.l[0]),variant=protocolVariant(n,state.taskVariant),group=M.taskMap.group(state.taskGroup),current=tree.nodes.get(state.l.at(-1));
 if(!n){$('tree-l').innerHTML='<div class="focus-empty"><h2>先选任务，再读方法</h2><p>协议条件和来源会在这里出现；机制细节最后展开。</p></div>';return;}
 const label=variant?.title||variant?.label||M.taskMap.label(n.id),all=tree.paths.filter(p=>M.startsWith(p.nodeIds,state.l)&&(!variant?.paper_ids||variant.paper_ids.includes(p.paperId))&&(p.viewKind===state.lFacet||p.viewKind==='protocol'));
 let html='<nav class="breadcrumbs" aria-label="文献树当前位置"><button type="button" data-action="global">← 回全局</button><button type="button" data-action="taskGroup" data-id="'+e(group?.id)+'">'+e(group?.label)+'</button><span aria-current="page">'+e(label)+'</span></nav><header class="panel-head"><h2 id="title-l">'+e(label)+'</h2><p id="focus-title-l" tabindex="-1" class="next-step">先核对协议，再比较方法；同篇论文保留一份身份与证据</p></header><div class="tree-body literature-focus" id="body-l" tabindex="0" role="region" aria-label="协议条件与代表方法">';
 html+='<details class="protocol-summary" '+(state.l.length===1?'open':'')+'><summary>任务条件与协议版本</summary>'+protocolFields(variant||n);
 if(variant)html+='<p class="locator">'+e(variant.locator||'')+'</p>'+sourceLink(variant.source_url,'协议原文');
 else html+=(n.protocol_variants?.length?'<details class="historical-source-context"><summary>原始来源记录 · 保留历史，具体条件以下方版本为准</summary>'+taskOriginHtml(n)+'</details>':taskOriginHtml(n));
 const variants=(n.protocol_variants||[]).filter(v=>!state.taskVariant||v.id===state.taskVariant);if(variants.length)html+='<div class="protocol-versions">'+variants.map(variantHtml).join('')+'</div>';
 const evs=(n.evidence_ids||[]).map(id=>tree.evidence.get(id)).filter(Boolean);if(evs.length)html+='<details><summary>原有证据记录（'+evs.length+'）</summary>'+evs.map(ev=>evidenceCard(ev)).join('')+'</details>';
 const corrections=(tree.raw.correction_history||[]).filter(c=>c.selector?.node_id===n.id);if(corrections.length)html+='<details><summary>查看本轮纠错记录</summary><pre class="correction-record">'+e(JSON.stringify(corrections,null,2))+'</pre></details>';
 html+='</details><div class="method-heading"><h3>代表流程与表示</h3><div class="facet-controls" aria-label="比较方法的组织方式">'+[['pipeline','看整体流程'],['representation','看信息表示']].map(([id,label])=>'<button type="button" data-action="facet" data-facet="'+id+'" aria-pressed="'+(state.lFacet===id)+'">'+label+'</button>').join('')+'</div></div><p class="scope-small">这些是当前语料中的比较入口，不代表首创或先后继承。只有有直接来源的技术发展才另行说明。</p>';
 if(state.l.length>1)html+='<p class="focus-selection">当前方法：'+e(current?.label)+' <button type="button" class="quiet" data-action="crumb" data-key="l" data-depth="1">返回本协议全部方法</button></p>';
 const groups=new Map();for(const path of all.filter(p=>p.viewKind!=='protocol')){const id=path.nodeIds[1];if(!groups.has(id))groups.set(id,[]);groups.get(id).push(path);}
 const protocolSources=all.filter(p=>p.viewKind==='protocol');if(protocolSources.length)html+='<aside class="protocol-source-records"><h3>定义与评测规范</h3><p>规范文献没有新策略，不归入方法分支。</p>'+protocolSources.map(p=>'<button type="button" class="paper-chip" data-action="path" data-key="l" data-id="'+e(p.id)+'">'+e(model.papers.get(p.paperId)?.short_name)+' · 规范证据 ↗</button>').join('')+'</aside>';
 if(!groups.size&&!protocolSources.length)html+='<p class="empty-coverage">当前语料中没有此协议的完整方法挂载。保留来源与空覆盖，不把相近任务硬填进来。</p>';
 for(const [id,paths] of groups){const method=tree.nodes.get(id),papers=[...new Set(paths.map(p=>p.paperId))],evs=(method?.evidence_ids||[]).map(id=>tree.evidence.get(id)).filter(Boolean),modules=[...new Set(paths.flatMap(p=>p.nodeIds.filter(id=>tree.nodes.get(id)?.type==='module')))];
 html+='<article class="method-comparison" data-method-id="'+e(id)+'"><h4>'+e(method?.label||id)+'</h4>'+(method?.key_recognition?'<p>'+e(method.key_recognition)+'</p>':'')+'<div class="method-paper-list">'+papers.map(pid=>{const path=paths.find(p=>p.paperId===pid);return '<button type="button" class="paper-chip" data-action="path" data-key="l" data-id="'+e(path.id)+'">'+e(model.papers.get(pid)?.short_name||pid)+' <span>证据 ↗</span></button>';}).join('')+'</div>';
 if(modules.length)html+='<details class="mechanism-detail"><summary>再看机制细节 · '+modules.length+' 个来源模块</summary>'+modules.map(mid=>{const m=tree.nodes.get(mid),mp=paths.filter(p=>p.nodeIds.includes(mid));return '<section><h5>'+e(m.label)+'</h5>'+contractHtml(m)+'<p>'+[...new Set(mp.map(p=>p.paperId))].map(pid=>e(model.papers.get(pid)?.short_name)).join('、')+'</p>'+((m.evidence_ids||[]).map(id=>tree.evidence.get(id)).filter(Boolean).map(ev=>evidenceCard(ev)).join(''))+'</section>';}).join('')+'</details>';
 if(evs.length)html+='<details><summary>比较入口的依据（'+evs.length+'）</summary>'+evs.map(ev=>evidenceCard(ev)).join('')+'</details>';
 html+='</article>';
 }
 if(n.id==='task-imagegoal-multigoal')html+='<aside class="bounded-development"><h3>有直接证据的技术发展</h3><p>MemoNav 沿用 VGM 的拓扑图、定位、视觉编码器与策略网络，修改记忆模块：选择性遗忘、全局记忆与工作记忆。</p><p>这只支持“基于 VGM 的记忆改动”，不证明 VGM 是 ImageNav 或图记忆首作。</p>'+sourceLink('https://arxiv.org/html/2402.19161v2','MemoNav v2 §3.1–3.2、§5.1、Table 1、§9.1')+'</aside>';
 html+='</div><div class="pager"><button type="button" data-action="taskGroup" data-id="'+e(group?.id)+'">← 返回协议目录</button><span>源路径与证据保留 · 机制按需展开</span></div>';
 $('tree-l').innerHTML=html;
}

function renderGlobal(){
 const maps=['l','c'].map(key=>{if(key==='l')return taskMapHtml();const tree=model.trees[key],t=atlases[key],path=state.origin?.key===key?state.origin.path:state[key],selected=t.nodes.find(n=>n.path.length===path.length&&M.startsWith(n.path,path))?.id||t.root,roots=t.by.get(t.root).children;
  return '<section id="global-panel-'+key+'" role="tabpanel" tabindex="0" '+(state.globalTree!==key?'hidden ':'')+'class="global-tree '+(key==='c'?'global-challenge':'')+'" aria-labelledby="global-tab-'+key+'"><header><h2 id="global-title-'+key+'">'+(key==='l'?'文献脉络全树':'Challenge–Insight 全树')+'</h2><span>'+roots.length+(key==='l'?' 个任务':' 个难点')+' · '+t.paperCount+' 篇唯一论文</span></header><p class="global-levels">'+(key==='l'?'任务 → Pipeline / Representation → Module → Paper':'Challenge → Insight → Paper')+'</p>'+M.atlas.html(t,{selected,view:key})+'<p class="global-caveat">'+t.paperCount+' 篇唯一论文 · '+t.pathCount+' 条来源路径'+(key==='l'?' · 任务来源与全领域首创分开，首创待核':' · 连线是阅读组织，不代表学术继承')+'</p></section>';
 }).join('');
 const context=goalContextHtml(),tabs=[['l','看领域脉络','文献脉络树','研究任务、方法与论文的全局结构'],['c','看难点与解法','Challenge–Insight 树','同一难点下的解法分叉'],['a','读懂一篇论文','单篇解析树','五主枝与所有原问题的全貌']].map(([key,label,term,help])=>'<button type="button" role="tab" id="global-tab-'+key+'" aria-controls="global-panel-'+key+'" aria-describedby="'+(key==='a'?'single-paper-scope':'shared-goal-title shared-goal-scope')+'" aria-selected="'+(state.globalTree===key)+'" tabindex="'+(state.globalTree===key?'0':'-1')+'" data-action="globalTree" data-key="'+key+'"><strong>'+label+'</strong><span>'+help+'</span><small>'+term+'</small></button>');
 $('global-map').innerHTML='<h2 class="sr-only" tabindex="-1" id="global-title">三树导航</h2><div class="global-tabs" role="tablist" aria-label="你想怎样读论文"><div class="goal-tab-group" role="presentation">'+context.shared+tabs.slice(0,2).join('')+'</div><div class="single-paper-tab-group" role="presentation">'+context.single+tabs[2]+'</div></div><div class="global-columns">'+maps+analysisEntryHtml()+'</div>';
 $('branch-rail').innerHTML='';$('tree-workspace').classList.toggle('is-focused',state.globalTree!=='a');$('tree-workspace').classList.toggle('is-analysis-entry',state.globalTree==='a');$('tree-workspace').classList.toggle('is-catalog',state.view==='catalog');$('tree-workspace').classList.toggle('is-root-overview',state.view==='trees'&&!state.paper&&['l','c'].includes(state.globalTree)&&!state[state.globalTree].length);
}
function renderTree(key){
 if(key==='l'){renderLiteratureFocus();return;}
 if(!state[key].length){$('tree-'+key).innerHTML='<div class="focus-empty"><span class="eyebrow">可读支路窗</span><h2 id="focus-title-'+key+'" tabindex="-1">在全树中选一个节点</h2><p>这里展开当前支路，保留祖先和同层兄弟。</p><p>全树中的主枝可直接点击；也可用主枝选择器，或在图中按方向键浏览、回车展开。</p></div>';return;}
 const b=M.branch(model,state,key),isL=key==='l',tree=b.tree,root=tree.nodes.get(b.prefix[0]),title=isL?'文献脉络树':'Challenge–Insight 树';
 const example=M.pathsForPaper(model,'harnessvln').find(path=>path.key===key&&(key!=='l'||path.viewKind===state.lFacet)&&M.startsWith(path.nodeIds,b.prefix));
 const breadcrumbs='<nav class="breadcrumbs" aria-label="'+title+'当前位置"><span class="location-label">当前位置</span><button type="button" data-action="crumb" data-key="'+key+'" data-depth="0">← 返回总览</button>'+b.prefix.map((id,i)=>'<span class="crumb-separator" aria-hidden="true">›</span><span '+(i===b.prefix.length-1?'aria-current="page"':'')+'>'+e(tree.nodes.get(id)?.label||id)+'</span>').join('')+'</nav>';
 function detail(n){let html='',concept=n.concept_id?tree.raw.concept_catalog?.find(c=>c.concept_id===n.concept_id):null;
  if(concept?.common_property)html+='<p>'+e(concept.common_property)+'</p><p class="scope-small">'+(concept.shared_across_papers?'共享比较轴；下层保留各论文实现差异':'当前语料中的具体实现；不据此声称领域首创')+'</p>';
  if(n.key_recognition)html+='<p><b>关键认识：</b>'+e(n.key_recognition)+'</p>';
  if(n.why_it_addresses_challenge)html+='<p><b>为什么：</b>'+e(n.why_it_addresses_challenge)+'</p><p class="scope-small">'+(n.rationale?.author_rationale_anchors?.length?'编者综合；有部分作者论证锚点，逐篇见依据':'编者解释 · 作者是否如此论证待核')+'</p>';
  if(n.mechanism)html+='<p><b>实现机制：</b>'+e(n.mechanism)+'</p>';
  html+=contractHtml(n);const evs=(n.evidence_ids||[]).map(id=>tree.evidence.get(id)).filter(Boolean);
  if(evs.length)html+='<div class="node-evidence">'+evs.map(ev=>evidenceCard(ev)).join('')+'</div>';
  return html?'<details class="tree-node-details"><summary>'+(n.type==='task_contract'?'任务条件、定义来源与首创范围':'节点含义、比较边界与来源')+'</summary>'+html+'</details>':'';
 }
 const occurrence=prefix=>atlases[key].nodes.find(n=>n.path.length===prefix.length&&M.startsWith(n.path,prefix)),items=[],pages=[];
 function gather(prefix,depth){const n=tree.nodes.get(prefix.at(-1)),occ=occurrence(prefix),expanded=M.startsWith(b.prefix,prefix),isPaper=n.type==='paper_ref',all=M.matchingPaths(tree,prefix,isL?state.lFacet:undefined),item={id:occ.id,sourceId:n.id,label:n.label,contentTitle:(typeLabel[n.type]||n.type)+' · '+new Set(all.map(p=>p.paperId)).size+' 篇',depth,children:[],prefix,expanded,isPaper};items.push(item);
  if(expanded&&!isPaper){const atFocus=prefix.length===b.prefix.length,view={...state,[key]:prefix,pages:{...state.pages,[key]:atFocus?state.pages[key]:(state.branchPages[M.pageKey(key,prefix)]||0)}},group=M.branch(model,view,key),next=b.prefix[prefix.length],children=[...group.items];if(next&&!children.some(x=>x.node.id===next)){const pinned=group.all.find(x=>x.node.id===next);if(pinned)children.push(pinned);children.sort((a,b)=>group.all.indexOf(a)-group.all.indexOf(b));}for(const child of children)item.children.push(gather([...prefix,child.node.id],depth+1));if(group.total>M.PAGE_SIZE)pages.push({prefix,group,atFocus});}return item.id;
 }
 const focusRoot=gather([b.prefix[0]],0),width=Math.max(220,Math.min(1100,($('tree-'+key)?.clientWidth||window.innerWidth/2||650)-28)),scene=M.atlas.readableLayout(items,focusRoot,{width}),by=new Map(scene.nodes.map(n=>[n.id,n]));
 let graph='<div class="read-tree-canvas" style="width:'+scene.width+'px;height:'+scene.height+'px"><svg class="read-tree-links" viewBox="0 0 '+scene.width+' '+scene.height+'" aria-hidden="true">';
 for(const edge of scene.edges){const a=by.get(edge.source),c=by.get(edge.target),x1=a.x+a.w,y1=a.y+a.h/2,x2=c.x,y2=c.y+c.h/2,mid=(x1+x2)/2;graph+='<path data-source="'+e(a.sourceId)+'" data-target="'+e(c.sourceId)+'" class="'+(a.expanded&&c.expanded?'active':'')+'" d="'+(scene.vertical?'M'+(a.x+7)+','+(a.y+a.h)+' V'+y2+' H'+x2:'M'+x1+','+y1+' C'+mid+','+y1+' '+mid+','+y2+' '+x2+','+y2)+'"/>';}
 graph+='</svg>'+scene.nodes.map(n=>'<button id="tree-node-'+key+'-'+e(n.sourceId)+'" class="node read-tree-node '+(n.depth===0?'graph-root ':'')+(n.expanded?'ancestor ':n.isPaper&&state.paper===tree.nodes.get(n.sourceId).paper_id?'active':'')+'" type="button" data-action="'+(n.expanded?'crumb':'enter')+'" data-key="'+key+'" data-id="'+e(n.sourceId)+'" data-depth="'+(n.prefix.length-1)+'" data-x="'+n.x+'" data-y="'+n.y+'" '+(!n.isPaper?'aria-expanded="'+n.expanded+'"':'')+' aria-label="'+e(n.label)+'" style="left:'+n.x+'px;top:'+n.y+'px;width:'+n.w+'px;height:'+n.h+'px"><span class="read-node-copy"><strong>'+e(n.label)+'</strong><span>'+e(n.contentTitle)+'</span></span><span class="node-toggle" aria-hidden="true">'+(n.isPaper?'↗':n.expanded?'−':'＋')+'</span></button>').join('')+'</div>';
 graph+=pages.map(({prefix,group,atFocus})=>'<div class="tree-level-pages" data-page-depth="'+prefix.length+'"><span>'+e(tree.nodes.get(prefix.at(-1)).label)+' · '+(group.page*M.PAGE_SIZE+1)+'–'+Math.min(group.total,(group.page+1)*M.PAGE_SIZE)+' / '+group.total+'</span><button type="button" data-action="page" data-key="'+key+'" data-depth="'+prefix.length+'" data-page="'+(group.page-1)+'" '+(!group.page?'disabled':'')+'>上一组兄弟</button><button type="button" data-action="page" data-key="'+key+'" data-depth="'+prefix.length+'" data-page="'+(group.page+1)+'" '+(group.page>=group.maxPage?'disabled':'')+'>下一组兄弟</button>'+(atFocus?'<label class="layer-jump">本层完整目录<select data-layer-jump="'+key+'"><option value="">直接选择任意子项…</option>'+group.all.map(item=>'<option value="'+e(item.node.id)+'">'+e(item.node.label)+' · '+item.paperIds.length+' 篇</option>').join('')+'</select></label>':'')+'</div>').join('');
 const rootHtml='<div class="focus-node-context">'+(statusLabel(root)?'<span class="status">'+e(statusLabel(root))+'</span>':'')+detail(b.parent||root)+'</div>';
 const next=b.total===0?'当前39篇中尚无此分支挂载，原任务及来源状态保留':b.parent?.type==='task_contract'?'点一种方法，让它下面长出关键模块':b.parent?.type==='pipeline'||b.parent?.type==='representation'?'点一个模块，让它下面长出论文':b.parent?.type==='challenge'?'点一种解法，让它下面长出相关论文':'点论文叶，打开已有证据';
 $('tree-'+key).innerHTML=breadcrumbs+'<header class="panel-head"><h2 id="title-'+key+'">'+title+' <span class="tree-reading-label">沿连线展开</span></h2><p id="focus-title-'+key+'" tabindex="-1" class="next-step">'+next+'；已展开节点可再点一次收起</p>'+(isL?'<div class="facet-controls" aria-label="选择方法组织方式">'+[['pipeline','方法流程 · Pipeline'],['representation','信息表示 · Representation']].map(([id,label])=>'<button type="button" data-action="facet" data-facet="'+id+'" aria-pressed="'+(state.lFacet===id)+'" class="'+(state.lFacet===id?'active':'')+'">'+label+'</button>').join('')+'</div>':'')+'</header><div class="tree-body nested-tree" id="body-'+key+'" tabindex="0" role="region" aria-label="'+title+'展开的子树">'+rootHtml+graph+'</div><div class="pager"><button type="button" data-action="back" data-key="'+key+'" '+(!b.prefix.length?'disabled':'')+'>← 收起一层</button><span>保留上层和相邻兄弟 · 连线仅表示阅读组织</span></div>';
}
function pathContext(){if(!state.origin)return null;const tree=model.trees[state.origin.key];return tree.paths.find(p=>p.paperId===state.paper&&p.nodeIds.length===state.origin.path.length&&M.startsWith(p.nodeIds,state.origin.path));}
function pathGroups(items,key){if(!items.length)return '<p>此树尚未接入该论文的已整理路径；记录仍在全量列表中。</p>';const groups=new Map();for(const p of items){const root=p.nodeIds[0];if(!groups.has(root))groups.set(root,[]);groups.get(root).push(p);}return [...groups.entries()].map(([root,paths])=>{const label=model.trees[key].nodes.get(root)?.label||root;const buttons=paths.map(path=>'<button type="button" class="path-button" data-action="path" data-key="'+key+'" data-id="'+e(path.id)+'"><span class="path-tree">'+(key==='l'?(path.viewKind==='representation'?'Representation 切面':path.viewKind==='protocol'?'任务 / 协议来源':'Pipeline 切面'):'Challenge → Insight')+' · 展开此路径 →</span>'+path.labels.map(e).join(' › ')+'</button>').join('');return paths.length>1?'<details class="membership-group"><summary>'+e(label)+' · 全部 '+paths.length+' 条归属</summary>'+buttons+'</details>':buttons;}).join('');}
function renderPaper(){const p=model.papers.get(state.paper);if(!p){$('paper-panel').innerHTML='<div class="read-start"><p class="eyebrow">论文证据</p><h2 id="paper-title">两棵树，共用一份证据</h2><p>逐层选择后，这里打开具体论文。不会在左右两侧各放一个相隔很远的副本。</p><ol><li>选择任务，进入 pipeline、representation 和 module</li><li>或选择共同 challenge，对照不同 insight</li><li>读论文证据，并查看同篇的其他归属</li></ol><p>也可直接搜索全部 39 篇，包括尚未完成结构审核的记录。</p><a href="all-papers.html">打开全量文字替代 ↗</a></div>';return;}
 const origin=state.origin?(state.origin.key==='l'?'文献树':'Challenge 树')+' · '+state.origin.path.slice(0,-1).map(id=>model.trees[state.origin.key].nodes.get(id)?.label||id).join(' › '):'来自全量论文列表';
 let content='',ctx=pathContext();const supplements=[];const supplementKeys=new Set();for(const tree of Object.values(model.trees)){const refs=new Set(tree.paths.filter(path=>path.paperId===p.canonical_id).flatMap(path=>path.evidenceIds));for(const ev of tree.evidence.values()){if((ev.paper_id===p.canonical_id||refs.has(ev.evidence_id))&&(ev.newly_checked||ev.verification_origin?.startsWith('primary_'))){const id=[ev.source_url,ev.locator,ev.statement||ev.claim].join('|');if(!supplementKeys.has(id)){supplementKeys.add(id);supplements.push(ev);}}}}
 if(state.tab==='analysis'){const A=window.AnalysisModel,filled=!!A?.mappingFor(window.C2_DATA,p.canonical_id),count=filled?A.counts(A.fromBundle(window.C2_DATA,p.canonical_id)):null;content=notice(filled?'C2 · 总览与焦点树 · 本地内容候选':'本篇论文解析树待建立')+'<section class="detail-section"><h3>'+e(filled?p.short_name+' 原方法解析':'可先查看原模板结构')+'</h3><p>'+(filled?count.original+'个原模板节点与'+count.instances+'个论文实例。'+count.answers+'条回答、作者主张及'+count.unknowns+'项未答分别保留；没有改变原有Stage。':'当前只有原目录及已读范围，尚无本篇全文解析。不会复制HarnessVLN的答案，也不会复制其他论文的答案。')+'</p>'+(count?.implementationUnknown?'<p>'+count.implementationUnknown+' 条实现未知 · '+count.implementationVerified+' 条实现核验；未独立复现</p>':'')+'<a class="quiet c2-open-link" href="analysis/reading.html#paper-'+e(p.canonical_id)+'" data-open-analysis="'+e(p.canonical_id)+'">'+(filled?'打开C2解析树 →':'打开原模板（本篇待建立） →')+'</a></section>';}

 if(state.tab==='overview'){content='<section class="detail-section"><h3>'+e(p.overview_label_zh||'研究概述')+'</h3><p>'+e(p.overview_zh||p.abstract_summary_zh||'此记录尚无概述；请查看证据。')+'</p><p class="scope-small">'+e(p.overview_scope_note_zh||'编辑归纳；并非全文翻译')+'</p></section><section class="detail-section"><h3>原记录的方法概述</h3><p><b>Pipeline：</b>'+e(p.pipeline)+'</p><p><b>Representation：</b>'+e(p.representation)+'</p><p><b>Module：</b>'+e(p.module)+'</p></section><section class="detail-section"><h3>适用条件与局限</h3>'+list(p.conditions||[])+'<p>'+e(p.limits)+'</p></section>';}
 if(state.tab==='evidence'){
  content=notice(scope(p)+'；'+(p.evidence||[]).length+' 条原记录证据。全文通读、代码运行与独立复现均不能由这些记录推定。');
  if(supplements.length)content+='<section class="detail-section"><h3>本轮结构核查补充</h3>'+supplements.map(ev=>evidenceCard(ev,p)).join('')+'</section>';
  if(ctx?.implementationVariant){const v=ctx.implementationVariant;content+='<section class="detail-section"><h3>此路径对应的论文实现</h3><p><b>'+e(v.label)+'</b></p>'+(v.kind==='named_baseline_comparison_variant'?'<p>'+e(v.pipeline)+'</p>':'')+'<p>'+e(v.representation_original||v.representation)+'</p><p>'+e(v.modules_original||(v.modules||[]).join('；'))+'</p><p><b>角色 / 边界：</b>'+e(v.scope_note)+'</p></section>';}
  if(ctx?.variant){const v=ctx.variant;content+='<section class="detail-section"><h3>当前 insight 下的具体方法变体</h3><p>'+e(v.method_claim||v.mechanism_variant)+'</p><p><b>适用边界：</b>'+e(v.boundary)+'</p>'+(v.rationale_status?'<p><b>此论文的 why 依据：</b>'+e(v.rationale_anchor_refs?.length?'有作者论证锚点；共同表述仍为编辑综合':'作者论证待核，当前为编辑解释')+'</p>':'')+'<p><b>与共同问题的关系：</b>'+e({direct:'直接处理该问题',adjacent:'相邻问题或不同表示；不可直接同协议比较',protocol:'协议 / 评测依据'}[v.relation_to_challenge]||v.relation_to_challenge)+'</p></section>';}
  if(ctx?.evidenceIds.length){content+='<section class="detail-section"><h3>当前归属的定位依据</h3>'+ctx.evidenceIds.map(id=>model.trees[state.origin.key].evidence.get(id)).filter(Boolean).map(ev=>evidenceCard(ev,p)).join('')+'</section>';}
  content+='<section class="detail-section"><h3>原记录全部证据</h3>'+(p.evidence||[]).map(ev=>evidenceCard(ev,p)).join('')+'</section><section class="detail-section"><h3>读到哪里 / 尚未核什么</h3>'+list(p.read_locations||[])+list(p.not_read||[])+'</section>';
 }
 if(state.tab==='paths'){const paths=M.pathsForPaper(model,p.canonical_id);content=notice('同篇可同时服务多个任务或共同问题。以下只导航既有合法完整路径，不表示学术继承。');for(const key of ['l','c']){const items=paths.filter(x=>x.key===key);content+='<section class="detail-section"><h3>'+(key==='l'?'文献脉络树':'Challenge–Insight 树')+' · '+items.length+' 个归属</h3>'+pathGroups(items,key)+'</section>';}}
 $('paper-panel').innerHTML='<header class="paper-head"><div class="node-type">论文与原文证据 · 同篇只保留一份</div><h2 id="paper-title" tabindex="-1">'+e(p.short_name)+'</h2><button type="button" class="close" data-action="closePaper" aria-label="关闭论文证据并返回原位置">×</button><p class="full-title">'+e(p.title)+'</p><div class="meta">'+e(p.version)+' · '+e(scope(p))+'</div><p class="origin-label">'+e(origin)+'</p></header><div class="paper-tabs" role="tablist" aria-label="论文内容">'+[['evidence','证据'],['overview','概述'],['paths','其他归属'],['analysis','论文解析树']].map(([id,label])=>'<button type="button" role="tab" id="tab-'+id+'" aria-controls="paper-body" aria-selected="'+(state.tab===id)+'" tabindex="'+(state.tab===id?'0':'-1')+'" class="'+(state.tab===id?'active':'')+'" data-action="tab" data-tab="'+id+'">'+label+'</button>').join('')+'</div><div class="paper-body" id="paper-body" role="tabpanel" tabindex="0" aria-labelledby="tab-'+e(state.tab)+'">'+content+sourceLink(p.source_url,'打开固定版本论文')+'</div>';
}
function renderCatalog(){const results=M.catalogResults(model,state.query),maxPage=Math.max(0,Math.ceil(results.length/M.CATALOG_PAGE_SIZE)-1),page=Math.min(state.pages.catalog,maxPage),items=results.slice(page*M.CATALOG_PAGE_SIZE,(page+1)*M.CATALOG_PAGE_SIZE);$('catalog-panel').innerHTML='<header class="catalog-head"><button type="button" class="inline-back" data-action="view" data-view="trees">← 返回树状阅读</button><h2 id="catalog-title" tabindex="-1">全部论文</h2><p>总收录 '+model.papers.size+' 篇 · 搜索结果 '+results.length+' 篇'+(state.query?' · “'+e(state.query)+'”':'')+'</p>'+(state.query?'<button class="inline-back" type="button" data-action="clearSearch">清空搜索，恢复全部记录</button>':'')+'</header><div id="catalog-list" class="catalog-list" tabindex="0" role="region" aria-label="论文搜索结果">'+(items.length?items.map(p=>{const paths=M.pathsForPaper(model,p.canonical_id),l=paths.filter(x=>x.key==='l').length,c=paths.filter(x=>x.key==='c').length;return '<button type="button" class="paper-row '+(state.paper===p.canonical_id?'active':'')+'" data-action="paper" data-id="'+e(p.canonical_id)+'"><strong>'+e(p.short_name)+'</strong><span class="meta">'+e(p.version)+' · '+e(scope(p))+'</span><p class="paper-summary">'+e(p.overview_zh||p.abstract_summary_zh||p.title)+'</p><span class="mapping">文献树 '+l+' 条候选路径 · Challenge 树 '+c+' 条候选路径 · 读证据 →</span></button>';}).join(''):'<div class="empty"><h3>没有匹配结果</h3><p>试试论文简称、具体机制或证据里的词。清空搜索不会删除任何收录记录。</p><button type="button" class="quiet" data-action="clearSearch">恢复全部 '+model.papers.size+' 篇</button></div>')+'</div><div class="pager"><button type="button" data-action="page" data-key="catalog" data-page="'+(page-1)+'" '+(!page?'disabled':'')+'>上一页</button><span>结果 '+(results.length?page*M.CATALOG_PAGE_SIZE+1:0)+'–'+Math.min(results.length,(page+1)*M.CATALOG_PAGE_SIZE)+' / '+results.length+'</span><button type="button" data-action="page" data-key="catalog" data-page="'+(page+1)+'" '+(page>=maxPage?'disabled':'')+'>下一页</button></div>';}
function scrollKey(id){return id+'|'+(id==='body-l'?state.lFacet+'|'+state.l.join('>')+'|'+state.pages.l:id==='body-c'?state.c.join('>')+'|'+state.pages.c:id==='paper-body'?state.paper+'|'+state.tab+'|'+JSON.stringify(state.origin):state.query+'|'+state.pages.catalog);}
function saveScroll(){if(state)documentPositions[M.serialize(state)]={y:window.scrollY||0,target:document.activeElement?.dataset?{...document.activeElement.dataset}:null};for(const id of ['body-l','body-c','paper-body','catalog-list'])if($(id)){scrollPositions[id]=$(id).scrollTop;branchScroll[scrollKey(id)]=$(id).scrollTop;}}
function render(action={}){const c=M.coverage(model);$('coverage').innerHTML='<span>总收录 <strong>'+c.catalog+'</strong> 篇</span><span>文献树候选挂载 <strong>'+c.literature+'</strong> 篇</span><span>Challenge 候选挂载 <strong>'+c.challenge+'</strong> 篇</span><span class="scope-note">结构候选与原有证据分开计数；不是 '+c.catalog+' 篇全文重读或首创审核完成</span>';$('tree-l').hidden=state.view!=='trees'||state.globalTree!=='l';$('tree-c').hidden=state.view!=='trees'||state.globalTree!=='c';$('global-map').hidden=state.view!=='trees';$('branch-rail').hidden=true;$('paper-panel').hidden=!state.paper||(state.view==='trees'&&(state.globalTree==='a'||state.origin&&state.origin.key!==state.globalTree));$('catalog-panel').hidden=state.view!=='catalog';$('navigation').classList.toggle('catalog-mode',state.view==='catalog');$('view-trees').classList.toggle('active',state.view==='trees');$('view-catalog').classList.toggle('active',state.view==='catalog');$('view-trees').setAttribute('aria-pressed',String(state.view==='trees'));$('view-catalog').setAttribute('aria-pressed',String(state.view==='catalog'));$('search').value=state.query;
 renderGlobal();renderTree('l');renderTree('c');renderCatalog();renderPaper();$('view-trees').hidden=true;$('navigation').classList.toggle('single-focus',!state.l.length||!state.c.length);
 const resets=new Set(action.resetScroll||[]);for(const id of ['body-l','body-c','paper-body','catalog-list'])if($(id))$(id).scrollTop=resets.has(id)?0:(branchScroll[scrollKey(id)]||0);
}
function dispatch(action,historyMode='push'){
 saveScroll();const before=state;state=M.reduce(model,state,action);if(state===before)return;
 const resets=[];if(action.type==='facet')resets.push('body-l');if(['enter','path','root'].includes(action.type))resets.push('body-'+action.key);if(['search','clearSearch','overview'].includes(action.type)||action.type==='page'&&action.key==='catalog')resets.push('catalog-list');if(['paper','enter','path','tab'].includes(action.type)&&(state.paper!==before.paper||state.tab!==before.tab||JSON.stringify(state.origin)!==JSON.stringify(before.origin)))resets.push('paper-body');if(['overview','global'].includes(action.type))resets.push('body-l','body-c','paper-body');
 if(historyMode)try{window.history[historyMode==='replace'?'replaceState':'pushState']({navigationState:state},'',M.serialize(state));}catch{}render({resetScroll:resets});
 $('announcement').textContent=action.type==='search'?M.catalogResults(model,state.query).length+' 篇搜索结果':state.paper?'已选择 '+model.papers.get(state.paper)?.short_name:'当前层已更新';
 if(['search','clearSearch'].includes(action.type)||action.type==='view'&&state.view==='catalog'){$('catalog-title')?.focus({preventScroll:true});$('catalog-panel')?.scrollIntoView({behavior:'auto',block:'start'});}
 if(action.type==='view'&&state.view==='trees'){$('global-tab-'+state.globalTree)?.focus({preventScroll:true});$('tree-workspace')?.scrollIntoView({behavior:'auto',block:'start'});}
 if(['global','overview','taskGroup'].includes(action.type)||['back','crumb'].includes(action.type)&&!state[action.key]?.length){if(action.type==='taskGroup')$('global-title-l')?.focus({preventScroll:true});const id=before[action.key]?.[0];restoreFocus(id?{action:'root',key:action.key,id}:null);if(!id)$('global-tab-'+state.globalTree)?.focus({preventScroll:true});$('tree-workspace')?.scrollIntoView({behavior:'auto',block:'start'});}
 else if(['root','enter','path','back','crumb','facet','page'].includes(action.type)&&state.view==='trees'&&state.globalTree!=='a'){
  const key=action.key||state.globalTree,exited=['back','crumb'].includes(action.type)?before[key][state[key].length]:null;
  if(exited)restoreFocus({action:'enter',key,id:exited});else if(action.type==='enter')$('tree-node-'+key+'-'+action.id)?.focus({preventScroll:true});else $('focus-title-'+key)?.focus({preventScroll:true});
  const reveal=action.type==='enter'?$('tree-node-'+key+'-'+action.id):null;const body=$('body-'+key);if(body&&reveal&&typeof reveal.offsetTop==='number'){body.scrollTop=Math.max(0,Number(reveal.dataset.y)||0);body.scrollLeft=Math.max(0,(Number(reveal.dataset.x)||0)-20);}
 }
 if(['enter','paper','path','locate'].includes(action.type)&&state.paper&&(state.paper!==before.paper||action.type==='paper'||action.type==='path')){$('paper-title')?.focus({preventScroll:true});$('paper-panel').scrollTop=0;}

}
function restoreFocus(target){if(!target)return;const found=(target.atlasId?[...document.querySelectorAll('[data-atlas-id]')].find(el=>el.dataset.atlasView===target.atlasView&&el.dataset.atlasId===target.atlasId):null)||(target.id&&target.key?$('tree-node-'+target.key+'-'+target.id):null)||[...document.querySelectorAll('[data-action]')].find(el=>el.dataset.action===target.action&&el.dataset.id===target.id&&el.dataset.key===target.key&&(target.depth===undefined||el.dataset.depth===target.depth)&&(target.page===undefined||el.dataset.page===target.page));if(found&&!found.disabled&&!found.closest('[hidden]')){found.focus({preventScroll:true});}else focusVisibleNavigation();}
function focusVisibleNavigation(){const ids=state.view==='catalog'?['catalog-title']:['body-'+state.globalTree,'focus-title-'+state.globalTree,'global-tab-'+state.globalTree];const target=ids.map($).find(el=>el&&!el.closest('[hidden]'));target?.focus({preventScroll:true});}
try{
 M.atlas.bind(document,view=>view==='entry-a'?analysisPreview():view==='analysis'?window.AnalysisC2?.getModel()&&M.atlas.analysis(window.AnalysisC2.getModel()):atlases[view],(view,n)=>{if(view==='analysis'){window.AnalysisC2.dispatch({type:n.parent?'enter':'overview',id:n.id});return;}if(view==='entry-a'){window.AnalysisC2.open(state.analysisPaper,window.NavigationPrototype?.getContext());if(n.parent)window.AnalysisC2.dispatch({type:'enter',id:n.id});return;}if(n.type==='paper_ref')opener={atlasView:view,atlasId:n.id};dispatch({type:'locate',key:view,id:n.id});if(n.type==='paper_ref'){$('paper-title')?.focus({preventScroll:true});}else{const target=$('tree-node-'+view+'-'+n.sourceId)||$('focus-title-'+view),body=$('body-'+view);target?.focus({preventScroll:true});if(body&&target&&typeof target.offsetTop==='number'){body.scrollTop=Math.max(0,Number(target.dataset.y)||0);body.scrollLeft=Math.max(0,(Number(target.dataset.x)||0)-20);}}},view=>{if(view==='analysis')window.AnalysisC2?.render();else{saveScroll();render();}});
 model=M.buildModel(window.PAPER_CATALOG,window.LITERATURE_TREE,window.CHALLENGE_TREE);atlases={l:M.atlas.paths(model,'l'),c:M.atlas.paths(model,'c')};const errs=M.validate(model);if(errs.length)throw new Error(errs.join('; '));state=M.deserialize(model,window.location.hash);render();
 document.addEventListener('change',event=>{if(event.target.matches('[data-analysis-picker]')){dispatch({type:'analysisPaper',id:event.target.value},'replace');$('analysis-paper-select')?.focus({preventScroll:true});return;}if(event.target.matches('[data-root-jump]')){const key=event.target.dataset.rootJump;if(event.target.value)dispatch({type:'root',key,id:event.target.value});else dispatch({type:'crumb',key,depth:0});return;}if(event.target.matches('[data-layer-jump]')&&event.target.value){const key=event.target.dataset.layerJump,id=event.target.value,items=M.branch(model,state,key).all,index=items.findIndex(item=>item.node.id===id),isPaper=model.trees[key].nodes.get(id)?.type==='paper_ref';dispatch({type:'page',key,page:Math.max(0,Math.floor(index/M.PAGE_SIZE))},'replace');if(isPaper)opener={action:'enter',key,id};dispatch({type:'enter',key,id});if(!isPaper)$('body-'+key)?.focus({preventScroll:true});}});
 document.addEventListener('click',event=>{const b=event.target.closest('button[data-action]');if(!b||b.disabled)return;const target={...b.dataset},action={...target,type:target.action};if(target.page!==undefined)action.page=Number(target.page);if(target.depth!==undefined)action.depth=Number(target.depth);const opensPaper=action.type==='paper'||action.type==='enter'&&model.trees[action.key]?.nodes.get(action.id)?.type==='paper_ref';if(opensPaper)opener=target;if(action.type==='path'){const p=model.trees[action.key].paths.find(path=>path.id===action.id);if(p)opener={action:'path',key:action.key,id:p.id};}dispatch(action);if(action.type==='closePaper')restoreFocus(opener);else if(!['paper','path','root','global','overview','enter','back','crumb','facet','page','view','clearSearch'].includes(action.type)&&!opensPaper)restoreFocus(target);});
 $('search-form').addEventListener('submit',event=>{event.preventDefault();dispatch({type:'search',query:$('search').value});});
 $('search').addEventListener('search',()=>{if(!$('search').value)dispatch({type:'clearSearch'});});
 document.addEventListener('keydown',event=>{if($('c2-app')&&!$('c2-app').hidden)return;if(event.key==='Escape'&&state.paper){event.preventDefault();dispatch({type:'closePaper'});restoreFocus(opener);}const tab=event.target.closest('[role="tab"]');if(tab?.dataset.action==='globalTree'&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=['l','c','a'],index=tabs.indexOf(state.globalTree),key=tabs[event.key==='Home'?0:event.key==='End'?2:(index+(event.key==='ArrowRight'?1:2))%3];dispatch({type:'globalTree',key},'replace');$('global-tab-'+key)?.focus({preventScroll:true});return;}if(tab&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const tabs=['evidence','overview','paths','analysis'],i=tabs.indexOf(state.tab),idx=event.key==='Home'?0:event.key==='End'?tabs.length-1:(i+(event.key==='ArrowRight'?1:tabs.length-1))%tabs.length;dispatch({type:'tab',tab:tabs[idx]},'replace');$('tab-'+tabs[idx]).focus({preventScroll:true});}});
 window.addEventListener('popstate',()=>{if(window.location.hash.startsWith('#analysis='))return;if(window.AnalysisC2?.isOpen())window.AnalysisC2.prepareNavigationHistory();else saveScroll();state=M.deserialize(model,window.location.hash);render();const pos=documentPositions[M.serialize(state)];if(pos){restoreFocus(pos.target);window.scrollTo?.(0,pos.y);}else if(state.view==='trees'&&state[state.globalTree]?.length)$('focus-title-'+state.globalTree)?.focus({preventScroll:true});else $('global-tab-'+state.globalTree)?.focus({preventScroll:true});$('announcement').textContent='已恢复浏览历史中的路径与选中论文';});
 window.NavigationPrototype={model,getState:()=>state,dispatch,render,getContext:()=>{saveScroll();return {state:JSON.parse(JSON.stringify(state)),branchScroll:{...branchScroll},scrollPositions:{...scrollPositions},windowY:window.scrollY||0};},restoreContext:context=>{state=M.sanitizeState(model,context.state);Object.assign(branchScroll,context.branchScroll||{});Object.assign(scrollPositions,context.scrollPositions||{});render();window.scrollTo?.(0,context.windowY||0);if(state.view==='trees'&&state.globalTree==='a')$('global-tab-a')?.focus({preventScroll:true});else if(state.paper)$('paper-title')?.focus({preventScroll:true});else $('global-tab-'+state.globalTree)?.focus({preventScroll:true});}};
}catch(err){$('load-error').hidden=false;console.error(err);}
})();
